Perkin-UAT/force-app/main/default/objects/B2B_Shipping_Methods__mdt/B2B_Shipping_Methods__mdt.object-meta.xml
<CustomObject>
    <label>B2B Shipping Methods</label>
    <pluralLabel>B2B Shipping Methods</pluralLabel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/B2B_Shipping_Methods__mdt/fields/Above_Threshold_Shipping_Charge__c.field-meta.xml
<CustomField>
    <fullName>Above_Threshold_Shipping_Charge__c</fullName>
    <label>Above Threshold Shipping Charge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Shipping_Methods__mdt/fields/Below_Threshold_Shipping_Charge__c.field-meta.xml
<CustomField>
    <fullName>Below_Threshold_Shipping_Charge__c</fullName>
    <label>Below Threshold Shipping Charge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Shipping_Methods__mdt/fields/Maximum_Shipping_Charge__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Shipping_Charge__c</fullName>
    <label>Maximum Shipping Charge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Shipping_Methods__mdt/fields/Percent_Calculation__c.field-meta.xml
<CustomField>
    <fullName>Percent_Calculation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Percent Calculation?</label>
    <type>Checkbox</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Shipping_Methods__mdt/fields/Percent_of_Net_Cost__c.field-meta.xml
<CustomField>
    <fullName>Percent_of_Net_Cost__c</fullName>
    <label>Percent of Net Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Shipping_Methods__mdt/fields/Threshold_Value__c.field-meta.xml
<CustomField>
    <fullName>Threshold_Value__c</fullName>
    <label>Threshold Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Subscriptions__c/B2B_Subscriptions__c.object-meta.xml
<CustomObject>
    <label>B2B Subscriptions</label>
    <nameField>
        <displayFormat>Sub# {00000}</displayFormat>
        <label>B2B Subscriptions</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B2B Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/B2B_Subscriptions__c/fields/B2B_Shipping_Method__c.field-meta.xml
<CustomField>
    <fullName>B2B_Shipping_Method__c</fullName>
    <label>B2B Shipping Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Order/fields/B2B_Subscriptions__c.field-meta.xml
<CustomField>
    <fullName>B2B_Subscriptions__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>B2B Subscriptions</label>
    <referenceTo>B2B_Subscriptions__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/classes/B2B_SubscriptionShippingCalHelper.cls
/**
 * @Test Class        : B2B_SubscriptionOrderSchedulerTest
**/
public with sharing class B2B_SubscriptionShippingCalHelper {

    public static Decimal calculateShippingCharge(Order orderRecord) {
        try {
            if (orderRecord == null || orderRecord.B2B_Subscriptions__c == null) return 0;

            String shippingMethod = orderRecord.B2B_Subscriptions__r.B2B_Shipping_Method__c;

            if (String.isBlank(shippingMethod) || String.isBlank(orderRecord.ShippingCountry)) {
                return 0;
            }
			System.debug('Shipping calculation ::: ' + shippingMethod +', '+ orderRecord.ShippingCountry);
            B2B_Shipping_Methods__mdt method = fetchShippingMethod(shippingMethod, orderRecord.ShippingCountry);
            if (method == null) return 0;

            return calculateCharge(orderRecord.TotalAmount, method);
        } catch (Exception ex) {
            System.debug('Error calculating shipping charge: ' + ex.getMessage());
            return 0;
        }
    }

    private static B2B_Shipping_Methods__mdt fetchShippingMethod(String methodLabel, String countryCode) {
        List<B2B_Shipping_Methods__mdt> methods = [
                SELECT MasterLabel, Threshold_Value__c, Below_Threshold_Shipping_Charge__c, 
                       Above_Threshold_Shipping_Charge__c, Percent_Calculation__c, 
                       Percent_of_Net_Cost__c, Maximum_Shipping_Charge__c, Country_Code__c
                FROM B2B_Shipping_Methods__mdt
                WHERE MasterLabel = :methodLabel
                AND Country_Code__c = :countryCode
                AND isActive__c = TRUE
                LIMIT 1
            ];
            return methods.isEmpty() ? null : methods[0];
      
    }

    private static Decimal calculateCharge(Decimal totalAmountRaw, B2B_Shipping_Methods__mdt method) {
        Decimal totalAmount = totalAmountRaw != null ? totalAmountRaw : 0;
        Decimal shippingCharge = 0;

        if (method.Percent_Calculation__c && method.Percent_of_Net_Cost__c != null) {
            shippingCharge = totalAmount * (method.Percent_of_Net_Cost__c / 100);
        } else {
            Boolean isBelowThreshold = method.Threshold_Value__c != null && totalAmount < method.Threshold_Value__c;
            shippingCharge = isBelowThreshold ? method.Below_Threshold_Shipping_Charge__c : method.Above_Threshold_Shipping_Charge__c;
        }

        if (method.Maximum_Shipping_Charge__c != null && shippingCharge > method.Maximum_Shipping_Charge__c) {
            shippingCharge = method.Maximum_Shipping_Charge__c;
        }

        return shippingCharge.setScale(2, RoundingMode.HALF_UP);
    }
}