Perkin-UAT/force-app/main/default/objects/Account/fields/Account_Alias__c.field-meta.xml
<CustomField>
    <fullName>Account_Alias__c</fullName>
    <label>Account Alias</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Account/fields/Enrolled_lives__c.field-meta.xml
<CustomField>
    <fullName>Enrolled_lives__c</fullName>
    <description>DX - 6/15/2017 not sure of still used</description>
    <label># Enrolled lives</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Account/recordTypes/Test.recordType-meta.xml
<RecordType>
    <fullName>Test</fullName>
    <active>true</active>
    <label>Test</label>
</RecordType>

Perkin-UAT/force-app/main/default/objects/Custom_Account_View_Hierarchy__c/Custom_Account_View_Hierarchy__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>View Hierarchy Button - List of account fields displayed</description>
    <label>Custom Account View Hierarchy Setting</label>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/Custom_Account_View_Hierarchy__c/fields/Field_List__c.field-meta.xml
<CustomField>
    <fullName>Field_List__c</fullName>
    <inlineHelpText>The List of Fields that are to be displayed on the Custom View Hierarchy on Account</inlineHelpText>
    <label>Field List</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/classes/TestViewAccountHierarchy.cls
/* Change Log
 * 
  Developer      Date    Description
  Tony Tran      01/24/17  Removed references to defunct CRM Address fields
                Note: need to revise this test class to include assertions to make tests more robust
 * 
 * 
 * 
*/ 

@isTest(seeAllData=true)
public class TestViewAccountHierarchy {
    @isTest
    public static void testOne(){
      Account testAccountOne =  new Account(Name='Test Account One',Account_Alias__c='Test',BillingStreet='Test street');
      insert testAccountOne;
      Account testAccountTwo =  new Account(Name='Test Account two',ParentId=testAccountOne.id,Account_Alias__c='Test',BillingStreet='Test street');
      insert testAccountTwo;
      Account testAccountThree =  new Account(Name='Test Account three',ParentId=testAccountTwo.id,Account_Alias__c='Test',BillingStreet='Test street');
      insert testAccountThree;
      Account testAccountFour =  new Account(Name='Test Account four',ParentId=testAccountThree.id,Account_Alias__c='Test',BillingStreet='Test street');
      insert testAccountFour;
       Custom_Account_View_Hierarchy__c ss = new Custom_Account_View_Hierarchy__c();
      ss.Name='Test';
      ss.Field_List__c='Account_Alias__c,Enrolled_lives__c,Name';
      insert ss;
      
      ApexPages.StandardController sc = new ApexPages.StandardController(testAccountOne);
      ViewAccountHierarchyController controller = new ViewAccountHierarchyController(sc);
      
     
      
      Pagereference pageRef = new PageReference('/ViewAccountHierarchy') ;
       pageRef.getParameters().put('id',testAccountOne.id);                         
       system.Test.setCurrentPage(pageRef);
       
       sc = new ApexPages.StandardController(testAccountTwo);
      controller = new ViewAccountHierarchyController(sc);
      
      pageRef = new PageReference('/ViewAccountHierarchy') ;
       pageRef.getParameters().put('id',testAccountTwo.id);                          
       system.Test.setCurrentPage(pageRef);
       
       String s = controller.getLabel('Account','Name');
       
       controller.findChildren(testAccountOne.id);
       controller.sortedAccountList = new List<Account>();
       controller.recursiveSortAccountHierarchy(testAccountOne.id);
       
       ApexPages.StandardController sc2 = new ApexPages.standardController(testAccountOne);
        ViewAccountHierarchyController controllerclass=new ViewAccountHierarchyController(sc2);
    }
}