Perkin-UAT/force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Account/fields/B2B_Is_Currently_Tax_Exempt__c.field-meta.xml
<CustomField>
    <fullName>B2B_Is_Currently_Tax_Exempt__c</fullName>
    <formula>AND(
  NOT(ISBLANK(B2B_Exemption_Code__c)),
  TODAY() &gt;= B2B_Effective_Date__c,
  TODAY() &lt;= B2B_Expiration_Date__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Currently Tax Exempt?</label>
    <type>Checkbox</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Account/fields/PKI_SAP_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>PKI_SAP_Customer_Number__c</fullName>
    <description>SAP - KNA1/KUNNR. Customer number for SoldToShipTo. IMPORTANT this is the external ID for the Customer Master integration used by Dell Boomi between SAP and SDFC. It is critical to the integrity of the data being passed from SAP</description>
    <externalId>true</externalId>
    <label>PKI SAP Customer Number</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>Accounts with business transactions associated with them</description>
    <label>Customer</label>
</RecordType>

Perkin-UAT/force-app/main/default/objects/Account/recordTypes/Test.recordType-meta.xml
<RecordType>
    <fullName>Test</fullName>
    <active>true</active>
    <label>Test</label>
</RecordType>

Perkin-UAT/force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Account Custom Tab Settings for the Account Hierarchy VF page</description>
    <label>Account Custom Tab Settings</label>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/B2B_Country_Tax_Config__mdt/B2B_Country_Tax_Config__mdt.object-meta.xml
<CustomObject>
    <description>Used to store Tax config as per countries.</description>
    <label>B2B Country Tax Config</label>
    <pluralLabel>B2B Country Tax Configs</pluralLabel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/B2B_Country_Tax_Config__mdt/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Country_Tax_Config__mdt/fields/SAP_Goods_Tax__c.field-meta.xml
<CustomField>
    <fullName>SAP_Goods_Tax__c</fullName>
    <label>SAP Goods Tax</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Country_Tax_Config__mdt/fields/Tax_Source__c.field-meta.xml
<CustomField>
    <fullName>Tax_Source__c</fullName>
    <label>Tax Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_HTTP_Service__mdt/B2B_HTTP_Service__mdt.object-meta.xml
<CustomObject>
    <description>Used to store the details of HTTP services. PERK-69</description>
    <label>B2B HTTP Service</label>
    <pluralLabel>B2B HTTP Services</pluralLabel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/B2B_HTTP_Service__mdt/fields/Auth_Codes__c.field-meta.xml
<CustomField>
    <fullName>Auth_Codes__c</fullName>
    <description>Used to store the authorization code. perk-69</description>
    <label>Auth Codes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_HTTP_Service__mdt/fields/End_Point__c.field-meta.xml
<CustomField>
    <fullName>End_Point__c</fullName>
    <description>Used to store the end point. Perk-69</description>
    <label>End Point</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_HTTP_Service__mdt/fields/Hmac_Algorithm__c.field-meta.xml
<CustomField>
    <fullName>Hmac_Algorithm__c</fullName>
    <label>Hmac Algorithm</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_HTTP_Service__mdt/fields/HTTP_Method__c.field-meta.xml
<CustomField>
    <fullName>HTTP_Method__c</fullName>
    <label>HTTP Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_HTTP_Service__mdt/fields/Org_Id_CA__c.field-meta.xml
<CustomField>
    <fullName>Org_Id_CA__c</fullName>
    <description>Org Id for Canada country</description>
    <label>Org Id CA</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_HTTP_Service__mdt/fields/Org_Id_US__c.field-meta.xml
<CustomField>
    <fullName>Org_Id_US__c</fullName>
    <description>Org ID for the US country</description>
    <label>Org Id US</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Tax_Exemption__c/B2B_Tax_Exemption__c.object-meta.xml
<CustomObject>
    <label>B2B Tax Exemption</label>
    <nameField>
        <displayFormat>TAX-{000000}</displayFormat>
        <label>B2B Tax Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B2B Tax Exemptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/B2B_Tax_Exemption__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>B2B Tax Exemptions</relationshipLabel>
    <relationshipName>B2B_Tax_Exemptions</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Tax_Exemption__c/fields/B2B_Is_Currently_Tax_Exempt__c.field-meta.xml
<CustomField>
    <fullName>B2B_Is_Currently_Tax_Exempt__c</fullName>
    <description>Formula to Check if the Date lies between the Effective date and Expiration Date</description>
    <formula>AND(
  NOT(ISBLANK(B2B_Exemption_Code__c)),
  TODAY() &gt;= B2B_Effective_Date__c,
  TODAY() &lt;= B2B_Expiration_Date__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Currently Tax Exempt?</label>
    <type>Checkbox</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Tax_Exemption__c/fields/B2B_State_Code__c.field-meta.xml
<CustomField>
    <fullName>B2B_State_Code__c</fullName>
    <label>B2B State Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NV</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
            <value>
                <fullName>NJ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/classes/B2BMetadataService.cls
/**
 * @description       : 
 * @author            : Gaurav Setia
 * @group             : 
 * @last modified on  : 02-25-2026
 * @last modified by  : Suhail Ahmed T 
**/
/* Test Class: B2BMetadataServiceTest */
public with sharing class B2BMetadataService {
  public static Map<String, Object> getTaxConfiguration(String implClassName) {
    Map<String, Object> metadataValues = new Map<String, Object>();
    
    List<B2B_HTTP_Service__mdt> metadataRecords = [
        SELECT
            End_Point__c,
            HTTP_Method__c,
            Named_Credentials__c,
            Auth_Codes__c,
            Password__c,
            Username__c,
            Hmac_Algorithm__c,
            Org_Id_CA__c,
            Org_Id_US__c,
            Impl_Class__c
        FROM B2B_HTTP_Service__mdt
        WHERE Impl_Class__c = :implClassName
        LIMIT 1
    ];
    
    if (!metadataRecords.isEmpty()) {
      B2B_HTTP_Service__mdt record = metadataRecords[0];
      metadataValues.put('EndPoint', record.End_Point__c);
      metadataValues.put('HTTPMethod', record.HTTP_Method__c);
      metadataValues.put('NamedCredential', record.Named_Credentials__c);
      metadataValues.put('HmacKey', record.Auth_Codes__c);
      metadataValues.put('Username', record.Username__c);
      metadataValues.put('Password', record.Password__c);
      metadataValues.put('HmacAlgorithm', record.Hmac_Algorithm__c);
      metadataValues.put('OrgIdCA', record.Org_Id_CA__c);
      metadataValues.put('OrgIdUS', record.Org_Id_US__c);
    }
    
    return metadataValues;
  }
  
  /**
   * Fetches tax configuration for a given currency code from B2B_Country_Tax_Config__mdt.
   */
  public static B2B_Country_Tax_Config__mdt getFlatTaxRateByCountry(String currencyCode) {
    if (String.isBlank(currencyCode)) {return null;
    }
    
    try {
      return [
            SELECT Id, Country__c, Currency_Code__c, Tax_Source__c, SAP_Goods_Tax__c 
            FROM B2B_Country_Tax_Config__mdt
            WHERE Currency_Code__c = :currencyCode
            LIMIT 1
        ];
    } catch (Exception e) {System.debug('Error fetching tax config: ' + e.getMessage());return null;
    }
  }

    //Method to fetch tax rate based on country code
     public static B2B_Country_Tax_Config__mdt getFlatTaxRateByCountryCode(String currencyCode,String countryCode) {
    if (String.isBlank(currencyCode)) {return null;
    }
    
    try {
      return [
            SELECT Id, Country__c, Currency_Code__c, Tax_Source__c, SAP_Goods_Tax__c 
            FROM B2B_Country_Tax_Config__mdt
            WHERE Currency_Code__c = :currencyCode
          AND Country_Code__c =: countryCode
            LIMIT 1
        ];
    } catch (Exception e) {System.debug('Error fetching tax config: ' + e.getMessage());return null;
    }
  }

  /**
   * Fetches the SAP Customer Number for an account.
   */
  public static String getSAPCustomerNumber(Id accountId) {
    if (accountId == null) {return null;
    }

    Account acc = [
        SELECT PKI_SAP_Customer_Number__c 
        FROM Account 
        WHERE Id = :accountId 
        LIMIT 1
    ];

    return acc != null ? acc.PKI_SAP_Customer_Number__c : null;
  }

  /**
   * Fetch if account is "Is Currently Tax Exempt" for stripe tax callout
   * @param mapParams Map containing 'accountId' and 'stateCode'
   */
  public static Boolean isAccountTaxExempt(Map<String, Object> mapParams){
    try {
        if (mapParams == null) return false;
        Id accountId = (mapParams.containsKey('accountId') && mapParams.get('accountId') != null)
            ? (Id)mapParams.get('accountId')
            : null;
        String stateCode = (mapParams.containsKey('stateCode') && mapParams.get('stateCode') != null)
            ? (String)mapParams.get('stateCode')
            : null;

        if (accountId == null || String.isBlank(stateCode)) return false;

        // First check Account's B2B_Is_Currently_Tax_Exempt__c
        Account acc = [
            SELECT B2B_Is_Currently_Tax_Exempt__c
            FROM Account
            WHERE Id = :accountId
            LIMIT 1
        ];
        if (acc != null && acc.B2B_Is_Currently_Tax_Exempt__c == true) {
            return true;
        }

        // Only check B2B_Tax_Exemption__c if Account is not tax exempt
        List<B2B_Tax_Exemption__c> exemptions = [
            SELECT Id, B2B_Is_Currently_Tax_Exempt__c
            FROM B2B_Tax_Exemption__c
            WHERE Account__c = :accountId
            AND B2B_State_Code__c = :stateCode
            LIMIT 1
        ];
        if (!exemptions.isEmpty()) {
            B2B_Tax_Exemption__c b2bTaxExemption = exemptions[0];
            return b2bTaxExemption != null && b2bTaxExemption.B2B_Is_Currently_Tax_Exempt__c == true;
        }
        return false;
    } catch (Exception e) {
        System.debug('Error fetching tax exemption: ' + e.getMessage());
        return false;
    }
  }
}