Perkin-UAT/force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Account/recordTypes/Test.recordType-meta.xml
<RecordType>
    <fullName>Test</fullName>
    <active>true</active>
    <label>Test</label>
</RecordType>

Perkin-UAT/force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Account Custom Tab Settings for the Account Hierarchy VF page</description>
    <label>Account Custom Tab Settings</label>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/Account__c/fields/Field_List__c.field-meta.xml
<CustomField>
    <fullName>Field_List__c</fullName>
    <description>The List of Fields that are to be displayed on the VF page Columns</description>
    <inlineHelpText>The List of Fields that are to be displayed on the VF page Columns</inlineHelpText>
    <label>Field List</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Account__c/fields/Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_API_Name__c</fullName>
    <description>The object API Name</description>
    <label>Object API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Account__c/fields/Tab_Name__c.field-meta.xml
<CustomField>
    <fullName>Tab_Name__c</fullName>
    <description>The Object name that will appear on the VF page as a Tab</description>
    <label>Tab Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/classes/AccountHierarchyCSVCreatorTest.cls
@isTest
private class AccountHierarchyCSVCreatorTest {

    @testSetup
    static void setupTestData() {
        // Create parent Account
        Account parentAccount = new Account(Name = 'Parent Account');
        insert parentAccount;

        // Create child Accounts
        Account childAccount1 = new Account(Name = 'Child Account 1', ParentId = parentAccount.Id);
        Account childAccount2 = new Account(Name = 'Child Account 2', ParentId = parentAccount.Id);
        insert new List<Account>{childAccount1, childAccount2};

        // Create a custom metadata record for testing
        Account__c accountMetadata = new Account__c(
            Tab_Name__c = 'Account',
            Field_List__c = 'Name,ParentId',
            Object_API_Name__c = 'Account',
            Name = 'Account c'
        );
        insert accountMetadata; 
    }

    @isTest
    static void testConstructorAndCSVGeneration() {
        // Retrieve the parent account from the test setup data
        Account parentAccount = [SELECT Id, Name FROM Account WHERE Name = 'Parent Account' LIMIT 1];

        // Set parameters for the VF page
        Test.setCurrentPageReference(new PageReference('/apex/AccountHierarchyPage'));
        ApexPages.currentPage().getParameters().put('accName', parentAccount.Name);
        ApexPages.currentPage().getParameters().put('accId', parentAccount.Id);
        ApexPages.currentPage().getParameters().put('basObj', 'Account');
        ApexPages.currentPage().getParameters().put('sortColumn', 'Name');
        ApexPages.currentPage().getParameters().put('sortOrder', 'ASC');

        // Instantiate the class
        Test.startTest();
        AccountHierarchyCSVCreator creator = new AccountHierarchyCSVCreator();
        Test.stopTest();

        // Assert that CSV data is generated correctly
        System.assertNotEquals(null, creator.CSVData, 'Expected CSVData to be populated.');
        System.assertNotEquals('', creator.textdata, 'Expected textdata to be populated.');
        System.assert(creator.textdata.contains('Parent Account'), 'Expected textdata to contain Parent Account.');
    }

    @isTest
    static void testFindChildren() {
        // Retrieve the parent account from the test setup data
        Account parentAccount = [SELECT Id FROM Account WHERE Name = 'Parent Account' LIMIT 1];

        // Call the findChildren method
        Test.startTest();
        AccountHierarchyCSVCreator.findChildren(parentAccount.Id);
        Test.stopTest();

        // Assert that child accounts were added to the hierarchy list
        //System.assert(AccountHierarchyCSVCreator.accountHierarchyList.contains(parentAccount.Id), 
        //              'Expected parent account ID to be in accountHierarchyList.');
        
        List<Account> childAccounts = [SELECT Id FROM Account WHERE ParentId = :parentAccount.Id];
        
        for (Account child : childAccounts) {
            System.assert(AccountHierarchyCSVCreator.accountHierarchyList.contains(child.Id), 
                          'Expected child account ID to be in accountHierarchyList.');
            System.assert(AccountHierarchyCSVCreator.accountDetailsMap.containsKey(child.Id), 
                          'Expected child account to be in accountDetailsMap.');
            System.assert(AccountHierarchyCSVCreator.parentChildLinkedListMap.containsKey(parentAccount.Id), 
                          'Expected parent-child relationship to exist in parentChildLinkedListMap.');
            //System.assert(AccountHierarchyCSVCreator.parentChildLinkedListMap.get(parentAccount.Id).contains(child), 
            //              'Expected child account to be linked under its parent in parentChildLinkedListMap.');
        }
    }

    @isTest
    static void testGetLabel() {
        // Call the getLabel method for a standard field
        String label = AccountHierarchyCSVCreator.getLabel('Account', 'Name');

        // Assert that the label is correct
        System.assertEquals('Account Name', label, 'Expected label for "Name" field to be "Account Name".');
    }

    @isTest
    static void testEdgeCaseNoChildren() {
        // Create an account with no children
        Account standaloneAccount = new Account(Name = 'Standalone Account');
        insert standaloneAccount;

        // Call findChildren on this standalone account
        Test.startTest();
        AccountHierarchyCSVCreator.findChildren(standaloneAccount.Id);
        Test.stopTest();

        // Assert that only this account is in the hierarchy list
        //System.assert(AccountHierarchyCSVCreator.accountHierarchyList.contains(standaloneAccount.Id), 
        //              'Expected standalone account ID to be in accountHierarchyList.');
        
        List<Account> children = [SELECT Id FROM Account WHERE ParentId = :standaloneAccount.Id];
        
        System.assertEquals(0, children.size(), 
                            'Expected no child accounts for standalone account.');
    }
}