Perkin-UAT/force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Account/recordTypes/Test.recordType-meta.xml
<RecordType>
    <fullName>Test</fullName>
    <active>true</active>
    <label>Test</label>
</RecordType>

Perkin-UAT/force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Account Custom Tab Settings for the Account Hierarchy VF page</description>
    <label>Account Custom Tab Settings</label>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/Contact/fields/INF_Product_Line__c.field-meta.xml
<CustomField>
    <fullName>INF_Product_Line__c</fullName>
    <label>INF Product Line</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>QA/QC</fullName>
            </value>
            <value>
                <fullName>Enterprise R-D</fullName>
            </value>
            <value>
                <fullName>Personal Applications</fullName>
            </value>
            <value>
                <fullName>Analysis-Visualisation</fullName>
            </value>
            <value>
                <fullName>Elements</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Contact/fields/INF_Tech_Contact__c.field-meta.xml
<CustomField>
    <fullName>INF_Tech_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tech Contact</label>
    <type>Checkbox</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/INF_Application__c/INF_Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/INF_Application__c/fields/INF_BL__c.field-meta.xml
<CustomField>
    <fullName>INF_BL__c</fullName>
    <label>Business Line</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Analysis-Visualisation</fullName>
            </value>
            <value>
                <fullName>Elements</fullName>
            </value>
            <value>
                <fullName>Enterprise R-D</fullName>
            </value>
            <value>
                <fullName>Imaging</fullName>
            </value>
            <value>
                <fullName>Personal Applications</fullName>
            </value>
            <value>
                <fullName>QA/QC</fullName>
            </value>
            <value>
                <fullName>Signals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/INF_Application__c/fields/INF_Product_Group__c.field-meta.xml
<CustomField>
    <fullName>INF_Product_Group__c</fullName>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Spotfire</fullName>
            </value>
            <value>
                <fullName>E-Notebook</fullName>
            </value>
            <value>
                <fullName>CBOE</fullName>
            </value>
            <value>
                <fullName>iLab/Limslink</fullName>
            </value>
            <value>
                <fullName>Personal Applications</fullName>
            </value>
            <value>
                <fullName>GeoSpiza</fullName>
            </value>
            <value>
                <fullName>Columbus &amp; Volocity</fullName>
            </value>
            <value>
                <fullName>Elements</fullName>
            </value>
            <value>
                <fullName>Signals Notebook</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/INF_Application__c/fields/INF_Product_Line__c.field-meta.xml
<CustomField>
    <fullName>INF_Product_Line__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AVS</fullName>
            </value>
            <value>
                <fullName>AVC</fullName>
            </value>
            <value>
                <fullName>DSK</fullName>
            </value>
            <value>
                <fullName>ENT</fullName>
            </value>
            <value>
                <fullName>QAS</fullName>
            </value>
            <value>
                <fullName>ISS</fullName>
            </value>
            <value>
                <fullName>ELM</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>SIG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/INF_Bugs_Suggestions__c/INF_Bugs_Suggestions__c.object-meta.xml
<CustomObject>
    <label>Bugs &amp; Suggestions</label>
    <nameField>
        <displayFormat>B-{00000000}</displayFormat>
        <label>Bug Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bugs &amp; Suggestions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/INF_Bugs_Suggestions__c/fields/Bug__c.field-meta.xml
<CustomField>
    <fullName>Bug__c</fullName>
    <label>Bug</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/INF_Bugs_Suggestions__c/fields/INF_Bug_Number__c.field-meta.xml
<CustomField>
    <fullName>INF_Bug_Number__c</fullName>
    <label>Bug#</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/INF_Bugs_Suggestions__c/fields/INF_Case__c.field-meta.xml
<CustomField>
    <fullName>INF_Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Bugs &amp; Suggestions</relationshipLabel>
    <relationshipName>Bugs_Suggestions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/INF_Bugs_Suggestions__c/fields/INF_Title__c.field-meta.xml
<CustomField>
    <fullName>INF_Title__c</fullName>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/INF_Bugs_Suggestions__c/fields/INF_Type__c.field-meta.xml
<CustomField>
    <fullName>INF_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bug</fullName>
                <default>true</default>
                <label>Bug</label>
            </value>
            <value>
                <fullName>Suggestion</fullName>
            </value>
            <value>
                <fullName>Tibco Bug</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/INF_Case_Application__c/INF_Case_Application__c.object-meta.xml
<CustomObject>
    <label>Case Application</label>
    <nameField>
        <displayFormat>CA-{000000000}</displayFormat>
        <label>Case Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/INF_Case_Application__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>INF_Application__c</referenceTo>
    <relationshipLabel>Case Applications</relationshipLabel>
    <relationshipName>Case_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/INF_Case_Application__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Applications</relationshipLabel>
    <relationshipName>Case_Applications</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/INF_Case_Survey__c/INF_Case_Survey__c.object-meta.xml
<CustomObject>
    <label>Case Survey</label>
    <nameField>
        <displayFormat>Survey-{0000}</displayFormat>
        <label>Case Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Surveys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/INF_Case_Survey__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Surveys</relationshipLabel>
    <relationshipName>Case_Surveys</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/INF_Case_Survey__c/fields/INF_Recently_Created_Survey__c.field-meta.xml
<CustomField>
    <fullName>INF_Recently_Created_Survey__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Recently Created Survey</label>
    <type>Checkbox</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/INF_Case_Survey__c/fields/INF_Support_Sat_Bin__c.field-meta.xml
<CustomField>
    <fullName>INF_Support_Sat_Bin__c</fullName>
    <label>Support Satisfaction Bin</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Difficult</fullName>
            </value>
            <value>
                <fullName>Easy</fullName>
            </value>
            <value>
                <fullName>Excellent Product</fullName>
            </value>
            <value>
                <fullName>Excellent Service</fullName>
            </value>
            <value>
                <fullName>Fast Resolution</fullName>
            </value>
            <value>
                <fullName>Frequency of Updates</fullName>
            </value>
            <value>
                <fullName>Neither</fullName>
            </value>
            <value>
                <fullName>No Solution</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Phone Issues</fullName>
            </value>
            <value>
                <fullName>Problem Solved</fullName>
            </value>
            <value>
                <fullName>Rep Communication Skills</fullName>
            </value>
            <value>
                <fullName>Rep Understanding of the Problem</fullName>
            </value>
            <value>
                <fullName>SDK</fullName>
            </value>
            <value>
                <fullName>Software Activation</fullName>
            </value>
            <value>
                <fullName>Software Defect</fullName>
            </value>
            <value>
                <fullName>Took too long</fullName>
            </value>
            <value>
                <fullName>Unsupported Environment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/INF_Case_Survey__c/fields/INF_Support_sat_Comments__c.field-meta.xml
<CustomField>
    <fullName>INF_Support_sat_Comments__c</fullName>
    <label>Support Satisfaction Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/INF_Case_Survey__c/fields/INF_Support_Sat_No__c.field-meta.xml
<CustomField>
    <fullName>INF_Support_Sat_No__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Support Satisfaction No</label>
    <type>Checkbox</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/INFEnvironmentalData__c/INFEnvironmentalData__c.object-meta.xml
<CustomObject>
    <label>Environment</label>
    <nameField>
        <label>Evironment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/INFEnvironmentalData__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Environments</relationshipLabel>
    <relationshipName>Environment</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Lead/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads (Account)</relationshipLabel>
    <relationshipName>Leads2</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Lead/fields/INF_Related_case__c.field-meta.xml
<CustomField>
    <fullName>INF_Related_case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/classes/CaseMergeControllerTest.cls
@isTest
public class CaseMergeControllerTest{
    static testMethod void searchTaskTestMethod(){
        Account acc = CT_TestDataSetupUtility.createTestAccount('TEST','77778','Test');
        insert acc;
        Contact con = CT_TestDataSetupUtility.createTestContact(acc.id,'test','test','test@test.com');
        insert con;
        Case casetoinsert = CT_TestDataSetupUtility.createTestCase('Informatics','New','test','Phone',acc.id,con.id);
        insert casetoinsert;
        Lead leadinsert = new Lead(LastName = 'Test User',
                                   Company = 'Test Company',
                                   Phone = '8005551212',
                                   Fax = '8005551212',
                                   Email = 'sumit.shingavi@cloudsherpas.com',
                                   Street = '123 Main Street',
                                   City = 'Pleasantville',
                                   State = 'New Jersey',
                                   PostalCode = '66666',
                                   Country = 'US',
                                   Status = 'New',INF_Related_case__c=casetoinsert.Id);
        
        insert leadinsert;
        CaseComment casecomment = CT_TestDataSetupUtility.createTestCaseComment(casetoinsert.id,'test');
        insert casecomment;
        EmailMessage em = new EmailMessage (Subject='test',ccAddress='test@perkinelmer.com.pkisbxfull.full;',MessageDate=Date.Today(),TextBody='test',HtmlBody='test',Incoming = true,Status ='3',Parentid=casetoinsert.id);
        insert em;
        Attachment att = new Attachment(Name='test',Body=Blob.valueof('test'),Parentid=casetoinsert.id);
        insert att;
        
        INF_Bugs_Suggestions__c bugs = new INF_Bugs_Suggestions__c (Bug__c='test',INF_Bug_Number__c='test',INF_Title__c='test',INF_Type__c='Bug',INF_Case__c =casetoinsert.id);
        insert bugs;
        
        Task taskcall = new Task(Subject='test',Description='test',Type ='Phone Call',Status ='Completed',WhatId =casetoinsert.id );
        insert taskcall;
        
        Task taskemail = new Task(Subject='test',Description='test',Type ='Email',Status ='Completed',WhatId =casetoinsert.id );
        insert taskemail;
        
        INF_Case_Survey__c  survey = new INF_Case_Survey__c(INF_Recently_Created_Survey__c=true,INF_Support_Sat_Bin__c='test',INF_Support_sat_Comments__c='test',INF_Support_Sat_No__c=true,Case__c=casetoinsert.id);
        insert survey;
        
        Case casetoinsert1 = CT_TestDataSetupUtility.createTestCase('Informatics','New','test','Phone',acc.id,con.id);
        insert casetoinsert1;
        
        Test.startTest();
        Test.setCurrentPage(new PageReference('/apex/MergeCase?id='+casetoinsert1.Id));
        CaseMergeController jpc = new CaseMergeController(new ApexPages.StandardController(casetoinsert1));
        jpc.mrgCase.ParentId = casetoinsert.id;
        jpc.mergecase();
        jpc.cancel();
        Test.stopTest();
    }
    
    static testMethod void searchTaskTestMethod1(){
        
        Account acc = CT_TestDataSetupUtility.createTestAccount('TEST','77778','Test');
        insert acc;
        Contact con = CT_TestDataSetupUtility.createTestContact(acc.id,'test','test','test@test.com');
        insert con;
        Case casetoinsert = CT_TestDataSetupUtility.createTestCase('Informatics','New','test','Phone',acc.id,con.id);
        insert casetoinsert;
        
        Lead leadinsert = new Lead( LastName = 'Test User',
                                   Company = 'Test Company',
                                   Phone = '8005551212',
                                   Fax = '8005551212',
                                   Email = 'sumit.shingavi@cloudsherpas.com',
                                   Street = '123 Main Street',
                                   City = 'Pleasantville',
                                   State = 'New Jersey',
                                   PostalCode = '66666',
                                   Country = 'US',
                                   Status = 'New',INF_Related_case__c=casetoinsert.Id);
        
        insert leadinsert;
        Task taskcall = new Task(Subject='test',Description='test',Type ='Phone Call',Status ='Completed',WhatId =casetoinsert.id );
        insert taskcall;
        
        Task taskemail = new Task(Subject='test',Description='test',Type ='Email',Status ='Completed',WhatId =casetoinsert.id );
        insert taskemail;
        
        Test.startTest();
        Test.setCurrentPage(new PageReference('/apex/CaseEditPage?id='+casetoinsert.Id));
        CaseEditController jpc = new CaseEditController(new ApexPages.StandardController(casetoinsert));
        jpc.cancel();
        jpc.save();
        jpc.getCase();
        Test.stopTest();
    }
    
    static testMethod void searchTaskTestMethod2(){
        
        Account acc = CT_TestDataSetupUtility.createTestAccount('TEST','77778','Test');
        insert acc;
        Contact con = CT_TestDataSetupUtility.createTestContact(acc.id,'test','test','test@test.com');
        insert con;
        Case casetoinsert = CT_TestDataSetupUtility.createTestCase('Informatics','New','test','Phone',acc.id,con.id);
        insert casetoinsert;
        
        Lead leadinsert = new Lead( LastName = 'Test User',
                                   Company = 'Test Company',
                                   Phone = '8005551212',
                                   Fax = '8005551212',
                                   Email = 'sumit.shingavi@cloudsherpas.com',
                                   Street = '123 Main Street',
                                   City = 'Pleasantville',
                                   State = 'New Jersey',
                                   PostalCode = '66666',
                                   Country = 'US',
                                   Status = 'New',INF_Related_case__c=casetoinsert.Id);
        
        insert leadinsert;
        INF_Application__c app = new INF_Application__c(Name='test',INF_Product_Group__c='CBOE',INF_Product_Line__c ='test',INF_BL__c='test');
        insert app;
        INF_Case_Application__c caseapp = new INF_Case_Application__c(Application__c=app.id,Case__c = casetoinsert.id);
        insert caseapp;
        
        Task taskcall = new Task(Subject='test',Description='test',Type ='Phone Call',Status ='Completed',WhatId =casetoinsert.id );
        insert taskcall;
        
        Task taskemail = new Task(Subject='test',Description='test',Type ='Email',Status ='Completed',WhatId =casetoinsert.id );
        insert taskemail;
        Set<Id> caseids = new Set<Id>();
        caseids.add(casetoinsert.id);
        delete caseapp;
    }
    
    static testMethod void searchTaskTestMethod4(){
        Id caseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Informatics').getRecordTypeId();
        Account acc = CT_TestDataSetupUtility.createTestAccount('TEST','77778','Test');
        insert acc;
        Contact con = CT_TestDataSetupUtility.createTestContact(acc.id,'test','test','test@test.com');
        insert con;
        Case casetoinsert = CT_TestDataSetupUtility.createTestCase('Informatics','New','test','Phone',acc.id,con.id);
        insert casetoinsert;
        
        Lead leadinsert = new Lead( LastName = 'Test User',
                                   Company = 'Test Company',
                                   Phone = '8005551212',
                                   Fax = '8005551212',
                                   Email = 'sumit.shingavi@cloudsherpas.com',
                                   Street = '123 Main Street',
                                   City = 'Pleasantville',
                                   State = 'New Jersey',
                                   PostalCode = '66666',
                                   Country = 'US',
                                   Status = 'New',INF_Related_case__c=casetoinsert.Id);
        
        insert leadinsert;
        
        Task taskcall = new Task(Subject='test',Description='test',Type ='Phone Call',Status ='Completed',WhatId =casetoinsert.id );
        insert taskcall;
        
        Task taskemail = new Task(Subject='test',Description='test',Type ='Email',Status ='Completed',WhatId =casetoinsert.id );
        insert taskemail;
        casetoinsert.RecordTypeId = caseRecordTypeId;
        update casetoinsert;
        EmailMessage em = new EmailMessage (Subject='test',MessageDate=Date.Today(),TextBody='test',HtmlBody='test',Incoming = false,Status ='3',Parentid=casetoinsert.id);
        insert em;
    }
    
    static testMethod void searchTaskTestMethod21(){
        
        Account acc = CT_TestDataSetupUtility.createTestAccount('TEST','77778','Test');
        insert acc;
        Contact con = CT_TestDataSetupUtility.createTestContact(acc.id,'test','test','test@test.com');
        insert con;
        Contact con1 = CT_TestDataSetupUtility.createTestContact(acc.id,'test','test','test1@test.com');
        insert con1;
        
        Case casetoinsert = CT_TestDataSetupUtility.createTestCase('Informatics','New','test','Phone',acc.id,con.id);
        insert casetoinsert;
        
        Lead leadinsert = new Lead( LastName = 'Test User',
                                   Company = 'Test Company',
                                   Phone = '8005551212',
                                   Fax = '8005551212',
                                   Email = 'sumit.shingavi@cloudsherpas.com',
                                   Street = '123 Main Street',
                                   City = 'Pleasantville',
                                   State = 'New Jersey',
                                   PostalCode = '66666',
                                   Country = 'US',
                                   Status = 'New',INF_Related_case__c=casetoinsert.Id);
        
        insert leadinsert;
        
        Task taskcall = new Task(Subject='test',Description='test',Type ='Phone Call',Status ='Completed',WhatId =casetoinsert.id );
        insert taskcall;
        
        Task taskemail = new Task(Subject='test',Description='test',Type ='Email',Status ='Completed',WhatId =casetoinsert.id );
        insert taskemail;
        
        con1.INF_Tech_Contact__c =TRUE;
        update con1;
        INFEnvironmentalData__c env = new INFEnvironmentalData__c(Name='test',Account__c=acc.id);
        insert env;
        EmailTemplate emtemp = [select id from EmailTemplate where isActive = TRUE LIMIT 1];    
        SendMassEmail.SendEmail(String.Valueof(con1.id),emtemp.id);
    }
}