Perkin-UAT/force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Account/recordTypes/Test.recordType-meta.xml
<RecordType>
    <fullName>Test</fullName>
    <active>true</active>
    <label>Test</label>
</RecordType>

Perkin-UAT/force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Account Custom Tab Settings for the Account Hierarchy VF page</description>
    <label>Account Custom Tab Settings</label>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/Account__c/fields/Field_List__c.field-meta.xml
<CustomField>
    <fullName>Field_List__c</fullName>
    <description>The List of Fields that are to be displayed on the VF page Columns</description>
    <inlineHelpText>The List of Fields that are to be displayed on the VF page Columns</inlineHelpText>
    <label>Field List</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Account__c/fields/Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_API_Name__c</fullName>
    <description>The object API Name</description>
    <label>Object API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Account__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <description>The Order in which the Object tab has to be displayed</description>
    <inlineHelpText>The Order in which the tab has to be displayed</inlineHelpText>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Account__c/fields/Tab_Name__c.field-meta.xml
<CustomField>
    <fullName>Tab_Name__c</fullName>
    <description>The Object name that will appear on the VF page as a Tab</description>
    <label>Tab Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/classes/TestAccountHierarchy.cls
@isTest(seeAllData=true)
public class TestAccountHierarchy {
    public static AccountHierarchyController controller;
    public static Account testAccountOne;
    public static AccountHierarchyCSVCreator csvCreator;
    @isTest
    public static void testOne(){
        testAccountOne =  new Account(Name='Test Account One');
        insert testAccountOne;
        Account testAccountTwo =  new Account(Name='Test Account two',ParentId=testAccountOne.id);
        insert testAccountTwo;
        Account testAccountThree =  new Account(Name='Test Account three',ParentId=testAccountTwo.id);
        insert testAccountThree;
        Account testAccountFour =  new Account(Name='Test Account four',ParentId=testAccountThree.id);
        insert testAccountFour;
         
        Contact contactOneAccountOne = new Contact(FirstName='Test Contact One',LastName='Account One',AccountId=testAccountOne.id);
        insert contactOneAccountOne;
        Contact contactTwoAccountTwo = new Contact(FirstName='Test Contact Two',LastName='Account Two',AccountId=testAccountTwo.id);
        insert contactTwoAccountTwo;
        Contact contactThreeAccountThree = new Contact(FirstName='Test Contact Three',LastName='Account Three',AccountId=testAccountThree.id);
        insert contactThreeAccountThree;
        Contact contactFourAccountFour = new Contact(FirstName='Test Contact Four',LastName='Account Four',AccountId=testAccountFour.id);
        insert contactFourAccountFour;
        
        Asset assetOneAccountOne = new Asset(Name='Test Asset One',AccountId=testAccountOne.id);
        insert assetOneAccountOne;
        Asset assetTwoAccountTwo = new Asset(Name='Test Asset Two',AccountId=testAccountTwo.id);
        insert assetTwoAccountTwo;
        Asset assetThreeAccountThree = new Asset(Name='Test Asset Three',AccountId=testAccountThree.id);
        insert assetThreeAccountThree;
        Asset assetFourAccountFour = new Asset(Name='Test Asset Four',AccountId=testAccountFour.id);
        insert assetFourAccountFour;
        
        Account__c acc=new Account__c();
        acc.Tab_Name__c='Accounts';
        acc.Object_API_Name__c='Account';
        acc.Name='Account';
        acc.Field_List__c='Name,Type';
        acc.Sort_Order__c=1;
        insert acc;
        
        ApexPages.StandardController sc = new ApexPages.StandardController(testAccountOne);
        controller = new AccountHierarchyController(sc);
        
        List<Account__c> tabSetting = new List<Account__c>(); 
        tabSetting =  [SELECT Tab_Name__c,Field_List__c,Object_API_Name__c 
                                  FROM Account__c ];
       Pagereference pageRef = new PageReference('/Account_Hierarchy') ;
       pageRef.getParameters().put('id',testAccountOne.id);                          
       system.Test.setCurrentPage(pageRef);
       
       if(tabSetting.size() == 0){
           AccountHierarchyController.getDataList('Accounts',testAccountOne.id);
            controller.sortOrder = 'ASC';
            controller.sortColumn = '1';
            controller.sortBaseObject = 'Accounts';
            controller.exportToCSV();
           
       }
                                  
       for(Account__c setting:tabSetting){
            AccountHierarchyController.getDataList(setting.Tab_Name__c,testAccountOne.id);
            controller.sortOrder = 'ASC';
            controller.sortColumn = '1';
            controller.sortBaseObject = setting.Tab_Name__c;
            controller.exportToCSV();
        }  
      pageRef = new PageReference('/AccountHierarchyCSVPage') ;
        pageRef.getParameters().put('accName',testAccountOne.Name);
        pageRef.getParameters().put('accId',testAccountOne.id);
        for(Account__c setting:tabSetting){
            pageRef.getParameters().put('basObj',setting.Tab_Name__c);
            pageRef.getParameters().put('sortColumn',setting.Field_List__c.split(',')[Integer.ValueOf(controller.sortColumn)]);
            pageRef.getParameters().put('sortOrder','ASC');
            system.Test.setCurrentPage(pageRef);
            csvCreator = new AccountHierarchyCSVCreator();  
        }
        
                             
    }
    
    
}