Perkin-UAT/force-app/main/default/objects/Account/fields/fxSearchCity__c.field-meta.xml
<CustomField>
    <fullName>fxSearchCity__c</fullName>
    <description>This field is created per ATEAM-1366 and is used to store the ShippingCity into plain english character for Diacritics using A.CLS: CharacterReplaceFunction</description>
    <label>fxSearchCity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Account/fields/fxSearchName__c.field-meta.xml
<CustomField>
    <fullName>fxSearchName__c</fullName>
    <description>This field is created per ATEAM-1366 and is used to store the Account Name into plain english character for Diacritics using A.CLS: CharacterReplaceFunction</description>
    <label>fxSearchName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Account/fields/fxSearchStreet__c.field-meta.xml
<CustomField>
    <fullName>fxSearchStreet__c</fullName>
    <description>This field is created per ATEAM-1366 and is used to store the ShippingStreet into plain english character for Diacritics using A.CLS: CharacterReplaceFunction</description>
    <label>fxSearchStreet</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Account/fields/PKI_SAP_Account_Group__c.field-meta.xml
<CustomField>
    <fullName>PKI_SAP_Account_Group__c</fullName>
    <defaultValue>&quot;OMIT&quot;</defaultValue>
    <label>SAP Account Group</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Account/fields/PKI_SAP_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>PKI_SAP_Customer_Number__c</fullName>
    <description>SAP - KNA1/KUNNR. Customer number for SoldToShipTo. IMPORTANT this is the external ID for the Customer Master integration used by Dell Boomi between SAP and SDFC. It is critical to the integrity of the data being passed from SAP</description>
    <externalId>true</externalId>
    <label>PKI SAP Customer Number</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Account/recordTypes/Test.recordType-meta.xml
<RecordType>
    <fullName>Test</fullName>
    <active>true</active>
    <label>Test</label>
</RecordType>

Perkin-UAT/force-app/main/default/classes/SmartSearchApexController_Test.cls
@isTest
private class SmartSearchApexController_Test {
  @testSetup
  static void createTestData() {
    Id accountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
      .get('Prospect')
      .getRecordTypeId();

    Account acc = (Account) PKI_Data_Factory.createSObject(
      new Account(
        fxSearchCity__c = 'São Paulo',
        PKI_SAP_Customer_Number__c = '123456',
        RecordTypeId = accountRecordTypeId,
        PKI_SAP_Account_Group__c = 'SFDC',
        fxSearchName__c = 'TEST PKI Account',
        fxSearchStreet__c = '123 TEST street'
      ),
      true
    );
  }

  @isTest
  static void test_fetchAccount() {
    List<Account> account_Obj = [SELECT Id FROM ACCOUNT LIMIT 1];
    SmartSearchApexController.Inputs inputs = new SmartSearchApexController.Inputs();
    inputs.searchStreet = '123 TEST street';
    inputs.maxResults = 3;
    inputs.searchKeyWord = 'TEST PKI Account';
    inputs.searchCity = 'São Paulo';
    inputs.searchCountry = 'BR';
    inputs.searchSAP = '123456';

    Test.startTest();
    String res = SmartSearchApexController.retrieveSearchResults(
      JSON.serialize(inputs)
    );
    SmartSearchApexController.result results = (SmartSearchApexController.result) JSON.deserialize(
      res,
      SmartSearchApexController.result.class
    );
    Test.stopTest();
    System.assertEquals(
      false,
      results.isMore,
      'should have  been false as no more results than returned'
    );
    System.assert(String.isBlank(results.message));
    System.assertEquals(1, results.accounts.size());
  }
}