Perkin-UAT/force-app/main/default/objects/Account/fields/Market_Segment__c.field-meta.xml
<CustomField>
    <fullName>Market_Segment__c</fullName>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Academic</fullName>
            </value>
            <value>
                <fullName>ADMET</fullName>
            </value>
            <value>
                <fullName>Aerospace</fullName>
            </value>
            <value>
                <fullName>Agriculture &amp; Feed</fullName>
            </value>
            <value>
                <fullName>API Synthesis/Scale-Up</fullName>
            </value>
            <value>
                <fullName>Assay Development</fullName>
            </value>
            <value>
                <fullName>Automotive &amp; Machinery</fullName>
            </value>
            <value>
                <fullName>BEER BEV AND WINE</fullName>
            </value>
            <value>
                <fullName>BioTech</fullName>
            </value>
            <value>
                <fullName>Cancer</fullName>
            </value>
            <value>
                <fullName>Cell Biology</fullName>
            </value>
            <value>
                <fullName>Chemicals</fullName>
            </value>
            <value>
                <fullName>Clinical Research</fullName>
            </value>
            <value>
                <fullName>COMMERCIAL CONTRACT TESTING LABS</fullName>
            </value>
            <value>
                <fullName>Environmental</fullName>
            </value>
            <value>
                <fullName>FEED &amp; PET FOOD</fullName>
            </value>
            <value>
                <fullName>Forensic Science</fullName>
            </value>
            <value>
                <fullName>Genomics/Genetics</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>GRAIN GENERAL &amp; TRADE UNPROCESSED (INCL FARMERS)</fullName>
            </value>
            <value>
                <fullName>GRAIN PROCESSING (INCL STARCH PRODUCTION)</fullName>
            </value>
            <value>
                <fullName>Hospitals &amp; Clinics</fullName>
            </value>
            <value>
                <fullName>Immunology</fullName>
            </value>
            <value>
                <fullName>Independent Testing</fullName>
            </value>
            <value>
                <fullName>Lead Discovery</fullName>
            </value>
            <value>
                <fullName>Lead Validation &amp; Optimization</fullName>
            </value>
            <value>
                <fullName>LIQUID MILK</fullName>
            </value>
            <value>
                <fullName>MEAT</fullName>
            </value>
            <value>
                <fullName>Metals</fullName>
            </value>
            <value>
                <fullName>Microbiology</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Account/recordTypes/Test.recordType-meta.xml
<RecordType>
    <fullName>Test</fullName>
    <active>true</active>
    <label>Test</label>
</RecordType>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Dealer_Portal_Opp__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Portal_Opp__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dealer Portal Opp</label>
    <type>Checkbox</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Market_Segment__c.field-meta.xml
<CustomField>
    <fullName>Market_Segment__c</fullName>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Academia</fullName>
            </value>
            <value>
                <fullName>Aerospace</fullName>
            </value>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Biofuels</fullName>
            </value>
            <value>
                <fullName>Cellular Research</fullName>
            </value>
            <value>
                <fullName>Chemicals</fullName>
            </value>
            <value>
                <fullName>Clinical / Biomonitoring</fullName>
            </value>
            <value>
                <fullName>Clinical Genetics and Diagnostics</fullName>
            </value>
            <value>
                <fullName>Consumer products and Product Safety</fullName>
            </value>
            <value>
                <fullName>Consumer Products Supplier</fullName>
            </value>
            <value>
                <fullName>Research and Drug Discovery</fullName>
            </value>
            <value>
                <fullName>Electronics / Electroplating</fullName>
            </value>
            <value>
                <fullName>Environmental</fullName>
            </value>
            <value>
                <fullName>Foods &amp; Beverages</fullName>
            </value>
            <value>
                <fullName>Forensics</fullName>
            </value>
            <value>
                <fullName>General Manufacturing</fullName>
            </value>
            <value>
                <fullName>Genomics</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Homeland Security</fullName>
            </value>
            <value>
                <fullName>Imaging</fullName>
            </value>
            <value>
                <fullName>Life Science Research</fullName>
            </value>
            <value>
                <fullName>Lubricants</fullName>
            </value>
            <value>
                <fullName>Mining</fullName>
            </value>
            <value>
                <fullName>Mining / Metal</fullName>
            </value>
            <value>
                <fullName>NGS</fullName>
            </value>
            <value>
                <fullName>Nuclear</fullName>
            </value>
            <value>
                <fullName>Nuclear Power and Radiation Safety</fullName>
            </value>
            <value>
                <fullName>Nutraceuticals</fullName>
            </value>
            <value>
                <fullName>Optics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Revenue_Rec_Date__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Rec_Date__c</fullName>
    <inlineHelpText>Revenue Recognition Date. Typically set as 5 days from close date unless you provide a different date.</inlineHelpText>
    <label>Revenue Rec Date</label>
    <type>Date</type>
</CustomField>

Perkin-UAT/force-app/main/default/classes/test_revenue_rec_date_populate.cls
@isTest
private class test_revenue_rec_date_populate
{
   public static opportunity opp;
   public static user user2;
  static testMethod void testinsert() {
    //create opportunity
    opportunity test_o = new opportunity();
    test_o.Name = 'Test';
    test_o.StageName = 'Stage 1 - Qualification';
    test_o.CloseDate = date.parse('3/10/2012');
    test_o.Revenue_rec_date__c = date.parse('3/1/2012');
    test_o.Market_Segment__c = 'Duplicate';
    test_o.Type = 'New Business';  
    test_o.Dealer_Portal_Opp__c = true;                                     
     insert test_o;                                    
    }
  static testmethod void testDealerPortal(){
    //Create user
        //UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
        Profile profile1 = [Select Id from Profile where name = 'System Administrator'];
        User portalAccountOwner1 = new User(
                   // UserRoleId = portalRole.Id,
                    ProfileId = profile1.Id,
                    Username = System.now().millisecond() + 'test2@test.com1',
                    Alias = 'batman',
                    Email='bruce.wayne@wayneenterprises.com',
                    EmailEncodingKey='UTF-8',
                    Firstname='Bruce',
                    Lastname='Wayne',
                    LanguageLocaleKey='en_US',
                    LocaleSidKey='en_US',
                    TimeZoneSidKey='America/Chicago'
        );
        
        Database.insert(portalAccountOwner1);
        Account portalAccount1;
        Contact contact1;
        System.runAs(portalAccountOwner1){
        //Create account
        portalAccount1 = new Account(
                        Name = 'TestAccount',
            			ShippingStreet = 'Test',
            			ShippingCity = 'Test',
            			ShippingPostalCode = '123456',
            			ShippingState = 'test',
            			ShippingCountry = 'IN',
                        OwnerId = portalAccountOwner1.Id
        );
        Database.insert(portalAccount1);
        
        //Create contact
        contact1 = new Contact(
        FirstName = 'Test',
        Lastname = 'McTesty',
        AccountId = portalAccount1.Id,
        Email = System.now().millisecond() + 'test@test.com'
		);
		Database.insert(contact1);
		}      
		//Profile portalProfile = [SELECT Id FROM Profile WHERE Name LIKE 'Dx Partner Community User' Limit 1];
		User user1 = new User(
   			Username = System.now().millisecond() + 'test12345@test.com1',
//    		ContactId = contact1.Id,
    		ProfileId = profile1.Id,
    		Alias = 'test123',
    		Email = 'test12345@test.com',
    		EmailEncodingKey = 'UTF-8',
    		LastName = 'McTesty',
    		CommunityNickname = 'test12345',
    		TimeZoneSidKey = 'America/Los_Angeles',
    		LocaleSidKey = 'en_US',
    		LanguageLocaleKey = 'en_US'
		);
		Database.insert(user1);
        Exception msg;
        Opportunity O = new Opportunity();
    //    RecordType r = [select Id from RecordType Where DeveloperName = 'Dx_EMEA_Record_Type']; removing reference for Dx_EMEA_Record_Type
    RecordType r = [SELECT SobjectType, Id, Name FROM RecordType where SobjectType ='opportunity' AND developername='PKI_Americas_SPI' limit 1];
        test.startTest();
        System.runAs(user1){
            o.name = 'test opp';
            O.StageName = 'Stage 1 - Create/Plan';
            o.RecordTypeId = r.id;
            o.CloseDate = Date.today().adddays(5);
            insert o;
            o.stageName = 'Stage 4 - prove';
         
            update o; 
        }
       test.stopTest();
        List<ProcessInstance> pi = [Select Id,(Select Id From Workitems) From ProcessInstance Where TargetObjectId = :o.id];
      if(pi != null && pi.size()>0){
          Id WorkItemId = pi[0].WorkItems[0].Id;
        Approval.ProcessWorkitemRequest req2 = new Approval.ProcessWorkitemRequest();
		req2.setComments('Approving request.');
		req2.setAction('Approve');
        req2.setWorkitemId(WorkItemId);
        Approval.ProcessResult result2 =  Approval.process(req2);
      }  
      
      /* this.opp = o;
       this.user2 = user1;
      System.runAs(user1){
		 try{
               o.stageName = 'Closed/Won';
               update o; 
            }
         catch(Exception e){
                msg = e;
            }*/
		
     // }
     }
    static testmethod void testDealerPortal2(){
       Profile profile1 = [Select Id from Profile where name = 'System Administrator'];
        User portalAccountOwner1 = new User(
                   // UserRoleId = portalRole.Id,
                    ProfileId = profile1.Id,
                    Username = System.now().millisecond() + 'test2@test.com1',
                    Alias = 'batman',
                    Email='bruce.wayne@wayneenterprises.com',
                    EmailEncodingKey='UTF-8',
                    Firstname='Bruce',
                    Lastname='Wayne',
                    LanguageLocaleKey='en_US',
                    LocaleSidKey='en_US',
                    TimeZoneSidKey='America/Chicago'
        );
        
        Database.insert(portalAccountOwner1);
        Account portalAccount1;
        Contact contact1;
        System.runAs(portalAccountOwner1){
        //Create account
        portalAccount1 = new Account(
                        Name = 'TestAccount',
            			ShippingStreet = 'Test',
            			ShippingCity = 'Test',
            			ShippingPostalCode = '123456',
            			ShippingState = 'test',
            			ShippingCountry = 'IN',
                        OwnerId = portalAccountOwner1.Id
        );
        Database.insert(portalAccount1);
        
        //Create contact
        contact1 = new Contact(
        FirstName = 'Test',
        Lastname = 'McTesty',
        AccountId = portalAccount1.Id,
        Email = System.now().millisecond() + 'test@test.com'
		);
		Database.insert(contact1);
		}      
		//Profile portalProfile = [SELECT Id FROM Profile WHERE Name LIKE 'Dx Partner Community User' Limit 1];
		User user1 = new User(
   			Username = System.now().millisecond() + 'test12345@test.com1',
//    		ContactId = contact1.Id,
    		ProfileId = profile1.Id,
    		Alias = 'test123',
    		Email = 'test12345@test.com',
    		EmailEncodingKey = 'UTF-8',
    		LastName = 'McTesty',
    		CommunityNickname = 'test12345',
    		TimeZoneSidKey = 'America/Los_Angeles',
    		LocaleSidKey = 'en_US',
    		LanguageLocaleKey = 'en_US'
		);
		Database.insert(user1);
        Exception msg;
        Opportunity O = new Opportunity();
     //   RecordType r = [select Id from RecordType Where DeveloperName = 'Dx_EMEA_Record_Type']; removing reference for Dx_EMEA_Record_Type 
        RecordType r = [SELECT SobjectType, Id, Name FROM RecordType where SobjectType ='opportunity' AND developername='PKI_Americas_SPI' limit 1];
        System.runAs(user1){
            o.name = 'test opp';
            O.StageName = 'Stage 1 - Create/Plan';
            o.RecordTypeId = r.id;
            o.CloseDate = Date.today().adddays(5);
            insert o;
            o.stageName = 'Stage 4 - prove';
         
            update o; 
        }
       test.startTest();
        List<ProcessInstance> pi = [Select Id,(Select Id From Workitems) From ProcessInstance Where TargetObjectId = :o.id];
        if(pi != null && pi.size()>0){
        Id WorkItemId = pi[0].WorkItems[0].Id;
         Approval.ProcessWorkitemRequest req2 = new Approval.ProcessWorkitemRequest();
		req2.setComments('Approving request.');
		req2.setAction('Approve');
        req2.setWorkitemId(WorkItemId);
        Approval.ProcessResult result2 =  Approval.process(req2);
        }
	   system.debug('Stage now' + o.StageName);
        
        
       System.runAs(user1){
		 try{
               o.stageName = 'Closed Won';
               update o; 
            }
         catch(Exception e){
                msg = e;
            }
		
     }
        Attachment att = new Attachment();
        att.parentId = o.id;
        att.Name ='Quote';
        att.body = Blob.valueof('Empty test');
        insert att;
        
        ContentVersion contentVersion = new ContentVersion(
  			 Title = 'Quote New',
 			 PathOnClient = 'Quote.docx',
  			 VersionData = Blob.valueOf('Test Content')
			);
			insert contentVersion;    
		List<ContentDocument> cd = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];

        ContentDocumentLink cl = new ContentDocumentLink();
        cl.ContentDocumentId = cd[0].id;
        cl.LinkedEntityId = o.id;
        cl.ShareType = 'V';
        upsert cl;
        o.StageName = 'Closed Won';
        update o;
	 test.stopTest();
    }
  }