Perkin-UAT/force-app/main/default/objects/Account/fields/MDM_Status__c.field-meta.xml
<CustomField>
    <fullName>MDM_Status__c</fullName>
    <label>MDM Status</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Account/fields/Opportunity_Info__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Info__c</fullName>
    <description>Displays concatenated opportunity details on account</description>
    <formula>&#39;Open:&#39; + Text(No_Of_Open_Opportunities_INF__c) + &#39;/Closed:&#39; +  Text(No_Of_Closed_Won_Opportunities_INF__c)</formula>
    <label>Opportunity Info</label>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Account/fields/PKI_SAP_Account_Group__c.field-meta.xml
<CustomField>
    <fullName>PKI_SAP_Account_Group__c</fullName>
    <defaultValue>&quot;OMIT&quot;</defaultValue>
    <label>SAP Account Group</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Account/fields/PKI_SAP_Customer_Base_Name__c.field-meta.xml
<CustomField>
    <fullName>PKI_SAP_Customer_Base_Name__c</fullName>
    <description>SAP - KNA1/HNAME1. Standard name applied to all related accounts in the hierarchy</description>
    <label>PKI SAP Customer Base Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Account/fields/PKI_SAP_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>PKI_SAP_Customer_Number__c</fullName>
    <description>SAP - KNA1/KUNNR. Customer number for SoldToShipTo. IMPORTANT this is the external ID for the Customer Master integration used by Dell Boomi between SAP and SDFC. It is critical to the integrity of the data being passed from SAP</description>
    <externalId>true</externalId>
    <label>PKI SAP Customer Number</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Account/fields/PKI_SAP_Name_2__c.field-meta.xml
<CustomField>
    <fullName>PKI_SAP_Name_2__c</fullName>
    <description>SAP - KNA1/NAME2
MG changed label to &#39;Account Name 2&#39;  7-21-20  API name stays same</description>
    <label>Account Name 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Account/fields/PKI_SAP_Name_3__c.field-meta.xml
<CustomField>
    <fullName>PKI_SAP_Name_3__c</fullName>
    <description>SAP - KNA1/NAME3</description>
    <label>NAME3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Account/fields/PKI_SAP_Name_4__c.field-meta.xml
<CustomField>
    <fullName>PKI_SAP_Name_4__c</fullName>
    <description>SAP - KNA1/NAME4</description>
    <label>NAME4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Account/fields/PKICountry__c.field-meta.xml
<CustomField>
    <fullName>PKICountry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to PKI Country object to use for other Territory detail information</description>
    <inlineHelpText>Lookup to PKI Country object to use for other Territory detail information</inlineHelpText>
    <label>PKI Country</label>
    <referenceTo>PKI_Country__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>Accounts with business transactions associated with them</description>
    <label>Customer</label>
</RecordType>

Perkin-UAT/force-app/main/default/objects/User/fields/PKICountry__c.field-meta.xml
<CustomField>
    <fullName>PKICountry__c</fullName>
    <label>PKI Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>G_PICK_025_Territory_Country</valueSetName>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/classes/searchAccountController.cls
public with sharing class searchAccountController {

 // This accomodates Lightning Smart Search and list is fetching data based on parameters per MDM Team      
 @AuraEnabled

public static List < account > fetchAccount(String searchKeyWord,String searchSAP,string searchCity, string searchStreet,string searchCountry) {
//Boolean PKI SAP Customer Base Number = false;
 String strSoqlQuery = 'Select  id, Name,PKI_SAP_Customer_Number__c, PKI_SAP_Name_2__c, PKI_SAP_Customer_Base_Name__c,Opportunity_Info__c, ShippingCountry,ShippingCity, ShippingStreet,ShippingState,PKI_SAP_Name_3__c,PKI_SAP_Name_4__c from account where ';
String FixedFilter= '(PKI_SAP_Account_Group__c=\'0001\' OR PKI_SAP_Account_Group__c=\'ZBR1\' OR PKI_SAP_Account_Group__c=\'SFDC\') AND (PKI_SAP_Marked_For_Deletion__c=false) AND (MDM_Status__c!=\'Rejected\')';
    
    list <account> lstOfAccount= new list <account> ();
    
if(!string.isblank(searchKeyWord)){
string nam=searchKeyWord.trim();
 String NameKey ='%'+nam+'%';
FixedFilter+='AND Name LIKE \'%' + NameKey +  '%\' ' ;
}

if(!string.isblank(searchSAP)){
//string sap=searchSAP.trim(); this field it feeds externalId for PKI_SAP_Customer_Number__c.
 String sapNo =searchSAP;
FixedFilter+='AND PKI_SAP_Customer_Number__c=:sapNo ' ;
}

if(!string.isblank(searchStreet)){
//string site=searchStreet.trim(); this field it feeds shipping street for ShippingStreet, this fields is locked down for MDM.
String siteS =searchStreet;
FixedFilter+='AND ShippingStreet LIKE \'%' + siteS +  '%\' ' ;
}

if(!string.isblank(searchCity)){
//this field it feeds shipping street for ShippingCity, this fields is locked down for MDM.
string street=searchCity.trim();
 String streetc ='%'+street+'%';
FixedFilter+='AND ShippingCity LIKE \'%' + streetc +  '%\' ' ;
}

if(!string.isblank(searchCountry)){
// this field it feeds shipping street for ShippingCountry, this fields is locked down for MDM.
string streetco=searchCountry.trim();
 String streetS ='%'+streetco+'%';
FixedFilter+='AND ShippingCountry=: streetco  ' ;
}


strSoqlQuery+=FixedFilter+' ORDER BY Opportunity_Info__c DESC LIMIT 200';
    system.debug('---strSoqlQuery '+strSoqlQuery);
    try{lstOfAccount= Database.query(strSoqlQuery);}catch (QueryException e){ system.debug('Query Exception:'+e.getMessage());return null;}

system.debug('---lstOfAccount '+lstOfAccount);

  return lstOfAccount;

}

    //added as a request for MDM APAC Launch May,2021
    @AuraEnabled
    public static User fetchUserInfo(){
        return [SELECT Id, Name, PKICountry__c FROM User WHERE Id =: UserInfo.getUserId()];
    }

}