Perkin-UAT/force-app/main/default/objects/Account/fields/PKI_SAP_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>PKI_SAP_Customer_Number__c</fullName>
    <description>SAP - KNA1/KUNNR. Customer number for SoldToShipTo. IMPORTANT this is the external ID for the Customer Master integration used by Dell Boomi between SAP and SDFC. It is critical to the integrity of the data being passed from SAP</description>
    <externalId>true</externalId>
    <label>PKI SAP Customer Number</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Account/recordTypes/Test.recordType-meta.xml
<RecordType>
    <fullName>Test</fullName>
    <active>true</active>
    <label>Test</label>
</RecordType>

Perkin-UAT/force-app/main/default/objects/Contact/fields/PKI_SAP_Contact_ID__c.field-meta.xml
<CustomField>
    <fullName>PKI_SAP_Contact_ID__c</fullName>
    <description>PLEASE DO NOT EDIT OR UPDATE THIS FIELD IN DATALOADS ... IT IS AN EXTERNAL ID FIELD TO SAP</description>
    <externalId>true</externalId>
    <label>PKI SAP Contact ID</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Contact/fields/PKI_SAP_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>PKI_SAP_Customer_Number__c</fullName>
    <label>PKI SAP Customer Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/Partnum__c.field-meta.xml
<CustomField>
    <fullName>Partnum__c</fullName>
    <description>Unique External Id that stores the Material ID from QS3 . Same as SAP Product code.
Same as Material Number from SAP.</description>
    <externalId>true</externalId>
    <label>Part Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/SVMX_PS_External_ID__c.field-meta.xml
<CustomField>
    <fullName>SVMX_PS_External_ID__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_Install_Request__c/SMAX_PS_Install_Request__c.object-meta.xml
<CustomObject>
    <label>Install Request</label>
    <nameField>
        <label>Install Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Install Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_Install_Request__c/fields/SMAX_PS_Account__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Install Requests</relationshipLabel>
    <relationshipName>Install_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_Install_Request__c/fields/SMAX_PS_Account_ExtId__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_Account_ExtId__c</fullName>
    <label>Account External Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_Install_Request__c/fields/SMAX_PS_Contact__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact Number</description>
    <inlineHelpText>Contact Number</inlineHelpText>
    <label>Contact Number</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Install Requests</relationshipLabel>
    <relationshipName>Install_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_Install_Request__c/fields/SMAX_PS_Contact_ExtId__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_Contact_ExtId__c</fullName>
    <label>Contact External Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_Install_Request__c/fields/SMAX_PS_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_Error_Message__c</fullName>
    <description>Error message encountered when trying to generate Work Order.</description>
    <inlineHelpText>Error message encountered when trying to generate Work Order.</inlineHelpText>
    <label>Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_Install_Request__c/fields/SMAX_PS_External_Id__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_External_Id__c</fullName>
    <description>Unique External Id for this Install Request.  Should be populated with:
SalesOrderNumber-LineNumber-EquipmentNumber</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique External Id for this Install Request.  Should be populated with:
SalesOrderNumber-LineNumber-EquipmentNumber</inlineHelpText>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_Install_Request__c/fields/SMAX_PS_InstalledProduct__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_InstalledProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installed Product</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Install Requests</relationshipLabel>
    <relationshipName>Install_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_Install_Request__c/fields/SMAX_PS_InstalledProduct_ExtId__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_InstalledProduct_ExtId__c</fullName>
    <label>Installed Product External Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_Install_Request__c/fields/SMAX_PS_InstallType__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_InstallType__c</fullName>
    <label>Install Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>INSTALLATION</fullName>
            </value>
            <value>
                <fullName>PHONE</fullName>
            </value>
            <value>
                <fullName>PIV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_Install_Request__c/fields/SMAX_PS_Location__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>SVMXC__Site__c</referenceTo>
    <relationshipLabel>Install Requests</relationshipLabel>
    <relationshipName>Install_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_Install_Request__c/fields/SMAX_PS_Location_ExtId__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_Location_ExtId__c</fullName>
    <label>Location External Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_Install_Request__c/fields/SMAX_PS_Product__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Install Requests</relationshipLabel>
    <relationshipName>Install_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_Install_Request__c/fields/SMAX_PS_Product_ExtId__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_Product_ExtId__c</fullName>
    <label>Product External Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_Install_Request__c/fields/SMAX_PS_SalesOrderLineNumber__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_SalesOrderLineNumber__c</fullName>
    <description>Sales Order Line Number</description>
    <inlineHelpText>Sales Order Line Number</inlineHelpText>
    <label>Sales Order Line Number</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_Install_Request__c/fields/SMAX_PS_SalesOrderNumber__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_SalesOrderNumber__c</fullName>
    <description>Sales Order Number</description>
    <inlineHelpText>Sales Order Number</inlineHelpText>
    <label>Sales Order Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_Install_Request__c/fields/SMAX_PS_Status__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>On-Hold</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/classes/SMAX_PS_CreateInstallWorkOrdersBatch_UT.cls
@isTest
public class SMAX_PS_CreateInstallWorkOrdersBatch_UT {
	
	public static testmethod void testSuccessBatch(){
		
		Account acct = SMAX_PS_TestDataFactory.createTestAccount('PkiTest', 'TESTXYZ0000001','GB');
		Contact cont = SMAX_PS_TestDataFactory.createTestContact('Sir', 'Testalot', acct, 'TESTXYZ000001A');
		Product2 pd = SMAX_PS_TestDataFactory.createTestProduct('TestProduct', 'PRXYZ106','TST');
		pd.Partnum__c = pd.ProductCode;
		update pd;
		SVMXC__Site__c loc = SMAX_PS_TestDataFactory.createTestLocation(acct,'TestLocationSite', 'TESTXYZ121212','LOC123');
		loc.SMAX_PS_SalesOrg__c = 'TST2';
		update loc;
		SVMXC__Installed_Product__c ip = SMAX_PS_TestDataFactory.createIP('123456',acct,loc,'5545333',pd);
		ip.SVMX_PS_External_ID__c = 'TESTXYZ00001I';
		update ip;

		SMAX_PS_Install_Request__c ir = new SMAX_PS_Install_Request__c();
		ir.SMAX_PS_Account_ExtId__c = acct.PKI_SAP_Customer_Number__c;
		ir.SMAX_PS_Contact_ExtId__c = cont.PKI_SAP_Contact_ID__c;
		ir.SMAX_PS_InstalledProduct_ExtId__c = ip.SVMX_PS_External_ID__c;
		ir.SMAX_PS_Location_ExtId__c = loc.SVMX_PS_External_ID__c;
		ir.SMAX_PS_Product_ExtId__c = pd.Partnum__c;
		ir.SMAX_PS_InstallType__c = 'INSTALLATION';
		ir.SMAX_PS_SalesOrderNumber__c = 'SOXYZ10010';
		ir.SMAX_PS_SalesOrderLineNumber__c = '0012';
		ir.SMAX_PS_External_Id__c = ir.SMAX_PS_SalesOrderNumber__c + '-' + ir.SMAX_PS_SalesOrderLineNumber__c + '-' + ir.SMAX_PS_InstalledProduct_ExtId__c;

		insert ir;

		Test.startTest(); 
		
		SMAX_PS_CreateInstallWorkOrdersBatch obj = new SMAX_PS_CreateInstallWorkOrdersBatch(new Set<String> { 'TST2' });
		Database.executeBatch(obj);
		
		Test.stopTest();

		SMAX_PS_Install_Request__c result = [SELECT Id, Name, SMAX_PS_Status__c, SMAX_PS_Account__c, SMAX_PS_Location__c, SMAX_PS_Product__c, 
			SMAX_PS_InstalledProduct__c, SMAX_PS_Contact__c FROM SMAX_PS_Install_Request__c WHERE Id = :ir.Id];
		System.debug('RESULT InstallRequest (Success): ' + result);
		System.assertEquals(acct.Id, result.SMAX_PS_Account__c);
		System.assertEquals(loc.Id, result.SMAX_PS_Location__c);
		System.assertEquals(pd.Id, result.SMAX_PS_Product__c);
		System.assertEquals(ip.Id, result.SMAX_PS_InstalledProduct__c);
		System.assertEquals(cont.Id, result.SMAX_PS_Contact__c);
		System.assertEquals('Success', result.SMAX_PS_Status__c);
	}


	public static testmethod void testOnHoldBatch(){
		
		Account acct = SMAX_PS_TestDataFactory.createTestAccount('PkiTest', 'TESTXYZ0000001','GB');
		Contact cont = SMAX_PS_TestDataFactory.createTestContact('Sir', 'Testalot', acct, 'TESTXYZ000001A');
		Product2 pd = SMAX_PS_TestDataFactory.createTestProduct('TestProduct', 'PRXYZ106','TST');
		pd.Partnum__c = pd.ProductCode;
		update pd;
		SVMXC__Site__c loc = SMAX_PS_TestDataFactory.createTestLocation(acct,'TestLocationSite', 'TESTXYZ121212','LOC123');
		SVMXC__Installed_Product__c ip = SMAX_PS_TestDataFactory.createIP('123456',acct,loc,'5545333',pd);
		ip.SVMX_PS_External_ID__c = 'TESTXYZ00001I';
		update ip;

		SMAX_PS_Install_Request__c ir = new SMAX_PS_Install_Request__c();
		ir.SMAX_PS_Account_ExtId__c = acct.PKI_SAP_Customer_Number__c + '??';
		ir.SMAX_PS_Contact_ExtId__c = cont.PKI_SAP_Contact_ID__c + '??';
		ir.SMAX_PS_InstalledProduct_ExtId__c = ip.SVMX_PS_External_ID__c + '??';
		ir.SMAX_PS_Location_ExtId__c = loc.SVMX_PS_External_ID__c + '??';
		ir.SMAX_PS_Product_ExtId__c = pd.Partnum__c + '??';
		ir.SMAX_PS_InstallType__c = 'INSTALLATION';
		ir.SMAX_PS_SalesOrderNumber__c = 'SOXYZ10010';
		ir.SMAX_PS_SalesOrderLineNumber__c = '0012';
		ir.SMAX_PS_External_Id__c = ir.SMAX_PS_SalesOrderNumber__c + '-' + ir.SMAX_PS_SalesOrderLineNumber__c + '-' + ir.SMAX_PS_InstalledProduct_ExtId__c;

		insert ir;

		Test.startTest(); 
		
		SMAX_PS_CreateInstallWorkOrdersBatch obj = new SMAX_PS_CreateInstallWorkOrdersBatch(null);
		Database.executeBatch(obj);
		
		Test.stopTest();

		SMAX_PS_Install_Request__c result = [SELECT Id, Name, SMAX_PS_Status__c, SMAX_PS_Account__c, SMAX_PS_Location__c, SMAX_PS_Product__c, 
			SMAX_PS_InstalledProduct__c, SMAX_PS_Contact__c FROM SMAX_PS_Install_Request__c WHERE Id = :ir.Id];
		System.debug('RESULT InstallRequest (On-Hold): ' + result);
		System.assertEquals(null, result.SMAX_PS_Account__c);
		System.assertEquals(null, result.SMAX_PS_Location__c);
		System.assertEquals(null, result.SMAX_PS_Product__c);
		System.assertEquals(null, result.SMAX_PS_InstalledProduct__c);
		System.assertEquals(null, result.SMAX_PS_Contact__c);
		System.assertEquals('On-Hold', result.SMAX_PS_Status__c);
	}

	public static testmethod void testSalesOrgBatch(){
		
		Account acct = SMAX_PS_TestDataFactory.createTestAccount('PkiTest', 'TESTXYZ0000001','GB');
		Contact cont = SMAX_PS_TestDataFactory.createTestContact('Sir', 'Testalot', acct, 'TESTXYZ000001A');
		Product2 pd = SMAX_PS_TestDataFactory.createTestProduct('TestProduct', 'PRXYZ106','TST');
		pd.Partnum__c = pd.ProductCode;
		update pd;

		SVMXC__Site__c loc1 = SMAX_PS_TestDataFactory.createTestLocation(acct,'TestLocationSite1', 'TESTXYZ121111','LOC1_1');
		SVMXC__Site__c loc2 = SMAX_PS_TestDataFactory.createTestLocation(acct,'TestLocationSite2', 'TESTXYZ122222','LOC1_2');
		loc1.SMAX_PS_SalesOrg__c = 'TST1';
		loc2.SMAX_PS_SalesOrg__c = 'TST2';
		update new List<SVMXC__Site__c> { loc1, loc2 };

		SVMXC__Installed_Product__c ip1 = SMAX_PS_TestDataFactory.createIP('123456-1',acct,loc1,'5545333',pd);
		ip1.SVMX_PS_External_ID__c = 'TESTXYZ00001I';
		SVMXC__Installed_Product__c ip2 = SMAX_PS_TestDataFactory.createIP('123456-2',acct,loc2,'5545333',pd);
		ip2.SVMX_PS_External_ID__c = 'TESTXYZ00002I';
		update new List<SVMXC__Installed_Product__c> { ip1, ip2 };

		SMAX_PS_Install_Request__c ir1 = new SMAX_PS_Install_Request__c();
		ir1.SMAX_PS_Account_ExtId__c = acct.PKI_SAP_Customer_Number__c;
		ir1.SMAX_PS_Contact_ExtId__c = cont.PKI_SAP_Contact_ID__c;
		ir1.SMAX_PS_InstalledProduct_ExtId__c = ip1.SVMX_PS_External_ID__c;
		ir1.SMAX_PS_Location_ExtId__c = loc1.SVMX_PS_External_ID__c;
		ir1.SMAX_PS_Product_ExtId__c = pd.Partnum__c;
		ir1.SMAX_PS_InstallType__c = 'INSTALLATION';
		ir1.SMAX_PS_SalesOrderNumber__c = 'SOXYZ10010';
		ir1.SMAX_PS_SalesOrderLineNumber__c = '0012';
		ir1.SMAX_PS_External_Id__c = ir1.SMAX_PS_SalesOrderNumber__c + '-' + ir1.SMAX_PS_SalesOrderLineNumber__c + '-' + ir1.SMAX_PS_InstalledProduct_ExtId__c;

		SMAX_PS_Install_Request__c ir2 = new SMAX_PS_Install_Request__c();
		ir2.SMAX_PS_Account_ExtId__c = acct.PKI_SAP_Customer_Number__c;
		ir2.SMAX_PS_Contact_ExtId__c = cont.PKI_SAP_Contact_ID__c;
		ir2.SMAX_PS_InstalledProduct_ExtId__c = ip2.SVMX_PS_External_ID__c;
		ir2.SMAX_PS_Location_ExtId__c = loc2.SVMX_PS_External_ID__c;
		ir2.SMAX_PS_Product_ExtId__c = pd.Partnum__c;
		ir2.SMAX_PS_InstallType__c = 'INSTALLATION';
		ir2.SMAX_PS_SalesOrderNumber__c = 'SOXYZ10010';
		ir2.SMAX_PS_SalesOrderLineNumber__c = '0012';
		ir2.SMAX_PS_External_Id__c = ir2.SMAX_PS_SalesOrderNumber__c + '-' + ir2.SMAX_PS_SalesOrderLineNumber__c + '-' + ir2.SMAX_PS_InstalledProduct_ExtId__c;

		insert new List<SMAX_PS_Install_Request__c> { ir1, ir2 };

		Test.startTest(); 
		
		SMAX_PS_CreateInstallWorkOrdersBatch obj = new SMAX_PS_CreateInstallWorkOrdersBatch(new Set<String> { 'TST2' });
		Database.executeBatch(obj);
		
		Test.stopTest();

		SMAX_PS_Install_Request__c result1 = [SELECT Id, Name, SMAX_PS_Status__c, SMAX_PS_Account__c, SMAX_PS_Location__c, SMAX_PS_Product__c, 
			SMAX_PS_InstalledProduct__c, SMAX_PS_Contact__c, SMAX_PS_Error_Message__c FROM SMAX_PS_Install_Request__c WHERE Id = :ir1.Id];
		System.debug('RESULT InstallRequest (SalesOrg On-Hold): ' + result1);
		System.assertNotEquals(null, result1.SMAX_PS_Location__c);
		// ITSVMX-1278 Do not set to On-Hold
		//System.assertEquals('On-Hold', result1.SMAX_PS_Status__c);
		System.assert(result1.SMAX_PS_Error_Message__c.contains('SalesOrg'));

		SMAX_PS_Install_Request__c result2 = [SELECT Id, Name, SMAX_PS_Status__c, SMAX_PS_Account__c, SMAX_PS_Location__c, SMAX_PS_Product__c, 
			SMAX_PS_InstalledProduct__c, SMAX_PS_Contact__c, SMAX_PS_Error_Message__c FROM SMAX_PS_Install_Request__c WHERE Id = :ir2.Id];
		System.debug('RESULT InstallRequest (SalesOrg Success): ' + result2);
		System.assertNotEquals(null, result2.SMAX_PS_Location__c);
		System.assertEquals('Success', result2.SMAX_PS_Status__c);
	}
}