Perkin-UAT/force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>Accounts with business transactions associated with them</description>
    <label>Customer</label>
</RecordType>

Perkin-UAT/force-app/main/default/objects/Account/recordTypes/Test.recordType-meta.xml
<RecordType>
    <fullName>Test</fullName>
    <active>true</active>
    <label>Test</label>
</RecordType>

Perkin-UAT/force-app/main/default/objects/B2B_Attachment__c/B2B_Attachment__c.object-meta.xml
<CustomObject>
    <label>B2B Attachment</label>
    <nameField>
        <displayFormat>BA-{0000}</displayFormat>
        <label>B2B Attachment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B2B Attachments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/B2B_Attachment__c/fields/Cart__c.field-meta.xml
<CustomField>
    <fullName>Cart__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cart</label>
    <referenceTo>WebCart</referenceTo>
    <relationshipLabel>B2B Attachments</relationshipLabel>
    <relationshipName>B2B_Attachments</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/CommerceEntitlementPolicy/fields/B2B_Sales_Org_And_Sales_Status__c.field-meta.xml
<CustomField>
    <fullName>B2B_Sales_Org_And_Sales_Status__c</fullName>
    <label>Sales Org And Sales Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/B2B_Sales_Org_And_Sales_Status__c.field-meta.xml
<CustomField>
    <fullName>B2B_Sales_Org_And_Sales_Status__c</fullName>
    <label>Sales Org And Sales Status</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1US0-Z3</fullName>
            </value>
            <value>
                <fullName>1US0-ZW</fullName>
            </value>
            <value>
                <fullName>1US0-ZY</fullName>
            </value>
            <value>
                <fullName>ATS0-Z3</fullName>
            </value>
            <value>
                <fullName>ATS0-ZW</fullName>
            </value>
            <value>
                <fullName>ATS0-ZY</fullName>
            </value>
            <value>
                <fullName>AUS0-ZW</fullName>
            </value>
            <value>
                <fullName>AUS0-ZY</fullName>
            </value>
            <value>
                <fullName>BES0-Z3</fullName>
            </value>
            <value>
                <fullName>BES0-ZW</fullName>
            </value>
            <value>
                <fullName>BES0-ZY</fullName>
            </value>
            <value>
                <fullName>BRS0-Z3</fullName>
            </value>
            <value>
                <fullName>BRS0-ZW</fullName>
            </value>
            <value>
                <fullName>BRS0-ZY</fullName>
            </value>
            <value>
                <fullName>CAS0-Z3</fullName>
            </value>
            <value>
                <fullName>CAS0-ZW</fullName>
            </value>
            <value>
                <fullName>CAS0-ZY</fullName>
            </value>
            <value>
                <fullName>CHS0-Z3</fullName>
            </value>
            <value>
                <fullName>CHS0-ZW</fullName>
            </value>
            <value>
                <fullName>CHS0-ZY</fullName>
            </value>
            <value>
                <fullName>CL10-ZW</fullName>
            </value>
            <value>
                <fullName>CL10-ZY</fullName>
            </value>
            <value>
                <fullName>CN10-9N</fullName>
            </value>
            <value>
                <fullName>CN10-ZW</fullName>
            </value>
            <value>
                <fullName>CN10-ZY</fullName>
            </value>
            <value>
                <fullName>DES0-Z3</fullName>
            </value>
            <value>
                <fullName>DES0-ZW</fullName>
            </value>
            <value>
                <fullName>DES0-ZY</fullName>
            </value>
            <value>
                <fullName>DKS0-Z3</fullName>
            </value>
            <value>
                <fullName>DKS0-ZW</fullName>
            </value>
            <value>
                <fullName>ESS0-ZY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/classes/B2BGTMOrderConfContTest.cls
@isTest
public with sharing class B2BGTMOrderConfContTest {

    private static final String PRODUCT_NAME = 'Test Product';
    private static final String CUSTOMER_EMAIL = 'customer@testing.cust';
    private static final String GUEST_CUSTOMER_EMAIL = 'guest_customer@testing.cust';
    private static final String LOCATION_NAME = 'Test';
    
    @TestSetup
    static void makeData(){
        Account userAccount = B2B_TestDataFactory.createAccount('TestAccount', true);
        Contact userContact = B2B_TestDataFactory.createContact('TestContact', userAccount.Id, true);
        User customerUser = B2B_TestDataFactory.createUser('Customer', CUSTOMER_EMAIL, userContact.Id, true); 

        B2B_TestDataFactory.createOrderDeliveryMethod(true);
        Product2 prod = B2B_TestDataFactory.createProduct(PRODUCT_NAME,true);
        WebStore store = B2B_TestDataFactory.createWebstore('Store',true);
        ContactPointAddress cpa = B2B_TestDataFactory.createShippingCPA(userAccount,true);
        WebCart currentCart  = B2B_TestDataFactory.createCart(userAccount.Id, customerUser.id , store.Id, cpa.Id ,true);
	
        B2B_Attachment__c attach = new B2B_Attachment__c(
        	Cart__c = currentCart.Id
        );
        insert attach;
        
        CommerceEntitlementPolicy policy = new CommerceEntitlementPolicy(
            Name = 'test policy',
			Description = 'test policy', 
            CanViewProduct = true, 
            CanViewPrice = true,
            IsActive = true,
            B2B_Sales_Org_And_Sales_Status__c = 'ESS0-ZY'
        );
        insert policy;
        
        CommerceEntitlementProduct prodEntitlement = new CommerceEntitlementProduct(
        	PolicyId = policy.Id,
            ProductId = prod.Id
        );
        insert prodEntitlement;

        Order order = new Order(
            AccountId = userAccount.Id,
            Status = 'Draft',
            EffectiveDate = Date.today()
        );
        insert order; 

        OrderItem orderItem = new OrderItem(
            OrderId = order.Id,
            Product2Id = prod.Id,
            Quantity = 1,
            ListPrice = 100.00,
            UnitPrice = 100.00
        );
        insert orderItem;
    }

    @isTest
    public static void B2B_CreateProductEntitlementBatch_test(){
        List<Order> order = [SELECT Id FROM Order LIMIT 1];
        Test.startTest();
        Order retOrd = B2BGTMOrderConfCont.getOrderWithItems(order[0].Id);
        Test.stopTest();
        Assert.isNotNull(retOrd);
    }
    
}