Perkin-UAT/force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>Accounts with business transactions associated with them</description>
    <label>Customer</label>
</RecordType>

Perkin-UAT/force-app/main/default/objects/Account/recordTypes/Test.recordType-meta.xml
<RecordType>
    <fullName>Test</fullName>
    <active>true</active>
    <label>Test</label>
</RecordType>

Perkin-UAT/force-app/main/default/objects/B2B_Attachment__c/B2B_Attachment__c.object-meta.xml
<CustomObject>
    <label>B2B Attachment</label>
    <nameField>
        <displayFormat>BA-{0000}</displayFormat>
        <label>B2B Attachment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B2B Attachments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/B2B_Attachment__c/fields/Cart__c.field-meta.xml
<CustomField>
    <fullName>Cart__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cart</label>
    <referenceTo>WebCart</referenceTo>
    <relationshipLabel>B2B Attachments</relationshipLabel>
    <relationshipName>B2B_Attachments</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/CommerceEntitlementPolicy/fields/B2B_Sales_Org_And_Sales_Status__c.field-meta.xml
<CustomField>
    <fullName>B2B_Sales_Org_And_Sales_Status__c</fullName>
    <label>Sales Org And Sales Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/B2B_Sales_Org_And_Sales_Status__c.field-meta.xml
<CustomField>
    <fullName>B2B_Sales_Org_And_Sales_Status__c</fullName>
    <label>Sales Org And Sales Status</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1US0-Z3</fullName>
            </value>
            <value>
                <fullName>1US0-ZW</fullName>
            </value>
            <value>
                <fullName>1US0-ZY</fullName>
            </value>
            <value>
                <fullName>ATS0-Z3</fullName>
            </value>
            <value>
                <fullName>ATS0-ZW</fullName>
            </value>
            <value>
                <fullName>ATS0-ZY</fullName>
            </value>
            <value>
                <fullName>AUS0-ZW</fullName>
            </value>
            <value>
                <fullName>AUS0-ZY</fullName>
            </value>
            <value>
                <fullName>BES0-Z3</fullName>
            </value>
            <value>
                <fullName>BES0-ZW</fullName>
            </value>
            <value>
                <fullName>BES0-ZY</fullName>
            </value>
            <value>
                <fullName>BRS0-Z3</fullName>
            </value>
            <value>
                <fullName>BRS0-ZW</fullName>
            </value>
            <value>
                <fullName>BRS0-ZY</fullName>
            </value>
            <value>
                <fullName>CAS0-Z3</fullName>
            </value>
            <value>
                <fullName>CAS0-ZW</fullName>
            </value>
            <value>
                <fullName>CAS0-ZY</fullName>
            </value>
            <value>
                <fullName>CHS0-Z3</fullName>
            </value>
            <value>
                <fullName>CHS0-ZW</fullName>
            </value>
            <value>
                <fullName>CHS0-ZY</fullName>
            </value>
            <value>
                <fullName>CL10-ZW</fullName>
            </value>
            <value>
                <fullName>CL10-ZY</fullName>
            </value>
            <value>
                <fullName>CN10-9N</fullName>
            </value>
            <value>
                <fullName>CN10-ZW</fullName>
            </value>
            <value>
                <fullName>CN10-ZY</fullName>
            </value>
            <value>
                <fullName>DES0-Z3</fullName>
            </value>
            <value>
                <fullName>DES0-ZW</fullName>
            </value>
            <value>
                <fullName>DES0-ZY</fullName>
            </value>
            <value>
                <fullName>DKS0-Z3</fullName>
            </value>
            <value>
                <fullName>DKS0-ZW</fullName>
            </value>
            <value>
                <fullName>ESS0-ZY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/classes/B2B_CreateProductEntitlementJobTest.cls
@isTest
public class B2B_CreateProductEntitlementJobTest {
    
    private static final String PRODUCT_NAME = 'Test Product';
    private static final String CUSTOMER_EMAIL = 'customer@testing.cust';
    private static final String GUEST_CUSTOMER_EMAIL = 'guest_customer@testing.cust';
    private static final String LOCATION_NAME = 'Test';
    
    @TestSetup
    static void makeData(){
        Contact con = new Contact(
            LastName = 'Test'
        );
        insert con;
        
        ContentVersion cv = new ContentVersion(
        	Title = 'Test',
            PathOnClient = 'Test',
            VersionData = EncodingUtil.base64Decode('Test'),
            IsMajorVersion = FALSE
        );
        insert cv;
        
        Account userAccount = B2B_TestDataFactory.createAccount('TestAccount', true);
        Contact userContact = B2B_TestDataFactory.createContact('TestContact', userAccount.Id, true);
        User customerUser = B2B_TestDataFactory.createUser('Customer', CUSTOMER_EMAIL, userContact.Id, true); 

        B2B_TestDataFactory.createOrderDeliveryMethod(true);
        Product2 prod = B2B_TestDataFactory.createProduct(PRODUCT_NAME,true);
        WebStore store = B2B_TestDataFactory.createWebstore('Store',true);
        ContactPointAddress cpa = B2B_TestDataFactory.createShippingCPA(userAccount,true);
        WebCart currentCart  = B2B_TestDataFactory.createCart(userAccount.Id, customerUser.id , store.Id, cpa.Id ,true);
	
        B2B_Attachment__c attach = new B2B_Attachment__c(
        	Cart__c = currentCart.Id
        );
        insert attach;
        
        CommerceEntitlementPolicy policy = new CommerceEntitlementPolicy(
            Name = 'test policy',
			Description = 'test policy', 
            CanViewProduct = true, 
            CanViewPrice = true,
            IsActive = true,
            B2B_Sales_Org_And_Sales_Status__c = 'ESS0-ZY'
        );
        insert policy;
        
        CommerceEntitlementProduct prodEntitlement = new CommerceEntitlementProduct(
        	PolicyId = policy.Id,
            ProductId = prod.Id
        );
        insert prodEntitlement;
    }

	@isTest
    public static void B2B_CreateProductEntitlementBatch_test(){
        Product2 prod = B2B_TestDataFactory.getProductByName( PRODUCT_NAME );
        prod.B2B_Sales_Org_And_Sales_Status__c = 'ESS0-ZY,BES0-ZW';
        update prod;
		String query = 'SELECT Id, B2B_Sales_Org_And_Sales_Status__c FROM Product2 WHERE B2B_Sales_Org_And_Sales_Status__c != null AND Id =\'' +prod.Id+'\'';
        Test.startTest();
        B2B_CreateProductEntitlementBatch ba= new B2B_CreateProductEntitlementBatch( query );
        Id jobid= Database.executeBatch(ba,1);
        Test.stopTest();
        Assert.isNotNull(prod);
    }
    
    @isTest
    public static void B2B_ProductEntitlementInvocable_test(){
        Product2 prod = B2B_TestDataFactory.getProductByName( PRODUCT_NAME );
        String query = 'SELECT Id, B2B_Sales_Org_And_Sales_Status__c FROM Product2 WHERE B2B_Sales_Org_And_Sales_Status__c != null AND Id =\'' +prod.Id+'\'';
        Test.startTest();
        B2B_ProductEntitlementInvocable ba= new B2B_ProductEntitlementInvocable();
        Test.stopTest();
        Assert.isNotNull(prod);
    }
    
    @isTest
    public static void B2B_DeleteExistingProductEntitlement_test(){
        Product2 prod = B2B_TestDataFactory.getProductByName( PRODUCT_NAME );
        prod.B2B_Sales_Org_And_Sales_Status__c = 'ESS0-ZY,BES0-ZW';
        update prod;
		String query = 'SELECT Id FROM CommerceEntitlementProduct';
        Test.startTest();
        B2B_DeleteExistingProductEntitlement ba= new B2B_DeleteExistingProductEntitlement( query );
        Id jobid= Database.executeBatch(ba,1);
        Test.stopTest();
        Assert.isNotNull(prod);
    }
}