Perkin-UAT/force-app/main/default/objects/Account/recordTypes/Test.recordType-meta.xml
<RecordType>
    <fullName>Test</fullName>
    <active>true</active>
    <label>Test</label>
</RecordType>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>This Field is required under the &quot;Electronic Delivery Section&quot; when the Opportunity is moved to &quot;Stage-6 &quot; and the details are sent to NetSuite when the Order is processed through integration(ITSFDC-5103)</description>
    <inlineHelpText>Mandatory field, Opportunity cannot be submitted to Stage 6 if blank. The contact in this field will receive a software email notification</inlineHelpText>
    <label>First Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>This Field is required under the &quot;Electronic Delivery Section&quot; when the Opportunity is moved to &quot;Stage-6 &quot; and the details are sent to NetSuite when the Order is processed through integration(ITSFDC-5103)</description>
    <inlineHelpText>Mandatory field, Opportunity cannot be submitted to Stage 6 if blank. The contact in this field will receive a software email notification</inlineHelpText>
    <label>Last Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Owned_by_Company__c.field-meta.xml
<CustomField>
    <fullName>Owned_by_Company__c</fullName>
    <description>Determines whether the record belongs to one company vs. others (for example: LSDx vs AES) (Source: CMC Story #S-696879)</description>
    <label>Owned by Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>G_PICK_050_Owned_by_Company</valueSetName>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Primary_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Primary_Email_Address__c</fullName>
    <description>This Field is required under the &quot;Electronic Delivery Section&quot; when the Opportunity is moved to &quot;Stage-6 &quot; and the details are sent to NetSuite when the Order is processed through integration(ITSFDC-5103)</description>
    <inlineHelpText>Mandatory field, Opportunity cannot be submitted to Stage 6 if blank. Add email for contact in this field that will receive a software email notification</inlineHelpText>
    <label>Primary Email Address</label>
    <type>Email</type>
</CustomField>

Perkin-UAT/force-app/main/default/classes/submitOrderTest.cls
@isTest 
public class submitOrderTest 
{
static testMethod void submitOrderTest() 
{
    Account testAccount = new Account();
    testAccount.Name='Test Account' ;
    testAccount.CurrencyIsoCode = 'USD';
    testAccount.BillingStreet ='1234';
    testAccount.BillingCity='Boston';
    testAccount.BillingState='MA';
    testAccount.BillingCountry='US';
    testAccount.BillingPostalCode='123455';
    testAccount.ShippingStreet ='1234';
    testAccount.ShippingCity='Boston';
    testAccount.ShippingState='MA';
    testAccount.ShippingCountry='US';
    testAccount.ShippingPostalCode='123455';
    insert testAccount;
    
    Opportunity opp=new opportunity();
    opp.Name='testopp';
    opp.CloseDate=system.today()+50;
    opp.StageName='Open';
    opp.AccountId= testAccount.Id;
    opp.First_Name__c = 'Test FirstName';
    Opp.Last_Name__c = 'Test LastName';
    Opp.Primary_Email_Address__c = 'test@primary.com';
    opp.stageName='Stage 6 - Implement (Closed)';
    opp.Owned_by_Company__c = 'LSDX';
    
    insert opp;
    
    Test.StartTest(); 
    
    PageReference pageRef = Page.submitOrderController;
    pageRef.getparameters().put('id', opp.id);  
    Test.setCurrentPage(pageRef);
    
    apexpages.StandardController sc = new Apexpages.StandardController(opp);
    submitOrderController ext = new submitOrderController(sc);         
    ext.UpdateOpp();  
    
    Test.StopTest();
}
}