Perkin-UAT/force-app/main/default/objects/Account/recordTypes/Test.recordType-meta.xml
<RecordType>
    <fullName>Test</fullName>
    <active>true</active>
    <label>Test</label>
</RecordType>

Perkin-UAT/force-app/main/default/objects/Month_Rep_Target__c/Month_Rep_Target__c.object-meta.xml
<CustomObject>
    <description>SBE: EH Only - Part of the custom AOP reporting package developed by GSP from the UK. One of several custom objects this object is used to store each sales person&#39;s monthly base &amp; stretch quotas and then compare against their current sales funnel</description>
    <label>Month Rep Target</label>
    <nameField>
        <displayFormat>MRT - {00000}</displayFormat>
        <label>Month Rep Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Month Rep Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/Month_Rep_Target__c/fields/Sales_Person__c.field-meta.xml
<CustomField>
    <fullName>Sales_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Person</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Month_Rep_Targets</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Month_Rep_Target__c/fields/Unique_Field__c.field-meta.xml
<CustomField>
    <fullName>Unique_Field__c</fullName>
    <externalId>true</externalId>
    <label>Unique Field</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Month_Territory_Target__c/Month_Territory_Target__c.object-meta.xml
<CustomObject>
    <label>Month Territory Target</label>
    <nameField>
        <displayFormat>MTTN-{0000}</displayFormat>
        <label>Month Territory Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Month Territory Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/Month_Territory_Target__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>01-Jan</fullName>
            </value>
            <value>
                <fullName>02-Feb</fullName>
            </value>
            <value>
                <fullName>03-Mar</fullName>
            </value>
            <value>
                <fullName>04-Apr</fullName>
            </value>
            <value>
                <fullName>05-May</fullName>
            </value>
            <value>
                <fullName>06-Jun</fullName>
            </value>
            <value>
                <fullName>07-Jul</fullName>
            </value>
            <value>
                <fullName>08-Aug</fullName>
            </value>
            <value>
                <fullName>09-Sep</fullName>
            </value>
            <value>
                <fullName>10-Oct</fullName>
            </value>
            <value>
                <fullName>11-Nov</fullName>
            </value>
            <value>
                <fullName>12-Dec</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Month_Territory_Target__c/fields/Unique_Field__c.field-meta.xml
<CustomField>
    <fullName>Unique_Field__c</fullName>
    <externalId>true</externalId>
    <label>Unique Field</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Month_Rep_Target__c.field-meta.xml
<CustomField>
    <fullName>Month_Rep_Target__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Month Rep Target</label>
    <referenceTo>Month_Rep_Target__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Month_Territory_Target__c.field-meta.xml
<CustomField>
    <fullName>Month_Territory_Target__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Month Territory Target</label>
    <referenceTo>Month_Territory_Target__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Line</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/OpportunityLineItem/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <formula>PricebookEntry.Product2.product_line__c</formula>
    <label>Product Line</label>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/product_line__c.field-meta.xml
<CustomField>
    <fullName>product_line__c</fullName>
    <description>Product Line code from SAP</description>
    <label>Product Line</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/classes/GSP_trgOpportunityMethods_TEST.cls
@isTest
public with sharing class GSP_trgOpportunityMethods_TEST
{
    private static Map<Integer, String> monthToStringMap = new Map<Integer, String>{ 1 => '1 - Jan', 2 => '2 - Feb', 3 => '3 => Mar', 4 => '4 - Apr', 5 => '5 - May',
        6 => '6 - Jun', 7 => '7 - Jul', 8 => '8 - Aug', 9 => '9 - Sept', 10 => '10 - Oct', 11 => '11 - Nov', 12 => '12 - Dec' };
    private static String PRODUCT_LINE = 'SOS';
    
    @isTest(seeAllData=true)
    public static void test_UpdateTargets()
    {
        User user = [select Id FROM User where IsActive = true LIMIT 1];
        Territory2 territory;
        System.runAs(user)
        {
        
            territory = new Territory2(
                Name = 'Apex Test Territory');
       //     insert territory;
            System.assertNotEquals(territory2.Id, null);
        }  
        
        
        Month_Rep_Target__c monthRepTarget = new Month_Rep_Target__c(
            Month__c = monthToStringMap.get(Date.today().month()),
            Year__c = String.valueOf(Date.today().year()),
            Sales_Person__c = UserInfo.getUserId());
        insert monthRepTarget;
        System.assertNotEquals(monthRepTarget.Id, null);
        
        Month_Territory_Target__c monthTerritoryTarget = new Month_Territory_Target__c(
            Year__c = String.valueOf(Date.today().year()),
            Start_Date__c = Date.today().toStartOfMonth(),
            Month__c = monthToStringMap.get(Date.today().month()),
            Unique_Field__c = 'Apex Test Territory');
        insert monthTerritoryTarget;
        System.assertNotEquals(monthTerritoryTarget.Id, null);
        
        Account account = new Account(
            Name = 'Apex Test Account',
            ShippingCountry = 'US');
        insert account;
        System.assertNotEquals(account.Id, null);
        
        Opportunity opportunity = new Opportunity(
            Name = 'Apex Test Opportunity',
            CloseDate = Date.today(),
            StageName = 'Prospecting',
            AccountId = account.Id,
        //    Territory2 = territory2.Id,
            Month_Territory_Target__c = monthTerritoryTarget.Id,
            Month_Rep_Target__c = monthRepTarget.Id,
            Solution_Area_of_Interest__c='Energy');
        insert opportunity;
        System.assertNotEquals(opportunity.Id, null);
        
        Pricebook2 standardPricebook,
            customPricebook;
        List<Pricebook2> pricebooks = new List<Pricebook2>([
            SELECT
                Id,
                Name,
                IsStandard,
                IsActive
            FROM
                Pricebook2
            WHERE
                IsStandard = true
            OR
                (IsActive = true
            AND
                IsStandard = false)
            ORDER BY
                IsStandard DESC
            LIMIT 2]);System.debug(pricebooks);
        System.assert(pricebooks.size() > 0);
        for (Pricebook2 pricebook : pricebooks)
        {
            if (pricebook.IsStandard)
            {
                standardPricebook = pricebook;
            }
            else
            {
                System.assertEquals(pricebook.IsActive, true);
                customPricebook = pricebook;
            }
        }
        System.assertNotEquals(standardPricebook, null);
        if (!standardPricebook.IsActive)
        {
            System.assertNotEquals(customPricebook, null, 'No pricebooks defined, unable to continue.');
        }
        
        List<Product2> productCache = new List<Product2>();
        for (Integer i = 0; i < 3; i++)
        {
            Product2 product = new Product2(
                Name = 'Apex Test Product ' + i,
                IsActive = true,
                Product_Line__c = PRODUCT_LINE);
            productCache.add(product);
        }
        insert productCache;
        
        List<PricebookEntry> pricebookEntries = new List<PricebookEntry>();
        List<PricebookEntry> standardPricebookEntryCache = new List<PricebookEntry>();
        List<PricebookEntry> customPricebookEntryCache = new List<PricebookEntry>();
        List<OpportunityLineItem> opportunityLineItemCache = new List<OpportunityLineItem>();
        for (Integer i = 0; i < productCache.size(); i++)
        {
            Product2 product = productCache.get(i);
            PricebookEntry standardPricebookEntry = new PricebookEntry(
                Product2Id = product.Id,
                Pricebook2Id = standardPricebook.Id,
                UnitPrice = (i + 1) * 1000,
                IsActive = true);
            standardPricebookEntryCache.add(standardPricebookEntry);
            if (!standardPricebook.IsActive)
            {
                PricebookEntry customPricebookEntry = new PricebookEntry(
                Product2Id = product.Id,
                Pricebook2Id = customPricebook.Id,
                UnitPrice = (i + 1) * 1000,
                IsActive = true);
                customPricebookEntryCache.add(customPricebookEntry);
            }
        }
        insert standardPricebookEntryCache;
        if (!customPricebookEntryCache.isEmpty())
        {
            insert customPricebookEntryCache;
            pricebookEntries = customPricebookEntryCache;
        }
        else
        {
            pricebookEntries = standardPricebookEntryCache;
        }
        
        for (Integer i = 0; i < pricebookEntries.size(); i++)
        {
            PricebookEntry pricebookEntry = pricebookEntries.get(i);
            OpportunityLineItem opportunityLineItem = new OpportunityLineItem(
                PricebookEntryId = pricebookEntry.Id,
                Quantity = 3,
                UnitPrice = (i + 1) * 1000,
                OpportunityId = opportunity.Id);
            opportunityLineItemCache.add(opportunityLineItem);
        }
        insert opportunityLineItemCache;
        
        opportunity.CloseDate = Date.today().addMonths(1);
        update opportunity;
    }
}