Perkin-UAT/force-app/main/default/objects/Account/recordTypes/Test.recordType-meta.xml
<RecordType>
    <fullName>Test</fullName>
    <active>true</active>
    <label>Test</label>
</RecordType>

Perkin-UAT/force-app/main/default/objects/BD_Tender_Payment__c/BD_Tender_Payment__c.object-meta.xml
<CustomObject>
    <label>Tender-Bid Payment</label>
    <nameField>
        <displayFormat>TPMT-{0000}</displayFormat>
        <label>Tender-Bid Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tender-Bid Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/BD_Tender_Payment__c/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/BD_Tender_Payment__c/fields/BD_Account__c.field-meta.xml
<CustomField>
    <fullName>BD_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SC-406 Renamed label to Tender-Bid</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Tender-Bid Payments</relationshipLabel>
    <relationshipName>Tender_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/BD_Tender_Payment__c/fields/BD_Parent_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>BD_Parent_Opportunity__c</fullName>
    <description>SC-406 Renamed label to Tender-Bid</description>
    <label>Parent Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Tender-Bid Payments</relationshipLabel>
    <relationshipName>Tender_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Perkin-UAT/force-app/main/default/classes/TenderPaymentExtControllerTests.cls
@isTest
private class TenderPaymentExtControllerTests {
    @testSetup
    static void createTestData() {
        Account testAccount = new Account(
            Name = 'Test Account'
        );
        insert testAccount;

        Opportunity testOpp = new Opportunity();
            testOpp.Name = 'Test Opportunity';
            testOpp.StageName = 'Prospecting';
            testOpp.CloseDate = Date.today().addDays(30);
            testOpp.Amount = 10000;
            testOpp.AccountId = testAccount.Id;
        
        insert testOpp;

    }
    
    testMethod static void testSubmit() {
        Opportunity opp = [SELECT Id, AccountId FROM Opportunity limit 1];

        BD_Tender_Payment__c payment = new BD_Tender_Payment__c();
        payment.BD_Parent_Opportunity__c = opp.Id;
        payment.BD_Account__c = opp.AccountId;
        insert payment;
        
        Test.startTest();
        TenderPaymentExtController con = new TenderPaymentExtController(new ApexPages.StandardController(payment));
        con.onSubmit();
        payment = [SELECT ApprovalStatus__c FROM BD_Tender_Payment__c WHERE Id = :payment.Id LIMIT 1];
        Test.stopTest();
        
        System.assertEquals('Approved', payment.ApprovalStatus__c);
    }
    
    testMethod static void testRecall() {
        Opportunity opp = [SELECT Id, AccountId FROM Opportunity limit 1];

        BD_Tender_Payment__c payment = new BD_Tender_Payment__c();
        payment.BD_Parent_Opportunity__c = opp.Id;
        payment.BD_Account__c = opp.AccountId;
        insert payment;
        
        Test.startTest();
        TenderPaymentExtController con = new TenderPaymentExtController(new ApexPages.StandardController(payment));
        con.onRecall();
        payment = [SELECT ApprovalStatus__c FROM BD_Tender_Payment__c WHERE Id = :payment.Id LIMIT 1];
        Test.stopTest();
        
        System.assertEquals('Recalled', payment.ApprovalStatus__c);
    }
}