Perkin-UAT/force-app/main/default/objects/Account/recordTypes/Test.recordType-meta.xml
<RecordType>
    <fullName>Test</fullName>
    <active>true</active>
    <label>Test</label>
</RecordType>

Perkin-UAT/force-app/main/default/objects/BD_Quote_Event__e/BD_Quote_Event__e.object-meta.xml
<CustomObject>
    <label>Quote Event</label>
    <pluralLabel>Quote Events</pluralLabel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/BD_Quote_Event__e/fields/BD_Action__c.field-meta.xml
<CustomField>
    <fullName>BD_Action__c</fullName>
    <label>Action</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/BD_Quote_Event__e/fields/BD_Quote_Id__c.field-meta.xml
<CustomField>
    <fullName>BD_Quote_Id__c</fullName>
    <label>Quote Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_Platform_Event_Log__c/SMAX_PS_Platform_Event_Log__c.object-meta.xml
<CustomObject>
    <description>Object to record history of all Platform Events sent from the system.
This object is created as a backup / failsafe in case of connectivity problems.</description>
    <label>Platform Event Log</label>
    <nameField>
        <displayFormat>PE-{0000000000}</displayFormat>
        <label>Platform Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Platform Event Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_Platform_Event_Log__c/fields/SMAX_PS_Related_Element_Id__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_Related_Element_Id__c</fullName>
    <externalId>true</externalId>
    <label>Related Element Identifier</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/classes/BD_QuoteEventHandlerTest.cls
@isTest
public class BD_QuoteEventHandlerTest {
	@testSetup
    static void createTestData() {
        Account testAccount = new Account();
        testAccount.Name = 'Test Account';
        insert testAccount;
        
        List<SBQQ__Quote__c> quotes = new List<SBQQ__Quote__c>();
        
        for (Integer i = 0; i < 3; i++) {
            SBQQ__Quote__c quote = new SBQQ__Quote__c(
                SBQQ__Account__c = testAccount.Id
            );
            quotes.add(quote);
        }
        insert quotes;
       
    }
    
    @isTest
    static void testCreationOfPlatformEventLogs() {
        
        List<SBQQ__Quote__c> quotes = [SELECT Id FROM SBQQ__Quote__c LIMIT 3];
        
        List<BD_Quote_Event__e> quoteEvents = new List<BD_Quote_Event__e>();
        
        for (SBQQ__Quote__c quote : quotes) {
                BD_Quote_Event__e event = new BD_Quote_Event__e();
                event.BD_Quote_Id__c = quote.Id;
                event.BD_Action__c = 'CREATE';
            quoteEvents.add(event);
        }
        Test.startTest();
        EventBus.publish(quoteEvents);
        Test.stopTest();
        
        List<SMAX_PS_Platform_Event_Log__c> logs = [SELECT Id, SMAX_PS_Related_Element_Id__c 
                                                    FROM SMAX_PS_Platform_Event_Log__c];
        
        Assert.areEqual(3, logs.size(), 'Expected 3 Platform Event Log records');
    }
}