Perkin-UAT/force-app/main/default/objects/Account/recordTypes/Test.recordType-meta.xml
<RecordType>
    <fullName>Test</fullName>
    <active>true</active>
    <label>Test</label>
</RecordType>

Perkin-UAT/force-app/main/default/objects/BD_Contract_Discount_Exception__c/BD_Contract_Discount_Exception__c.object-meta.xml
<CustomObject>
    <label>Contract Discount Exception</label>
    <nameField>
        <displayFormat>CDE-{0000}</displayFormat>
        <label>Contract Discount Exception Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Discount Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/BD_Contract_Discount_Exception__c/fields/BD_Discount_Type__c.field-meta.xml
<CustomField>
    <fullName>BD_Discount_Type__c</fullName>
    <label>Discount Type</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/BD_Contract_Discount_Exception__c/fields/BD_External_ID__c.field-meta.xml
<CustomField>
    <fullName>BD_External_ID__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Perkin-UAT/force-app/main/default/objects/BD_Contract_Discount_Exception__c/fields/BD_Last_Txn_Number__c.field-meta.xml
<CustomField>
    <fullName>BD_Last_Txn_Number__c</fullName>
    <label>Last Txn Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/BD_Contract_Discount_Exception__c/fields/BD_Parts_Product__c.field-meta.xml
<CustomField>
    <fullName>BD_Parts_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parts Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contract Discount Exceptions (Parts Product)</relationshipLabel>
    <relationshipName>Parts_Contract_Discount_Exceptions</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/BD_Contract_Discount_Exception__c/fields/BD_Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>BD_Sales_Org__c</fullName>
    <label>Sales Org</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/BD_Contract_Discount_Exception__c/fields/BD_SAP_Activity_Type__c.field-meta.xml
<CustomField>
    <fullName>BD_SAP_Activity_Type__c</fullName>
    <label>SAP Activity Type</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/BD_Extended_Warranty_Part__c/BD_Extended_Warranty_Part__c.object-meta.xml
<CustomObject>
    <description>Extended Warranty Parts are mappings of Equipment Products to their Child Parts that should be covered under an Extended Warranty.</description>
    <label>Extended Warranty Part</label>
    <nameField>
        <displayFormat>EWP-{00000000}</displayFormat>
        <label>Extended Warranty Part Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Extended Warranty Parts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/BD_Extended_Warranty_Part__c/fields/BD_Covered_Part__c.field-meta.xml
<CustomField>
    <fullName>BD_Covered_Part__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Covered Part</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Extended Warranty Parts (Covered Part)</relationshipLabel>
    <relationshipName>Extended_Warranty_Parts</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/BD_Extended_Warranty_Part__c/fields/BD_Equipment_Product__c.field-meta.xml
<CustomField>
    <fullName>BD_Equipment_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipment Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Extended Warranty Parts</relationshipLabel>
    <relationshipName>Extended_Warranty_Equipment</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/BD_Extended_Warranty_Part__c/fields/BD_Extended_Months__c.field-meta.xml
<CustomField>
    <fullName>BD_Extended_Months__c</fullName>
    <label>Extended Months</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/BD_Extended_Warranty_Part__c/fields/BD_External_Key__c.field-meta.xml
<CustomField>
    <fullName>BD_External_Key__c</fullName>
    <externalId>true</externalId>
    <label>External Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Perkin-UAT/force-app/main/default/objects/BD_Extended_Warranty_Part__c/fields/BD_Is_Deleted__c.field-meta.xml
<CustomField>
    <fullName>BD_Is_Deleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Deleted</label>
    <type>Checkbox</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/BD_Extended_Warranty_Part__c/fields/BD_Last_Txn_Number__c.field-meta.xml
<CustomField>
    <fullName>BD_Last_Txn_Number__c</fullName>
    <label>Last Txn Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/BD_Extended_Warranty_Part__c/fields/BD_Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>BD_Sales_Org__c</fullName>
    <label>Sales Org</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Contract/recordTypes/ServiceContract.recordType-meta.xml
<RecordType>
    <fullName>ServiceContract</fullName>
    <active>true</active>
    <description>Service contract for installed equipment</description>
    <label>Service Contract</label>
</RecordType>

Perkin-UAT/force-app/main/default/objects/Product2/fields/Partnum__c.field-meta.xml
<CustomField>
    <fullName>Partnum__c</fullName>
    <description>Unique External Id that stores the Material ID from QS3 . Same as SAP Product code.
Same as Material Number from SAP.</description>
    <externalId>true</externalId>
    <label>Part Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/SMAX_PS_ActivityType__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_ActivityType__c</fullName>
    <label>Activity Type</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/SMAX_PS_CompletedTxnNum__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_CompletedTxnNum__c</fullName>
    <label>Completed Transaction Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/SMAX_PS_Medical_Classification__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_Medical_Classification__c</fullName>
    <description>Medical Classification copied from a Product Classification with Characteristic of PE Medical Device</description>
    <inlineHelpText>Medical Classification copied from a Product Classification with Characteristic of PE Medical Device</inlineHelpText>
    <label>Medical Classification</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_ProductClassification__c/SMAX_PS_ProductClassification__c.object-meta.xml
<CustomObject>
    <label>Product Classification</label>
    <nameField>
        <displayFormat>PCLS-{00000000}</displayFormat>
        <label>Product Classification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_ProductClassification__c/fields/SMAX_PS_Product__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Classifications</relationshipLabel>
    <relationshipName>Product_Classifications</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_ProductPlant__c/SMAX_PS_ProductPlant__c.object-meta.xml
<CustomObject>
    <label>Product Plant</label>
    <nameField>
        <displayFormat>PPNT-{00000000}</displayFormat>
        <label>Product Plant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Plants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_ProductPlant__c/fields/BD_Refurbished_Part__c.field-meta.xml
<CustomField>
    <fullName>BD_Refurbished_Part__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Refurbished Part</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Plants (Refurbished Part)</relationshipLabel>
    <relationshipName>Product_Plants2</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_ProductPlant__c/fields/BD_Refurbished_Part_Number__c.field-meta.xml
<CustomField>
    <fullName>BD_Refurbished_Part_Number__c</fullName>
    <label>Refurbished Part Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_ProductPlant__c/fields/BD_Return_Part__c.field-meta.xml
<CustomField>
    <fullName>BD_Return_Part__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Return Part</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Plants (Return Part)</relationshipLabel>
    <relationshipName>Product_Plants1</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_ProductPlant__c/fields/BD_Return_Part_Number__c.field-meta.xml
<CustomField>
    <fullName>BD_Return_Part_Number__c</fullName>
    <label>Return Part Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_ProductPlant__c/fields/SMAX_PS_PlannedDeliveryTimeInDays__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_PlannedDeliveryTimeInDays__c</fullName>
    <label>Delivery Time In Days</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_ProductPlant__c/fields/SMAX_PS_Plant__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_Plant__c</fullName>
    <label>Plant</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_ProductPlant__c/fields/SMAX_PS_Product__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Plants</relationshipLabel>
    <relationshipName>Product_Plants</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_ProductRevision__c/SMAX_PS_ProductRevision__c.object-meta.xml
<CustomObject>
    <label>Product Revision</label>
    <nameField>
        <displayFormat>PREV-{00000000}</displayFormat>
        <label>Product Revision Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Revisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_ProductRevision__c/fields/SMAX_PS_Product__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Revisions</relationshipLabel>
    <relationshipName>Product_Revisions</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_ProductSales__c/SMAX_PS_ProductSales__c.object-meta.xml
<CustomObject>
    <label>Product Sales</label>
    <nameField>
        <displayFormat>PSLS-{00000000}</displayFormat>
        <label>Product Sales Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Sales</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_ProductSales__c/fields/SMAX_PS_PartDescription__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_PartDescription__c</fullName>
    <label>Part Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_ProductSales__c/fields/SMAX_PS_PartNumber__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_PartNumber__c</fullName>
    <externalId>true</externalId>
    <label>Part Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_ProductSales__c/fields/SMAX_PS_Product__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Sales</relationshipLabel>
    <relationshipName>Product_Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_ProductSales__c/fields/SMAX_PS_ProductType__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_ProductType__c</fullName>
    <externalId>true</externalId>
    <label>Product Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_ProductSales__c/fields/SMAX_PS_SAP_ActivityType__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_SAP_ActivityType__c</fullName>
    <label>SAP Activity Type</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/classes/SMAX_PS_Product_UT.cls
/*
    Test Class for  SMAX_PS_ProductManager
    Client      :   PerkinElmer
    Created by  :   Veerendra on 2017-10-11
*/
@IsTest(SeeAllData=false)
public class SMAX_PS_Product_UT
{
    static testMethod void createProductTestData()
    {
        // Insert Product
        Product2 prod = new Product2(Name='Test Product', Description='Test Product Description this is a really long one to make sure we test the truncation logic when the description is too long and to make sure this is a really long one we will keep repeating ourselves repeating ourselves repeating ourselves repeating ourselves repeating ourselves repeating ourselves', 
            Partnum__c='TESTT00100101', SVMXC__Product_Type__c='Service Parts', SMAX_PS_ActivityType__c='ACT001');
        Product2 part = new Product2(Name='Test Part', Description='Test Part Description',
                Partnum__c='TESTP00100101', SVMXC__Product_Type__c='Consumable');
        Product2 returnPart = new Product2(Name='Test Return Part', Description='Test Return Part Description',
                Partnum__c='TESTP00100101C', SVMXC__Product_Type__c='Consumable');
        insert new List<Product2> { prod, part, returnPart };

        // Insert Product Revision
        SMAX_PS_ProductRevision__c prodRev = new SMAX_PS_ProductRevision__c(
                            SMAX_PS_Product__c=prod.Id);
        insert prodRev;

        // Insert Product Classification
        SMAX_PS_ProductClassification__c prodCls = new SMAX_PS_ProductClassification__c(
            SMAX_PS_Product__c=prod.Id,
            SMAX_PS_Characteristic__c = 'PE_MEDICAL_DEVICE',
            SMAX_PS_Value__c = 'Y');
        insert prodCls;
        

        // Insert Product Sales
        SMAX_PS_ProductSales__c prodSales = new SMAX_PS_ProductSales__c(
            SMAX_PS_Product__c=prod.Id);
        insert prodSales;

        // Insert Product Plant
        SMAX_PS_ProductPlant__c prodPlant = new SMAX_PS_ProductPlant__c(
            SMAX_PS_Product__c=prod.Id, SMAX_PS_Plant__c = 'TS12');
        SMAX_PS_ProductPlant__c partPlant = new SMAX_PS_ProductPlant__c(
                SMAX_PS_Product__c=part.Id, SMAX_PS_Plant__c = 'TS12', BD_Return_Part_Number__c = returnPart.Partnum__c);
        insert new List<SMAX_PS_ProductPlant__c> { prodPlant, partPlant };

        // ITSFDC-350 Adding Contract Discount Exception (CDE)
        BD_Contract_Discount_Exception__c cde1 = new BD_Contract_Discount_Exception__c(BD_Parts_Product__c = prod.Id,
            BD_Last_Txn_Number__c = 'Joe', BD_Discount_Type__c = 'Service Parts', BD_SAP_Activity_Type__c = 'PM',
            BD_Sales_Org__c = 'US11', BD_External_ID__c = prod.Partnum__c+'-US11-PM-*');
        BD_Contract_Discount_Exception__c cde2 = new BD_Contract_Discount_Exception__c(BD_Parts_Product__c = prod.Id,
                BD_Last_Txn_Number__c = 'ABC', BD_Discount_Type__c = 'Service Parts', BD_SAP_Activity_Type__c = 'REP',
                BD_Sales_Org__c = 'US11', BD_External_ID__c = prod.Partnum__c+'-US11-REP-*');
        insert new List<BD_Contract_Discount_Exception__c> { cde1, cde2 };

        // ITSFDC-507 Adding Extended Warranty Parts (EWP)
        BD_Extended_Warranty_Part__c ewp1 = new BD_Extended_Warranty_Part__c(BD_Equipment_Product__c = prod.Id,
            BD_Last_Txn_Number__c = 'Joe', BD_Sales_Org__c = 'US11', BD_External_Key__c = prod.Partnum__c+'-US11-'+part.Partnum__c,
            BD_Covered_Part__c = part.Id, BD_Extended_Months__c = 9);
        BD_Extended_Warranty_Part__c ewp2 = new BD_Extended_Warranty_Part__c(BD_Equipment_Product__c = prod.Id,
                BD_Last_Txn_Number__c = 'ABC', BD_Sales_Org__c = null, BD_External_Key__c = prod.Partnum__c+'-*-'+part.Partnum__c,
                BD_Covered_Part__c = part.Id, BD_Extended_Months__c = 15);
        insert new List<BD_Extended_Warranty_Part__c> { ewp1, ewp2 };

        prod.SMAX_PS_CompletedTxnNum__c='ABC';
        update prod;
        
          // Insert Product Classification
        SMAX_PS_ProductClassification__c prodCls2 = new SMAX_PS_ProductClassification__c(
            SMAX_PS_Product__c=prod.Id,
            SMAX_PS_Characteristic__c = 'PE_MEDICAL_DEVICE',
            SMAX_PS_Value__c = 'Y');
        insert prodCls2;
        update prodCls2;
        Product2 updated = [SELECT Id, Name, ProductCode, SMAX_PS_Medical_Classification__c FROM Product2 WHERE Id = :prod.Id];
       // System.assertEquals('Y', updated.SMAX_PS_Medical_Classification__c);

        /*SMAX_PS_ProductSales__c prodSalesResult = [SELECT Id, Name, SMAX_PS_PartDescription__c,
            SMAX_PS_PartNumber__c, SMAX_PS_ProductType__c, SMAX_PS_SAP_ActivityType__c 
            FROM SMAX_PS_ProductSales__c WHERE Id = :prodSales.Id];
        System.assertNotEquals(null, prodSalesResult.SMAX_PS_PartDescription__c);
        System.assertEquals(prod.Partnum__c, prodSalesResult.SMAX_PS_PartNumber__c);
        System.assertEquals(prod.SVMXC__Product_Type__c, prodSalesResult.SMAX_PS_ProductType__c);
        System.assertEquals(prod.SMAX_PS_ActivityType__c, prodSalesResult.SMAX_PS_SAP_ActivityType__c);

        SMAX_PS_ProductPlant__c partPlantResult = [SELECT Id, Name, BD_Return_Part__c
            FROM SMAX_PS_ProductPlant__c WHERE Id = :partPlant.Id];
        //System.assertEquals(returnPart.Id, partPlantResult.BD_Return_Part__c);

        List<BD_Contract_Discount_Exception__c> cdeResults = [SELECT Id, Name FROM BD_Contract_Discount_Exception__c
            WHERE BD_Parts_Product__c = :prod.Id];
        //System.assertEquals(1, cdeResults.size());

        List<BD_Extended_Warranty_Part__c> ewpResults = [SELECT Id, Name, BD_External_Key__c FROM BD_Extended_Warranty_Part__c
            WHERE BD_Equipment_Product__c = :prod.Id AND BD_Is_Deleted__c = FALSE];*/
        //System.assertEquals(1, ewpResults.size());

        delete prod;
    }

    // 2022/07/13 Tony ITSVMX-562 Modify the replenishment parts ordering process
    @IsTest
    static void testProcessProductPlantForRefurbishedParts() {

        Account acct = SMAX_PS_TestDataFactory.createTestAccount('Test Acct', 'TST1001001');

        // Create an Active Service Contract
        Date startDate = System.today() - 30;
        Date endDate = System.today() + 30;
        SVMXC__Service_Contract__c serviceContract = SMAX_PS_TestDataFactory.createSvcMaintContract('TestSvcContract', acct.Id, startDate, endDate);
        SVMXC__Service_Contract__c serviceContractItem = SMAX_PS_TestDataFactory.createContractItem(serviceContract, 'TestSvcContractItem', startDate, endDate);

        // Create Service Contract Services with Service Parts Discount Covered = 100.00
        SVMXC__Service_Contract_Services__c serviceContractServices = SMAX_PS_TestDataFactory.createEntitlement(serviceContractItem, 'Parts', 10, 10);
        serviceContractServices.SMAX_PS_ServicePartsDiscountCovered__c = 100.00;
        update serviceContractServices;
        System.debug('serviceContractServices: ' + serviceContractServices);

        Contact cont = SMAX_PS_TestDataFactory.createTestContact('Testie', 'Testerson', acct, 'TEST000000101');
        SVMXC__Site__c loc = SMAX_PS_TestDataFactory.createTestLocation(acct, 'Test Loc', 'TLOC0010101', 'TST001');
        Product2 product1 = SMAX_PS_TestDataFactory.createTestProduct('Test Product', 'TPRD1001', 'Test');
        Product2 product2 = SMAX_PS_TestDataFactory.createTestProduct('Test Refurb Product', 'Refurb123', 'Test');

        // Create an Installed Product with Medical Device = FALSE
        SVMXC__Installed_Product__c ip = SMAX_PS_TestDataFactory.createIP('TESTX0000234001', acct, loc, 'TST00101', product1);
        ip.SMAX_PS_MaintenancePlant__c = 'P123';
        update ip;
        //System.debug('ip.SMAX_PS_IsMedicalDevice__c: ' + ip.SMAX_PS_IsMedicalDevice__c);

        // Create Product Plant
        SMAX_PS_ProductPlant__c productPlant = new SMAX_PS_ProductPlant__c();
        productPlant.SMAX_PS_Product__c = product1.Id;
        productPlant.SMAX_PS_Plant__c = 'P123';
//      productPlant.BD_Refurbished_Part__c = product2.Id;  // This should be set by the code in SMAX_PS_ProductManager.processProductPlant()
        productPlant.BD_Refurbished_Part_Number__c = 'Refurb123';
        insert productPlant;
        productPlant.SMAX_PS_PlannedDeliveryTimeInDays__c = '3';
        update productPlant;

        List<SMAX_PS_ProductPlant__c> testProductPlants = [SELECT Id, BD_Refurbished_Part_Number__c, BD_Refurbished_Part__c FROM SMAX_PS_ProductPlant__c WHERE BD_Refurbished_Part__c = :product2.Id];
        //System.debug('testProductPlants: ' + testProductPlants.size() + ' ' + testProductPlants);
        //System.assertEquals(1, testProductPlants.size(), 'There should be 1 record that has the correct Refurbished Part associated to it.');

    }
}