Perkin-UAT/force-app/main/default/objects/Account/recordTypes/Test.recordType-meta.xml
<RecordType>
    <fullName>Test</fullName>
    <active>true</active>
    <label>Test</label>
</RecordType>

Perkin-UAT/force-app/main/default/objects/Demo_Log__c/Demo_Log__c.object-meta.xml
<CustomObject>
    <label>Demo Log</label>
    <nameField>
        <displayFormat>INF-RML-{000000000}</displayFormat>
        <label>Demo Request No#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demo Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/Demo_Log__c/fields/Demo_Lead_INF__c.field-meta.xml
<CustomField>
    <fullName>Demo_Lead_INF__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity Leader</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Demo_Request</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Demo_Log__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>R00N30000001GFdsEAG</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Demo_Log__c/fields/Primary_Product_INF__c.field-meta.xml
<CustomField>
    <fullName>Primary_Product_INF__c</fullName>
    <label>Primary Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Attivio</fullName>
            </value>
            <value>
                <fullName>CAFÉ  - Medical Review</fullName>
            </value>
            <value>
                <fullName>CAFÉ - RBM</fullName>
            </value>
            <value>
                <fullName>CAFÉ - RWE</fullName>
            </value>
            <value>
                <fullName>ChemDraw</fullName>
            </value>
            <value>
                <fullName>Columbus</fullName>
            </value>
            <value>
                <fullName>Elements</fullName>
            </value>
            <value>
                <fullName>E-Notebook Biology</fullName>
            </value>
            <value>
                <fullName>E-Notebook Chemistry</fullName>
            </value>
            <value>
                <fullName>E-Notebook Formulations</fullName>
            </value>
            <value>
                <fullName>iLab</fullName>
            </value>
            <value>
                <fullName>Inventory</fullName>
            </value>
            <value>
                <fullName>Inventory Ent</fullName>
            </value>
            <value>
                <fullName>Lead Discovery</fullName>
            </value>
            <value>
                <fullName>Lead Discovery Premium</fullName>
            </value>
            <value>
                <fullName>LimsLink</fullName>
            </value>
            <value>
                <fullName>Registration</fullName>
            </value>
            <value>
                <fullName>Signals Clinical</fullName>
            </value>
            <value>
                <fullName>Signals Data Factory</fullName>
            </value>
            <value>
                <fullName>Signals Lead Discovery</fullName>
            </value>
            <value>
                <fullName>Signals Medical Review</fullName>
            </value>
            <value>
                <fullName>Signals Notebook</fullName>
            </value>
            <value>
                <fullName>Signals Notebook - Biology</fullName>
            </value>
            <value>
                <fullName>Signals Notebook - Chemistry</fullName>
            </value>
            <value>
                <fullName>Signals Notebook for ChemDraw</fullName>
            </value>
            <value>
                <fullName>Signals Screening</fullName>
            </value>
            <value>
                <fullName>Signals Translational</fullName>
            </value>
            <value>
                <fullName>Spotfire Biology</fullName>
            </value>
            <value>
                <fullName>Spotfire Chemistry</fullName>
            </value>
            <value>
                <fullName>Spotfire Clinical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Demo_Log__c/recordTypes/Informatics.recordType-meta.xml
<RecordType>
    <fullName>Informatics</fullName>
    <active>true</active>
    <label>Informatics</label>
</RecordType>

Perkin-UAT/force-app/main/default/classes/Test_Informatics_Mapping.cls
@isTest
public class Test_Informatics_Mapping {
  @isTest
    public static void Inf_Dmeo_Logs_MappingTest(){
        Id DemoLogRT = Schema.getGlobalDescribe().get('Demo_Log__c').getDescribe().getRecordTypeInfosByName().get('Informatics').getRecordTypeId();
        Id OppRT = Schema.getGlobalDescribe().get('Opportunity').getDescribe().getRecordTypeInfosByName().get('Informatics').getRecordTypeId();
        Id AccRT = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Prospect').getRecordTypeId();
        
        Account acc = new Account();
        acc.RecordTypeId = AccRT;
        acc.name = 'Test Prospect Account';
        acc.ShippingCity = 'Test';
        acc.ShippingState = 'Test State';
        acc.ShippingStreet = 'test street';
        acc.ShippingCountry = 'IT';
        acc.ShippingPostalCode = '123456';
        insert acc;
        
        Opportunity opp = new Opportunity();
        opp.RecordTypeId = OppRT;
        opp.AccountId = acc.id;
        opp.Name = 'Test Informatics Opportunity';
        opp.StageName = 'Stage 1 - Create/Plan';
        opp.CloseDate = Date.today().addDays(5);
        insert opp;
        
        Test.startTest();
        Demo_Log__c dmo = new Demo_Log__c();
        dmo.RecordTypeId = DemoLogRT;
        dmo.Opportunity__c = opp.id;
        dmo.Primary_Product_INF__c = 'E-Notebook Biology';
        insert dmo;
        Demo_Log__c dmo1 = [Select Demo_Lead_INF__r.Name From Demo_Log__c where Id = :dmo.id];
        //System.assert(dmo1.Demo_Lead_INF__r.Name == 'Linda Kewitsch');
        Country_Region_Mapping cm = new Country_Region_Mapping();
        String s = cm.GetGlobalRegion('JP');
        String s1 = cm.GetGlobalRegion('US');
        dmo.Primary_Product_INF__c = 'ChemDraw';
        update dmo;
        Test.stopTest();
        
    }
}