Perkin-UAT/force-app/main/default/objects/Account/recordTypes/Test.recordType-meta.xml
<RecordType>
    <fullName>Test</fullName>
    <active>true</active>
    <label>Test</label>
</RecordType>

Perkin-UAT/force-app/main/default/objects/Contact/fields/INF_Product_Line__c.field-meta.xml
<CustomField>
    <fullName>INF_Product_Line__c</fullName>
    <label>INF Product Line</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>QA/QC</fullName>
            </value>
            <value>
                <fullName>Enterprise R-D</fullName>
            </value>
            <value>
                <fullName>Personal Applications</fullName>
            </value>
            <value>
                <fullName>Analysis-Visualisation</fullName>
            </value>
            <value>
                <fullName>Elements</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Contact/fields/Solution_Area_of_Interest__c.field-meta.xml
<CustomField>
    <fullName>Solution_Area_of_Interest__c</fullName>
    <description>ORIG:ANNUITAS PDG Program

NEW: SS This field is now used on Interaction, Interaction Assignment Rule, Lead, Contact, Oppty</description>
    <label>Solution Area of Interest</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Air</fullName>
            </value>
            <value>
                <fullName>Applied Genomics</fullName>
            </value>
            <value>
                <fullName>Biologics</fullName>
            </value>
            <value>
                <fullName>Cannabis</fullName>
            </value>
            <value>
                <fullName>Cell and Gene Therapy</fullName>
            </value>
            <value>
                <fullName>Chemicals</fullName>
            </value>
            <value>
                <fullName>Clinical Studies</fullName>
            </value>
            <value>
                <fullName>Digital Lab</fullName>
            </value>
            <value>
                <fullName>Energy</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Forensics and Security</fullName>
            </value>
            <value>
                <fullName>Geochemistry, Mining and Metals</fullName>
            </value>
            <value>
                <fullName>Life Science Research</fullName>
            </value>
            <value>
                <fullName>Material</fullName>
            </value>
            <value>
                <fullName>Maternal Fetal Health</fullName>
            </value>
            <value>
                <fullName>Newborn Screening</fullName>
            </value>
            <value>
                <fullName>Pre-Clinical Drug Development</fullName>
            </value>
            <value>
                <fullName>Pre-Clinical Drug Discovery</fullName>
            </value>
            <value>
                <fullName>QA/QC Drug Manufacturing Process</fullName>
            </value>
            <value>
                <fullName>Soil/Solids</fullName>
            </value>
            <value>
                <fullName>Strategic Services</fullName>
            </value>
            <value>
                <fullName>Water</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/INF_Application__c/INF_Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/INF_Application__c/fields/INF_Product_Group__c.field-meta.xml
<CustomField>
    <fullName>INF_Product_Group__c</fullName>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Spotfire</fullName>
            </value>
            <value>
                <fullName>E-Notebook</fullName>
            </value>
            <value>
                <fullName>CBOE</fullName>
            </value>
            <value>
                <fullName>iLab/Limslink</fullName>
            </value>
            <value>
                <fullName>Personal Applications</fullName>
            </value>
            <value>
                <fullName>GeoSpiza</fullName>
            </value>
            <value>
                <fullName>Columbus &amp; Volocity</fullName>
            </value>
            <value>
                <fullName>Elements</fullName>
            </value>
            <value>
                <fullName>Signals Notebook</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/INF_Application__c/fields/INF_Product_Line__c.field-meta.xml
<CustomField>
    <fullName>INF_Product_Line__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AVS</fullName>
            </value>
            <value>
                <fullName>AVC</fullName>
            </value>
            <value>
                <fullName>DSK</fullName>
            </value>
            <value>
                <fullName>ENT</fullName>
            </value>
            <value>
                <fullName>QAS</fullName>
            </value>
            <value>
                <fullName>ISS</fullName>
            </value>
            <value>
                <fullName>ELM</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>SIG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/INF_Case_Application__c/INF_Case_Application__c.object-meta.xml
<CustomObject>
    <label>Case Application</label>
    <nameField>
        <displayFormat>CA-{000000000}</displayFormat>
        <label>Case Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/INF_Case_Application__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>INF_Application__c</referenceTo>
    <relationshipLabel>Case Applications</relationshipLabel>
    <relationshipName>Case_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/INF_Case_Application__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Applications</relationshipLabel>
    <relationshipName>Case_Applications</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/INF_Case_Survey__c/INF_Case_Survey__c.object-meta.xml
<CustomObject>
    <label>Case Survey</label>
    <nameField>
        <displayFormat>Survey-{0000}</displayFormat>
        <label>Case Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Surveys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/INF_Case_Survey__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Surveys</relationshipLabel>
    <relationshipName>Case_Surveys</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/INF_Case_Survey__c/fields/INF_Recently_Created_Survey__c.field-meta.xml
<CustomField>
    <fullName>INF_Recently_Created_Survey__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Recently Created Survey</label>
    <type>Checkbox</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/INF_Case_Survey__c/fields/INF_Support_Sat_Bin__c.field-meta.xml
<CustomField>
    <fullName>INF_Support_Sat_Bin__c</fullName>
    <label>Support Satisfaction Bin</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Difficult</fullName>
            </value>
            <value>
                <fullName>Easy</fullName>
            </value>
            <value>
                <fullName>Excellent Product</fullName>
            </value>
            <value>
                <fullName>Excellent Service</fullName>
            </value>
            <value>
                <fullName>Fast Resolution</fullName>
            </value>
            <value>
                <fullName>Frequency of Updates</fullName>
            </value>
            <value>
                <fullName>Neither</fullName>
            </value>
            <value>
                <fullName>No Solution</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Phone Issues</fullName>
            </value>
            <value>
                <fullName>Problem Solved</fullName>
            </value>
            <value>
                <fullName>Rep Communication Skills</fullName>
            </value>
            <value>
                <fullName>Rep Understanding of the Problem</fullName>
            </value>
            <value>
                <fullName>SDK</fullName>
            </value>
            <value>
                <fullName>Software Activation</fullName>
            </value>
            <value>
                <fullName>Software Defect</fullName>
            </value>
            <value>
                <fullName>Took too long</fullName>
            </value>
            <value>
                <fullName>Unsupported Environment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/INF_Case_Survey__c/fields/INF_Support_sat_Comments__c.field-meta.xml
<CustomField>
    <fullName>INF_Support_sat_Comments__c</fullName>
    <label>Support Satisfaction Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/INF_Case_Survey__c/fields/INF_Support_Sat_No__c.field-meta.xml
<CustomField>
    <fullName>INF_Support_Sat_No__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Support Satisfaction No</label>
    <type>Checkbox</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/INF_Case_Survey__c/fields/INF_Support_Sat_Yes__c.field-meta.xml
<CustomField>
    <fullName>INF_Support_Sat_Yes__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Support Satisfaction Yes</label>
    <type>Checkbox</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SAI_Lead_Routing_Values__c/SAI_Lead_Routing_Values__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>For PDG Lead Routing</description>
    <label>SAI Lead Routing Values</label>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/SAI_Lead_Routing_Values__c/fields/SAI_Values__c.field-meta.xml
<CustomField>
    <fullName>SAI_Values__c</fullName>
    <label>SAI Values</label>
    <type>TextArea</type>
</CustomField>

Perkin-UAT/force-app/main/default/classes/SurveySubmitControllerTest.cls
@isTest
public class SurveySubmitControllerTest{
    static testMethod void SurveySubmitController(){
             SAI_Lead_Routing_Values__c cc =new SAI_Lead_Routing_Values__c();
            cc.SAI_Values__c = 'Applied Genomics, Maternal Fetal Health, Newborn Screening';
            insert cc;
           Account acc = CT_TestDataSetupUtility.createTestAccount('TEST','77778','Test');
            insert acc;
            Contact con = CT_TestDataSetupUtility.createTestContact(acc.id,'test','test','test@test.com');
                con.Solution_Area_of_Interest__c = 'Air';
            insert con;
            Case casetoinsert = CT_TestDataSetupUtility.createTestCase('Informatics','New','test','Phone',acc.id,con.id);
            insert casetoinsert;
                
           
             Test.startTest();
             Test.setCurrentPage(new PageReference('/apex/SurveyPage?id='+casetoinsert.Id+'&mode=YES'));
             SurveySubmitController  jpc = new SurveySubmitController();
             jpc.initialize(); 
            // jpc.getItems();
             jpc.processSurveyCreationForYES();
             Test.stopTest(); 
  
    
    }
    
    static testMethod void SurveySubmitController1(){
       SAI_Lead_Routing_Values__c cc =new SAI_Lead_Routing_Values__c();
            cc.SAI_Values__c = 'Applied Genomics, Maternal Fetal Health, Newborn Screening';
            insert cc;
    Account acc = CT_TestDataSetupUtility.createTestAccount('TEST','77778','Test');
    insert acc;
    Contact con = CT_TestDataSetupUtility.createTestContact(acc.id,'test','test','test@test.com');
    insert con;
    Case casetoinsert = CT_TestDataSetupUtility.createTestCase('Informatics','New','test','Phone',acc.id,con.id);
    insert casetoinsert;
    
     Test.startTest();
     Test.setCurrentPage(new PageReference('/apex/SurveyPage?id='+casetoinsert.Id+'&mode=NO'));
     SurveySubmitController  jpc = new SurveySubmitController();
     jpc.initialize(); 
     jpc.comments ='Test';
     jpc.selectedvalue = 'Others';
     //jpc.getItems();
     jpc.processSurveyCreationForNO();
     Test.stopTest();
    }
    
    static testMethod void SurveySubmitController2(){
       SAI_Lead_Routing_Values__c cc =new SAI_Lead_Routing_Values__c();
            cc.SAI_Values__c = 'Applied Genomics, Maternal Fetal Health, Newborn Screening';
            insert cc;
    Account acc = CT_TestDataSetupUtility.createTestAccount('TEST','77778','Test');
    insert acc;
    Contact con = CT_TestDataSetupUtility.createTestContact(acc.id,'test','test','test@test.com');
    insert con;
    Case casetoinsert = CT_TestDataSetupUtility.createTestCase('Informatics','New','test','Phone',acc.id,con.id);
    insert casetoinsert;
    INF_Case_Survey__c survey = new INF_Case_Survey__c(Case__c = casetoinsert.id,INF_Support_Sat_No__c =true,INF_Support_sat_Comments__c ='test',INF_Support_Sat_Bin__c='Others',INF_Recently_Created_Survey__c=true);
    insert survey;
    
     Test.startTest();
     Test.setCurrentPage(new PageReference('/apex/SurveyPage?id='+casetoinsert.Id+'&mode=NO'));
     SurveySubmitController  jpc = new SurveySubmitController();
     jpc.initialize(); 
     jpc.comments ='Test';
     jpc.selectedvalue = 'Others';
   //  jpc.getItems();
     jpc.processSurveyCreationForNO();
     Test.stopTest();
    }
    
    static testMethod void SurveySubmitController3(){
       SAI_Lead_Routing_Values__c cc =new SAI_Lead_Routing_Values__c();
            cc.SAI_Values__c = 'Applied Genomics, Maternal Fetal Health, Newborn Screening';
            insert cc;
    Account acc = CT_TestDataSetupUtility.createTestAccount('TEST','77778','Test');
    insert acc;
    Contact con = CT_TestDataSetupUtility.createTestContact(acc.id,'test','test','test@test.com');
    insert con;
    Case casetoinsert = CT_TestDataSetupUtility.createTestCase('Informatics','New','test','Phone',acc.id,con.id);
    insert casetoinsert;
    INF_Application__c app = new INF_Application__c(Name='test',INF_Product_Group__c='CBOE',INF_Product_Line__c ='test');
    insert app;
    INF_Case_Application__c caseapp = new INF_Case_Application__c(Application__c=app.id,Case__c = casetoinsert.id);
    insert caseapp;
    INF_Case_Survey__c survey = new INF_Case_Survey__c(Case__c = casetoinsert.id,INF_Support_Sat_Yes__c = true,INF_Recently_Created_Survey__c=true);
    insert survey;
    
     Test.startTest();
     Test.setCurrentPage(new PageReference('/apex/SurveyPage?id='+casetoinsert.Id+'&mode=YES'));
     SurveySubmitController  jpc = new SurveySubmitController();
     jpc.initialize(); 
    // jpc.getItems();
     jpc.processSurveyCreationForYES();
     String a = jpc.getselectedvalue();
     jpc.setselectedvalue('a');
     jpc.processSurveyCreation();
     jpc.getYesItems();
     Test.stopTest();
    }
    static testMethod void SurveySubmitController4(){
       SAI_Lead_Routing_Values__c cc =new SAI_Lead_Routing_Values__c();
            cc.SAI_Values__c = 'Applied Genomics, Maternal Fetal Health, Newborn Screening';
            insert cc;
    Account acc = CT_TestDataSetupUtility.createTestAccount('TEST','77778','Test');
    insert acc;
    Contact con = CT_TestDataSetupUtility.createTestContact(acc.id,'test','test','test@test.com');
    insert con;
    Case casetoinsert = CT_TestDataSetupUtility.createTestCase('Informatics','New','test','Phone',acc.id,con.id);
    insert casetoinsert;
    INF_Application__c app = new INF_Application__c(Name='test',INF_Product_Group__c='CBOE',INF_Product_Line__c ='test');
    insert app;
    INF_Case_Application__c caseapp = new INF_Case_Application__c(Application__c=app.id,Case__c = casetoinsert.id);
    insert caseapp;
    INF_Case_Survey__c survey = new INF_Case_Survey__c(Case__c = casetoinsert.id,INF_Support_Sat_Yes__c = true,INF_Recently_Created_Survey__c=true);
    insert survey;
    Datetime now = Datetime.now().addDays(-1);
    Test.setCreatedDate(survey.Id, now); 
    
     Test.startTest();
     Test.setCurrentPage(new PageReference('/apex/SurveyPage?id='+casetoinsert.Id+'&mode=NO'));
     SurveySubmitController  jpc = new SurveySubmitController();
     jpc.initialize(); 
    // jpc.getItems();
     jpc.processSurveyCreationForYES();
     String a = jpc.getselectedvalue();
     jpc.setselectedvalue('a');
     jpc.processSurveyCreation();
     jpc.getYesItems();
     
      Test.setCurrentPage(new PageReference('/apex/SurveyPage?id='+casetoinsert.Id+'&mode=YES'));
       jpc = new SurveySubmitController();
     jpc.initialize(); 
    // jpc.getItems();
     jpc.processSurveyCreationForYES();
     a = jpc.getselectedvalue();
     jpc.setselectedvalue('a');
     jpc.processSurveyCreation();
     jpc.getYesItems();
     Test.stopTest();
    }
}