Perkin-UAT/force-app/main/default/objects/Account/recordTypes/Test.recordType-meta.xml
<RecordType>
    <fullName>Test</fullName>
    <active>true</active>
    <label>Test</label>
</RecordType>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Account_Type_INF__c.field-meta.xml
<CustomField>
    <fullName>Account_Type_INF__c</fullName>
    <description>This field is used within Informatics quote process to drive related Price List.  Do not modify without contacting Informatics SalesForce.com support</description>
    <inlineHelpText>Price List requires Acct Type</inlineHelpText>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Commercial</fullName>
                <default>true</default>
                <label>Commercial</label>
            </value>
            <value>
                <fullName>Academic</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Renewal_Required_INF__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Required_INF__c</fullName>
    <label>Renewal Required?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Strategic_Market_INF__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Market_INF__c</fullName>
    <label>Strategic Market</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Life Sciences Research</fullName>
            </value>
            <value>
                <fullName>Clinical &amp; Translational</fullName>
            </value>
            <value>
                <fullName>Related Markets</fullName>
            </value>
            <value>
                <fullName>Production Support</fullName>
            </value>
            <value>
                <fullName>Academic &amp; Government</fullName>
            </value>
            <value>
                <fullName>Clinical</fullName>
            </value>
            <value>
                <fullName>Applied Markets</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/OpportunityLineItem/fields/End_Date_INF__c.field-meta.xml
<CustomField>
    <fullName>End_Date_INF__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/OpportunityLineItem/fields/Start_Date_INF__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_INF__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/License_Type_INF__c.field-meta.xml
<CustomField>
    <fullName>License_Type_INF__c</fullName>
    <label>License Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/Product_Type_INF__c.field-meta.xml
<CustomField>
    <fullName>Product_Type_INF__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>License</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/classes/TestDelOppLineTrigger.cls
@isTest(seeAllData=true)
public class TestDelOppLineTrigger {
	static testMethod void Test_Method1(){
        Opportunity newOpps = new Opportunity();
        Account ac = new Account ();
        ac.name='Test Account';
        ac.shippingCountry = 'US';
        ac.Industry ='Biotech';
        ac.CurrencyIsoCode = 'USD';
        ac.BillingStreet = 'Street1';
        ac.BillingCity = 'City1';
        ac.BillingState = 'State';
        ac.BillingCountry ='US';
        ac.BillingPostalCode = '12345';
        insert ac;
        System.debug('#######ACC:' + ac.Id);
		newOpps = new Opportunity(Name='opp1',AccountId=ac.Id,/*RecordTypeId='01230000001aIi6',*/Renewal_Required_INF__c='Yes',Account_Type_INF__c='Academic',StageName='Stage 1 - Create/Plan',CloseDate=Date.today(),Strategic_Market_INF__c='Clinical',Type='New Account',ForecastCategoryName='Pipeline',CurrencyIsoCode = 'USD',Solution_Area_of_Interest__c='Energy');        
        insert newOpps;
        
        Pricebook2  standardPb = [select id, name, isActive from Pricebook2 where IsStandard = true limit 1];

        Pricebook2 pbk1 = new Pricebook2 (Name='Test Pricebook Entry 1',Description='Test Pricebook Entry 1');
        insert pbk1;
        
        Product2 prd1 = new Product2 (Name='Term test',ProductCode='CPH567',License_Type_INF__c='Services',Product_Type_INF__c='Services',Description='Test Product Entry 1');
		insert prd1;
        
        PricebookEntry pbe2 = new PricebookEntry (Product2ID=prd1.id,Pricebook2ID=standardPb.id,IsActive=true,UseStandardPrice=false,UnitPrice=50);
		insert pbe2;
        System.debug('#######OPP:' + newOpps.Id);
        List<OpportunityLineItem> newLineItems = new List<OpportunityLineItem>();
        newLineItems.add(new OpportunityLineItem(OpportunityID=newOpps.id,Start_Date_INF__c=Date.today(),End_Date_INF__c=Date.today(),TotalPrice=10,Quantity=1,PriceBookEntryID=pbe2.id));
        insert newLineItems;
		System.debug('#######LineItem:' + newLineItems[0].Id);
          
        OpportunityLineItem opline = new OpportunityLineItem();
        opline.Id = newLineItems[0].Id;
        delete opline;
    }
}