Perkin-UAT/force-app/main/default/objects/Account/recordTypes/Test.recordType-meta.xml
<RecordType>
    <fullName>Test</fullName>
    <active>true</active>
    <label>Test</label>
</RecordType>

Perkin-UAT/force-app/main/default/objects/B2B_Subscription_Items__c/B2B_Subscription_Items__c.object-meta.xml
<CustomObject>
    <label>B2B Subscription Items</label>
    <nameField>
        <displayFormat>SubItem# {00000}</displayFormat>
        <label>B2B Subscriptions tems</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B2B Subscription Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/B2B_Subscription_Items__c/fields/B2B_Product__c.field-meta.xml
<CustomField>
    <fullName>B2B_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>B2B Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>B2B Subscription Items</relationshipLabel>
    <relationshipName>B2B_Subscription_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Subscription_Items__c/fields/B2B_Subscriptions__c.field-meta.xml
<CustomField>
    <fullName>B2B_Subscriptions__c</fullName>
    <label>B2B Subscriptions</label>
    <referenceTo>B2B_Subscriptions__c</referenceTo>
    <relationshipLabel>B2B Subscription Items</relationshipLabel>
    <relationshipName>B2B_Subscription_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Subscription_Items__c/fields/B2B_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>B2B_Unit_Price__c</fullName>
    <label>B2B Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Subscriptions__c/B2B_Subscriptions__c.object-meta.xml
<CustomObject>
    <label>B2B Subscriptions</label>
    <nameField>
        <displayFormat>Sub# {00000}</displayFormat>
        <label>B2B Subscriptions</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B2B Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/B2B_Subscriptions__c/fields/B2B_Account__c.field-meta.xml
<CustomField>
    <fullName>B2B_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>B2B Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>B2B Subscriptions</relationshipLabel>
    <relationshipName>B2B_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Subscriptions__c/fields/B2B_Billing_Address__c.field-meta.xml
<CustomField>
    <fullName>B2B_Billing_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>B2B Billing Address</label>
    <referenceTo>ContactPointAddress</referenceTo>
    <relationshipLabel>B2B Subscriptions (B2B Billing Address)</relationshipLabel>
    <relationshipName>B2B_Subscriptions1</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Subscriptions__c/fields/B2B_Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>B2B_Billing_Frequency__c</fullName>
    <label>B2B Billing Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Every 1 Month</fullName>
            </value>
            <value>
                <fullName>Every 2 Months</fullName>
            </value>
            <value>
                <fullName>Every 3 Months</fullName>
            </value>
            <value>
                <fullName>Every 6 Months</fullName>
            </value>
            <value>
                <fullName>Every 12 Months</fullName>
            </value>
            <value>
                <fullName>Every 18 Months</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Subscriptions__c/fields/B2B_Contact__c.field-meta.xml
<CustomField>
    <fullName>B2B_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>B2B Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>B2B Subscriptions</relationshipLabel>
    <relationshipName>B2B_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Subscriptions__c/fields/B2B_End_Date__c.field-meta.xml
<CustomField>
    <fullName>B2B_End_Date__c</fullName>
    <label>B2B End Date</label>
    <type>Date</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Subscriptions__c/fields/B2B_Next_Billing_Date__c.field-meta.xml
<CustomField>
    <fullName>B2B_Next_Billing_Date__c</fullName>
    <label>B2B Next Billing Date</label>
    <type>Date</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Subscriptions__c/fields/B2B_Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>B2B_Payment_Method__c</fullName>
    <label>B2B Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PO</fullName>
            </value>
            <value>
                <fullName>card</fullName>
                <label>Card</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Subscriptions__c/fields/B2B_Po_Number__c.field-meta.xml
<CustomField>
    <fullName>B2B_Po_Number__c</fullName>
    <label>B2B Po Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Subscriptions__c/fields/B2B_Shipping_Address__c.field-meta.xml
<CustomField>
    <fullName>B2B_Shipping_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>B2B Shipping Address</label>
    <referenceTo>ContactPointAddress</referenceTo>
    <relationshipLabel>B2B Subscriptions</relationshipLabel>
    <relationshipName>B2B_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Subscriptions__c/fields/B2B_Shipping_Method__c.field-meta.xml
<CustomField>
    <fullName>B2B_Shipping_Method__c</fullName>
    <label>B2B Shipping Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Subscriptions__c/fields/B2B_Shipping_Provider__c.field-meta.xml
<CustomField>
    <fullName>B2B_Shipping_Provider__c</fullName>
    <label>B2B Shipping Provider</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Subscriptions__c/fields/B2B_Shipping_Provider_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>B2B_Shipping_Provider_Account_Number__c</fullName>
    <label>B2B Shipping Provider Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Subscriptions__c/fields/B2B_Special_Instruction__c.field-meta.xml
<CustomField>
    <fullName>B2B_Special_Instruction__c</fullName>
    <label>B2B Special Instruction</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Subscriptions__c/fields/B2B_Status__c.field-meta.xml
<CustomField>
    <fullName>B2B_Status__c</fullName>
    <label>B2B Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Subscriptions__c/fields/Subscription_Name__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Name__c</fullName>
    <label>Subscription Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/B2B_Quantity__c.field-meta.xml
<CustomField>
    <fullName>B2B_Quantity__c</fullName>
    <label>B2B Quantity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/B2B_Shipping_Method__c.field-meta.xml
<CustomField>
    <fullName>B2B_Shipping_Method__c</fullName>
    <label>Shipping Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/WebCart/fields/B2B_Shipping_Provider__c.field-meta.xml
<CustomField>
    <fullName>B2B_Shipping_Provider__c</fullName>
    <label>B2B Shipping Provider</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/WebCart/fields/B2B_Shipping_Provider_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>B2B_Shipping_Provider_Account_Number__c</fullName>
    <label>B2B Shipping Provider Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/WebCart/fields/B2B_Special_Instruction__c.field-meta.xml
<CustomField>
    <fullName>B2B_Special_Instruction__c</fullName>
    <description>Used to store the special instructions during checkout. Perk-292</description>
    <label>B2B Special Instruction</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/WebCart/fields/B2B_Subscriptions__c.field-meta.xml
<CustomField>
    <fullName>B2B_Subscriptions__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>B2B Subscription</label>
    <referenceTo>B2B_Subscriptions__c</referenceTo>
    <relationshipLabel>Carts</relationshipLabel>
    <relationshipName>Carts</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/classes/B2B_SubscriptionOrderSchedulerTest.cls
@isTest
public with sharing class B2B_SubscriptionOrderSchedulerTest {
    private static final String ACCOUNT_NAME = 'Test Account';
    private static final String CONTACT_NAME = 'Test Contact';
    private static final String PRODUCT_NAME = 'Test Product';
    private static final String LOCATION_NAME = 'Test';
    private static final String Community_Nickname = 'testuser';
    private static final String EMAIL = 'test@user.com';

    @TestSetup
    static void setup() {
        Product2 prod = B2B_TestDataFactory.createProduct(PRODUCT_NAME,true);
        List<Product2> prodList = new List<Product2>();
        prodList.add(prod);			
        Account acc = B2B_TestDataFactory.createAccount(ACCOUNT_NAME,true);
        Contact con = B2B_TestDataFactory.createContact(CONTACT_NAME,acc.Id,true);

        ContactPointAddress shippingAddress = B2B_TestDataFactory.createShippingCPA(acc,true);
        shippingAddress.Country = 'US';
        update shippingAddress;

        Schema.Location location = B2B_TestDataFactory.createLocation(LOCATION_NAME, true);

        OrderDeliveryMethod odm = B2B_TestDataFactory.createOrderDeliveryMethod(true);
        odm.Name = 'Freight Overnight';
        update odm;

        User custUser = B2B_TestDataFactory.createUser(Community_Nickname,EMAIL,con.Id,true);
        WebStore store = B2B_TestDataFactory.createWebstore('Test Store',true);
        WebCart cart = B2B_TestDataFactory.createCart(acc.Id,custUser.Id,store.Id,shippingAddress.Id,true);
        CartDeliveryGroup deliveryGroup = B2B_TestDataFactory.createCartDeliveryGroupWithCountryCode(cart.Id,odm.Id,'US',true);
        List<cartItem> cartitems = B2B_TestDataFactory.createCartitems(cart.Id,deliveryGroup.Id,prodList,location.Id,true);
        
        Product2 shipProduct = new Product2();
        shipProduct.Name = 'Delivery Charge' ;
        shipProduct.ProductCode = 'Delivery Charge' ;
        shipProduct.StockKeepingUnit = 'Delivery Charge' ;
        shipProduct.isActive = true ;
        insert shipProduct;

        ContactPointAddress billingAddress = new ContactPointAddress(
            AddressType = 'Billing',
            ParentId = acc.Id,
            Street = '123 Main St',
            City = 'TestCity',
            State = 'CA',
            PostalCode = '12345',
            Country = 'US',
            AddressFirstName = 'John',
            AddressLastName = 'Doe',
            Name = 'John Doe'
        );
        insert billingAddress;

        // Create Subscription
        B2B_Subscriptions__c sub = new B2B_Subscriptions__c(
            Subscription_Name__c = 'Test Subscription',
            B2B_Account__c = acc.Id,
            B2B_Contact__c = con.Id,
            B2B_Status__c = 'Active',
            B2B_Next_Billing_Date__c = Date.today(),
            B2B_Shipping_Address__c = shippingAddress.Id,
            B2B_Billing_Address__c = billingAddress.Id,
            CurrencyIsoCode = 'USD',
            B2B_Billing_Frequency__c = 'Monthly',
            B2B_Payment_Method__c = 'Credit Card',
            B2B_Special_Instruction__c = 'Handle with care',
            B2B_Po_Number__c = 'PO',
            B2B_Shipping_Method__c = 'Freight Overnight',
            B2B_End_Date__c = Date.today().addDays(7)
        );
        insert sub;

        // Create Subscription Item
        B2B_Subscription_Items__c subItem = new B2B_Subscription_Items__c(
            B2B_Subscriptions__c = sub.Id,
            B2B_Product__c = prod.Id,
            B2B_Quantity__c = 10,
            B2B_Unit_Price__c = 5000
        );
        insert subItem;
    }


    @isTest
    static void testSchedulerExecutesBatch() {
        Test.startTest();
        B2B_SubscriptionOrderScheduler scheduler = new B2B_SubscriptionOrderScheduler();
        scheduler.execute(null);
        Test.stopTest();

        List<B2B_Subscriptions__c> subs = [
            SELECT Id FROM B2B_Subscriptions__c WHERE B2B_Next_Billing_Date__c = :Date.today()
        ];
        System.assert(!subs.isEmpty(), 'Subscription should exist for today’s date');
    }
    
    @isTest
    static void testSchedulerExecutesBatchToCancel() {
        Account testAcc = [SELECT Id FROM Account WHERE Name = :ACCOUNT_NAME LIMIT 1];
        Contact testContact = [SELECT Id FROM Contact WHERE AccountId = :testAcc.Id LIMIT 1];
        ContactPointAddress cpa = [SELECT Id FROM ContactPointAddress WHERE ParentId = :testAcc.Id LIMIT 1];
        // Create Subscription
        B2B_Subscriptions__c subToCancel = new B2B_Subscriptions__c(
            Subscription_Name__c = 'Test Subscription to cancel',
            B2B_Account__c = testAcc.Id,
            B2B_Contact__c = testContact.Id,
            B2B_Status__c = 'Active',
            B2B_Next_Billing_Date__c = Date.today(),
            B2B_Shipping_Address__c = cpa.Id,
            B2B_Billing_Address__c = cpa.Id,
            CurrencyIsoCode = 'USD',
            B2B_Billing_Frequency__c = 'Monthly',
            B2B_Payment_Method__c = 'Credit Card',
            B2B_Special_Instruction__c = 'Handle with care',
            B2B_Po_Number__c = 'PO',
            B2B_Shipping_Method__c = 'Freight Overnight',
            B2B_End_Date__c = Date.today()
        );
        insert subToCancel;
		String queryStr = 'SELECT Id, Subscription_Name__c, B2B_Account__c, B2B_Contact__c, B2B_Next_Billing_Date__c, OwnerId, ' +
                   'B2B_Shipping_Address__c, B2B_Billing_Address__c, B2B_Shipping_Method__c, CurrencyIsoCode,' +
                   'B2B_Billing_Frequency__c, B2B_Payment_Method__c, B2B_Special_Instruction__c, B2B_Shipping_Provider__c,' +
                   'B2B_Shipping_Provider_Account_Number__c, B2B_Po_Number__c, B2B_End_Date__c,' +
                   'B2B_Billing_Address__r.Street, B2B_Billing_Address__r.City, B2B_Billing_Address__r.State, '+
                    'B2B_Billing_Address__r.PostalCode, B2B_Billing_Address__r.Country, '+
                    'B2B_Shipping_Address__r.Street, B2B_Shipping_Address__r.City, B2B_Shipping_Address__r.State, '+
                    'B2B_Shipping_Address__r.PostalCode, B2B_Shipping_Address__r.Country '+
                   'FROM B2B_Subscriptions__c ' +
                   'WHERE Id = ' + '\'' + subToCancel.Id +'\'';
        Test.startTest();
        B2B_SubscriptionOrderBatch ba= new B2B_SubscriptionOrderBatch(queryStr);
        Id jobid = Database.executeBatch( ba , 1 );
        Test.stopTest();

        List<B2B_Subscriptions__c> subs = [
            SELECT Id FROM B2B_Subscriptions__c WHERE B2B_Next_Billing_Date__c = :Date.today()
        ];
        System.assert(!subs.isEmpty(), 'Subscription should exist for today’s date');
    }
}