Perkin-UAT/force-app/main/default/objects/Account/recordTypes/Test.recordType-meta.xml
<RecordType>
    <fullName>Test</fullName>
    <active>true</active>
    <label>Test</label>
</RecordType>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <description>Identify Customer Industry Application. Standardized Names (no double spaces, no space after slash, spaces before and after &#39;&amp;&#39;, use &#39;&amp;&#39; vs &#39;and&#39;, space after commas, lists do not have comma before last item and use &#39;&amp;&#39; before last item)</description>
    <label>Application</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Application_Market__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agricultural Genetics</fullName>
            </value>
            <value>
                <fullName>Agriculture Research</fullName>
            </value>
            <value>
                <fullName>Agrigenomics</fullName>
            </value>
            <value>
                <fullName>Air Testing</fullName>
            </value>
            <value>
                <fullName>Allergy DX</fullName>
            </value>
            <value>
                <fullName>Ancestry</fullName>
            </value>
            <value>
                <fullName>Animal Diagnostics</fullName>
            </value>
            <value>
                <fullName>Antibiotics</fullName>
            </value>
            <value>
                <fullName>API/Compound Analysis</fullName>
            </value>
            <value>
                <fullName>Authenticity &amp; Adulteration</fullName>
            </value>
            <value>
                <fullName>Autoimmun DX</fullName>
            </value>
            <value>
                <fullName>Automated Systems</fullName>
            </value>
            <value>
                <fullName>Basic Research</fullName>
            </value>
            <value>
                <fullName>Batteries, Power &amp; Utilities</fullName>
            </value>
            <value>
                <fullName>Beverages</fullName>
            </value>
            <value>
                <fullName>Biological Pathogens &amp; Toxins</fullName>
            </value>
            <value>
                <fullName>Biologics Development ADME/Tox</fullName>
            </value>
            <value>
                <fullName>Biologics Development Cell line development</fullName>
            </value>
            <value>
                <fullName>Biologics Development GLP Pre-clinical studies</fullName>
            </value>
            <value>
                <fullName>Biologics Development GLP Safety/Tox</fullName>
            </value>
            <value>
                <fullName>Biologics Lot Release</fullName>
            </value>
            <value>
                <fullName>Biomarker Development</fullName>
            </value>
            <value>
                <fullName>Biophysical characterization</fullName>
            </value>
            <value>
                <fullName>BioTherapeutic Manufacturing</fullName>
            </value>
            <value>
                <fullName>Blood Screening</fullName>
            </value>
            <value>
                <fullName>Bone Metabolism</fullName>
            </value>
            <value>
                <fullName>Cannabis/Hemp</fullName>
            </value>
            <value>
                <fullName>Cell Culture</fullName>
            </value>
            <value>
                <fullName>Chemical Food Safety</fullName>
            </value>
            <value>
                <fullName>Chemicals &amp; Mining</fullName>
            </value>
            <value>
                <fullName>Materials</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Application_Market__c.field-meta.xml
<CustomField>
    <fullName>Application_Market__c</fullName>
    <description>Identify Customer Market. Standardized Names (no double spaces, no space after slash, spaces before and after &#39;&amp;&#39;, use &#39;&amp;&#39; vs &#39;and&#39;, space after commas, lists do not have comma before last item and use &#39;&amp;&#39; before last item)</description>
    <label>Application Market</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Application_Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Academia &amp; Academic Research</fullName>
            </value>
            <value>
                <fullName>Air</fullName>
            </value>
            <value>
                <fullName>Alcoholic &amp; Non-Alcoholic Beverages</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Applied Genomics</fullName>
            </value>
            <value>
                <fullName>Basic Research</fullName>
            </value>
            <value>
                <fullName>Biologics/Vaccines Drug Development</fullName>
            </value>
            <value>
                <fullName>Biologics Manufacturing QA/QC</fullName>
            </value>
            <value>
                <fullName>Cannabis/Hemp</fullName>
            </value>
            <value>
                <fullName>Chemicals</fullName>
            </value>
            <value>
                <fullName>Chemicals &amp; Mining</fullName>
            </value>
            <value>
                <fullName>Clinical Diagnostics</fullName>
            </value>
            <value>
                <fullName>Contract Lab</fullName>
            </value>
            <value>
                <fullName>Dairy</fullName>
            </value>
            <value>
                <fullName>Detection</fullName>
            </value>
            <value>
                <fullName>Drug Discovery</fullName>
            </value>
            <value>
                <fullName>Drug QA/QC Manufacturing</fullName>
            </value>
            <value>
                <fullName>Edible Oils</fullName>
            </value>
            <value>
                <fullName>Energy</fullName>
            </value>
            <value>
                <fullName>Energy &amp; Petrochem</fullName>
            </value>
            <value>
                <fullName>Environmental</fullName>
            </value>
            <value>
                <fullName>Flavor &amp; Fragrance</fullName>
            </value>
            <value>
                <fullName>Forensics &amp; Security</fullName>
            </value>
            <value>
                <fullName>Fruits &amp; Vegetables</fullName>
            </value>
            <value>
                <fullName>Government/Academic</fullName>
            </value>
            <value>
                <fullName>Government &amp; Academia</fullName>
            </value>
            <value>
                <fullName>Imaging</fullName>
            </value>
            <value>
                <fullName>Immunodiagnostics</fullName>
            </value>
            <value>
                <fullName>Material</fullName>
            </value>
            <value>
                <fullName>Materials</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Application_Segment__c.field-meta.xml
<CustomField>
    <fullName>Application_Segment__c</fullName>
    <defaultValue>if($RecordType.DeveloperName =&#39;Informatics&#39;,&#39;Informatics&#39;,null)</defaultValue>
    <description>Identify Customer Industry</description>
    <label>Application Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>COVID</fullName>
            </value>
            <value>
                <fullName>Diagnostics</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Informatics</fullName>
            </value>
            <value>
                <fullName>Life Science</fullName>
            </value>
            <value>
                <fullName>Environmental</fullName>
                <isActive>false</isActive>
                <label>Environmental</label>
            </value>
            <value>
                <fullName>Food And Agriculture</fullName>
                <isActive>false</isActive>
                <label>Food And Agriculture</label>
            </value>
            <value>
                <fullName>Human Health &amp; Life Sciences</fullName>
                <isActive>false</isActive>
                <label>Human Health &amp; Life Sciences</label>
            </value>
            <value>
                <fullName>Human Health and Life Sciences</fullName>
                <isActive>false</isActive>
                <label>Human Health and Life Sciences</label>
            </value>
            <value>
                <fullName>Industrial</fullName>
                <isActive>false</isActive>
                <label>Industrial</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/CountofRenewalProducts__c.field-meta.xml
<CustomField>
    <fullName>CountofRenewalProducts__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This is used by Declarative Lookup Rollup Helper to determine how many products are renewable on this opportunity</description>
    <inlineHelpText>how many products are renewable on this opportunity</inlineHelpText>
    <label>Count of Renewal Products(INF)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/First_Email_Sent_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Email_Sent_Date__c</fullName>
    <label>1st Email Sent Date</label>
    <type>Date</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Second_Email_Sent_Date__c.field-meta.xml
<CustomField>
    <fullName>Second_Email_Sent_Date__c</fullName>
    <label>2nd Email Sent Date</label>
    <type>Date</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Strategic_Market_INF__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Market_INF__c</fullName>
    <label>Strategic Market</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Life Sciences Research</fullName>
            </value>
            <value>
                <fullName>Clinical &amp; Translational</fullName>
            </value>
            <value>
                <fullName>Related Markets</fullName>
            </value>
            <value>
                <fullName>Production Support</fullName>
            </value>
            <value>
                <fullName>Academic &amp; Government</fullName>
            </value>
            <value>
                <fullName>Clinical</fullName>
            </value>
            <value>
                <fullName>Applied Markets</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Third_Email_Sent_Date__c.field-meta.xml
<CustomField>
    <fullName>Third_Email_Sent_Date__c</fullName>
    <label>3rd Email Sent Date</label>
    <type>Date</type>
</CustomField>

Perkin-UAT/force-app/main/default/classes/Batch_ContractRenewalNoticeFails_Test.cls
@isTest
public class Batch_ContractRenewalNoticeFails_Test {
    public static testmethod void batchRenewalFailTest(){
        Id INFORMATICS_RECORDTYPEID = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Informatics').getRecordTypeId();
        
        Account acc = new Account();
        acc.name = 'Test Account';
        acc.ShippingCity = 'test city';
        acc.ShippingCountry = 'US';
        acc.ShippingPostalCode = '12345678';
        acc.ShippingState = 'AX';
        acc.ShippingStreet = 'Test Street';
        insert acc;
        
        Opportunity opprt = new Opportunity(Name='TestOpprt',AccountId=acc.id,Strategic_Market_INF__c='Life Sciences Research', recordtypeId = INFORMATICS_RECORDTYPEID, Application__c = 'Materials', Application_Segment__c = 'Informatics', Application_Market__c = 'Applied'
                                            ,Type='New Products',CloseDate=System.today() + 120,StageName='Stage 5 - Negotiation',Pricebook2Id = Test.getStandardPricebookId(), currencyISOCode ='USD',CountofRenewalProducts__c = 1,First_Email_Sent_Date__c= system.today().addDays(-45), Second_Email_Sent_Date__c= system.today(), Third_Email_Sent_Date__c=system.today());
        insert opprt;
        
        List<EmailMessage> emailMessages = new List<EmailMessage>();
        EmailMessage emailMessage = new EmailMessage(); 
        emailMessage.status = '3'; // email was sent 
        emailMessage.fromName = 'Magulan Duraipandian'; // from name 
        emailMessage.subject = 'PerkinElmer Informatics Contract Renewal Quotation - 2nd Notice'; // email subject 
        emailMessage.htmlBody = '<html><body><b>Hello</b></body></html>'; // email body 
        emailMessage.RelatedToId = opprt.Id; 
        emailMessages.add(emailMessage); // insert 
        
        EmailMessage emailMessage2 = new EmailMessage(); 
        emailMessage2.status = '3'; // email was sent 
        emailMessage2.fromName = 'Magulan Duraipandian'; // from name 
        emailMessage2.subject = 'PerkinElmer Informatics Contract Renewal Quotation - Final Notice'; // email subject 
        emailMessage2.htmlBody = '<html><body><b>Hello</b></body></html>'; // email body 
        emailMessage2.RelatedToId = opprt.Id; 
        emailMessages.add(emailMessage2);
	
        if(!emailMessages.isEmpty()){
            insert emailMessages;
        }   
        
        Batch_ContractRenewalNoticeFails testBatch = new Batch_ContractRenewalNoticeFails();
		database.executeBatch(testBatch);
    }
    
    public static testmethod void testAutoActivateOrderSchedular(){
        Test.startTest();
            Schedule_ContractRenewalNoticeFails schedularClass = new Schedule_ContractRenewalNoticeFails();
            String schedularTime = '0 0 0,2,4,6,8,10,12,14,16,18,20,22 * * ? * *'; 
            system.schedule('Auto Activate Order1', schedularTime, schedularClass); 
        Test.stopTest();
    }
}