Perkin-UAT/force-app/main/default/objects/Account/recordTypes/Test.recordType-meta.xml
<RecordType>
    <fullName>Test</fullName>
    <active>true</active>
    <label>Test</label>
</RecordType>

Perkin-UAT/force-app/main/default/objects/Activity/fields/SMAX_PS_Owned_By_Company__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_Owned_By_Company__c</fullName>
    <description>The Company/ Business Entity that owns the record</description>
    <label>Owned By Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>G_PICK_050_Owned_by_Company</valueSetName>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SVMX_PS_Service_Alert__c/SVMX_PS_Service_Alert__c.object-meta.xml
<CustomObject>
    <label>Service Alert</label>
    <nameField>
        <displayFormat>SA-{0000000}</displayFormat>
        <label>Service Alert Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Alerts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/SVMX_PS_Service_Alert__c/fields/SMAX_PS_Initial_Response_Email__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_Initial_Response_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <description>ITSVMX-1507 Used to trigger an email response from Tech Support to the creator of the Tech Support Service Alert</description>
    <label>Initial Response Email</label>
    <type>Checkbox</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SVMX_PS_Service_Alert__c/fields/SVMX_PS_Country__c.field-meta.xml
<CustomField>
    <fullName>SVMX_PS_Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>AW</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BF</fullName>
            </value>
            <value>
                <fullName>BG</fullName>
            </value>
            <value>
                <fullName>BR</fullName>
            </value>
            <value>
                <fullName>BS</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>CL</fullName>
            </value>
            <value>
                <fullName>CN</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CR</fullName>
            </value>
            <value>
                <fullName>CZ</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>DK</fullName>
            </value>
            <value>
                <fullName>DO</fullName>
            </value>
            <value>
                <fullName>EC</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>FI</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>GB</fullName>
            </value>
            <value>
                <fullName>GR</fullName>
            </value>
            <value>
                <fullName>GT</fullName>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SVMX_PS_Service_Alert__c/fields/SVMX_PS_Installed_Product__c.field-meta.xml
<CustomField>
    <fullName>SVMX_PS_Installed_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installed Product</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Service Alerts</relationshipLabel>
    <relationshipName>Service_Alerts</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SVMX_PS_Service_Alert__c/fields/SVMX_PS_Manager_Approval_User__c.field-meta.xml
<CustomField>
    <fullName>SVMX_PS_Manager_Approval_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager Approval User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Service_Alerts3</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SVMX_PS_Service_Alert__c/fields/SVMX_PS_Quality_Comments__c.field-meta.xml
<CustomField>
    <fullName>SVMX_PS_Quality_Comments__c</fullName>
    <label>Quality Comments</label>
    <type>TextArea</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SVMX_PS_Service_Alert__c/fields/SVMX_PS_Region__c.field-meta.xml
<CustomField>
    <fullName>SVMX_PS_Region__c</fullName>
    <label>Region_deprecated</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SVMX_PS_Service_Alert__c/fields/SVMX_PS_Stage__c.field-meta.xml
<CustomField>
    <fullName>SVMX_PS_Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Investigating</fullName>
                <label>Replacement Requested</label>
            </value>
            <value>
                <fullName>Pending_Approval</fullName>
                <label>Pending Approval</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SVMX_PS_Service_Alert__c/fields/SVMX_PS_Status__c.field-meta.xml
<CustomField>
    <fullName>SVMX_PS_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BU Investigating</fullName>
            </value>
            <value>
                <fullName>Quality Approved</fullName>
                <label>Business Unit Approved</label>
            </value>
            <value>
                <fullName>Quality Rejected</fullName>
                <label>Business Unit Rejected</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Confidence Testing</fullName>
            </value>
            <value>
                <fullName>Engineering Investigating</fullName>
            </value>
            <value>
                <fullName>Field Service Investigating</fullName>
            </value>
            <value>
                <fullName>Implementation Specialist Investigating</fullName>
            </value>
            <value>
                <fullName>Manager Approved</fullName>
            </value>
            <value>
                <fullName>Manager Rejected</fullName>
            </value>
            <value>
                <fullName>New instrument ordered</fullName>
            </value>
            <value>
                <fullName>New instrument shipped</fullName>
            </value>
            <value>
                <fullName>No Activity</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Parts Shipped</fullName>
            </value>
            <value>
                <fullName>Pending Manager Approval</fullName>
            </value>
            <value>
                <fullName>Product Specialist Investigating</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Replacement Completed</fullName>
            </value>
            <value>
                <fullName>Replacement Requested</fullName>
            </value>
            <value>
                <fullName>Request Canceled</fullName>
            </value>
            <value>
                <fullName>Sent to CRC</fullName>
            </value>
            <value>
                <fullName>Shipping Damage</fullName>
            </value>
            <value>
                <fullName>Software Investigating</fullName>
            </value>
            <value>
                <fullName>Support Investigating</fullName>
            </value>
            <value>
                <fullName>Waiting on Parts/Materials</fullName>
            </value>
            <value>
                <fullName>Waiting on Supplier Direct Delivered Part</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SVMX_PS_Service_Alert__c/fields/SVMX_PS_Sub_Region__c.field-meta.xml
<CustomField>
    <fullName>SVMX_PS_Sub_Region__c</fullName>
    <label>Sub-Region</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SVMX_PS_Service_Alert__c/fields/SVMX_PS_Technician__c.field-meta.xml
<CustomField>
    <fullName>SVMX_PS_Technician__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Technician</label>
    <referenceTo>SVMXC__Service_Group_Members__c</referenceTo>
    <relationshipLabel>Service Alerts</relationshipLabel>
    <relationshipName>Service_Alerts</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SVMX_PS_Service_Alert__c/recordTypes/Replacement_Alert.recordType-meta.xml
<RecordType>
    <fullName>Replacement_Alert</fullName>
    <active>true</active>
    <label>Replacement Alert</label>
</RecordType>

Perkin-UAT/force-app/main/default/objects/SVMX_PS_Service_Alert__c/recordTypes/Technical_Support_Request.recordType-meta.xml
<RecordType>
    <fullName>Technical_Support_Request</fullName>
    <active>true</active>
    <label>Technical Support Request</label>
</RecordType>

Perkin-UAT/force-app/main/default/objects/User/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMERICAS</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/User/fields/Sub_Region__c.field-meta.xml
<CustomField>
    <fullName>Sub_Region__c</fullName>
    <label>Sub-Region</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Region__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>AUSTRALIA</fullName>
            </value>
            <value>
                <fullName>CANADA</fullName>
            </value>
            <value>
                <fullName>CHINA</fullName>
            </value>
            <value>
                <fullName>EUROPE</fullName>
            </value>
            <value>
                <fullName>INDIA</fullName>
            </value>
            <value>
                <fullName>INDONESIA</fullName>
            </value>
            <value>
                <fullName>ISRAEL</fullName>
            </value>
            <value>
                <fullName>JAPAN</fullName>
            </value>
            <value>
                <fullName>KOREA, REPUBLIC OF</fullName>
            </value>
            <value>
                <fullName>KOSEA</fullName>
            </value>
            <value>
                <fullName>LATIN AMERICA</fullName>
            </value>
            <value>
                <fullName>MALAYSIA</fullName>
            </value>
            <value>
                <fullName>NORTH AMERICA</fullName>
            </value>
            <value>
                <fullName>PHILIPPINES</fullName>
            </value>
            <value>
                <fullName>SINGAPORE</fullName>
            </value>
            <value>
                <fullName>SOUTH AMERICA</fullName>
            </value>
            <value>
                <fullName>SOUTH ASIA</fullName>
            </value>
            <value>
                <fullName>SOUTH PAC</fullName>
            </value>
            <value>
                <fullName>THAILAND</fullName>
            </value>
            <value>
                <fullName>UNITED STATES</fullName>
            </value>
            <value>
                <fullName>VIETNAM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/classes/SMAX_PS_ServiceAlert_UT.cls
/**
 * Created by tony on 11/9/20.
 *
 * Updates:
 * 01/23/2023   tony    ITSVMX-1123 Custom Metadata types - Service Alert CRC Email Address updates on new CRC email addresses
 */

@IsTest
private class SMAX_PS_ServiceAlert_UT {

    @TestSetup
    static void testData() {
        // create new contact
        Contact contact = new Contact();
        contact.FirstName = 'Needed for';
        contact.LastName = 'Service Alert Email Notification';
        contact.Email = 'test@someplace.com.invalid';

        insert contact;
        System.debug('Inserted Contact: ' + contact);
    }

    @IsTest
    static void test_updateServiceAlerts() {

        // create Users
        User user1 = SMAX_PS_TestDataFactory.createTestUser('Test1');
        user1.Region__c = 'AMERICAS';
        user1.Sub_Region__c = 'NORTH AMERICA';
        user1.Email = 'test1@someplace.com';
        update user1;
        System.debug('inserted user1: ' + user1);

        User user2 = SMAX_PS_TestDataFactory.createTestUser('Test2');
        user2.Region__c = 'AMERICAS';
        user2.Sub_Region__c = 'NORTH AMERICA';
        user2.Email = 'test2@someplace.com';
        update user2;
        System.debug('inserted user2: ' + user2);

        User user3 = SMAX_PS_TestDataFactory.createTestUser('Test3');
        user3.Region__c = 'AMERICAS';
        user3.Sub_Region__c = 'NORTH AMERICA';
        user3.Email = 'test3@someplace.com';
        update user3;
        System.debug('inserted user3: ' + user3);

        Product2 prod = SMAX_PS_TestDataFactory.createTestProduct('TestProd', 'ProdCode', 'GC');
        System.debug('inserted prod: ' + prod);

        Account acct = SMAX_PS_TestDataFactory.createTestAccount('TestAccount', 'acct1234');

        SVMXC__Site__c loc = SMAX_PS_TestDataFactory.createTestLocation(acct, 'TestLoc', 'loc1234', '122');

        SVMXC__Installed_Product__c installedProduct = SMAX_PS_TestDataFactory.createIP('Serial1', acct, loc, 'Model1234', prod);
        System.debug('inserted installedProduct: ' + installedProduct);

        // create Technicians
        SVMXC__Service_Group_Members__c tech = SMAX_PS_TestDataFactory.createTestTechnician('TestTeam', user1, 'TechName1', 'Plant1', '123');
        System.debug('inserted Technician: ' + tech);

        tech.SVMXC__Country__c = 'US';
        tech.SMAX_PS_Plant__c = 'US12';
        tech.SVMXC__Email__c = 'test1@someplace.com';
        update tech;

        SVMXC__Service_Group_Members__c tech2 = SMAX_PS_TestDataFactory.createTestTechnician('TestTeam', user3, 'TechName2', 'Plant2', '124');
        System.debug('inserted Technician: ' + tech2);

        tech2.SVMXC__Email__c = 'test3@someplace.com';
        update tech2;

        // get record type id
        Id replacementAlertRecordTypeID = Schema.SObjectType.SVMX_PS_Service_Alert__c.getRecordTypeInfosByDeveloperName().get('Replacement_Alert').getRecordTypeId();

        // create Service Alert where user is also a Technician
        SVMX_PS_Service_Alert__c serviceAlert1 = new SVMX_PS_Service_Alert__c(
                SVMX_PS_Quality_Comments__c = 'Test Service Alert 1',
                OwnerId = user1.Id,
                SVMX_PS_Installed_Product__c = installedProduct.Id // Added so we can test Product Line of 'GC'
        );
        System.debug('inserting Service Alert: ' + serviceAlert1);
        insert serviceAlert1;

        // create Service Alert where user is not a Technician
        SVMX_PS_Service_Alert__c serviceAlert2 = new SVMX_PS_Service_Alert__c(
                SVMX_PS_Quality_Comments__c = 'Test Service Alert 2',
                OwnerId = user2.Id
        );
        System.debug('inserting Service Alert: ' + serviceAlert2);
        insert serviceAlert2;

        // create Service Alert where user is not a Technician but a Technician has been assigned
        SVMX_PS_Service_Alert__c serviceAlert3 = new SVMX_PS_Service_Alert__c(
                SVMX_PS_Quality_Comments__c = 'Test Service Alert 3',
                OwnerId = user2.Id,
                SVMX_PS_Technician__c = tech.Id
        );
        System.debug('inserting Service Alert: ' + serviceAlert3);
        insert serviceAlert3;


        // create Service Alert where user is not a Technician but a Technician has been assigned
        SVMX_PS_Service_Alert__c serviceAlert4 = new SVMX_PS_Service_Alert__c(
                RecordTypeId = replacementAlertRecordTypeID,
                SVMX_PS_Quality_Comments__c = 'Test Service Alert 4',
                OwnerId = user2.Id,
                SVMX_PS_Technician__c = tech.Id

        );
        System.debug('inserting Service Alert: ' + serviceAlert4);
        insert serviceAlert4;

        serviceAlert4.SVMX_PS_Technician__c = tech2.Id;
        serviceAlert4.SVMX_PS_Status__c = 'Quality Approved';  // 12/15/2020 tony - added for code coverage
        serviceAlert4.SVMX_PS_Manager_Approval_User__c = UserInfo.getUserId(); // 02/11/2025 added for code coverage
        serviceAlert4.SMAX_PS_Owned_By_Company__c = 'AES';
        serviceAlert4.SVMX_PS_Country__c = 'US';
        System.debug('updating Service Alert 4: ' + serviceAlert4);
        update serviceAlert4;

        // 02/11/2025 create Service Alert to test Technical Support Service Alert Response Email
        Id techSupportRecordTypeID = Schema.SObjectType.SVMX_PS_Service_Alert__c.getRecordTypeInfosByDeveloperName().get('Technical_Support_Request').getRecordTypeId();
        //serviceAlert3.RecordTypeId = techSupportRecordTypeID;
        SVMX_PS_Service_Alert__c serviceAlert5 = new SVMX_PS_Service_Alert__c(
                SVMX_PS_Quality_Comments__c = 'Test Service Alert 5',
                OwnerId = user1.Id,
                SVMX_PS_Technician__c = tech.Id, // Added so we can test Technician is being set
                RecordTypeId = techSupportRecordTypeID,
                SVMX_PS_Installed_Product__c = installedProduct.Id // Added so we can test Product Line of 'GC'
        );
        System.debug('inserting Service Alert: ' + serviceAlert5);
        insert serviceAlert5;

        // 02/11/2025 update Service Alert to test Technical Support Service Alert Response Email
        serviceAlert5.SMAX_PS_Initial_Response_Email__c = true;
        //serviceAlert5.SVMX_PS_Manager_Approval_User__c = user2.Id;
        System.debug('updating Service Alert 5: ' + serviceAlert5);
        update serviceAlert5;


        // Verify Results
        System.debug('sa4 Emails Sent: ' + Limits.getEmailInvocations());
        // Check that all the Service Alert notification emails were sent
        // 3/11/21 Tony - changed as Production sends a different amount of Email Invocations.
        System.assert(Limits.getEmailInvocations() > 0);

        Test.startTest();
        SVMX_PS_Service_Alert__c sa1 = [
                SELECT Id, SVMX_PS_Technician__c, OwnerId, SVMX_PS_Region__c, SVMX_PS_Sub_Region__c
                FROM SVMX_PS_Service_Alert__c
                WHERE Id = :serviceAlert1.Id
        ];
        System.debug('sa1: ' + sa1);
        // Check that Technician is being set when Owner is a Technician
        System.assert(sa1.SVMX_PS_Technician__c == tech.Id);

        SVMX_PS_Service_Alert__c sa2 = [
                SELECT Id, SVMX_PS_Technician__c, OwnerId, SVMX_PS_Region__c, SVMX_PS_Sub_Region__c
                FROM SVMX_PS_Service_Alert__c
                WHERE Id = :serviceAlert2.Id
        ];
        System.debug('sa2: ' + sa2);
        // Check that Technician is not being set when Owner is NOT a Technician
        System.assert(sa2.SVMX_PS_Technician__c == null);

        SVMX_PS_Service_Alert__c sa3 = [
                SELECT Id, SVMX_PS_Technician__c, OwnerId, SVMX_PS_Region__c, SVMX_PS_Sub_Region__c
                FROM SVMX_PS_Service_Alert__c
                WHERE Id = :serviceAlert3.Id
        ];
        System.debug('sa3: ' + sa3);
        // Check that Owner is being changed to the Technician's User when the Technician value has been set
        System.assert(sa3.OwnerId == user1.Id);

        SVMX_PS_Service_Alert__c sa4 = [
                SELECT Id, SVMX_PS_Technician__c, OwnerId, SVMX_PS_Region__c, SVMX_PS_Sub_Region__c
                FROM SVMX_PS_Service_Alert__c
                WHERE Id = :serviceAlert4.Id
        ];
        System.debug('sa4: ' + sa4);
        // Check that Owner is being changed to the Technician's User when the Technician value is UPDATED
        System.assert(sa4.OwnerId == user3.Id);

        // Added for code coverage on non-used trigger events
        delete serviceAlert4;
        undelete serviceAlert4;

        Test.stopTest();
    }

    @IsTest
    static void test_updatePath() {

        // create User
        User user1 = SMAX_PS_TestDataFactory.createTestUser('Test1');
        user1.Region__c = 'AMERICAS';
        user1.Sub_Region__c = 'NORTH AMERICA';
        update user1;
        System.debug('inserted user1: ' + user1);

        // create Technicians
        SVMXC__Service_Group_Members__c tech = SMAX_PS_TestDataFactory.createTestTechnician('TestTeam', user1, 'TechName1', 'Plant1', '123');
        System.debug('inserted Technician: ' + tech);

        // create Service Alert
        SVMX_PS_Service_Alert__c serviceAlert1 = new SVMX_PS_Service_Alert__c(
                SVMX_PS_Quality_Comments__c = 'Test Service Alert 1',
                OwnerId = user1.Id
        );
        System.debug('inserting Service Alert: ' + serviceAlert1);
        insert serviceAlert1;

        // Verify Results
        Test.startTest();
        SVMX_PS_Service_Alert__c sa1 = [
                SELECT Id, SVMX_PS_Technician__c, OwnerId, SVMX_PS_Status__c, SVMX_PS_Stage__c
                FROM SVMX_PS_Service_Alert__c
                WHERE Id = :serviceAlert1.Id
        ];
        System.debug('sa1: ' + sa1);
        // Check that Stage is not set
        System.assert(sa1.SVMX_PS_Stage__c == null);

        sa1.SVMX_PS_Status__c = 'No Activity';
        update sa1;

        sa1 = [
                SELECT Id, SVMX_PS_Technician__c, OwnerId, SVMX_PS_Status__c, SVMX_PS_Stage__c
                FROM SVMX_PS_Service_Alert__c
                WHERE Id = :serviceAlert1.Id
        ];
        System.debug('sa1 updated: ' + sa1);
        // Check that Stage has changed
        // 12/3/20 tony - changed to Investigating since someone changed the mapping
        System.assertEquals('Investigating', sa1.SVMX_PS_Stage__c);
        Test.stopTest();
    }
}