Perkin-UAT/force-app/main/default/objects/Account/recordTypes/Test.recordType-meta.xml
<RecordType>
    <fullName>Test</fullName>
    <active>true</active>
    <label>Test</label>
</RecordType>

Perkin-UAT/force-app/main/default/objects/B2B_Subscription_Items__c/B2B_Subscription_Items__c.object-meta.xml
<CustomObject>
    <label>B2B Subscription Items</label>
    <nameField>
        <displayFormat>SubItem# {00000}</displayFormat>
        <label>B2B Subscriptions tems</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B2B Subscription Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/B2B_Subscription_Items__c/fields/B2B_Product__c.field-meta.xml
<CustomField>
    <fullName>B2B_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>B2B Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>B2B Subscription Items</relationshipLabel>
    <relationshipName>B2B_Subscription_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Subscription_Items__c/fields/B2B_Subscriptions__c.field-meta.xml
<CustomField>
    <fullName>B2B_Subscriptions__c</fullName>
    <label>B2B Subscriptions</label>
    <referenceTo>B2B_Subscriptions__c</referenceTo>
    <relationshipLabel>B2B Subscription Items</relationshipLabel>
    <relationshipName>B2B_Subscription_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Subscription_Items__c/fields/B2B_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>B2B_Unit_Price__c</fullName>
    <label>B2B Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Subscriptions__c/B2B_Subscriptions__c.object-meta.xml
<CustomObject>
    <label>B2B Subscriptions</label>
    <nameField>
        <displayFormat>Sub# {00000}</displayFormat>
        <label>B2B Subscriptions</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B2B Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/B2B_Subscriptions__c/fields/B2B_Account__c.field-meta.xml
<CustomField>
    <fullName>B2B_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>B2B Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>B2B Subscriptions</relationshipLabel>
    <relationshipName>B2B_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Subscriptions__c/fields/B2B_Billing_Address__c.field-meta.xml
<CustomField>
    <fullName>B2B_Billing_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>B2B Billing Address</label>
    <referenceTo>ContactPointAddress</referenceTo>
    <relationshipLabel>B2B Subscriptions (B2B Billing Address)</relationshipLabel>
    <relationshipName>B2B_Subscriptions1</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Subscriptions__c/fields/B2B_Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>B2B_Billing_Frequency__c</fullName>
    <label>B2B Billing Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Every 1 Month</fullName>
            </value>
            <value>
                <fullName>Every 2 Months</fullName>
            </value>
            <value>
                <fullName>Every 3 Months</fullName>
            </value>
            <value>
                <fullName>Every 6 Months</fullName>
            </value>
            <value>
                <fullName>Every 12 Months</fullName>
            </value>
            <value>
                <fullName>Every 18 Months</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Subscriptions__c/fields/B2B_Contact__c.field-meta.xml
<CustomField>
    <fullName>B2B_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>B2B Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>B2B Subscriptions</relationshipLabel>
    <relationshipName>B2B_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Subscriptions__c/fields/B2B_Next_Billing_Date__c.field-meta.xml
<CustomField>
    <fullName>B2B_Next_Billing_Date__c</fullName>
    <label>B2B Next Billing Date</label>
    <type>Date</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Subscriptions__c/fields/B2B_Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>B2B_Payment_Method__c</fullName>
    <label>B2B Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PO</fullName>
            </value>
            <value>
                <fullName>card</fullName>
                <label>Card</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Subscriptions__c/fields/B2B_Po_Number__c.field-meta.xml
<CustomField>
    <fullName>B2B_Po_Number__c</fullName>
    <label>B2B Po Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Subscriptions__c/fields/B2B_Shipping_Address__c.field-meta.xml
<CustomField>
    <fullName>B2B_Shipping_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>B2B Shipping Address</label>
    <referenceTo>ContactPointAddress</referenceTo>
    <relationshipLabel>B2B Subscriptions</relationshipLabel>
    <relationshipName>B2B_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Subscriptions__c/fields/B2B_Shipping_Method__c.field-meta.xml
<CustomField>
    <fullName>B2B_Shipping_Method__c</fullName>
    <label>B2B Shipping Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Subscriptions__c/fields/B2B_Special_Instruction__c.field-meta.xml
<CustomField>
    <fullName>B2B_Special_Instruction__c</fullName>
    <label>B2B Special Instruction</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Subscriptions__c/fields/B2B_Status__c.field-meta.xml
<CustomField>
    <fullName>B2B_Status__c</fullName>
    <label>B2B Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Subscriptions__c/fields/B2B_Stripe_Payment_Intent__c.field-meta.xml
<CustomField>
    <fullName>B2B_Stripe_Payment_Intent__c</fullName>
    <description>Stripe Payment Intent for future payments</description>
    <label>B2B Stripe Payment Intent</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Subscriptions__c/fields/Subscription_Name__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Name__c</fullName>
    <label>Subscription Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Order/fields/B2B_Subscriptions__c.field-meta.xml
<CustomField>
    <fullName>B2B_Subscriptions__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>B2B Subscriptions</label>
    <referenceTo>B2B_Subscriptions__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/B2B_Quantity__c.field-meta.xml
<CustomField>
    <fullName>B2B_Quantity__c</fullName>
    <label>B2B Quantity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/B2B_Shipping_Method__c.field-meta.xml
<CustomField>
    <fullName>B2B_Shipping_Method__c</fullName>
    <label>Shipping Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/classes/B2B_SubscriptionTaxQueueableTest.cls
/**
 * @description       : 
 * @author            : Gaurav Setia
 * @group             : 
 * @last modified on  : 08-13-2025
 * @last modified by  : Gaurav Setia
**/
@IsTest
private class B2B_SubscriptionTaxQueueableTest {

    private static final String ACCOUNT_NAME = 'Test Account';
    private static final String CONTACT_NAME = 'Test Contact';
    private static final String PRODUCT_NAME = 'Test Product';
    private static final String LOCATION_NAME = 'Test';
    private static final String Community_Nickname = 'testuser';
    private static final String EMAIL = 'test@user.com';

    @TestSetup
    static void setup() {
        Product2 product = B2B_TestDataFactory.createProduct(PRODUCT_NAME,true);	
        Account acc = B2B_TestDataFactory.createAccount(ACCOUNT_NAME,true);
        Contact con = B2B_TestDataFactory.createContact(CONTACT_NAME,acc.Id,true);
        OrderDeliveryMethod ordDelMed = B2B_TestDataFactory.createOrderDeliveryMethod(true);
        Order ord = B2B_TestDataFactory.createOrder('Test Order', acc.Id, Test.getStandardPricebookId(), true);
        OrderDeliveryGroup ordDelGrp = B2B_TestDataFactory.createOrderDeliveryGroup('Test ODG', ordDelMed.Id, ord.Id, true);
        PricebookEntry pbEntry = [SELECT Id FROM PricebookEntry WHERE Product2Id =: product.Id LIMIT 1];
        OrderItem orderItem = B2B_TestDataFactory.createOrderItem(ord.Id, pbEntry.Id, ordDelGrp.Id, true);

        ContactPointAddress shippingAddress = B2B_TestDataFactory.createShippingCPA(acc,true);
        shippingAddress.Country = 'US';
        update shippingAddress;

        ContactPointAddress billingAddress = new ContactPointAddress(
            AddressType = 'Billing',
            ParentId = acc.Id,
            Street = '123 Main St',
            City = 'TestCity',
            State = 'CA',
            PostalCode = '12345',
            Country = 'US',
            AddressFirstName = 'John',
            AddressLastName = 'Doe',
            Name = 'John Doe'
        );
        insert billingAddress;
        
        // Create Subscription
        B2B_Subscriptions__c sub = new B2B_Subscriptions__c(
            Subscription_Name__c = 'Test Subscription',
            B2B_Account__c = acc.Id,
            B2B_Contact__c = con.Id,
            B2B_Status__c = 'Active',
            B2B_Next_Billing_Date__c = Date.today(),
            B2B_Shipping_Address__c = shippingAddress.Id,
            B2B_Billing_Address__c = billingAddress.Id,
            CurrencyIsoCode = 'USD',
            B2B_Billing_Frequency__c = 'Monthly',
            B2B_Payment_Method__c = 'Credit Card',
            B2B_Special_Instruction__c = 'Handle with care',
            B2B_Po_Number__c = 'PO',
            B2B_Shipping_Method__c = 'Freight Overnight',
            B2B_Stripe_Payment_Intent__c = 'pi_13451Sre2OxY3Au2'
        );
        insert sub;

        // Create Subscription Item
        B2B_Subscription_Items__c subItem = new B2B_Subscription_Items__c(
            B2B_Subscriptions__c = sub.Id,
            B2B_Product__c = product.Id,
            B2B_Quantity__c = 10,
            B2B_Unit_Price__c = 5000
        );
        insert subItem;

        ord.ShippingCountry = 'SE';
        ord.B2B_Subscriptions__c = sub.Id;
        update ord;
    }
   
    @IsTest
    static void executeTest() {
        //Given
        List<Order> orders = [SELECT Id, B2B_Subscriptions__c, ShippingCountry, CurrencyIsoCode, 
            (SELECT Id, UnitPrice, Quantity, TotalPrice, Product2Id FROM OrderItems )
            FROM Order LIMIT 1];

        Test.setMock(HttpCalloutMock.class, new B2BStripeTaxMock(orders[0]));
        //When
        Test.startTest();
        ID jobID = System.enqueueJob(new B2B_SubscriptionTaxQueueable(orders[0].Id, orders[0].B2B_Subscriptions__c));
        B2B_SubscriptionTaxQueueable.applyFlatTax(orders[0], orders[0].OrderItems);
        B2B_SubscriptionTaxQueueable.applyFlatTaxToOrderItems(orders[0].OrderItems, 10.00);
        Test.stopTest();

        //Then
        System.assert(jobID != null, 'jobID should not be null');
    }

}