Perkin-UAT/force-app/main/default/objects/Account/recordTypes/Test.recordType-meta.xml
<RecordType>
    <fullName>Test</fullName>
    <active>true</active>
    <label>Test</label>
</RecordType>

Perkin-UAT/force-app/main/default/objects/Contact/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <inlineHelpText>This field maps over from the Lead Page</inlineHelpText>
    <label>Product Line</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AA</fullName>
            </value>
            <value>
                <fullName>AGO</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>AMS</fullName>
            </value>
            <value>
                <fullName>ANP</fullName>
            </value>
            <value>
                <fullName>APS</fullName>
            </value>
            <value>
                <fullName>ARS</fullName>
            </value>
            <value>
                <fullName>ATT</fullName>
            </value>
            <value>
                <fullName>AVC</fullName>
            </value>
            <value>
                <fullName>AVS</fullName>
            </value>
            <value>
                <fullName>AWS</fullName>
            </value>
            <value>
                <fullName>BIO</fullName>
            </value>
            <value>
                <fullName>BTX</fullName>
            </value>
            <value>
                <fullName>CAT</fullName>
            </value>
            <value>
                <fullName>CCM</fullName>
            </value>
            <value>
                <fullName>CHS</fullName>
            </value>
            <value>
                <fullName>CLH</fullName>
            </value>
            <value>
                <fullName>CLR</fullName>
            </value>
            <value>
                <fullName>CRD</fullName>
            </value>
            <value>
                <fullName>CSA</fullName>
            </value>
            <value>
                <fullName>CSB</fullName>
            </value>
            <value>
                <fullName>DAB</fullName>
            </value>
            <value>
                <fullName>DAO</fullName>
            </value>
            <value>
                <fullName>DCS</fullName>
            </value>
            <value>
                <fullName>DEL</fullName>
            </value>
            <value>
                <fullName>DIA</fullName>
            </value>
            <value>
                <fullName>DIS</fullName>
            </value>
            <value>
                <fullName>DL</fullName>
            </value>
            <value>
                <fullName>DLS</fullName>
            </value>
            <value>
                <fullName>DNA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Contact/fields/Solution_Area_of_Interest__c.field-meta.xml
<CustomField>
    <fullName>Solution_Area_of_Interest__c</fullName>
    <description>ORIG:ANNUITAS PDG Program

NEW: SS This field is now used on Interaction, Interaction Assignment Rule, Lead, Contact, Oppty</description>
    <label>Solution Area of Interest</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Air</fullName>
            </value>
            <value>
                <fullName>Applied Genomics</fullName>
            </value>
            <value>
                <fullName>Biologics</fullName>
            </value>
            <value>
                <fullName>Cannabis</fullName>
            </value>
            <value>
                <fullName>Cell and Gene Therapy</fullName>
            </value>
            <value>
                <fullName>Chemicals</fullName>
            </value>
            <value>
                <fullName>Clinical Studies</fullName>
            </value>
            <value>
                <fullName>Digital Lab</fullName>
            </value>
            <value>
                <fullName>Energy</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Forensics and Security</fullName>
            </value>
            <value>
                <fullName>Geochemistry, Mining and Metals</fullName>
            </value>
            <value>
                <fullName>Life Science Research</fullName>
            </value>
            <value>
                <fullName>Material</fullName>
            </value>
            <value>
                <fullName>Maternal Fetal Health</fullName>
            </value>
            <value>
                <fullName>Newborn Screening</fullName>
            </value>
            <value>
                <fullName>Pre-Clinical Drug Development</fullName>
            </value>
            <value>
                <fullName>Pre-Clinical Drug Discovery</fullName>
            </value>
            <value>
                <fullName>QA/QC Drug Manufacturing Process</fullName>
            </value>
            <value>
                <fullName>Soil/Solids</fullName>
            </value>
            <value>
                <fullName>Strategic Services</fullName>
            </value>
            <value>
                <fullName>Water</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Account_Type_INF__c.field-meta.xml
<CustomField>
    <fullName>Account_Type_INF__c</fullName>
    <description>This field is used within Informatics quote process to drive related Price List.  Do not modify without contacting Informatics SalesForce.com support</description>
    <inlineHelpText>Price List requires Acct Type</inlineHelpText>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Commercial</fullName>
                <default>true</default>
                <label>Commercial</label>
            </value>
            <value>
                <fullName>Academic</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/GP_OrderNum_INF__c.field-meta.xml
<CustomField>
    <fullName>GP_OrderNum_INF__c</fullName>
    <label>INF OrderNum</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Order_Processing_Status_INF__c.field-meta.xml
<CustomField>
    <fullName>Order_Processing_Status_INF__c</fullName>
    <label>Order Processing Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Revenue Review Required</fullName>
            </value>
            <value>
                <fullName>AR Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Primary Contact)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Line</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Renewal_Required_INF__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Required_INF__c</fullName>
    <label>Renewal Required?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Revenue_Rec_Date__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Rec_Date__c</fullName>
    <inlineHelpText>Revenue Recognition Date. Typically set as 5 days from close date unless you provide a different date.</inlineHelpText>
    <label>Revenue Rec Date</label>
    <type>Date</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Run_Rate_Opp_INF__c.field-meta.xml
<CustomField>
    <fullName>Run_Rate_Opp_INF__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Run Rate Opp?</label>
    <type>Checkbox</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/OpportunityLineItem/fields/End_Date_INF__c.field-meta.xml
<CustomField>
    <fullName>End_Date_INF__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/OpportunityLineItem/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <formula>TEXT( PricebookEntry.Product2.Family )</formula>
    <label>Product Family</label>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/OpportunityLineItem/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <formula>PricebookEntry.Product2.product_line__c</formula>
    <label>Product Line</label>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/OpportunityLineItem/fields/Product_Status__c.field-meta.xml
<CustomField>
    <fullName>Product_Status__c</fullName>
    <formula>IF( PricebookEntry.Product2.IsActive=TRUE, &quot;ACTIVE&quot;, &quot;INACTIVE&quot;)</formula>
    <label>Product Status</label>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/OpportunityLineItem/fields/Start_Date_INF__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_INF__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/OpportunityLineItem/fields/Type_INF__c.field-meta.xml
<CustomField>
    <fullName>Type_INF__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>License</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Subscription</fullName>
            </value>
            <value>
                <fullName>Perpetual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/License_Type_INF__c.field-meta.xml
<CustomField>
    <fullName>License_Type_INF__c</fullName>
    <label>License Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/product_line__c.field-meta.xml
<CustomField>
    <fullName>product_line__c</fullName>
    <description>Product Line code from SAP</description>
    <label>Product Line</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/Product_Type_INF__c.field-meta.xml
<CustomField>
    <fullName>Product_Type_INF__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>License</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/classes/TestCreateRenewalOppClosedWon.cls
@isTest(seeAllData=true)
private class TestCreateRenewalOppClosedWon {
 public static void test_UpdateTargets()
    {
        User user = [select Id FROM User where IsActive = true LIMIT 1];
        Territory2 territory;
        System.runAs(user)
        {
        
            territory = new Territory2(
                Name = 'Apex Test Territory');
       //     insert territory;
            System.assertNotEquals(territory2.Id, null);
        }  
     }
 static testMethod void CreateRenewalOnlosedWonOpportunity(){
 Set<Id> SetOfOppIds = new Set<Id>();
    
    /* Added by Gireesh AccountId='0013000001DIhdl' */
    List<Opportunity> newOpps = new List<Opportunity>();
     List<Opportunity> listOfOpp = new List<Opportunity>();
     
     Account ac = new Account ();
          
            ac.name='Test Account';
            ac.shippingCountry = 'US';
            ac.Industry ='Biotech';
            ac.CurrencyIsoCode = 'USD';
            ac.BillingStreet = 'Street1';
            ac.BillingCity = 'City1';
            ac.BillingState = 'State';
            ac.BillingCountry ='US';
            ac.BillingPostalCode = '12345';
            insert ac;
            
           /* Insert an Contact */
           Contact co = new Contact ();
           co.AccountId=ac.id;
           co.FirstName='Test Name';
           co.LastName='Test';
           insert co;
    
        for (Integer i = 0; i < 10; i++)
         {  
             
            // RecordType optyrecordtype = [select id from recordType where Name='informatics' limit 1];
           newOpps.add(new Opportunity(Name='opp'+i,AccountId=ac.Id,Probability=99,Renewal_Required_INF__c='Yes'/*,RecordTypeId='01230000001aIi6'*/,Account_Type_INF__c='Academic',Primary_Contact__c=co.Id,StageName='Stage 7 - Submit Order',CloseDate=Date.today(),Revenue_Rec_Date__c = Date.today(),Solution_Area_of_Interest__c='Energy'));
         }
        insert newOpps;
        
        
//get standard pricebook
Pricebook2  standardPb = [select id, name, isActive from Pricebook2 where IsStandard = true limit 1];


Pricebook2 pbk1 = new Pricebook2 (Name='Test Pricebook Entry 1',Description='Test Pricebook Entry 1');
insert pbk1;

Product2 prd1 = new Product2 (Name='Term test',ProductCode='CPH567',License_Type_INF__c='Services',Product_Type_INF__c='Services',Description='Test Product Entry 1');
insert prd1;

Product2 prd2 = new Product2 (Name='test product',ProductCode='CPH568',License_Type_INF__c='Services',Product_Type_INF__c='Services',Description='Test Product Entry 2');
insert prd2;

Product2 prd3 = new Product2 (Name='test product',ProductCode='CPH569',License_Type_INF__c='Services',Product_Type_INF__c='Services',Description='Test Product Entry 3');
insert prd3;



PricebookEntry pbe2 = new PricebookEntry (Product2ID=prd2.id,Pricebook2ID=standardPb.id,IsActive=true,
        UseStandardPrice=false,UnitPrice=50);
insert pbe2;

// Create a task for each one
List<OpportunityLineItem> newLineItems = new List<OpportunityLineItem>();
List<Opportunity> OppsUpdate = new List<Opportunity>();
  

for(Opportunity opp : newOpps){
newLineItems.add(new OpportunityLineItem(OpportunityID=opp.id,Start_Date_INF__c=Date.today(),End_Date_INF__c=Date.today(),TotalPrice=10,Quantity=1,PriceBookEntryID=pbe2.id));
//newLineItems.add(new OpportunityLineItem(OpportunityID=opp.id,Start_Date_INF__c=Date.today(),End_Date_INF__c=Date.today(),TotalPrice=10,Quantity=1,PriceBookEntryID=pbe2.id));
SetOfOppIds.add(opp.id);
}
insert newLineItems;

 /*for(Opportunity op :[Select Id,
                          (Select Type_INF__c, PricebookEntry.Product2.License_Type_INF__c,Start_Date_INF__c, Product_Status__c,
                           Product_Line__c,Quantity, Product_Family__c,OpportunityId, Id, End_Date_INF__c,PricebookEntryId,
                           UnitPrice,PricebookEntry.Product2.Product_Type_INF__c From OpportunityLineItems
                           WHERE (PricebookEntry.Product2.License_Type_INF__c ='Services' OR PricebookEntry.Product2.Product_Type_INF__c ='Services'))                                    
                        From Opportunity o where Id IN:SetOfOppIds]){
    
    if(op.OpportunityLineItems.size()>0)
    {
       for(OpportunityLineItem opp : op.OpportunityLineItems)
           {
             op.Order_Processing_Status_INF__c = 'Revenue Review Required';
             listOfOpp.add(op);           
           } 
             if(listOfOpp.size()>0)
                  update listOfOpp;    
      } 
}*/

    
}

 static testMethod void CreateRenewalOnlosedWon(){
 
  Account ac = new Account ();
          
            ac.name='Test Account';
            ac.shippingCountry = 'US';
            ac.Industry ='Biotech';
            ac.CurrencyIsoCode = 'USD';
            ac.BillingStreet = 'Street1';
            ac.BillingCity = 'City1';
            ac.BillingState = 'State';
            ac.BillingCountry ='US';
            ac.BillingPostalCode = '12345';
            insert ac;
            
           /* Insert an Contact */
           Contact co = new Contact ();
           co.AccountId=ac.id;
           co.FirstName='Test Name';
           co.LastName='Test';
           insert co;
           
           id rtID=Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Informatics').getRecordTypeId();

           Opportunity opp=new Opportunity();
           opp.Name='opl';
           opp.AccountId=ac.Id;
           opp.RecordtypeId=rtID;
           opp.Probability=99;
           opp.Renewal_Required_INF__c='No';
           opp.Run_Rate_Opp_INF__c=true;
           opp.Account_Type_INF__c='Academic';
           opp.Primary_Contact__c=co.Id;
           opp.StageName='Stage 2 - Qualified';
           opp.CloseDate=Date.today();
           opp.Revenue_Rec_Date__c = Date.today();
           opp.Solution_Area_of_Interest__c='Energy';
           insert opp;
           
          
           opp.StageName='Closed Won';
           opp.Run_Rate_Opp_INF__c=false;
           opp.Renewal_Required_INF__c='Yes';
      opp.GP_OrderNum_INF__c='12312';   
           update opp; 
 }
 
 
 static testMethod void Createopptesr(){
 
  Account ac = new Account ();
          
            ac.name='Test Account';
            ac.shippingCountry = 'US';
            ac.Industry ='Biotech';
            ac.CurrencyIsoCode = 'USD';
            ac.BillingStreet = 'Street1';
            ac.BillingCity = 'City1';
            ac.BillingState = 'State';
            ac.BillingCountry ='US';
            ac.BillingPostalCode = '12345';
            insert ac;
            
           /* Insert an Contact */
           Contact co = new Contact ();
           co.AccountId=ac.id;
           co.FirstName='Test Name';
           co.LastName='Test';
           insert co;
           
           id rtID=Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Informatics').getRecordTypeId();

           Opportunity opp=new Opportunity();
           opp.Name='opl';
           opp.AccountId=ac.Id;
           opp.RecordtypeId=rtID;
           opp.Probability=99;
           opp.Renewal_Required_INF__c='No';
           opp.Run_Rate_Opp_INF__c=true;
           opp.Account_Type_INF__c='Academic';
           opp.Primary_Contact__c=co.Id;
           opp.StageName='Stage 2 - Qualified';
           opp.CloseDate=Date.today();
           opp.Revenue_Rec_Date__c = Date.today();
           opp.Solution_Area_of_Interest__c='Energy';
       opp.GP_OrderNum_INF__c='12312';
           insert opp;
           
          
           opp.StageName='Stage 6 - Implement (Closed)';
      opp.GP_OrderNum_INF__c='12312';
           update opp; 
 }
 
 
  
 static testMethod void setOfOpp_NonRenew(){
 
  Account ac = new Account ();
          
            ac.name='Test Account';
            ac.shippingCountry = 'US';
            ac.Industry ='Biotech';
            ac.CurrencyIsoCode = 'USD';
            ac.BillingStreet = 'Street1';
            ac.BillingCity = 'City1';
            ac.BillingState = 'State';
            ac.BillingCountry ='US';
            ac.BillingPostalCode = '12345';
            insert ac;
            
           /* Insert an Contact */
           Contact co = new Contact ();
           co.AccountId=ac.id;
           co.FirstName='Test Name';
           co.LastName='Test';
           insert co;
           
           id rtID=Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Informatics').getRecordTypeId();

           Opportunity opp=new Opportunity();
           opp.Name='opl';
           opp.AccountId=ac.Id;
           opp.RecordtypeId=rtID;
           opp.Probability=99;
           opp.Renewal_Required_INF__c='No';
           opp.Run_Rate_Opp_INF__c=true;
           opp.Account_Type_INF__c='Academic';
           opp.Primary_Contact__c=co.Id;
           opp.StageName='Stage 2 - Qualified';
           opp.CloseDate=Date.today();
           opp.Revenue_Rec_Date__c = Date.today();
           opp.Solution_Area_of_Interest__c='Energy';
       opp.GP_OrderNum_INF__c='12312';
           insert opp;
           
          
           opp.StageName='Closed Won';
           opp.Renewal_Required_INF__c='No';
           opp.Run_Rate_Opp_INF__c=false;
       opp.GP_OrderNum_INF__c='12312';
           update opp; 
Test.startTest();           
           //get standard pricebook
Pricebook2  standardPb = [select id, name, isActive from Pricebook2 where IsStandard = true limit 1];


Pricebook2 pbk1 = new Pricebook2 (Name='Test Pricebook Entry 1',Description='Test Pricebook Entry 1');
insert pbk1;

Product2 prd1 = new Product2 (Name='Term test',ProductCode='CPH567',License_Type_INF__c='Services',Product_Type_INF__c='Services',Description='Test Product Entry 1');
insert prd1;

Product2 prd2 = new Product2 (Name='test product',ProductCode='CPH568',License_Type_INF__c='Services',Product_Type_INF__c='Services',Description='Test Product Entry 2');
insert prd2;

Product2 prd3 = new Product2 (Name='test product',ProductCode='CPH569',License_Type_INF__c='Services',Product_Type_INF__c='Services',Description='Test Product Entry 3');
insert prd3;



PricebookEntry pbe2 = new PricebookEntry (Product2ID=prd2.id,Pricebook2ID=standardPb.id,IsActive=true,
        UseStandardPrice=false,UnitPrice=50);
insert pbe2;
           
          OpportunityLineItem opl= new OpportunityLineItem();
          opl.OpportunityID=opp.id;
          opl.Start_Date_INF__c=Date.today();
          opl.End_Date_INF__c=Date.today();
          opl.TotalPrice=10;
          opl.Quantity=1;
          opl.PriceBookEntryID=pbe2.id;
          insert opl;
     Test.stopTest();
           
 }
 
 
  
 static testMethod void setOfOpp_allCpb(){
 
  Account ac = new Account ();
          
            ac.name='Test Account';
            ac.shippingCountry = 'US';
            ac.Industry ='Biotech';
            ac.CurrencyIsoCode = 'USD';
            ac.BillingStreet = 'Street1';
            ac.BillingCity = 'City1';
            ac.BillingState = 'State';
            ac.BillingCountry ='US';
            ac.BillingPostalCode = '12345';
            insert ac;
            
           /* Insert an Contact */
           Contact co = new Contact ();
           co.AccountId=ac.id;
           co.FirstName='Test Name';
           co.LastName='Test';
           insert co;
           
           id rtID=Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Informatics').getRecordTypeId();

           Opportunity opp=new Opportunity();
           opp.Name='opl';
           opp.AccountId=ac.Id;
           opp.RecordtypeId=rtID;
           opp.Probability=99;
           opp.Renewal_Required_INF__c='No';
           opp.Run_Rate_Opp_INF__c=true;
           opp.Account_Type_INF__c='Academic';
           opp.Primary_Contact__c=co.Id;
           opp.StageName='Stage 2 - Qualified';
           opp.CloseDate=Date.today();
           opp.Revenue_Rec_Date__c = Date.today();
           opp.Solution_Area_of_Interest__c='Energy';
       opp.GP_OrderNum_INF__c='12312';
           insert opp;
           
          
           opp.StageName='Closed Won';
           opp.Renewal_Required_INF__c='No';
           opp.Run_Rate_Opp_INF__c=false;
       opp.GP_OrderNum_INF__c='12312';
           update opp; 
     Test.startTest();
           
           //get standard pricebook
Pricebook2  standardPb = [select id, name, isActive from Pricebook2 where IsStandard = true limit 1];


Pricebook2 pbk1 = new Pricebook2 (Name='Test Pricebook Entry 1',Description='Test Pricebook Entry 1');
insert pbk1;

Product2 prd1 = new Product2 (Name='Term test',ProductCode='CPH567',License_Type_INF__c='Perpetual',Product_Type_INF__c='Services',Description='Test Product Entry 1');
insert prd1;

Product2 prd2 = new Product2 (Name='test product',ProductCode='CPH568',License_Type_INF__c='Perpetual',Product_Type_INF__c='Services',Description='Test Product Entry 2');
insert prd2;

Product2 prd3 = new Product2 (Name='test product',ProductCode='CPH569',License_Type_INF__c='Perpetual',Product_Type_INF__c='Services',Description='Test Product Entry 3');
insert prd3;



PricebookEntry pbe2 = new PricebookEntry (Product2ID=prd2.id,Pricebook2ID=standardPb.id,IsActive=true,
        UseStandardPrice=false,UnitPrice=50);
insert pbe2;
           
          OpportunityLineItem opl= new OpportunityLineItem();
          opl.OpportunityID=opp.id;
          opl.Start_Date_INF__c=Date.today();
          opl.End_Date_INF__c=Date.today();
          opl.TotalPrice=10;
          opl.Quantity=1;
          opl.PriceBookEntryID=pbe2.id;
          insert opl;
          
          //Now update the OCR for the primary contact
        OpportunityContactRole ocr = new OpportunityContactRole();
        ocr.ContactId = co.Id;
        ocr.OpportunityId = opp.Id;
        ocr.IsPrimary = TRUE;
        ocr.Role = 'Decision Maker';
        insert ocr;
     
     Test.stopTest();
          
           
 }
 
 static testMethod void setOfOpp_allprime(){
 
  Account ac = new Account ();
          
            ac.name='Test Account';
            ac.shippingCountry = 'US';
            ac.Industry ='Biotech';
            ac.CurrencyIsoCode = 'USD';
            ac.BillingStreet = 'Street1';
            ac.BillingCity = 'City1';
            ac.BillingState = 'State';
            ac.BillingCountry ='US';
            ac.BillingPostalCode = '12345';
            insert ac;
            
           /* Insert an Contact */
           Contact co = new Contact ();
           co.AccountId=ac.id;
           co.FirstName='Test Name';
           co.LastName='Test';
           insert co;
           
           id rtID=Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Informatics').getRecordTypeId();

           
           Opportunity opp=new Opportunity();
           opp.Name='opl';
           opp.AccountId=ac.Id;
           opp.RecordtypeId=rtID;
           opp.Probability=99;
           opp.Renewal_Required_INF__c='No';
           opp.Run_Rate_Opp_INF__c=true;
           opp.Account_Type_INF__c='Academic';
           opp.Primary_Contact__c=co.Id;
           opp.StageName='Stage 2 - Qualified';
           opp.CloseDate=Date.today();
           opp.Revenue_Rec_Date__c = Date.today();
           opp.Solution_Area_of_Interest__c='Energy';
           insert opp;
           
          
           opp.StageName='Closed Won';
           opp.Run_Rate_Opp_INF__c=false;
           opp.Renewal_Required_INF__c='Yes';
      opp.GP_OrderNum_INF__c='12312';   
           update opp; 
     Test.startTest();
           
           //get standard pricebook
//Pricebook2  standardPb = [select id, name, isActive from Pricebook2 where IsStandard = true limit 1];



// Instantiate the Pricebook2 record first, setting the Id
Pricebook2 standardPricebook = new Pricebook2(
    Id = Test.getStandardPricebookId(),
    IsActive = true
);

// Run an update DML on the Pricebook2 record
// This is the weird workaround that enables IsStandard to become true
// on the PricebookEntry record
standardPricebook.name='Informatics';


// Re-Query for the Pricebook2 record, for debugging
Pricebook2  standardPb  = [SELECT IsStandard FROM Pricebook2 WHERE Id = :standardPricebook.Id];




Pricebook2 pbk1 = new Pricebook2 (Name='Test Pricebook Entry 1',Description='Test Pricebook Entry 1');
insert pbk1;

Product2 prd1 = new Product2 (Name='Term test',ProductCode='CPH567',License_Type_INF__c='Subscription',Product_Type_INF__c='Services',Description='Test Product Entry 1');
insert prd1;

Product2 prd2 = new Product2 (Name='test product',ProductCode='CPH568',License_Type_INF__c='Subscription',Product_Type_INF__c='Services',Description='Test Product Entry 2');
insert prd2;

Product2 prd3 = new Product2 (Name='test product',ProductCode='CPH569',License_Type_INF__c='Subscription',Product_Type_INF__c='Services',Description='Test Product Entry 3');
insert prd3;



PricebookEntry pbe2 = new PricebookEntry (Product2ID=prd2.id,Pricebook2ID=standardPb.id,IsActive=true,
        UseStandardPrice=false,UnitPrice=50);
insert pbe2;


           
          OpportunityLineItem opl= new OpportunityLineItem();
          opl.OpportunityID=opp.id;
          opl.Start_Date_INF__c=Date.today();
          opl.End_Date_INF__c=Date.today();
          opl.TotalPrice=10;
          opl.Quantity=1;
          opl.PriceBookEntryID=pbe2.id;
          insert opl;
          
          //Now update the OCR for the primary contact
        OpportunityContactRole ocr = new OpportunityContactRole();
        ocr.ContactId = co.Id;
        ocr.OpportunityId = opp.Id;
        ocr.IsPrimary = TRUE;
        ocr.Role = 'Decision Maker';
        insert ocr;
          Test.stopTest();
           
 }
 
 
}