Perkin-UAT/force-app/main/default/objects/Account/recordTypes/Test.recordType-meta.xml
<RecordType>
    <fullName>Test</fullName>
    <active>true</active>
    <label>Test</label>
</RecordType>

Perkin-UAT/force-app/main/default/objects/B2B_Deal_Discount__c/B2B_Deal_Discount__c.object-meta.xml
<CustomObject>
    <label>B2B Deal Discount</label>
    <nameField>
        <label>B2B Deal Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2B Deal Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/B2B_Deal_Discount_Line__c/B2B_Deal_Discount_Line__c.object-meta.xml
<CustomObject>
    <label>B2B Deal Discount Line</label>
    <nameField>
        <displayFormat>DealLine# {00000}</displayFormat>
        <label>B2B Deal Discount Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B2B Deal Discount Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/B2B_Deal_Discount_Line__c/fields/B2B_Deal_Discount__c.field-meta.xml
<CustomField>
    <fullName>B2B_Deal_Discount__c</fullName>
    <label>B2B Deal Discount</label>
    <referenceTo>B2B_Deal_Discount__c</referenceTo>
    <relationshipLabel>B2B Deal Discount Lines</relationshipLabel>
    <relationshipName>B2B_Deal_Discount_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Deal_Discount_Line__c/fields/B2B_Discount__c.field-meta.xml
<CustomField>
    <fullName>B2B_Discount__c</fullName>
    <label>B2B Discount %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Deal_Discount_Line__c/fields/B2B_End_Date__c.field-meta.xml
<CustomField>
    <fullName>B2B_End_Date__c</fullName>
    <label>B2B End Date</label>
    <type>Date</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Deal_Discount_Line__c/fields/B2B_Item_Class__c.field-meta.xml
<CustomField>
    <fullName>B2B_Item_Class__c</fullName>
    <label>B2B Item Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Deal_Discount_Line__c/fields/B2B_Product_Line__c.field-meta.xml
<CustomField>
    <fullName>B2B_Product_Line__c</fullName>
    <label>B2B Product Line</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Deal_Discount_Line__c/fields/B2B_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>B2B_Start_Date__c</fullName>
    <label>B2B Start Date</label>
    <type>Date</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Deals__c/B2B_Deals__c.object-meta.xml
<CustomObject>
    <label>B2B Deals</label>
    <nameField>
        <displayFormat>Deal# {00000}</displayFormat>
        <label>B2B Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B2B Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/B2B_Deals__c/fields/B2B_Account__c.field-meta.xml
<CustomField>
    <fullName>B2B_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>B2B Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>B2B Deals</relationshipLabel>
    <relationshipName>B2B_Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Deals__c/fields/B2B_Currency__c.field-meta.xml
<CustomField>
    <fullName>B2B_Currency__c</fullName>
    <label>B2B Currency</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Deals__c/fields/B2B_Deal_Discount__c.field-meta.xml
<CustomField>
    <fullName>B2B_Deal_Discount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>B2B Deal Discount</label>
    <referenceTo>B2B_Deal_Discount__c</referenceTo>
    <relationshipLabel>B2B Deal Discounts</relationshipLabel>
    <relationshipName>B2B_Deal_Discounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Deals__c/fields/B2B_Deal_Number__c.field-meta.xml
<CustomField>
    <fullName>B2B_Deal_Number__c</fullName>
    <label>B2B Deal Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/CartItem/fields/B2B_Deal_Discount__c.field-meta.xml
<CustomField>
    <fullName>B2B_Deal_Discount__c</fullName>
    <label>B2B Deal Discount %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Contact/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <inlineHelpText>This field maps over from the Lead Page</inlineHelpText>
    <label>Product Line</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AA</fullName>
            </value>
            <value>
                <fullName>AGO</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>AMS</fullName>
            </value>
            <value>
                <fullName>ANP</fullName>
            </value>
            <value>
                <fullName>APS</fullName>
            </value>
            <value>
                <fullName>ARS</fullName>
            </value>
            <value>
                <fullName>ATT</fullName>
            </value>
            <value>
                <fullName>AVC</fullName>
            </value>
            <value>
                <fullName>AVS</fullName>
            </value>
            <value>
                <fullName>AWS</fullName>
            </value>
            <value>
                <fullName>BIO</fullName>
            </value>
            <value>
                <fullName>BTX</fullName>
            </value>
            <value>
                <fullName>CAT</fullName>
            </value>
            <value>
                <fullName>CCM</fullName>
            </value>
            <value>
                <fullName>CHS</fullName>
            </value>
            <value>
                <fullName>CLH</fullName>
            </value>
            <value>
                <fullName>CLR</fullName>
            </value>
            <value>
                <fullName>CRD</fullName>
            </value>
            <value>
                <fullName>CSA</fullName>
            </value>
            <value>
                <fullName>CSB</fullName>
            </value>
            <value>
                <fullName>DAB</fullName>
            </value>
            <value>
                <fullName>DAO</fullName>
            </value>
            <value>
                <fullName>DCS</fullName>
            </value>
            <value>
                <fullName>DEL</fullName>
            </value>
            <value>
                <fullName>DIA</fullName>
            </value>
            <value>
                <fullName>DIS</fullName>
            </value>
            <value>
                <fullName>DL</fullName>
            </value>
            <value>
                <fullName>DLS</fullName>
            </value>
            <value>
                <fullName>DNA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/B2B_Item_Class__c.field-meta.xml
<CustomField>
    <fullName>B2B_Item_Class__c</fullName>
    <label>Item Class</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>G</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/B2B_Product_Line__c.field-meta.xml
<CustomField>
    <fullName>B2B_Product_Line__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AA</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>AWS</fullName>
            </value>
            <value>
                <fullName>BIO</fullName>
            </value>
            <value>
                <fullName>CLR</fullName>
            </value>
            <value>
                <fullName>CSB</fullName>
            </value>
            <value>
                <fullName>DAB</fullName>
            </value>
            <value>
                <fullName>DAO</fullName>
            </value>
            <value>
                <fullName>DEL</fullName>
            </value>
            <value>
                <fullName>DIA</fullName>
            </value>
            <value>
                <fullName>DL</fullName>
            </value>
            <value>
                <fullName>DLS</fullName>
            </value>
            <value>
                <fullName>EZR</fullName>
            </value>
            <value>
                <fullName>FAP</fullName>
            </value>
            <value>
                <fullName>FN</fullName>
            </value>
            <value>
                <fullName>FTF</fullName>
            </value>
            <value>
                <fullName>GC</fullName>
            </value>
            <value>
                <fullName>GM</fullName>
            </value>
            <value>
                <fullName>HCA</fullName>
            </value>
            <value>
                <fullName>HCS</fullName>
            </value>
            <value>
                <fullName>HTS</fullName>
            </value>
            <value>
                <fullName>ICP</fullName>
            </value>
            <value>
                <fullName>IMF</fullName>
            </value>
            <value>
                <fullName>IMG</fullName>
            </value>
            <value>
                <fullName>INV</fullName>
            </value>
            <value>
                <fullName>IR</fullName>
            </value>
            <value>
                <fullName>LC</fullName>
            </value>
            <value>
                <fullName>LCA</fullName>
            </value>
            <value>
                <fullName>LCM</fullName>
            </value>
            <value>
                <fullName>LM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/Item_Class__c.field-meta.xml
<CustomField>
    <fullName>Item_Class__c</fullName>
    <label>IGOR Item Class</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/product_line__c.field-meta.xml
<CustomField>
    <fullName>product_line__c</fullName>
    <description>Product Line code from SAP</description>
    <label>Product Line</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/classes/B2BCustomPricingServiceTest.cls
@IsTest
public without sharing class B2BCustomPricingServiceTest {
    @testSetup static void setup() {
        // WebStore testWebStore = new WebStore(Name='TestWebStore');
        // insert testWebStore;

        WebStore webStore = B2B_TestDataFactory.createWebstore('TestWebStore',true);
        Product2 prod = B2B_TestDataFactory.createProduct('Test Product',true);
        List<Product2> prodList = new List<Product2>();
        prodList.add(prod);	
        Account account = B2B_TestDataFactory.createAccount('Test Account', true);
        Contact contact = B2B_TestDataFactory.createContact('Test Contact', account.Id, true);
        User user = B2B_TestDataFactory.createUser('test', 'test@gmail.com', contact.Id, true);
        ContactPointAddress cpa = B2B_TestDataFactory.createShippingCPA(account,true);
        WebCart cart = B2B_TestDataFactory.createCart(account.Id, user.Id, webStore.Id, cpa.Id, true);

        Schema.Location location = B2B_TestDataFactory.createLocation('Test', true);
        OrderDeliveryMethod odm = B2B_TestDataFactory.createOrderDeliveryMethod(true);
        CartDeliveryGroup deliveryGroup = B2B_TestDataFactory.createCartDeliveryGroupWithCountryCode(cart.Id,odm.Id,'US',true);
        List<cartItem> cartitems1 = B2B_TestDataFactory.createCartitems(cart.Id,deliveryGroup.Id,prodList,location.Id,true);

        B2B_Deal_Discount__c dealDiscount = new B2B_Deal_Discount__c();
        dealDiscount.Name = 'Deal Discount Test';
        insert dealDiscount;

        B2B_Deals__c deals = new B2B_Deals__c();
        deals.B2B_Account__c = account.Id;
        deals.B2B_Currency__c = 'USD' ;
        deals.B2B_Deal_Number__c = 'Deal001' ;
        deals.B2B_Deal_Discount__c = dealDiscount.Id;
        insert deals;

        B2B_Deal_Discount_Line__c dealItem = new B2B_Deal_Discount_Line__c();
        // dealItem.B2B_Deal_Discount__c = deals.Id;
        dealItem.B2B_Deal_Discount__c = dealDiscount.Id;
        dealItem.B2B_Discount__c = 5.00; 
        dealItem.B2B_Item_Class__c = '3'; 
        dealItem.B2B_Product_Line__c = 'AA'; 
        dealItem.B2B_Start_Date__c = Date.today(); 
        dealItem.B2B_End_Date__c =Date.today() + 10; 
        insert dealItem;


        Product2 shipProduct = new Product2();
        shipProduct.Name = 'Prod1';
        shipProduct.ProductCode = 'Prod1';
        shipProduct.StockKeepingUnit = 'Prod1';
        shipProduct.isActive = true ;
        shipProduct.product_line__c = 'AA' ;
        shipProduct.Item_Class__c = '3' ;
        insert shipProduct;
    }


    @isTest 
    static void testProcessPriceIntegration() {
        Test.startTest();
        Account account = [SELECT Id FROM Account WHERE Name='Test Account' LIMIT 1];
        WebStore webStore = [SELECT Id FROM WebStore WHERE Name='TestWebStore' LIMIT 1];
        Product2 prod = [SELECT Id FROM Product2 WHERE Name='Prod1' LIMIT 1];
        
        commercestorepricing.PricingRequestItem requestItem = new commercestorepricing.PricingRequestItem(prod.Id);
        commercestorepricing.PricingRequest request = new commercestorepricing.PricingRequest();
        request.setWebStoreId(webStore.Id);
        request.setEffectiveAccountId(account.Id);
        request.addPricingRequestItem(requestItem);

        User user = [SELECT Id FROM User WHERE Email = 'test@gmail.com' LIMIT 1];

        System.runAS(user) {
            B2BCustomPricingService apexSample = new B2BCustomPricingService();
            commercestorepricing.PricingResponse response = apexSample.processPrice(request);
        }
        Test.stopTest();
    }

    @isTest 
    static void testGuestProcessPriceIntegration() {
        Test.startTest();
        Id accountId = UserInfo.getUserId();
        WebStore webStore = [SELECT Id FROM WebStore WHERE Name='TestWebStore' LIMIT 1];
        Product2 prod = [SELECT Id FROM Product2 WHERE Name='Prod1' LIMIT 1];
        
        commercestorepricing.PricingRequestItem requestItem = new commercestorepricing.PricingRequestItem(prod.Id);
        commercestorepricing.PricingRequest request = new commercestorepricing.PricingRequest();
        request.setWebStoreId(webStore.Id);
        request.setEffectiveAccountId(accountId);
        request.addPricingRequestItem(requestItem);

        B2BCustomPricingService apexSample = new B2BCustomPricingService();
        commercestorepricing.PricingResponse response = apexSample.processPrice(request);

        Test.stopTest();
    }


    @isTest
    static void test_processTransactionalPrice_withCustomAccount() {
        Account acc = [SELECT Id FROM Account WHERE Name='Test Account' LIMIT 1];
        Product2 prod = [SELECT Id FROM Product2 WHERE Name='Prod1' LIMIT 1];
        String cartItemId = [SELECT Id FROM CartItem WHERE Cart.AccountId =: acc.Id LIMIT 1].Id;

        // Prepare request item using correct constructor
        commercestorepricing.TransactionalPricingRequestItem reqItem = 
            // new commercestorepricing.TransactionalPricingRequestItem('Line-001', prod.Id, 2);
            new commercestorepricing.TransactionalPricingRequestItem(cartItemId, prod.Id, 2);

        // Prepare full request
        commercestorepricing.TransactionalPricingRequest request = new commercestorepricing.TransactionalPricingRequest();
        request.setEffectiveAccountId(acc.Id);
        request.setCurrencyIsoCode('USD');
        request.addTxnPricingRequestItem(reqItem);

        Test.startTest();
        commercestorepricing.TransactionalPricingResponse response = new B2BCustomPricingService().processTransactionalPrice(request);
        Test.stopTest();

        System.assertNotEquals(null, response);
        System.assertEquals('USD', response.getCurrencyIsoCode());
        System.assertEquals(1, response.getTxnPricingResponseItems().size());
    }



}