Perkin-UAT/force-app/main/default/objects/Account/recordTypes/Test.recordType-meta.xml
<RecordType>
    <fullName>Test</fullName>
    <active>true</active>
    <label>Test</label>
</RecordType>

Perkin-UAT/force-app/main/default/objects/B2B_Deal_Discount__c/B2B_Deal_Discount__c.object-meta.xml
<CustomObject>
    <label>B2B Deal Discount</label>
    <nameField>
        <label>B2B Deal Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2B Deal Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/B2B_Deal_Discount_Line__c/B2B_Deal_Discount_Line__c.object-meta.xml
<CustomObject>
    <label>B2B Deal Discount Line</label>
    <nameField>
        <displayFormat>DealLine# {00000}</displayFormat>
        <label>B2B Deal Discount Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B2B Deal Discount Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/B2B_Deal_Discount_Line__c/fields/B2B_Deal_Discount__c.field-meta.xml
<CustomField>
    <fullName>B2B_Deal_Discount__c</fullName>
    <label>B2B Deal Discount</label>
    <referenceTo>B2B_Deal_Discount__c</referenceTo>
    <relationshipLabel>B2B Deal Discount Lines</relationshipLabel>
    <relationshipName>B2B_Deal_Discount_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Deal_Discount_Line__c/fields/B2B_Discount__c.field-meta.xml
<CustomField>
    <fullName>B2B_Discount__c</fullName>
    <label>B2B Discount %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Deal_Discount_Line__c/fields/B2B_End_Date__c.field-meta.xml
<CustomField>
    <fullName>B2B_End_Date__c</fullName>
    <label>B2B End Date</label>
    <type>Date</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Deal_Discount_Line__c/fields/B2B_Item_Class__c.field-meta.xml
<CustomField>
    <fullName>B2B_Item_Class__c</fullName>
    <label>B2B Item Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Deal_Discount_Line__c/fields/B2B_Product_Line__c.field-meta.xml
<CustomField>
    <fullName>B2B_Product_Line__c</fullName>
    <label>B2B Product Line</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Deal_Discount_Line__c/fields/B2B_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>B2B_Start_Date__c</fullName>
    <label>B2B Start Date</label>
    <type>Date</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Deals__c/B2B_Deals__c.object-meta.xml
<CustomObject>
    <label>B2B Deals</label>
    <nameField>
        <displayFormat>Deal# {00000}</displayFormat>
        <label>B2B Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B2B Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/B2B_Deals__c/fields/B2B_Account__c.field-meta.xml
<CustomField>
    <fullName>B2B_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>B2B Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>B2B Deals</relationshipLabel>
    <relationshipName>B2B_Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Deals__c/fields/B2B_Currency__c.field-meta.xml
<CustomField>
    <fullName>B2B_Currency__c</fullName>
    <label>B2B Currency</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Deals__c/fields/B2B_Deal_Discount__c.field-meta.xml
<CustomField>
    <fullName>B2B_Deal_Discount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>B2B Deal Discount</label>
    <referenceTo>B2B_Deal_Discount__c</referenceTo>
    <relationshipLabel>B2B Deal Discounts</relationshipLabel>
    <relationshipName>B2B_Deal_Discounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Deals__c/fields/B2B_Deal_Number__c.field-meta.xml
<CustomField>
    <fullName>B2B_Deal_Number__c</fullName>
    <label>B2B Deal Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/classes/B2B_DealValidatorTest.cls
@isTest
public with sharing class B2B_DealValidatorTest {

    @TestSetup
    static void setupData() {
        // Create Account with currency
        Account acc = new Account(
            Name = 'Test Account',
            CurrencyIsoCode = 'USD'
        );
        insert acc;

        // Create Deal for the account
        /*B2B_Deals__c deal = new B2B_Deals__c(
            B2B_Account__c = acc.Id,
            B2B_Currency__c = 'USD',
            B2B_Deal_Number__c = 'Deal001'
        );
        insert deal;*/
        
        B2B_Deal_Discount__c dealDiscount = new B2B_Deal_Discount__c(
            Name = 'Test Deal Discount Test',
            CurrencyIsoCode = 'USD'
        );
        insert dealDiscount;
        
        B2B_Deals__c deals = new B2B_Deals__c();
        deals.B2B_Account__c = acc.Id;
        deals.B2B_Currency__c = 'USD' ;
        deals.B2B_Deal_Number__c = 'Deal001' ;
        deals.B2B_Deal_Discount__c = dealDiscount.Id;
        insert deals;

        B2B_Deal_Discount_Line__c dealItem = new B2B_Deal_Discount_Line__c();
        dealItem.B2B_Deal_Discount__c = dealDiscount.Id;
        dealItem.B2B_Discount__c = 5.00; 
        dealItem.B2B_Item_Class__c = '3'; 
        dealItem.B2B_Product_Line__c = 'AA'; 
        dealItem.B2B_Start_Date__c = Date.today(); 
        dealItem.B2B_End_Date__c =Date.today() + 10; 
        insert dealItem;
    }

    @isTest
    static void testValidateDeals_Positive() {
        Account acc = [SELECT Id FROM Account WHERE Name = 'Test Account' LIMIT 1];

        Map<String, Object> inputParams = new Map<String, Object>();
        inputParams.put('effectiveAccountId', acc.Id);

        Map<String, Object> result = B2B_DealValidator.validateDealsOnAccount(inputParams);

        System.assertEquals(true, result.get('hasDeals'), 'Expected hasDeals to be true');
        System.assertEquals(true, result.get('isSuccess'), 'Expected isSuccess to be true');
    }

    @isTest
    static void testValidateDeals_Negative() {
        // Create account without deals
        Account acc = new Account(
            Name = 'No Deal Account',
            CurrencyIsoCode = 'USD'
        );
        insert acc;

        Map<String, Object> inputParams = new Map<String, Object>();
        inputParams.put('effectiveAccountId', acc.Id);

        Map<String, Object> result = B2B_DealValidator.validateDealsOnAccount(inputParams);

        System.assertEquals(false, result.get('hasDeals'), 'Expected hasDeals to be false');
        System.assertEquals(true, result.get('isSuccess'), 'Expected isSuccess to be true');
    }

    @isTest
    static void testValidateDeals_NullInput() {
        Map<String, Object> result = B2B_DealValidator.validateDealsOnAccount(null);

        System.assertEquals(false, result.get('hasDeals'), 'Expected hasDeals to be false');
        System.assertEquals(false, result.get('isSuccess'), 'Expected isSuccess to be false');
    }
}