Perkin-UAT/force-app/main/default/objects/Account/recordTypes/Test.recordType-meta.xml
<RecordType>
    <fullName>Test</fullName>
    <active>true</active>
    <label>Test</label>
</RecordType>

Perkin-UAT/force-app/main/default/objects/B2B_Deal_Discount__c/B2B_Deal_Discount__c.object-meta.xml
<CustomObject>
    <label>B2B Deal Discount</label>
    <nameField>
        <label>B2B Deal Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2B Deal Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/B2B_Deal_Discount_Line__c/B2B_Deal_Discount_Line__c.object-meta.xml
<CustomObject>
    <label>B2B Deal Discount Line</label>
    <nameField>
        <displayFormat>DealLine# {00000}</displayFormat>
        <label>B2B Deal Discount Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B2B Deal Discount Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/B2B_Deal_Discount_Line__c/fields/B2B_Deal_Discount__c.field-meta.xml
<CustomField>
    <fullName>B2B_Deal_Discount__c</fullName>
    <label>B2B Deal Discount</label>
    <referenceTo>B2B_Deal_Discount__c</referenceTo>
    <relationshipLabel>B2B Deal Discount Lines</relationshipLabel>
    <relationshipName>B2B_Deal_Discount_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Deal_Discount_Line__c/fields/B2B_Discount__c.field-meta.xml
<CustomField>
    <fullName>B2B_Discount__c</fullName>
    <label>B2B Discount %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Deal_Discount_Line__c/fields/B2B_End_Date__c.field-meta.xml
<CustomField>
    <fullName>B2B_End_Date__c</fullName>
    <label>B2B End Date</label>
    <type>Date</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Deal_Discount_Line__c/fields/B2B_Item_Class__c.field-meta.xml
<CustomField>
    <fullName>B2B_Item_Class__c</fullName>
    <label>B2B Item Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Deal_Discount_Line__c/fields/B2B_Product_Line__c.field-meta.xml
<CustomField>
    <fullName>B2B_Product_Line__c</fullName>
    <label>B2B Product Line</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Deal_Discount_Line__c/fields/B2B_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>B2B_Start_Date__c</fullName>
    <label>B2B Start Date</label>
    <type>Date</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Deals__c/B2B_Deals__c.object-meta.xml
<CustomObject>
    <label>B2B Deals</label>
    <nameField>
        <displayFormat>Deal# {00000}</displayFormat>
        <label>B2B Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B2B Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/B2B_Deals__c/fields/B2B_Account__c.field-meta.xml
<CustomField>
    <fullName>B2B_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>B2B Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>B2B Deals</relationshipLabel>
    <relationshipName>B2B_Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Deals__c/fields/B2B_Currency__c.field-meta.xml
<CustomField>
    <fullName>B2B_Currency__c</fullName>
    <label>B2B Currency</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Deals__c/fields/B2B_Deal_Discount__c.field-meta.xml
<CustomField>
    <fullName>B2B_Deal_Discount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>B2B Deal Discount</label>
    <referenceTo>B2B_Deal_Discount__c</referenceTo>
    <relationshipLabel>B2B Deal Discounts</relationshipLabel>
    <relationshipName>B2B_Deal_Discounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Deals__c/fields/B2B_Deal_Number__c.field-meta.xml
<CustomField>
    <fullName>B2B_Deal_Number__c</fullName>
    <label>B2B Deal Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/CartItem/fields/B2B_Deal_Discount__c.field-meta.xml
<CustomField>
    <fullName>B2B_Deal_Discount__c</fullName>
    <label>B2B Deal Discount %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/B2B_Item_Class__c.field-meta.xml
<CustomField>
    <fullName>B2B_Item_Class__c</fullName>
    <label>Item Class</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>G</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/B2B_Product_Line__c.field-meta.xml
<CustomField>
    <fullName>B2B_Product_Line__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AA</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>AWS</fullName>
            </value>
            <value>
                <fullName>BIO</fullName>
            </value>
            <value>
                <fullName>CLR</fullName>
            </value>
            <value>
                <fullName>CSB</fullName>
            </value>
            <value>
                <fullName>DAB</fullName>
            </value>
            <value>
                <fullName>DAO</fullName>
            </value>
            <value>
                <fullName>DEL</fullName>
            </value>
            <value>
                <fullName>DIA</fullName>
            </value>
            <value>
                <fullName>DL</fullName>
            </value>
            <value>
                <fullName>DLS</fullName>
            </value>
            <value>
                <fullName>EZR</fullName>
            </value>
            <value>
                <fullName>FAP</fullName>
            </value>
            <value>
                <fullName>FN</fullName>
            </value>
            <value>
                <fullName>FTF</fullName>
            </value>
            <value>
                <fullName>GC</fullName>
            </value>
            <value>
                <fullName>GM</fullName>
            </value>
            <value>
                <fullName>HCA</fullName>
            </value>
            <value>
                <fullName>HCS</fullName>
            </value>
            <value>
                <fullName>HTS</fullName>
            </value>
            <value>
                <fullName>ICP</fullName>
            </value>
            <value>
                <fullName>IMF</fullName>
            </value>
            <value>
                <fullName>IMG</fullName>
            </value>
            <value>
                <fullName>INV</fullName>
            </value>
            <value>
                <fullName>IR</fullName>
            </value>
            <value>
                <fullName>LC</fullName>
            </value>
            <value>
                <fullName>LCA</fullName>
            </value>
            <value>
                <fullName>LCM</fullName>
            </value>
            <value>
                <fullName>LM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/classes/B2B_CustomPromotionCalculatorTest.cls
@isTest
public with sharing class B2B_CustomPromotionCalculatorTest {
    private static final String ACCOUNT_NAME = 'Test Account';
    private static final String CONTACT_NAME = 'Test Contact';
    private static final String PRODUCT_NAME = 'Test Product';
    private static final String LOCATION_NAME = 'Test';
    private static final String Community_Nickname = 'testuser';
    private static final String EMAIL = 'test@user.com';

    static B2B_CustomPromotionCalculator calculator = new B2B_CustomPromotionCalculator();

    @TestSetup
    static void setup() {
        Product2 prod = B2B_TestDataFactory.createProduct(PRODUCT_NAME,true);
        List<Product2> prodList = new List<Product2>();
        prodList.add(prod);			
        Account acc = B2B_TestDataFactory.createAccount(ACCOUNT_NAME,true);
        Contact con = B2B_TestDataFactory.createContact(CONTACT_NAME,acc.Id,true);
        ContactPointAddress cpa = B2B_TestDataFactory.createShippingCPA(acc,true);
        Schema.Location location = B2B_TestDataFactory.createLocation(LOCATION_NAME, true);
        OrderDeliveryMethod odm = B2B_TestDataFactory.createOrderDeliveryMethod(true);
        User custUser = B2B_TestDataFactory.createUser(Community_Nickname,EMAIL,con.Id,true);
        WebStore store = B2B_TestDataFactory.createWebstore('Test Store',true);
        WebCart cart = B2B_TestDataFactory.createCart(acc.Id,custUser.Id,store.Id,cpa.Id,true);
        CartDeliveryGroup deliveryGroup = B2B_TestDataFactory.createCartDeliveryGroupWithCountryCode(cart.Id,odm.Id,'US',true);
        List<cartItem> cartitems = B2B_TestDataFactory.createCartitems(cart.Id,deliveryGroup.Id,prodList,location.Id,true);
        
        
        B2B_Deal_Discount__c dealdiscount = new B2B_Deal_Discount__c(
        	Name = 'Test dealdiscount',
            CurrencyIsoCode = 'USD'
        );
        insert dealdiscount;
        
        B2B_Deals__c deals = new B2B_Deals__c();
        deals.B2B_Account__c = acc.Id;
        deals.B2B_Currency__c = 'USD' ;
        deals.B2B_Deal_Number__c = 'Deal001' ;
        deals.B2B_Deal_Discount__c = dealdiscount.Id;
        insert deals;
        
        B2B_Deal_Discount_Line__c dealItem = new B2B_Deal_Discount_Line__c();
        dealItem.B2B_Deal_Discount__c = dealdiscount.Id;
        dealItem.B2B_Discount__c = 5.00; 
        dealItem.B2B_Item_Class__c = '3'; 
        dealItem.B2B_Product_Line__c = 'AA'; 
        dealItem.B2B_Start_Date__c = Date.today(); 
        dealItem.B2B_End_Date__c =Date.today() + 10; 
        insert dealItem;
    }

    @isTest
    public static void testValidAccount(){
        CartDeliveryGroup deliveryGroup = [SELECT Id FROM CartDeliveryGroup WHERE Name = 'Default' LIMIT 1];
        delete deliveryGroup;
        Schema.WebCart cart = [SELECT Id FROM WebCart WHERE Name='Cart' LIMIT 1];
        CartExtension.Cart cartObject = CartExtension.CartTestUtil.getCart(cart.Id);
        
        CartExtension.CartCalculateCalculatorRequest request = new CartExtension.CartCalculateCalculatorRequest(cartObject,CartExtension.OptionalBuyerActionDetails.empty());
        Test.startTest();
        calculator.calculate(request);
        Test.stopTest();
        
    }
    @isTest
    public static void testValidAccountNegavtive(){
        B2B_Deals__c deal = [SELECT Id FROM B2B_Deals__c WHERE B2B_Deal_Number__c =: 'Deal001' LIMIT 1];
		delete deal;
        CartDeliveryGroup deliveryGroup = [SELECT Id FROM CartDeliveryGroup WHERE Name = 'Default' LIMIT 1];
        delete deliveryGroup;
        Schema.WebCart cart = [SELECT Id FROM WebCart WHERE Name='Cart' LIMIT 1];
        CartExtension.Cart cartObject = CartExtension.CartTestUtil.getCart(cart.Id);
        
        CartExtension.CartCalculateCalculatorRequest request = new CartExtension.CartCalculateCalculatorRequest(cartObject,CartExtension.OptionalBuyerActionDetails.empty());
        Test.startTest();
        calculator.calculate(request);
        Test.stopTest();
        
    }

    @isTest
    public static void testCartValidationOutput() {
        WebCart cartRecord = [SELECT Id, AccountId FROM WebCart WHERE Name='Cart' LIMIT 1];
        CartExtension.Cart cartObject = CartExtension.CartTestUtil.getCart(cartRecord.Id);

        //Add fake ValidationOutput to trigger cleanUpCVO for-loop
        CartExtension.CartValidationOutput mockCVO = new CartExtension.CartValidationOutput(
            CartExtension.CartValidationOutputTypeEnum.PROMOTIONS,
            CartExtension.CartValidationOutputLevelEnum.INFO
        );
        cartObject.getCartValidationOutputs().add(mockCVO);

        CartExtension.CartCalculateCalculatorRequest request = new CartExtension.CartCalculateCalculatorRequest(
            cartObject, CartExtension.OptionalBuyerActionDetails.empty()
        );

        Test.startTest();
        calculator.calculate(request); 
        Test.stopTest();
    }

    @isTest
    public static void testForGuest() {
        WebCart cartRecord = [SELECT Id, AccountId FROM WebCart WHERE Name='Cart' LIMIT 1];
        cartRecord.AccountId = UserInfo.getUserId();
        update cartRecord;
        CartExtension.Cart cartObject = CartExtension.CartTestUtil.getCart(cartRecord.Id);

        CartExtension.CartCalculateCalculatorRequest request = new CartExtension.CartCalculateCalculatorRequest(
            cartObject, CartExtension.OptionalBuyerActionDetails.empty()
        );

        Test.startTest();
        calculator.calculate(request);
        Test.stopTest();
    }
    
    @isTest
    public static void testAddCartValidationOutputTrigger() {
        WebCart cartRecord = [SELECT Id, AccountId FROM WebCart WHERE Name='Cart' LIMIT 1];
        CartExtension.Cart cartObject = CartExtension.CartTestUtil.getCart(cartRecord.Id);
    
        // Inject mock adjustment basis
        CartExtension.CartAdjustmentBasis mockBasis = new CartExtension.CartAdjustmentBasis();
        mockBasis.setAdjustmentBasisDetail('Mock Detail');
        cartObject.getCartAdjustmentBases().add(mockBasis);
    
        CartExtension.CartCalculateCalculatorRequest request = new CartExtension.CartCalculateCalculatorRequest(
            cartObject, CartExtension.OptionalBuyerActionDetails.empty()
        );
    
        Test.startTest();
        calculator.calculate(request);
        Test.stopTest();
    }
}