Perkin-UAT/force-app/main/default/objects/Account/recordTypes/Test.recordType-meta.xml
<RecordType>
    <fullName>Test</fullName>
    <active>true</active>
    <label>Test</label>
</RecordType>

Perkin-UAT/force-app/main/default/objects/Case_Response_Tracking__c/Case_Response_Tracking__c.object-meta.xml
<CustomObject>
    <description>This is used to capture Handle Time for a case</description>
    <label>Case Response Tracking</label>
    <nameField>
        <displayFormat>CRT-{000000}</displayFormat>
        <label>Case Response Tracking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Response Tracking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/Case_Response_Tracking__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Response Tracking</relationshipLabel>
    <relationshipName>Case_Response_Tracking</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Perkin-UAT/force-app/main/default/classes/CaseResponseTrackingService_Test.cls
@isTest
private class CaseResponseTrackingService_Test {
    
    @testsetup
    static void testSetupData() {
        //insert account
        Account acc = CT_TestDataSetupUtility.createTestAccount('TEST','77778','Test');
        insert acc;
        
        //insert contact
        Contact con = CT_TestDataSetupUtility.createTestContact(acc.id,'test','test','test@test.com');
        insert con;
        
        //insert case
        Case casetoinsert = CT_TestDataSetupUtility.createTestCase('Informatics','New','test','Phone',acc.id,con.id);
        insert casetoinsert;
    }
    
    @isTest
    static void testInsertMethod() {
        
        List<case> caseList = [SELECT Id, recordTypeId, OwnerId, BusinessHoursId, Status FROM Case];
        CaseResponseTrackingService.CRTInsert(caseList);
        
    }
    
    @isTest
    static void testUpdate() {
        
        List<case> caseList = [SELECT Id, recordTypeId, OwnerId, BusinessHoursId, Status FROM Case];
        map<id, case> oldMap = new map<id, case>(caseList);
        case c = caseList[0];
        c.Status = 'New Info';
        c.OwnerId = UserInfo.getUserId();
        
        map<id, case> newMap = new map<id, case>();
        newMap.put(c.id, c);

        CaseResponseTrackingService.caseResponseUpdateAction(oldMap, newMap);
    }
    
    @isTest
    static void testInsertHelper() {

        List<case> caseList = [SELECT Id, recordTypeId, OwnerId, BusinessHoursId, Status FROM Case];
        Set<id> caseOwnerIdSet = new Set<id>{UserInfo.getUserId()};

        CaseResponseTrackingService.caseResponseInsertAction(caseList, caseOwnerIdSet);
    }
    
    @isTest
    static void testGetRecords() {
        case c = [SELECT Id, recordTypeId, OwnerId, BusinessHoursId, Status FROM Case limit 1];

        Set<id> caseIds = new set<id>{c.id};
		Case_Response_Tracking__c crt = new Case_Response_Tracking__c(case__c = c.id);
        insert crt;
        CaseResponseTrackingService.getCaseResponseTrackingRecords(caseIds);
    }
}