Perkin-UAT/force-app/main/default/objects/BD_Quote_Event__e/BD_Quote_Event__e.object-meta.xml
<CustomObject>
    <label>Quote Event</label>
    <pluralLabel>Quote Events</pluralLabel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/BD_Quote_Event__e/fields/BD_Quote_Id__c.field-meta.xml
<CustomField>
    <fullName>BD_Quote_Id__c</fullName>
    <label>Quote Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_Platform_Event_Log__c/SMAX_PS_Platform_Event_Log__c.object-meta.xml
<CustomObject>
    <description>Object to record history of all Platform Events sent from the system.
This object is created as a backup / failsafe in case of connectivity problems.</description>
    <label>Platform Event Log</label>
    <nameField>
        <displayFormat>PE-{0000000000}</displayFormat>
        <label>Platform Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Platform Event Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_Platform_Event_Log__c/fields/SMAX_PS_Action__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_Action__c</fullName>
    <label>Action</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_Platform_Event_Log__c/fields/SMAX_PS_Event_JSON__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_Event_JSON__c</fullName>
    <label>Event JSON</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_Platform_Event_Log__c/fields/SMAX_PS_Platform_Event_Type__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_Platform_Event_Type__c</fullName>
    <label>Platform Event Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_Platform_Event_Log__c/fields/SMAX_PS_Related_Element_Id__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_Related_Element_Id__c</fullName>
    <externalId>true</externalId>
    <label>Related Element Identifier</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_Platform_Event_Log__c/fields/SMAX_PS_Replay_Id__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_Replay_Id__c</fullName>
    <label>Replay Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Perkin-UAT/force-app/main/default/classes/BD_QuoteEventHandler.cls
public class BD_QuoteEventHandler {
    public static void createPlatformEventLog(List<BD_Quote_Event__e> quoteEvents) {
        List<SMAX_PS_Platform_Event_Log__c> logs = new List<SMAX_PS_Platform_Event_Log__c>();
        for(BD_Quote_Event__e event : quoteEvents) {
            SMAX_PS_Platform_Event_Log__c platformEventLog = new SMAX_PS_Platform_Event_Log__c();
            platformEventLog.SMAX_PS_Action__c = 'ACCEPTED';
            platformEventLog.SMAX_PS_Replay_Id__c = Decimal.valueOf(event.ReplayId);
            platformEventLog.SMAX_PS_Platform_Event_Type__c = 'SBQQ__Quote__c';
            platformEventLog.SMAX_PS_Related_Element_Id__c = event.BD_Quote_Id__c;
            platformEventLog.SMAX_PS_Event_JSON__c = JSON.serialize(event);
            logs.add(platformEventLog);            
        }
        
        insert logs;
    }
}