Perkin-UAT/force-app/main/default/objects/FCO__c/FCO__c.object-meta.xml
<CustomObject>
    <label>FCO</label>
    <nameField>
        <label>FCO Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FCOs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/FCO__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>FCO</relationshipLabel>
    <relationshipName>FCO</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/FCO__c/fields/PSC_Status__c.field-meta.xml
<CustomField>
    <fullName>PSC_Status__c</fullName>
    <label>PSC Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Superceded</fullName>
            </value>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Scoping</fullName>
            </value>
            <value>
                <fullName>Logistics</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/classes/SVMX_NewFCO.cls
public class SVMX_NewFCO{

    public SVMX_NewFCO(ApexPages.StandardController controller) {

    }
    @testvisible FCO__c fco=new FCO__c();
    public FCO__c getFCO(){
        return fco;
    }
    public void setFCO(FCO__c fco){
        fco=fco;
    }
    public pagereference save(){
        pagereference pgref=null;
        if(fco.Product__c != null && fco.PSC_Status__c != null){
            try{
                Product2 prod=[select id,ProductCode from Product2 where id=:fco.Product__c];
                fco.Name=prod.ProductCode;
                insert fco;
                pgref= new pagereference('/'+fco.id);
                pgref.setRedirect(true);
            }catch(Exception E){
            }
        }
        return pgref;
    }
}