Perkin-UAT/force-app/main/default/objects/FCO__c/FCO__c.object-meta.xml
<CustomObject>
    <label>FCO</label>
    <nameField>
        <label>FCO Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FCOs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/FCO__c/fields/FCO_Type__c.field-meta.xml
<CustomField>
    <fullName>FCO_Type__c</fullName>
    <label>FCO Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer Notification</fullName>
            </value>
            <value>
                <fullName>Interaction Center Notification</fullName>
            </value>
            <value>
                <fullName>RMA</fullName>
            </value>
            <value>
                <fullName>Work Order - Field Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/FCO__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>FCO</relationshipLabel>
    <relationshipName>FCO</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/FCO__c/fields/PSC__c.field-meta.xml
<CustomField>
    <fullName>PSC__c</fullName>
    <label>PSC</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BMEI</fullName>
            </value>
            <value>
                <fullName>CMS</fullName>
            </value>
            <value>
                <fullName>Crawley</fullName>
            </value>
            <value>
                <fullName>Impac</fullName>
            </value>
            <value>
                <fullName>Linkoping</fullName>
            </value>
            <value>
                <fullName>Med Int</fullName>
            </value>
            <value>
                <fullName>NeuroMag</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/FCO__c/fields/PSC_Status__c.field-meta.xml
<CustomField>
    <fullName>PSC_Status__c</fullName>
    <label>PSC Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Superceded</fullName>
            </value>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Scoping</fullName>
            </value>
            <value>
                <fullName>Logistics</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/classes/SVMX_NewFCO_Test.cls
@isTest
private class SVMX_NewFCO_Test {
    private static testMethod void testSave() {        
        Test.startTest();        
        Product2 prod = new Product2(ProductCode='UTProd001',
                                     Name='UTProd001',
                                     Family='Oncology',
                                     SVMXC__Product_Line__c='Desktop',
                                     IsActive=true);
        insert prod;        
        
        FCO__c  fco = new FCO__c(Name='FCO UT',
                                 FCO_Type__c='Important Field Safety Notice',
                                 PSC_Status__c='New',
                                 PSC__c='CMS',
                                 Description__c='Description',
                                 Product__c = prod.Id
                                );        
        
        PageReference pageRef = Page.SVMX_NewFCO;     
        Test.setCurrentPageReference(pageRef);
        
        ApexPages.StandardController sc = new ApexPages.standardController(fco);
        SVMX_NewFCO newController = new SVMX_NewFCO(sc); 
        newController.FCO = fco; 
        newController.setFCO(fco);
        FCO__c s = newController.getFCO();
        System.assertEquals(fco,s);
        newController.save();
        Test.stopTest();
    }    
}