Perkin-UAT/force-app/main/default/objects/Lead/fields/BE__c.field-meta.xml
<CustomField>
    <fullName>BE__c</fullName>
    <description>Business Element/Business Unit</description>
    <inlineHelpText>Primary Business Unit for this Lead</inlineHelpText>
    <label>BE</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dx</fullName>
            </value>
            <value>
                <fullName>INF</fullName>
            </value>
            <value>
                <fullName>LST</fullName>
            </value>
            <value>
                <fullName>MED</fullName>
            </value>
            <value>
                <fullName>SVC</fullName>
            </value>
            <value>
                <fullName>ONE</fullName>
            </value>
            <value>
                <fullName>EH</fullName>
            </value>
            <value>
                <fullName>SDx,Dx</fullName>
            </value>
            <value>
                <fullName>SDx</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/BE__c.field-meta.xml
<CustomField>
    <fullName>BE__c</fullName>
    <description>Changed label from BE to BU and reactivating for Oct13</description>
    <inlineHelpText>Please select the Primary Business Unit for this opportunity.</inlineHelpText>
    <label>BU</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ASLS</fullName>
            </value>
            <value>
                <fullName>Dx</fullName>
            </value>
            <value>
                <fullName>GS</fullName>
            </value>
            <value>
                <fullName>INF</fullName>
            </value>
            <value>
                <fullName>LST</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SAI_Lead_Routing_Values__c/SAI_Lead_Routing_Values__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>For PDG Lead Routing</description>
    <label>SAI Lead Routing Values</label>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/SAI_Lead_Routing_Values__c/fields/SAI_Values__c.field-meta.xml
<CustomField>
    <fullName>SAI_Values__c</fullName>
    <label>SAI Values</label>
    <type>TextArea</type>
</CustomField>

Perkin-UAT/force-app/main/default/classes/DemoClass_Test.cls
@isTest
private class DemoClass_Test {    
    
    @testSetup
    static void setupData() {
        Opportunity opportunity_Obj = new Opportunity(name='test demo class opty',closedate= date.newinstance(2015,11,11),stagename='Prospecting',Solution_Area_of_Interest__c='Energy');
         insert opportunity_Obj;
       
        //Create Attachment
        Attachment attachment   = getAttachment(opportunity_Obj.Id, 'Quote Test Attachment', Blob.valueOf('Test Data')); 
        insert attachment;
        
    }    
    
    private testmethod static void testGetAttachments() {
        List<Opportunity> optyList = DemoClass.getAttachments();
        Attachment attachment   =  [SELECT Id FROM Attachment LIMIT 1];
        List<Attachment> attachmentList = DemoClass.getOppAttachments(attachment.Id);
        System.assertEquals(1, attachmentList.size());        
    }
    
    private testmethod static void testUtility() {
        SAI_Lead_Routing_Values__c cc =new SAI_Lead_Routing_Values__c();
        cc.SAI_Values__c = 'Applied Genomics, Maternal Fetal Health, Newborn Screening';
        insert cc;
        Lead LeadRecord = new Lead();
        LeadRecord.FirstName = 'TestUser: ';
        LeadRecord.LastName  = 'Class: ';
        LeadRecord.Title     =  'UnitTest';
        LeadRecord.Street = '225 Blvd';
        LeadRecord.City  = 'Montgomery';                
        LeadRecord.Status = 'Open';
        LeadRecord.Country = 'US';  
        LeadRecord.Company = 'Test';
        LeadRecord.Email = 'usertest-class-@test.com';
        //LeadRecord.BE__c = 'Dx';
        test.startTest();
        insert LeadRecord;
        Utility_Informatics.assignLeads_Informatics(new List<Id>{LeadRecord.Id} );
        test.stopTest();
        
        
    }
    
    private static Attachment getAttachment(Id recId, String name, Blob b) {        
        Attachment attachment = new Attachment();
        attachment.ParentId   = recId;
        attachment.Name       = name;
        attachment.Body       = b;        
        return attachment;        
    }
    
}