Perkin-UAT/force-app/main/default/objects/B2B_Product_Related_Resources__c/B2B_Product_Related_Resources__c.object-meta.xml
<CustomObject>
    <label>B2B Product Related Resources</label>
    <nameField>
        <displayFormat>BPRR-{0000000}</displayFormat>
        <label>B2B Product Related Resources Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B2B Product Related Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/B2B_Product_Related_Resources__c/fields/B2B_Product_Resources__c.field-meta.xml
<CustomField>
    <fullName>B2B_Product_Resources__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>B2B Product Resources</label>
    <referenceTo>B2B_Product_Resources__c</referenceTo>
    <relationshipLabel>B2B Product Related Resources</relationshipLabel>
    <relationshipName>B2B_Product_Related_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Product_Related_Resources__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>B2B Product Related Resources</relationshipLabel>
    <relationshipName>B2B_Product_Related_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Product_Resources__c/B2B_Product_Resources__c.object-meta.xml
<CustomObject>
    <label>B2B Product Resources</label>
    <nameField>
        <displayFormat>BPR-{0000000}</displayFormat>
        <label>B2B Product Resources Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B2B Product Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/B2B_Product_Resources__c/fields/Link_ID__c.field-meta.xml
<CustomField>
    <fullName>Link_ID__c</fullName>
    <label>Link ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Product_Resources__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>B2B Product Resources</relationshipLabel>
    <relationshipName>B2B_Product_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Product_Resources__c/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <label>Resource Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PI - Product Image</fullName>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
            <value>
                <fullName>Webinar</fullName>
            </value>
            <value>
                <fullName>All Resources</fullName>
            </value>
            <value>
                <fullName>Infographic</fullName>
            </value>
            <value>
                <fullName>Brief</fullName>
            </value>
            <value>
                <fullName>Blog</fullName>
            </value>
            <value>
                <fullName>Technical Note</fullName>
            </value>
            <value>
                <fullName>Case Study</fullName>
            </value>
            <value>
                <fullName>Application Note</fullName>
            </value>
            <value>
                <fullName>Calendar</fullName>
            </value>
            <value>
                <fullName>Article</fullName>
            </value>
            <value>
                <fullName>Link</fullName>
            </value>
            <value>
                <fullName>Brochure</fullName>
            </value>
            <value>
                <fullName>White Paper</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Video Talk</fullName>
            </value>
            <value>
                <fullName>Application Brief</fullName>
            </value>
            <value>
                <fullName>Category</fullName>
            </value>
            <value>
                <fullName>Webinar Resources</fullName>
            </value>
            <value>
                <fullName>Case Chemicals Testing Solutions</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Webinars</fullName>
            </value>
            <value>
                <fullName>Whitepaper</fullName>
            </value>
            <value>
                <fullName>Flyer</fullName>
            </value>
            <value>
                <fullName>Podcast</fullName>
            </value>
            <value>
                <fullName>Workflow Solutions</fullName>
            </value>
            <value>
                <fullName>FAQ</fullName>
            </value>
            <value>
                <fullName>Slideshow</fullName>
            </value>
            <value>
                <fullName>Chart &amp; Summary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Custom_Exception__c/Custom_Exception__c.object-meta.xml
<CustomObject>
    <description>To Get the Batch_EnableRenewalQuotedOnContracts Class  Exception logs in this Custom object</description>
    <label>Custom Exception</label>
    <nameField>
        <label>Custom Exception Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/Custom_Exception__c/fields/Exception_Messages__c.field-meta.xml
<CustomField>
    <fullName>Exception_Messages__c</fullName>
    <label>Exception Messages</label>
    <length>131071</length>
    <type>LongTextArea</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/B2B_Default_image__c.field-meta.xml
<CustomField>
    <fullName>B2B_Default_image__c</fullName>
    <label>Default image</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/B2B_Links__c.field-meta.xml
<CustomField>
    <fullName>B2B_Links__c</fullName>
    <label>B2B Links</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/B2B_Product_Resources_Links__c.field-meta.xml
<CustomField>
    <fullName>B2B_Product_Resources_Links__c</fullName>
    <label>Product Resources (Links)</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/B2B_Product_Resources_PDFs__c.field-meta.xml
<CustomField>
    <fullName>B2B_Product_Resources_PDFs__c</fullName>
    <label>Product Resources (PDFs)</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/B2B_Product_Resources_Videos__c.field-meta.xml
<CustomField>
    <fullName>B2B_Product_Resources_Videos__c</fullName>
    <label>Product Resources (Videos)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/B2B_Videos__c.field-meta.xml
<CustomField>
    <fullName>B2B_Videos__c</fullName>
    <label>B2B Videos</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/Is_B2B_Product__c.field-meta.xml
<CustomField>
    <fullName>Is_B2B_Product__c</fullName>
    <formula>NOT(ISNULL( B2B_Sales_Org_And_Sales_Status__c ))</formula>
    <label>Is B2B Product?</label>
    <type>Checkbox</type>
</CustomField>

Perkin-UAT/force-app/main/default/classes/B2B_LinkProductsWithResourcesBatch.cls
public with sharing class B2B_LinkProductsWithResourcesBatch implements Database.Batchable<sObject>{

    public final String QueryStr;

    //SELECT B2B_Links__c, B2B_Product_Resources_Links__c, B2B_Default_image__c, B2B_Product_Resources_PDFs__c, B2B_Product_Resources_Videos__c, B2B_Videos__c FROM product2 where Is_B2B_Product__c = true
    public B2B_LinkProductsWithResourcesBatch( String query ) {
        QueryStr = query;
        System.debug('B2B_LinkProductsWithResourcesBatch Query-- '+QueryStr);
    }

    public Database.QueryLocator start(Database.BatchableContext bc){
        System.debug('B2B_LinkProductsWithResourcesBatch start Query-- '+QueryStr);
        return Database.getQueryLocator( QueryStr );
    }

    public void execute(Database.BatchableContext bc, List<Product2> scope){
        try {
            // Create a map to store Product ID → Combined List of Values
            Map<Id, List<String>> productToResourcesMap = new Map<Id, List<String>>();
            List<B2B_Product_Related_Resources__c> productRelatedResourcesToInsert = new List<B2B_Product_Related_Resources__c>();
            for (Product2 product : scope) {
                List<String> combinedResources = new List<String>();

                if (String.isNotBlank(product.B2B_Product_Resources_PDFs__c)) {
                    combinedResources.addAll(product.B2B_Product_Resources_PDFs__c.split(','));
                }

                if (String.isNotBlank(product.B2B_Product_Resources_Videos__c)) {
                    combinedResources.addAll(product.B2B_Product_Resources_Videos__c.split(','));
                }

                if (String.isNotBlank(product.B2B_Links__c)) {
                    combinedResources.addAll(product.B2B_Links__c.split(','));
                }

                if (String.isNotBlank(product.B2B_Product_Resources_Links__c)) {
                    combinedResources.addAll(product.B2B_Product_Resources_Links__c.split(','));
                }

                if (String.isNotBlank(product.B2B_Default_image__c)) {
                    combinedResources.addAll(product.B2B_Default_image__c.split(','));
                }

                if (String.isNotBlank(product.B2B_Videos__c)) {
                    combinedResources.addAll(product.B2B_Videos__c.split(','));
                }

                // Store the combined list in the map
                productToResourcesMap.put(product.Id, combinedResources);
            }

            // for (Id productId : productToResourcesMap.keySet()) {
            //     System.debug('Product ID: ' + productId + ' → Combined Resources: ' + productToResourcesMap.get(productId));
            // }

            List<B2B_Product_Resources__c> resourceRecords = [SELECT Id, Link_ID__c, Active__c FROM B2B_Product_Resources__c WHERE Link_ID__c != '' AND Resource_Type__c != 'PI - Product Image' AND Active__c = true];

            for (Id productId : productToResourcesMap.keySet()) {
                List<String> combinedResources = productToResourcesMap.get(productId);
            
                for (B2B_Product_Resources__c resource : resourceRecords) {
                    // String linkIdStr = String.valueOf(resource.Link_ID__c);
                    
                    if (combinedResources.contains(resource.Link_ID__c.trim())) {
                        // Link the Product to the Resource
                        // resource.Product__c = productId;
                        B2B_Product_Related_Resources__c productRelatedResources = new B2B_Product_Related_Resources__c();
                        productRelatedResources.Product__c = productId;
                        productRelatedResources.B2B_Product_Resources__c = resource.Id;
                        productRelatedResourcesToInsert.add(productRelatedResources);
                    }
                }
            }

            if (!productRelatedResourcesToInsert.isEmpty()) {
                // insert productRelatedResourcesToInsert;
                Database.insert(productRelatedResourcesToInsert, false);
                System.debug('Inserted Records: ' + productRelatedResourcesToInsert);
            } else {
                System.debug('No records found for insert.');
                createCustomExceptionRecord('No records found for insert.');
            }

        } catch (Exception e) {
            System.debug('Exception-- '+e.getMessage());
            createCustomExceptionRecord(e.getMessage());
        }
    }
    
    public void finish(Database.BatchableContext bc){

    }

    public void createCustomExceptionRecord(String message){
        Custom_Exception__c customException = new Custom_Exception__c();
        customException.Name = 'B2B_LinkProductsWithResourcesBatch Exception';
        customException.Exception_Messages__c = message;
        insert customException;
    }
}