Perkin-UAT/force-app/main/default/objects/B2B_Product_Related_Resources__c/B2B_Product_Related_Resources__c.object-meta.xml
<CustomObject>
    <label>B2B Product Related Resources</label>
    <nameField>
        <displayFormat>BPRR-{0000000}</displayFormat>
        <label>B2B Product Related Resources Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B2B Product Related Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/B2B_Product_Related_Resources__c/fields/B2B_Product_Resources__c.field-meta.xml
<CustomField>
    <fullName>B2B_Product_Resources__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>B2B Product Resources</label>
    <referenceTo>B2B_Product_Resources__c</referenceTo>
    <relationshipLabel>B2B Product Related Resources</relationshipLabel>
    <relationshipName>B2B_Product_Related_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Product_Related_Resources__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>B2B Product Related Resources</relationshipLabel>
    <relationshipName>B2B_Product_Related_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Product_Resources__c/B2B_Product_Resources__c.object-meta.xml
<CustomObject>
    <label>B2B Product Resources</label>
    <nameField>
        <displayFormat>BPR-{0000000}</displayFormat>
        <label>B2B Product Resources Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B2B Product Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/B2B_Product_Resources__c/fields/PDF_Name__c.field-meta.xml
<CustomField>
    <fullName>PDF_Name__c</fullName>
    <label>PDF Name</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Product_Resources__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>B2B Product Resources</relationshipLabel>
    <relationshipName>B2B_Product_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Product_Resources__c/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <label>Resource Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PI - Product Image</fullName>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
            <value>
                <fullName>Webinar</fullName>
            </value>
            <value>
                <fullName>All Resources</fullName>
            </value>
            <value>
                <fullName>Infographic</fullName>
            </value>
            <value>
                <fullName>Brief</fullName>
            </value>
            <value>
                <fullName>Blog</fullName>
            </value>
            <value>
                <fullName>Technical Note</fullName>
            </value>
            <value>
                <fullName>Case Study</fullName>
            </value>
            <value>
                <fullName>Application Note</fullName>
            </value>
            <value>
                <fullName>Calendar</fullName>
            </value>
            <value>
                <fullName>Article</fullName>
            </value>
            <value>
                <fullName>Link</fullName>
            </value>
            <value>
                <fullName>Brochure</fullName>
            </value>
            <value>
                <fullName>White Paper</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Video Talk</fullName>
            </value>
            <value>
                <fullName>Application Brief</fullName>
            </value>
            <value>
                <fullName>Category</fullName>
            </value>
            <value>
                <fullName>Webinar Resources</fullName>
            </value>
            <value>
                <fullName>Case Chemicals Testing Solutions</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Webinars</fullName>
            </value>
            <value>
                <fullName>Whitepaper</fullName>
            </value>
            <value>
                <fullName>Flyer</fullName>
            </value>
            <value>
                <fullName>Podcast</fullName>
            </value>
            <value>
                <fullName>Workflow Solutions</fullName>
            </value>
            <value>
                <fullName>FAQ</fullName>
            </value>
            <value>
                <fullName>Slideshow</fullName>
            </value>
            <value>
                <fullName>Chart &amp; Summary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/B2B_Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>B2B_Brand_Name__c</fullName>
    <description>Used to select the brand name for products. Perk-75</description>
    <label>Brand Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AssureID</fullName>
            </value>
            <value>
                <fullName>BTO Orange Injection Port Septa</fullName>
            </value>
            <value>
                <fullName>Clarus</fullName>
            </value>
            <value>
                <fullName>Green Injection Port Septa</fullName>
            </value>
            <value>
                <fullName>LAMBDA</fullName>
            </value>
            <value>
                <fullName>Lumina</fullName>
            </value>
            <value>
                <fullName>NexION</fullName>
            </value>
            <value>
                <fullName>Pecosphere</fullName>
            </value>
            <value>
                <fullName>PerkinElmer Advanced Green</fullName>
            </value>
            <value>
                <fullName>PinAAcle</fullName>
            </value>
            <value>
                <fullName>PureView™</fullName>
            </value>
            <value>
                <fullName>SPB</fullName>
            </value>
            <value>
                <fullName>Spectrum Two</fullName>
            </value>
            <value>
                <fullName>Spheri-10</fullName>
            </value>
            <value>
                <fullName>Spheri-5</fullName>
            </value>
            <value>
                <fullName>Torion®</fullName>
            </value>
            <value>
                <fullName>TurboMatrix</fullName>
            </value>
            <value>
                <fullName>Pyris</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/B2B_Product_Group__c.field-meta.xml
<CustomField>
    <fullName>B2B_Product_Group__c</fullName>
    <description>Used to select groups for products. Perk-75</description>
    <label>Product Group</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AA Compressors</fullName>
            </value>
            <value>
                <fullName>Application Pack</fullName>
            </value>
            <value>
                <fullName>Blowers and Vents</fullName>
            </value>
            <value>
                <fullName>Burner Head Replacement Parts</fullName>
            </value>
            <value>
                <fullName>Caps/Septa</fullName>
            </value>
            <value>
                <fullName>Cartridge Columns</fullName>
            </value>
            <value>
                <fullName>Cell Holders &amp; Changers</fullName>
            </value>
            <value>
                <fullName>Chromatography</fullName>
            </value>
            <value>
                <fullName>Crimpers</fullName>
            </value>
            <value>
                <fullName>Decapper</fullName>
            </value>
            <value>
                <fullName>Detectors &amp; Kits</fullName>
            </value>
            <value>
                <fullName>Falling Number, AM, IM 8800</fullName>
            </value>
            <value>
                <fullName>Fiber Optic Accessories</fullName>
            </value>
            <value>
                <fullName>Filter Disks</fullName>
            </value>
            <value>
                <fullName>Fittings</fullName>
            </value>
            <value>
                <fullName>Flow Injection Tubing</fullName>
            </value>
            <value>
                <fullName>Flow-Through Cells</fullName>
            </value>
            <value>
                <fullName>Gas/Liquid Separators and Replacement Parts</fullName>
            </value>
            <value>
                <fullName>GC Compressors</fullName>
            </value>
            <value>
                <fullName>Hollow Cathode Lamp HCL</fullName>
            </value>
            <value>
                <fullName>Hydrogen Generators</fullName>
            </value>
            <value>
                <fullName>ICP-OES Compressors</fullName>
            </value>
            <value>
                <fullName>Injection Port Septa</fullName>
            </value>
            <value>
                <fullName>Kits</fullName>
            </value>
            <value>
                <fullName>Liner o-ring</fullName>
            </value>
            <value>
                <fullName>Mass Spectral Library</fullName>
            </value>
            <value>
                <fullName>Nitrogen Generators</fullName>
            </value>
            <value>
                <fullName>O-Rings</fullName>
            </value>
            <value>
                <fullName>Pads</fullName>
            </value>
            <value>
                <fullName>Regulators</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/classes/B2B_ProductSpecificationControllerTest.cls
/**
 * @description       : 
 * @author            : Swati Chilap
 * @group             : 
 * @last modified on  : 11-20-2025
 * @last modified by  : Swati Chilap
**/
@isTest
public with sharing class B2B_ProductSpecificationControllerTest {
  @TestSetup
  static void createTestData() {
    Product2 testProduct = new Product2();
    testProduct.Name = 'Test Product';
    testProduct.isActive = true;
    testProduct.B2B_Product_Group__c = 'Test Group';
    testProduct.B2B_Brand_Name__c = 'Test Brand';
    insert testProduct;

    // Create test Product Resources
    B2B_Product_Resources__c resource1 = new B2B_Product_Resources__c(
      Resource_Type__c = 'Application Brief',
      PDF_Name__c = 'Brief1.pdf',
      Product__c = testProduct.Id,
      Active__c = true
    );
    B2B_Product_Resources__c resource2 = new B2B_Product_Resources__c(
      Resource_Type__c = 'Application Brief',
      PDF_Name__c = 'Brief2.pdf',
      Product__c = testProduct.Id,
      Active__c = true
    );
    B2B_Product_Resources__c resource3 = new B2B_Product_Resources__c(
      Resource_Type__c = 'Application Note',
      PDF_Name__c = 'Note1.pdf',
      Product__c = testProduct.Id,
      Active__c = true
    );
    B2B_Product_Resources__c resource4 = new B2B_Product_Resources__c(
      Resource_Type__c = 'Brief',
      PDF_Name__c = 'Brief3.pdf',
      Product__c = testProduct.Id,
      Active__c = true
    );
    insert new List<B2B_Product_Resources__c>{
      resource1,
      resource2,
      resource3,
      resource4
    };

    // Create junction object records to link Product and Resources
    B2B_Product_Related_Resources__c rel1 = new B2B_Product_Related_Resources__c(
      Product__c = testProduct.Id,
      B2B_Product_Resources__c = resource1.Id
    );
    B2B_Product_Related_Resources__c rel2 = new B2B_Product_Related_Resources__c(
      Product__c = testProduct.Id,
      B2B_Product_Resources__c = resource2.Id
    );
    B2B_Product_Related_Resources__c rel3 = new B2B_Product_Related_Resources__c(
      Product__c = testProduct.Id,
      B2B_Product_Resources__c = resource3.Id
    );
    B2B_Product_Related_Resources__c rel4 = new B2B_Product_Related_Resources__c(
      Product__c = testProduct.Id,
      B2B_Product_Resources__c = resource4.Id
    );
    insert new List<B2B_Product_Related_Resources__c>{ rel1, rel2, rel3, rel4 };
  }

  @isTest
  static void getProductWithFieldSetTest() {
    Product2 product = [
      SELECT Id, Name, B2B_Product_Group__c, B2B_Brand_Name__c
      FROM Product2
      LIMIT 1
    ];
    Map<String, String> inputMap = new Map<String, String>();
    inputMap.put('Name', product.Name);
    inputMap.put('B2B_Product_Group__c', product.B2B_Product_Group__c);
    inputMap.put('B2B_Brand_Name__c', product.B2B_Brand_Name__c);

    Map<String, Object> mapParams = new Map<String, Object>{
      'fields' => inputMap
    };

    Test.startTest();
    Map<String, Object> result = B2B_ProductSpecificationController.getProductWithFieldSet(
      mapParams
    );
    Test.stopTest();
    System.assertEquals(true, result.get('isSuccess'));
  }

  @isTest
  static void getProductWithFieldSetNegativeTest() {
    Product2 product = [SELECT Id FROM Product2 LIMIT 1];
    Map<String, String> inputMap = new Map<String, String>();
    List<Map<String, String>> listOfMap = new List<Map<String, String>>();

    Map<String, Object> mapParams = new Map<String, Object>{
      'fields' => listOfMap
    };

    Test.startTest();
    Map<String, Object> result = B2B_ProductSpecificationController.getProductWithFieldSet(
      mapParams
    );
    Test.stopTest();
    System.assertNotEquals(true, result.get('isSuccess'));
  }

  @IsTest
  static void testGetProductResourcesByProductId() {
    Product2 testProduct = [SELECT Id FROM Product2 LIMIT 1];

    Test.startTest();
    Map<String, Object> result = B2B_ProductSpecificationController.getProductResourcesByProductId(
      testProduct.Id
    );
    Test.stopTest();
    System.assertEquals(true, result.get('isSuccess'));
  }
    
  @IsTest
  static void testGetProductResourcesByProductIdNegavtive() {
    Product2 testProduct = [SELECT Id FROM Product2 LIMIT 1];

    Test.startTest();
    Map<String, Object> result = B2B_ProductSpecificationController.getProductResourcesByProductId(
      null
    );
    Test.stopTest();
    System.assertEquals(true, result.get('isSuccess'));
  }
}