Perkin-UAT/force-app/main/default/objects/B2B_Product_Related_Resources__c/B2B_Product_Related_Resources__c.object-meta.xml
<CustomObject>
    <label>B2B Product Related Resources</label>
    <nameField>
        <displayFormat>BPRR-{0000000}</displayFormat>
        <label>B2B Product Related Resources Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B2B Product Related Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/B2B_Product_Related_Resources__c/fields/B2B_Product_Resources__c.field-meta.xml
<CustomField>
    <fullName>B2B_Product_Resources__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>B2B Product Resources</label>
    <referenceTo>B2B_Product_Resources__c</referenceTo>
    <relationshipLabel>B2B Product Related Resources</relationshipLabel>
    <relationshipName>B2B_Product_Related_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Product_Related_Resources__c/fields/B2B_Sequence__c.field-meta.xml
<CustomField>
    <fullName>B2B_Sequence__c</fullName>
    <label>B2B Sequence</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Product_Related_Resources__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>B2B Product Related Resources</relationshipLabel>
    <relationshipName>B2B_Product_Related_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Product_Resources__c/B2B_Product_Resources__c.object-meta.xml
<CustomObject>
    <label>B2B Product Resources</label>
    <nameField>
        <displayFormat>BPR-{0000000}</displayFormat>
        <label>B2B Product Resources Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B2B Product Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/B2B_Product_Resources__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>B2B Product Resources</relationshipLabel>
    <relationshipName>B2B_Product_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Product_Resources__c/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <label>Resource Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PI - Product Image</fullName>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
            <value>
                <fullName>Webinar</fullName>
            </value>
            <value>
                <fullName>All Resources</fullName>
            </value>
            <value>
                <fullName>Infographic</fullName>
            </value>
            <value>
                <fullName>Brief</fullName>
            </value>
            <value>
                <fullName>Blog</fullName>
            </value>
            <value>
                <fullName>Technical Note</fullName>
            </value>
            <value>
                <fullName>Case Study</fullName>
            </value>
            <value>
                <fullName>Application Note</fullName>
            </value>
            <value>
                <fullName>Calendar</fullName>
            </value>
            <value>
                <fullName>Article</fullName>
            </value>
            <value>
                <fullName>Link</fullName>
            </value>
            <value>
                <fullName>Brochure</fullName>
            </value>
            <value>
                <fullName>White Paper</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Video Talk</fullName>
            </value>
            <value>
                <fullName>Application Brief</fullName>
            </value>
            <value>
                <fullName>Category</fullName>
            </value>
            <value>
                <fullName>Webinar Resources</fullName>
            </value>
            <value>
                <fullName>Case Chemicals Testing Solutions</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Webinars</fullName>
            </value>
            <value>
                <fullName>Whitepaper</fullName>
            </value>
            <value>
                <fullName>Flyer</fullName>
            </value>
            <value>
                <fullName>Podcast</fullName>
            </value>
            <value>
                <fullName>Workflow Solutions</fullName>
            </value>
            <value>
                <fullName>FAQ</fullName>
            </value>
            <value>
                <fullName>Slideshow</fullName>
            </value>
            <value>
                <fullName>Chart &amp; Summary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Product_Resources__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

Perkin-UAT/force-app/main/default/classes/B2BProductResourceSortBatchTest.cls
/**
 * @description       : 
 * @author            : Swati Chilap
 * @group             : 
 * @last modified on  : 11-20-2025
 * @last modified by  : Swati Chilap
**/
@IsTest
public class B2BProductResourceSortBatchTest {

    @TestSetup
    static void setupData() {

        Product2 p1 = B2B_TestDataFactory.createProduct('Product A',true);
        Product2 p2 = B2B_TestDataFactory.createProduct('Product B',true);

        List<B2B_Product_Resources__c> resources = new List<B2B_Product_Resources__c>{
            new B2B_Product_Resources__c(
                Active__c = true,
                Resource_Type__c = 'Article',
                Title__c = 'Alpha'
            ),
            new B2B_Product_Resources__c(
                Active__c = true,
                Resource_Type__c = 'Case Study',
                Title__c = 'Beta'
            ),
            new B2B_Product_Resources__c(
                Active__c = true,
                Resource_Type__c = 'Article',
                Title__c = 'Gamma'
            )
        };
        insert resources;

        // Create junction records
        List<B2B_Product_Related_Resources__c> junctions = new List<B2B_Product_Related_Resources__c>{
            new B2B_Product_Related_Resources__c(
                Product__c = p1.Id,
                B2B_Product_Resources__c = resources[1].Id 
            ),
            new B2B_Product_Related_Resources__c(
                Product__c = p1.Id,
                B2B_Product_Resources__c = resources[0].Id 
            ),
            new B2B_Product_Related_Resources__c(
                Product__c = p2.Id,
                B2B_Product_Resources__c = resources[2].Id 
            )
        };
        insert junctions;
    }

    @IsTest
    static void testBatchSorting() {

        String q = 'SELECT Id, Product__c, B2B_Product_Resources__c, B2B_Sequence__c ' +
           'FROM B2B_Product_Related_Resources__c ' +
           'WHERE B2B_Product_Resources__r.Active__c = TRUE ' +
           'ORDER BY Product__c, B2B_Product_Resources__r.Resource_Type__c';

        // Run Batch
        Test.startTest();
        Database.executeBatch(new B2BProductResourceSortBatch(q), 200);
        Test.stopTest();

        // Query updated junctions
        List<B2B_Product_Related_Resources__c> updated = [
            SELECT Id,
                   Product__c,
                   B2B_Product_Resources__r.Resource_Type__c,
                   B2B_Sequence__c
            FROM B2B_Product_Related_Resources__c
            ORDER BY Product__c, B2B_Sequence__c
        ];

        System.debug('Sorted Junctions: ' + updated);

        System.assertEquals(100, updated[0].B2B_Sequence__c, 'First sort should be 100');
        System.assertEquals(200, updated[1].B2B_Sequence__c, 'Second sort should be 200');
        System.assertEquals(100, updated[2].B2B_Sequence__c, 'Different product starts at 100');
    }
}