Perkin-UAT/force-app/main/default/objects/B2B_Subscription_Items__c/B2B_Subscription_Items__c.object-meta.xml
<CustomObject>
    <label>B2B Subscription Items</label>
    <nameField>
        <displayFormat>SubItem# {00000}</displayFormat>
        <label>B2B Subscriptions tems</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B2B Subscription Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/B2B_Subscription_Items__c/fields/B2B_Product__c.field-meta.xml
<CustomField>
    <fullName>B2B_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>B2B Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>B2B Subscription Items</relationshipLabel>
    <relationshipName>B2B_Subscription_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Subscription_Items__c/fields/B2B_Subscriptions__c.field-meta.xml
<CustomField>
    <fullName>B2B_Subscriptions__c</fullName>
    <label>B2B Subscriptions</label>
    <referenceTo>B2B_Subscriptions__c</referenceTo>
    <relationshipLabel>B2B Subscription Items</relationshipLabel>
    <relationshipName>B2B_Subscription_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Subscription_Items__c/fields/B2B_Total_Price__c.field-meta.xml
<CustomField>
    <fullName>B2B_Total_Price__c</fullName>
    <formula>B2B_Quantity__c *  B2B_Unit_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>B2B Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Subscription_Items__c/fields/B2B_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>B2B_Unit_Price__c</fullName>
    <label>B2B Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Subscriptions__c/B2B_Subscriptions__c.object-meta.xml
<CustomObject>
    <label>B2B Subscriptions</label>
    <nameField>
        <displayFormat>Sub# {00000}</displayFormat>
        <label>B2B Subscriptions</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B2B Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/B2B_Subscriptions__c/fields/B2B_Contact__c.field-meta.xml
<CustomField>
    <fullName>B2B_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>B2B Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>B2B Subscriptions</relationshipLabel>
    <relationshipName>B2B_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Subscriptions__c/fields/B2B_Next_Billing_Date__c.field-meta.xml
<CustomField>
    <fullName>B2B_Next_Billing_Date__c</fullName>
    <label>B2B Next Billing Date</label>
    <type>Date</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Subscriptions__c/fields/B2B_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>B2B_Total_Amount__c</fullName>
    <label>B2B Total Amount</label>
    <summarizedField>B2B_Subscription_Items__c.B2B_Total_Price__c</summarizedField>
    <summaryForeignKey>B2B_Subscription_Items__c.B2B_Subscriptions__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Subscriptions__c/fields/Subscription_Name__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Name__c</fullName>
    <label>Subscription Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Order/fields/B2B_Subscriptions__c.field-meta.xml
<CustomField>
    <fullName>B2B_Subscriptions__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>B2B Subscriptions</label>
    <referenceTo>B2B_Subscriptions__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/B2B_Part_Number__c.field-meta.xml
<CustomField>
    <fullName>B2B_Part_Number__c</fullName>
    <label>Part Number</label>
    <length>255</length>
    <translateData>true</translateData>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/B2B_Quantity__c.field-meta.xml
<CustomField>
    <fullName>B2B_Quantity__c</fullName>
    <label>B2B Quantity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/classes/B2BSubscriptionHtmlGenerator.cls
//Test class - B2BSubscriptionReminderEmailTest
public class B2BSubscriptionHtmlGenerator {
public static String getSubscriptionDetails(B2B_Subscriptions__c subscription){
        String subDetail = 'Hi '+subscription.B2B_Contact__r.FirstName+' '+ subscription.B2B_Contact__r.LastName+',<br/>'+
            '<div style="padding-top: .25rem;">Your Next Subscription Order is coming soon<br/></div>'+
            '<div style="padding-top: .25rem;">Please find below details of your B2B Subscription.<br/></div>'+
            '<div style="padding-top: .25rem;"><b>Subscription Name</b> - '+subscription.Subscription_Name__c+ '<br/></div>'+
            '<div style="padding-top: .25rem;"><b>Order Date</b> -  '+subscription.B2B_Next_Billing_Date__c.format()+'.<br/></div>';      
        return subDetail;
    }
    
    public static String getItemRow(B2B_Subscription_Items__c subscriptionitem){
        String itemDetail = '<tr><td style="width:50%;padding: 8px; text-align: left;" width:"40%">'+
            subscriptionitem.B2B_Product__r.Name +'<br/>'+
            subscriptionitem.B2B_Product__r.B2B_Part_Number__c +
            '</td><td style="width:10%;padding: 8px; text-align: center;" width:"20%">'+
            subscriptionitem.B2B_Quantity__c +
            '</td><td style="width:20%;padding: 8px; text-align: center;" width:"20%">'+
            subscriptionitem.B2B_Unit_Price__c +'&nbsp;'+subscriptionitem.CurrencyIsoCode +
            '</td><td style="width:20%;padding: 8px; text-align: center;" width:"10%">'+
            subscriptionitem.B2B_Total_Price__c +'&nbsp;'+subscriptionitem.CurrencyIsoCode +
            '</td></tr>';
        return itemDetail;
    }
    public static String getSummary(B2B_Subscriptions__c subscription){
        String summary = '<table width="100%"><tr><td style="width:50%;padding: 8px; text-align: left;"></td>'+
            '<td style="width:10%;padding: 8px; text-align: left;">'+
            '</td><td style="width:20%;padding: 8px; text-align: center;font-weight: bold; background-color: #f2f2f2;">'+
            'Grand Total</td>'+
            '<td style="width:20%;padding: 8px; text-align: center;font-weight: bold; background-color: #f2f2f2;">'+
            subscription.B2B_Total_Amount__c+'&nbsp;'+subscription.CurrencyIsoCode+
            '</td></tr>'+
            '<tr><td style="width:50%;padding: 8px; text-align: left;"></td>'+
            '<td style="width:10%;padding: 8px; text-align: left;">'+
            '</td><td colspan ="2" style="width:40%;padding: 8px; text-align: center; background-color: #f2f2f2;">'+
            '*Note the Above amount is excluding Shipping & Tax</td>'+
            '</tr>'+
            '</table>';
        return summary;
    }
    
}