Perkin-UAT/force-app/main/default/objects/B2B_Subscription_Items__c/B2B_Subscription_Items__c.object-meta.xml
<CustomObject>
    <label>B2B Subscription Items</label>
    <nameField>
        <displayFormat>SubItem# {00000}</displayFormat>
        <label>B2B Subscriptions tems</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B2B Subscription Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/B2B_Subscription_Items__c/fields/B2B_Product__c.field-meta.xml
<CustomField>
    <fullName>B2B_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>B2B Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>B2B Subscription Items</relationshipLabel>
    <relationshipName>B2B_Subscription_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Subscription_Items__c/fields/B2B_Subscriptions__c.field-meta.xml
<CustomField>
    <fullName>B2B_Subscriptions__c</fullName>
    <label>B2B Subscriptions</label>
    <referenceTo>B2B_Subscriptions__c</referenceTo>
    <relationshipLabel>B2B Subscription Items</relationshipLabel>
    <relationshipName>B2B_Subscription_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Subscription_Items__c/fields/B2B_Total_Price__c.field-meta.xml
<CustomField>
    <fullName>B2B_Total_Price__c</fullName>
    <formula>B2B_Quantity__c *  B2B_Unit_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>B2B Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Subscription_Items__c/fields/B2B_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>B2B_Unit_Price__c</fullName>
    <label>B2B Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Subscriptions__c/B2B_Subscriptions__c.object-meta.xml
<CustomObject>
    <label>B2B Subscriptions</label>
    <nameField>
        <displayFormat>Sub# {00000}</displayFormat>
        <label>B2B Subscriptions</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B2B Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/B2B_Subscriptions__c/fields/B2B_Contact__c.field-meta.xml
<CustomField>
    <fullName>B2B_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>B2B Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>B2B Subscriptions</relationshipLabel>
    <relationshipName>B2B_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Subscriptions__c/fields/B2B_Next_Billing_Date__c.field-meta.xml
<CustomField>
    <fullName>B2B_Next_Billing_Date__c</fullName>
    <label>B2B Next Billing Date</label>
    <type>Date</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Subscriptions__c/fields/B2B_Status__c.field-meta.xml
<CustomField>
    <fullName>B2B_Status__c</fullName>
    <label>B2B Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Subscriptions__c/fields/B2B_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>B2B_Total_Amount__c</fullName>
    <label>B2B Total Amount</label>
    <summarizedField>B2B_Subscription_Items__c.B2B_Total_Price__c</summarizedField>
    <summaryForeignKey>B2B_Subscription_Items__c.B2B_Subscriptions__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Subscriptions__c/fields/Subscription_Name__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Name__c</fullName>
    <label>Subscription Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Custom_Exception__c/Custom_Exception__c.object-meta.xml
<CustomObject>
    <description>To Get the Batch_EnableRenewalQuotedOnContracts Class  Exception logs in this Custom object</description>
    <label>Custom Exception</label>
    <nameField>
        <label>Custom Exception Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/Custom_Exception__c/fields/B2B_Subscriptions__c.field-meta.xml
<CustomField>
    <fullName>B2B_Subscriptions__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>B2B Subscriptions</label>
    <referenceTo>B2B_Subscriptions__c</referenceTo>
    <relationshipLabel>Custom Exceptions</relationshipLabel>
    <relationshipName>Custom_Exceptions</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Custom_Exception__c/fields/Exception_Messages__c.field-meta.xml
<CustomField>
    <fullName>Exception_Messages__c</fullName>
    <label>Exception Messages</label>
    <length>131071</length>
    <type>LongTextArea</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Order/fields/B2B_Subscriptions__c.field-meta.xml
<CustomField>
    <fullName>B2B_Subscriptions__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>B2B Subscriptions</label>
    <referenceTo>B2B_Subscriptions__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/B2B_Part_Number__c.field-meta.xml
<CustomField>
    <fullName>B2B_Part_Number__c</fullName>
    <label>Part Number</label>
    <length>255</length>
    <translateData>true</translateData>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/B2B_Quantity__c.field-meta.xml
<CustomField>
    <fullName>B2B_Quantity__c</fullName>
    <label>B2B Quantity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/classes/B2BSubscriptionReminderEmail.cls
//Description - Send an Email notification to th customer for b2b subscription before 7 days the order is placed.
//Test class - B2BSubscriptionReminderEmailTest
public class B2BSubscriptionReminderEmail  implements Database.Batchable<sObject>,Schedulable{
    Set<Id> b2bSubscriptionIdSet = new Set<Id>();
    
    String query = '';
    public B2BSubscriptionReminderEmail(){}
    public B2BSubscriptionReminderEmail(String queryVal){
        this.query = queryVal;
    }
    public B2BSubscriptionReminderEmail(Set<Id> b2bSubscriptionIdSetVal){
        this.b2bSubscriptionIdSet = b2bSubscriptionIdSetVal;
    }
    //Schedule 's Execute method to call batch
    public void execute(SchedulableContext sc){
        //new B2BSubscriptionReminderEmail()
        Database.executeBatch(this,Integer.valueOf(Label.SubscriptionBatchSize));
    }
    
    /* Start of batch */
    public Iterable<sObject> start(Database.BatchableContext bc){
        Date nextBillingDate = System.today().addDays(Integer.valueOf(Label.ReminderDays));
        List<B2B_Subscriptions__c> b2bSubscriptionList = new List<B2B_Subscriptions__c>();
        // collect the batches of records or objects to be passed to execute
        // 00Xbc000001JimLEAS
        
        if(String.isBlank(query)){
            String baseQuery = 'SELECT Id,Subscription_Name__c,B2B_Status__c,B2B_Total_Amount__c,CurrencyIsoCode,'+
                'B2B_Next_Billing_Date__c,B2B_Contact__r.FirstName,B2B_Contact__r.LastName,'+
                'B2B_Contact__r.Email,(SELECT Id,B2B_Product__r.Name,'+
                'B2B_Product__r.B2B_Part_Number__c,B2B_Unit_Price__c, B2B_Quantity__c,B2B_Total_Price__c,CurrencyIsoCode FROM B2B_Subscription_Items__r)'+
                'FROM B2B_Subscriptions__c ';
            String whereClause = !b2bSubscriptionIdSet.isEmpty() ? ' WHERE Id IN: b2bSubscriptionIdSet ' :
            'WHERE B2B_Next_Billing_Date__c  =: nextBillingDate AND B2B_Contact__r.Email != null AND B2B_Status__c = \'Active\'';
            query = baseQuery + whereClause;
            
        }
        return Database.getQueryLocator(query);
    }
    
    /* Execute of batch */
    public void execute(Database.BatchableContext bc, List<B2B_Subscriptions__c> records){
        //try-catch
        try{
            processRecords(records);
        }catch(Exception e){
            Custom_Exception__c exc = new Custom_Exception__c();
            exc.Name = 'B2BSubscriptionReminderEmail Exceptions';
            exc.Exception_Messages__c =  e.getMessage();
            exc.Exception_Type__c = e.getTypeName();
            insert exc;
        }
        
    }
    
    public void finish(Database.BatchableContext bc){
        // execute any post-processing operations
    }
    
    private static void processRecords(List<B2B_Subscriptions__c> records){
        
        EmailTemplate emailtemplate = [SELECT Id,HTMLValue,Subject
                                       FROM EMailTemplate
                                       WHERE DeveloperName = 'B2B_Subscription_Reminder_Email'];
        List<Messaging.SingleEmailMessage> emailList = new List<Messaging.SingleEmailMessage>();
        List<OrgWideEmailAddress> orgWideEmailAddressList = [SELECT Id FROM OrgWideEmailAddress 
                                                             WHERE Address =: Label.SupportAdminEmailAddress];
        if(emailtemplate != null){
            //sunscriptionDetails
            for(B2B_Subscriptions__c subscription : records){
                //construct html
                String htmlValue = emailtemplate.htmlValue;
                htmlValue = htmlValue.replace('{LogoUrl}',Label.PerkinElmer_Logo_Url);
                htmlValue = htmlValue.replace('{B2B_PerkinElmer}',Label.B2B_PerkinElmer);
                htmlValue = htmlValue.replace('{sunscriptionDetails}',B2BSubscriptionHtmlGenerator.getSubscriptionDetails(subscription));
                htmlValue = htmlValue.replace('{summaryTable}',B2BSubscriptionHtmlGenerator.getSummary(subscription));
                String itemHtml = '';
                
                //iterate on lineitems
                for(B2B_Subscription_Items__c subscriptionItem : subscription.B2B_Subscription_Items__r){
                    itemHtml += B2BSubscriptionHtmlGenerator.getItemRow(subscriptionItem);
                }
                htmlValue = htmlValue.replace('{table}',itemHtml);
                
                //prepare mail instance
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();            
                mail.setHtmlBody(htmlValue);
                mail.setSubject(emailtemplate.Subject);
                if(!orgWideEmailAddressList.isEmpty()){
                    mail.setOrgWideEmailAddressId(orgWideEmailAddressList[0].Id);
                }
                mail.setToAddresses(new List<String>{subscription.B2B_Contact__r.Email});            
                emailList.add(mail);
                
                
            }
            if (!emailList.isEmpty()){
                //send mails
                Messaging.SendEmailResult[] results = Messaging.sendEmail(emailList, false);
                System.debug('results ::' + results);
                for (Messaging.SendEmailResult result : results){
                    if (!result.isSuccess()){
                        system.debug('result ' + result);
                    }
                }
            }
            
        }
    }
}