Perkin-UAT/force-app/main/default/objects/Contract/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <label>Warr/Renew/Restart</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Initial</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Restart</fullName>
            </value>
            <value>
                <fullName>Warranty</fullName>
                <default>true</default>
                <label>Warranty</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Contract/recordTypes/ServiceContract.recordType-meta.xml
<RecordType>
    <fullName>ServiceContract</fullName>
    <active>true</active>
    <description>Service contract for installed equipment</description>
    <label>Service Contract</label>
</RecordType>

Perkin-UAT/force-app/main/default/objects/ServiceContract/fields/Clone_From_ID__c.field-meta.xml
<CustomField>
    <fullName>Clone_From_ID__c</fullName>
    <description>A hidden field to be used with Clone with Line Items button.</description>
    <label>Clone From ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/ServiceContract/fields/Clone_Line_Items__c.field-meta.xml
<CustomField>
    <fullName>Clone_Line_Items__c</fullName>
    <defaultValue>false</defaultValue>
    <description>A hidden field to be used with Clone with Line Items button.</description>
    <label>Clone Line Items</label>
    <type>Checkbox</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/ServiceContract/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <description>LST Service Contract sales, measure Warranty. Renewals, New Business</description>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Warranty Conversion</fullName>
            </value>
            <value>
                <fullName>Contract Renewal</fullName>
            </value>
            <value>
                <fullName>New Contract</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/classes/ServiceContractButton.cls
/*
** Class:  ServiceContractButton WebService
** Created by OpFocus on 05/01/2012
** Description: ServiceContractButton is called from a button on Service Contract 
**              to clone the record and copy the products
*/   
global with sharing class ServiceContractButton {
//  This class creates a WebService cloneWithProduct
//  This WebService will be called from Clone with Product button on Service Contract
    WebService static String cloneServiceContract(Id serviceContractId) {
        String retVal = '';
        
        ServiceContract sc =
            [select Name, Id, Pricebook2Id, Term, Tax, Status, StartDate, SpecialTerms, ShippingStreet, ShippingState, 
                    ShippingPostalCode, ShippingHandling, ShippingCountry, ShippingCity, 
                    EndDate, Description, Contract_Type__c, ContactId, 
                    BillingStreet, BillingState, BillingPostalCode, BillingCountry, BillingCity, AccountId
             From   ServiceContract 
             where  Id = :serviceContractId ];  
                    
        ServiceContract scNew = sc.clone(false); 
        scNew.Name                = '***Clone***-'+sc.Name; 
        scNew.Clone_From_ID__c    = sc.Id;
        scNew.Clone_Line_Items__c = true;
        
        try {
            insert scNew;
        }
        catch (Exception ex) {
            
        }
        return retVal=scNew.Id;     
    }
}