Perkin-UAT/force-app/main/default/objects/Contract/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AA</fullName>
            </value>
            <value>
                <fullName>AMS</fullName>
            </value>
            <value>
                <fullName>ANP</fullName>
            </value>
            <value>
                <fullName>APS</fullName>
            </value>
            <value>
                <fullName>ARS</fullName>
            </value>
            <value>
                <fullName>AWS</fullName>
            </value>
            <value>
                <fullName>CHS</fullName>
            </value>
            <value>
                <fullName>CLH</fullName>
            </value>
            <value>
                <fullName>CLR</fullName>
            </value>
            <value>
                <fullName>CRD</fullName>
            </value>
            <value>
                <fullName>CSA</fullName>
            </value>
            <value>
                <fullName>DIA</fullName>
            </value>
            <value>
                <fullName>DNA</fullName>
            </value>
            <value>
                <fullName>ESS</fullName>
            </value>
            <value>
                <fullName>FAP</fullName>
            </value>
            <value>
                <fullName>FLR</fullName>
            </value>
            <value>
                <fullName>GC</fullName>
            </value>
            <value>
                <fullName>GSAE</fullName>
            </value>
            <value>
                <fullName>GSLE</fullName>
            </value>
            <value>
                <fullName>HCS</fullName>
            </value>
            <value>
                <fullName>HMG</fullName>
            </value>
            <value>
                <fullName>HTS</fullName>
            </value>
            <value>
                <fullName>IAS</fullName>
            </value>
            <value>
                <fullName>ICP</fullName>
            </value>
            <value>
                <fullName>ILB</fullName>
            </value>
            <value>
                <fullName>INV</fullName>
            </value>
            <value>
                <fullName>IR</fullName>
            </value>
            <value>
                <fullName>LC</fullName>
            </value>
            <value>
                <fullName>LCA</fullName>
            </value>
            <value>
                <fullName>LCM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Lead/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <description>Multi-select list, but prefer only one product line per lead for best results in reporting.</description>
    <inlineHelpText>Please select single PRIMARY product line for this lead.</inlineHelpText>
    <label>Product Line</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AA</fullName>
            </value>
            <value>
                <fullName>AGO</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>AMS</fullName>
            </value>
            <value>
                <fullName>ANP</fullName>
            </value>
            <value>
                <fullName>APS</fullName>
            </value>
            <value>
                <fullName>ARS</fullName>
            </value>
            <value>
                <fullName>ASE</fullName>
            </value>
            <value>
                <fullName>ASO</fullName>
            </value>
            <value>
                <fullName>ATT</fullName>
            </value>
            <value>
                <fullName>AVC</fullName>
            </value>
            <value>
                <fullName>AVS</fullName>
            </value>
            <value>
                <fullName>AWS</fullName>
            </value>
            <value>
                <fullName>BIO</fullName>
            </value>
            <value>
                <fullName>BTX</fullName>
            </value>
            <value>
                <fullName>CAT</fullName>
            </value>
            <value>
                <fullName>CCM</fullName>
            </value>
            <value>
                <fullName>CDI</fullName>
            </value>
            <value>
                <fullName>CHO</fullName>
            </value>
            <value>
                <fullName>CHS</fullName>
            </value>
            <value>
                <fullName>CKP</fullName>
            </value>
            <value>
                <fullName>CLH</fullName>
            </value>
            <value>
                <fullName>CLR</fullName>
            </value>
            <value>
                <fullName>CMG</fullName>
            </value>
            <value>
                <fullName>CRD</fullName>
            </value>
            <value>
                <fullName>CSA</fullName>
            </value>
            <value>
                <fullName>CSB</fullName>
            </value>
            <value>
                <fullName>DAB</fullName>
            </value>
            <value>
                <fullName>DAO</fullName>
            </value>
            <value>
                <fullName>DCS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Open_Lead_Notice__c/Open_Lead_Notice__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Open Lead Notice</label>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/Open_Lead_Notice__c/fields/Id1__c.field-meta.xml
<CustomField>
    <fullName>Id1__c</fullName>
    <label>Id1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Open_Lead_Notice__c/fields/Id2__c.field-meta.xml
<CustomField>
    <fullName>Id2__c</fullName>
    <label>Id2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Send_Mail_Settings__c/Send_Mail_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Batch Send Mail Settings</label>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/Send_Mail_Settings__c/fields/Allowed_ProductLines__c.field-meta.xml
<CustomField>
    <fullName>Allowed_ProductLines__c</fullName>
    <label>Allowed ProductLines</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Send_Mail_Settings__c/fields/bcc_mails__c.field-meta.xml
<CustomField>
    <fullName>bcc_mails__c</fullName>
    <label>bcc mails</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Send_Mail_Settings__c/fields/Schedule_Send_Mail__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Send_Mail__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Schedule Send Mail</label>
    <type>Checkbox</type>
</CustomField>

Perkin-UAT/force-app/main/default/classes/TestBatchSendEmail.cls
@isTest
private class TestBatchSendEmail {
    
    static testMethod void myUnitTest() { 
        Lead myLead = new Lead();
        myLead.FirstName = 'Jack';
        myLead.LastName = 'T Ripper';
        myLead.Email = 'Jack@Ripper.net';
        myLead.Company = 'Rippers & Co.';
        myLead.Status = 'Open';
        insert myLead;
        
        Lead myLead2 = new Lead();
        myLead2.FirstName = 'Omar';
        myLead2.LastName = 'Little';
        myLead2.Email = 'Omar@Little.com';
        myLead2.Company = 'Stick Em Up';
        myLead2.Status = 'Open';
        insert myLead2;
        
             test.startTest();  
            //custom settings insertion Open_Lead_Notice__c 
            Open_Lead_Notice__c leadNotice = new Open_Lead_Notice__c();
            leadNotice.Name = '2';
            leadNotice.Id1__c = myLead.id;
            leadNotice.Id2__c = mylead2.id;
            insert leadNotice;
            
            //Send_mail_settings insertion
            Send_Mail_Settings__c sm = new Send_Mail_Settings__c();
            sm.name = 'mail settings';
            sm.bcc_mails__c = 'test@testmail.com;sendmail@mail.com';
            sm.allowed_productlines__c = 'AA; AMS; ASO; GC; ICP; IR; LC; LCM; MAS; One Source: Multi-vendor; One Source: Qualification; One Source: Relocation; One Source: Training; RAM; Service Contract; SVC; TEA; TOF; UVS';
            insert sm;
            
            //Lead  insertion
            String countryNames = Label.CountryEmailInclude;
            List<String> countriesInclude = countryNames.split(',');
            List<Lead> leadsToInsert = new List<Lead>();
            for(Integer i=0;i<5;i++)
            {
                Lead leadRec = new Lead();
                leadRec.LastName = 'Name'+i;
                leadRec.product_Line__c='AA';
                leadRec.Company='Company'+i;
                leadRec.Country=countriesInclude.get(i);
                leadRec.Status='Open';
                
                Date myDate = Date.today().addDays(-7);
                Time myTime = Time.newInstance(8, 0, 0, 0);
                DateTime dt1 = DateTime.newInstanceGMT(myDate, myTime);
                
                leadRec.CreatedDate=dt1;
                leadRec.LastModifiedDate=dt1;
                // serializing the sobject to string.
                string leadJSON=JSON.serialize(leadRec);
                // De-serializing the string back to sobject
                Lead ll = (Lead) JSON.deserialize(leadJSON, Lead.class );
                leadsToInsert.add(ll);									
                
            }
        insert leadsToInsert;
        //System.debug('**** leadsToInsert before '+[ select id,name,LastModifiedDate,createddate from lead where name='Name0']);
        //Lead l = [ select id,name,LastModifiedDate from lead where name='Name0'];
       
        //call batch method
            BatchSendMail bse = new BatchSendMail();
            Database.executeBatch(bse);
            
        test.stopTest();
    }
    
    static testMethod void testScheduleSendEmail(){
        test.startTest();
            //Send_mail_settings insertion
            Send_Mail_Settings__c sm = new Send_Mail_Settings__c();
            sm.name = 'mail settings';
            sm.bcc_mails__c = 'test@testmail.com;sendmail@mail.com';
            sm.Schedule_send_mail__c = false;
            insert sm; 
            
            Schedule_BatchSendEmail sh1 = new Schedule_BatchSendEmail();
            String sch = '0 0 23 * * ?';
            System.Schedule('Test Schedule', sch, sh1);
        test.stopTest();
    }
}