Perkin-UAT/force-app/main/default/objects/User/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <label>Business</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EH</fullName>
            </value>
            <value>
                <fullName>DX</fullName>
            </value>
            <value>
                <fullName>LST</fullName>
            </value>
            <value>
                <fullName>Informatics</fullName>
            </value>
            <value>
                <fullName>OneSource</fullName>
            </value>
            <value>
                <fullName>Corp IT</fullName>
            </value>
            <value>
                <fullName>Corp Legal</fullName>
            </value>
            <value>
                <fullName>Corp Mrkt</fullName>
            </value>
            <value>
                <fullName>Corp HR</fullName>
            </value>
            <value>
                <fullName>Corp Operations</fullName>
            </value>
            <value>
                <fullName>Corp Finance</fullName>
            </value>
            <value>
                <fullName>Food Business</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/User/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/classes/TestRejectPage.cls
@isTest
private class TestRejectPage{
    @isTest
    private static void testClass()
    {
    
    Profile sysAdmin_Prof = [select Id from profile where Name='System Administrator']; //Querying for the profile to assign to the user.
        
//Creating the test user
User objUsr_INF = new User(alias = 'sINFUser', Business__c = 'Informatics' , Home_Country__c = 'US', email='standarduserPKIINF@perkinelmerINF.com',emailencodingkey='UTF-8',lastname='Testing', languagelocalekey='en_US',localesidkey='en_US', profileid = sysAdmin_Prof.Id,timezonesidkey='America/Los_Angeles', username='standarduser12343432@perkinelmerPKITEST.com');

insert objUsr_INF; //creating the user

System.runAs(objUsr_INF){

       Opportunity opp = new Opportunity();
        opp.Name='TestOpp';
        opp.StageName='Prospecting';
        opp.CloseDate=Date.NewInstance(2013,8,23);
        opp.Solution_Area_of_Interest__c='Energy';
        insert opp;

        // Add parameters to page URL 
        ApexPages.currentPage().getParameters().put('oppId', opp.id);
        ApexPages.currentPage().getParameters().put('oopOwner', 'basavaiah.gorikapudi@perkinelmer.com');
        ApexPages.currentPage().getParameters().put('body', 'TestEmail');
        ApexPages.StandardController sc = new ApexPages.standardController(opp);
        SendEmail sm= new SendEmail(sc);
        try{
            sm.navigateToRecord();
             sm.send();
             }catch(Exception e){} 
            
         }

     

       }

}