Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Booked_Date_INF__c.field-meta.xml
<CustomField>
    <fullName>Booked_Date_INF__c</fullName>
    <inlineHelpText>This field updated by Order Entry when opportunity is Booked</inlineHelpText>
    <label>Booked Date</label>
    <type>Date</type>
</CustomField>

Perkin-UAT/force-app/main/default/classes/Batch_OpprtunityLineItemRollup.cls
/*
This Batch Class will be used to Update the service product count,renewal product count and sum of Renewal Product
for the Opportunity
TEST CLASS : Test_OpportunityRollUp
*/
public class Batch_OpprtunityLineItemRollup implements Database.Batchable<SObject>,Database.stateful {

 public Database.QueryLocator  start(Database.BatchableContext bc) {
        
     //String query ='SELECT Id,OpportunityId FROM OpportunityLineItem Where OpportunityId !=\'\' and isRenewable__c=TRUE and opportunity.recordtype.developerName=\'Informatics\' and Opportunity.Booked_Date_INF__c >= 2015-01-01';
     String query ='SELECT Id,OpportunityId FROM OpportunityLineItem Where OpportunityId !=\'\' and opportunity.recordtype.developerName=\'Informatics\' and Opportunity.Booked_Date_INF__c >= 2015-01-01';
   
     if(Test.isRunningTest()){
            query += ' Limit 10';
        }
        return  Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext bc, List<OpportunityLineItem> opprtLineList){
        OpportunityLineItemRollupHandler.updateRollupCount(opprtLineList,null,null,false);
        
    }    
    public void finish(Database.BatchableContext bc){
        

    }   
    
}