Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Booked_Date_INF__c.field-meta.xml
<CustomField>
    <fullName>Booked_Date_INF__c</fullName>
    <inlineHelpText>This field updated by Order Entry when opportunity is Booked</inlineHelpText>
    <label>Booked Date</label>
    <type>Date</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Originating_Opportunity_INF__c.field-meta.xml
<CustomField>
    <fullName>Originating_Opportunity_INF__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Informatics - This field will get autopopulated with parent opportunity name/link when a renewal opportunity is created.</description>
    <label>Originating (Master) Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Child Opportunities</relationshipLabel>
    <relationshipName>Originating_Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/classes/Batch_UpdateOpprtunityChildCount.cls
/*
 This Batch Class will be used to Update the Child Opportunity count on the master opportunity
TEST CLASS : Test_OpportunityRollUp
 */
public class Batch_UpdateOpprtunityChildCount  implements Database.Batchable<SObject> {
    
    public Database.QueryLocator  start(Database.BatchableContext bc) {
        
        String query ='SELECT Id,Originating_Opportunity_INF__c FROM Opportunity Where Originating_Opportunity_INF__c !=\'\' and recordtype.developerName=\'Informatics\'  and Booked_Date_INF__c >= 2015-01-01 ';
        if(Test.isRunningTest()){
            query += ' Limit 10';
        }
        return  Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext bc, List<Opportunity> OpprtLst){
      
        OpportunityChildCountHandler.updateChildCount(OpprtLst,null,null,false);
    }    
    public void finish(Database.BatchableContext bc){
        
    }   
}