Perkin-UAT/force-app/main/default/objects/Opportunity/fields/First_Email_Sent_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Email_Sent_Date__c</fullName>
    <label>1st Email Sent Date</label>
    <type>Date</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/INF_Contains_final_notice__c.field-meta.xml
<CustomField>
    <fullName>INF_Contains_final_notice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>INF Contains final notice</label>
    <type>Checkbox</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/INF_Contains_second_notice__c.field-meta.xml
<CustomField>
    <fullName>INF_Contains_second_notice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>INF Contains second notice</label>
    <type>Checkbox</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Second_Email_Sent_Date__c.field-meta.xml
<CustomField>
    <fullName>Second_Email_Sent_Date__c</fullName>
    <label>2nd Email Sent Date</label>
    <type>Date</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Third_Email_Sent_Date__c.field-meta.xml
<CustomField>
    <fullName>Third_Email_Sent_Date__c</fullName>
    <label>3rd Email Sent Date</label>
    <type>Date</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SFDC_LOG__c/SFDC_LOG__c.object-meta.xml
<CustomObject>
    <description>This will store messages from processes, flows and apex classes</description>
    <label>SFDC_LOG</label>
    <nameField>
        <displayFormat>LOG-{000000000}</displayFormat>
        <label>SFDC_LOG Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SFDC_LOG</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/SFDC_LOG__c/fields/Log_Type__c.field-meta.xml
<CustomField>
    <fullName>Log_Type__c</fullName>
    <description>Used to decide if the SFDC LOg object record created are an Integration log type or Error/Exception log type</description>
    <label>Log Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error/Exception Log</fullName>
            </value>
            <value>
                <fullName>Integration Log</fullName>
            </value>
            <value>
                <fullName>CPQ Logs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SFDC_LOG__c/fields/Message_Long__c.field-meta.xml
<CustomField>
    <fullName>Message_Long__c</fullName>
    <description>If needed, a way to log long error messages)</description>
    <label>Message Long</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SFDC_LOG__c/fields/Running_User__c.field-meta.xml
<CustomField>
    <fullName>Running_User__c</fullName>
    <description>the user name running this automation as</description>
    <label>Running User</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SFDC_LOG__c/fields/Source_Name__c.field-meta.xml
<CustomField>
    <fullName>Source_Name__c</fullName>
    <description>The Name of the automation that ran the log event</description>
    <label>Source Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SFDC_LOG__c/fields/Source_Type__c.field-meta.xml
<CustomField>
    <fullName>Source_Type__c</fullName>
    <description>This is the type of automation that ran during the log event</description>
    <label>Source Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>APEX</fullName>
            </value>
            <value>
                <fullName>L.FLOW</fullName>
            </value>
            <value>
                <fullName>P.FLOW</fullName>
            </value>
            <value>
                <fullName>W.FLOW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/classes/Batch_ContractRenewalNoticeFails.cls
public class Batch_ContractRenewalNoticeFails implements Database.Batchable<SObject>, Database.stateful{
    
    public Database.QueryLocator  start(Database.BatchableContext bc) {
        //Getting all the orders which are created today
        String query = 'Select Id, INF_Contains_second_notice__c, INF_Contains_final_notice__c  From Opportunity WHERE Opportunity.RecordType.DeveloperName = \'Informatics\' AND Opportunity.StageName = \'Stage 5 - Negotiation\' AND First_Email_Sent_Date__c != null AND (INF_Contains_second_notice__c = false OR INF_Contains_final_notice__c =false) AND (Second_Email_Sent_Date__c = today OR Second_Email_Sent_Date__c = Yesterday OR Third_Email_Sent_Date__c = today OR Third_Email_Sent_Date__c = Yesterday)';
        system.debug('@@query= '+query);
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext bc, List<Opportunity> opportunities){
        system.debug('@@opportunities= '+opportunities.size());
        List<Opportunity> opportunityToUpdate = new List<Opportunity>();
        Map<Id, Boolean> secondNoticeFailedById = new Map<Id, Boolean>();
        Map<Id, Boolean> finalNoticeFailedById = new Map<Id, Boolean>();
        For(EmailMessage emailMessageRec: [SELECT Id, RelatedToId, Subject From EmailMessage Where RelatedToId IN :opportunities AND Subject like '%Contract Renewal Quotation%' ]){
            if(emailMessageRec.Subject.contains('2nd Notice')){
                secondNoticeFailedById.put(emailMessageRec.RelatedToId, true);
            } else if(emailMessageRec.Subject.contains('Final Notice')){
                finalNoticeFailedById.put(emailMessageRec.RelatedToId, true);
            } 
        }
        
        for(Opportunity oppotunityRec: opportunities){
            Boolean isAdded = false;
            if(secondNoticeFailedById.get(oppotunityRec.Id) != null){
                oppotunityRec.INF_Contains_second_notice__c = secondNoticeFailedById.get(oppotunityRec.Id);
                opportunityToUpdate.add(oppotunityRec);
                isAdded =true;
            }
            
            if(finalNoticeFailedById.get(oppotunityRec.Id) != null){
                oppotunityRec.INF_Contains_final_notice__c = finalNoticeFailedById.get(oppotunityRec.Id);
                if(!isAdded){
                    opportunityToUpdate.add(oppotunityRec);
                }
            }            
        }

        if(!opportunityToUpdate.isEmpty()){
            Database.SaveResult[] results =  Database.update(opportunityToUpdate, false);
            for(Database.SaveResult sr : results){
                if (!sr.isSuccess() || test.isRunningTest()) {
                    List<SFDC_LOG__c> logsToInsert= new List<SFDC_LOG__c>();
                    for(Database.Error err : sr.getErrors()) {
                        system.debug('@@error= '+sr.getErrors());
                        SFDC_LOG__c newLog = new SFDC_LOG__c();
                        newLog.Log_Type__c = 'CPQ Logs';
                        newLog.Message_Long__c = 'Record ID: '+sr.getId() +'</br> '+err.getMessage();
                        newLog.Running_User__c = UserInfo.getUserName();
                        newLog.Source_Name__c = 'Contract Renewal Fails';
                        newLog.Source_Type__c = 'APEX';
                        logsToInsert.add(newLog);
                    }
                    
                    if(!logsToInsert.isEmpty()){
                        insert logsToInsert;
                    }
                }
            } 
        } 
    }
    
    public void finish(Database.BatchableContext bc){
        
    }
}