Perkin-UAT/force-app/main/default/objects/B2B_Related_Product__c/B2B_Related_Product__c.object-meta.xml
<CustomObject>
    <label>B2B Related Product</label>
    <nameField>
        <displayFormat>BRP-{0000}</displayFormat>
        <label>B2B Related Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B2B Related Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/B2B_Related_Product__c/fields/Child_Product__c.field-meta.xml
<CustomField>
    <fullName>Child_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Child Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>B2B Related Products (Child Product)</relationshipLabel>
    <relationshipName>B2B_Related_Products1</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Related_Product__c/fields/Parent_Product__c.field-meta.xml
<CustomField>
    <fullName>Parent_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>B2B Related Products</relationshipLabel>
    <relationshipName>B2B_Related_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/B2B_Featured_Product__c.field-meta.xml
<CustomField>
    <fullName>B2B_Featured_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <label>B2B Featured Product</label>
    <type>Checkbox</type>
</CustomField>

Perkin-UAT/force-app/main/default/classes/B2B_RelatedProductControllerTest.cls
/**
 * @description       : test class for B2B_RelatedProductController & B2B_RelatedProductService
 * @author            : Meenakshi Jain
 * @Created date      : April 2025
**/
@isTest
public class B2B_RelatedProductControllerTest {
    //variables
    private static final String PRODUCT_NAME = 'Test Product';
    private static final String PRODUCTCHILD_NAME = 'Test Child Product';
    
    //create test data
    @testSetup
    public static void makeData(){
        Product2 prod = B2B_TestDataFactory.createProduct(PRODUCT_NAME,false);
        prod.B2B_Featured_Product__c = true;
        Product2 childProd = B2B_TestDataFactory.createProduct(PRODUCTCHILD_NAME,false);
        childProd.B2B_Featured_Product__c = true;
        List<Product2> prodList = new List<Product2>{prod,childProd};
            insert prodList;
        
        B2B_Related_Product__c b2bRelated = new B2B_Related_Product__c();
        b2bRelated.Parent_Product__c = prod.Id;
        b2bRelated.Child_Product__c = childProd.Id;
        insert b2bRelated;
    }
    
    //test for pdp page
    @isTest
    static void testPDPPage(){
        List<product2> prodList = [SELECT Id FROM Product2 WHERE Name =: PRODUCT_NAME ];
        Map<String,Object> mapParams = new Map<String,Object>();
        mapParams.put('isHomePage',false);
        mapParams.put('productId',prodList[0].Id);
        Map<String,Object> outputParam = B2B_RelatedProductController.getRelatedProducts(mapParams);
        Assert.areEqual(true, outputParam.containsKey('isSuccess'));
        Assert.areEqual(true, outputParam.containsKey('relatedProductList'));
        
    }
    
    //test for catch block
    @isTest
    static void testCatch(){
        Map<String,Object> outputParam = B2B_RelatedProductController.getRelatedProducts(null);
        Assert.areEqual(false, outputParam.get('isSuccess'));
    }
    
    //test for Home page
    @isTest
    static void testHomePage(){
        List<product2> prodList = [SELECT Id FROM Product2 WHERE Name =: PRODUCT_NAME ];
        Map<String,Object> mapParams = new Map<String,Object>();
        mapParams.put('isHomePage',true);
        
        Map<String,Object> outputParam = B2B_RelatedProductController.getRelatedProducts(mapParams);
        Assert.areEqual(true, outputParam.containsKey('isSuccess'));
        Assert.areEqual(true, outputParam.containsKey('relatedProductList'));
        
    }
}