Perkin-UAT/force-app/main/default/objects/B2B_Related_Product__c/B2B_Related_Product__c.object-meta.xml
<CustomObject>
    <label>B2B Related Product</label>
    <nameField>
        <displayFormat>BRP-{0000}</displayFormat>
        <label>B2B Related Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B2B Related Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/B2B_Related_Product__c/fields/Child_Product__c.field-meta.xml
<CustomField>
    <fullName>Child_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Child Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>B2B Related Products (Child Product)</relationshipLabel>
    <relationshipName>B2B_Related_Products1</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Related_Product__c/fields/Parent_Product__c.field-meta.xml
<CustomField>
    <fullName>Parent_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>B2B Related Products</relationshipLabel>
    <relationshipName>B2B_Related_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/B2B_Alternate_Products__c.field-meta.xml
<CustomField>
    <fullName>B2B_Alternate_Products__c</fullName>
    <label>B2B Alternate Products</label>
    <length>6000</length>
    <type>LongTextArea</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/B2B_Has_Related_Product__c.field-meta.xml
<CustomField>
    <fullName>B2B_Has_Related_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <label>B2B Has Related Product</label>
    <type>Checkbox</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/B2B_SKU__c.field-meta.xml
<CustomField>
    <fullName>B2B_SKU__c</fullName>
    <label>B2B SKU</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/Is_B2B_Product__c.field-meta.xml
<CustomField>
    <fullName>Is_B2B_Product__c</fullName>
    <formula>NOT(ISNULL( B2B_Sales_Org_And_Sales_Status__c ))</formula>
    <label>Is B2B Product?</label>
    <type>Checkbox</type>
</CustomField>

Perkin-UAT/force-app/main/default/classes/B2B_CreateRelatedProductsBatch.cls
/**
 * test class- B2B_CreateRelatedProductsBatchTest
*/
public with sharing class B2B_CreateRelatedProductsBatch implements Database.Batchable<sObject> {

    public final String QueryStr;

    // SELECT Id, B2B_Alternate_Products__c, B2B_SKU__c FROM Product2 where B2B_Has_Related_Product__c = true
    public B2B_CreateRelatedProductsBatch( String query ) {
        QueryStr = query;
        System.debug('B2B_CreateRelatedProductsBatch Query-- '+QueryStr);
    }

    public Database.QueryLocator start(Database.BatchableContext bc){
        System.debug('B2B_CreateRelatedProductsBatch start Query-- '+QueryStr);
        return Database.getQueryLocator( QueryStr );
    }
    
    public void execute(Database.BatchableContext bc, List<Product2> scope){
        try {
            List<Id> productIds = new List<Id>();
            List<B2B_Related_Product__c> relatedProductsToInsert = new List<B2B_Related_Product__c>();
            Map<String,Id> productSkuVsIdMap = new Map<String,Id>();
            //HT: Query Updated
            List<Product2> allProducts = [ SELECT Id, B2B_SKU__c FROM Product2 WHERE B2B_SKU__c != null AND Is_B2B_Product__c = true ];
            if( ! allProducts.isEmpty() ){
                for( Product2 prod : allProducts ){
                    productSkuVsIdMap.put(prod.B2B_SKU__c, prod.Id);
                }   
                for( Product2 prod : scope ){
                    Id parentProductId = prod.Id;
                    String alternateProductsStr = prod.B2B_Alternate_Products__c;
                    List<String> alternateProducts = alternateProductsStr.split(',');
                    if( ! alternateProducts.isEmpty() ){
                        for( String skuStr : alternateProducts ){
                            //Added the trim() method

                            skuStr = skuStr.trim();
                            if( productSkuVsIdMap.containsKey( skuStr ) ){

                                String childProductId = productSkuVsIdMap.get( skuStr );
                                if( String.isNotBlank( childProductId ) ){
                                    B2B_Related_Product__c relatedProductRecord = new B2B_Related_Product__c();
                                    relatedProductRecord.Parent_Product__c = parentProductId;
                                    relatedProductRecord.Child_Product__c = childProductId;
                                    relatedProductsToInsert.add( relatedProductRecord );
                                }
                            }
                        }
                    }
                }
                if( !relatedProductsToInsert.isEmpty() ){
                    Database.insert( relatedProductsToInsert, false );
                }
            }
        } catch (Exception e) {
            System.debug('Exception-- '+e.getMessage());
        }
    }
    
    public void finish(Database.BatchableContext bc){

    }
}