Perkin-UAT/force-app/main/default/objects/Batch_Target_Settings__c/Batch_Target_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Batch Target Settings</label>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/Batch_Target_Settings__c/fields/Lead_Metrics_Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Lead_Metrics_Batch_Size__c</fullName>
    <label>Lead Metrics Batch Size</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Batch_Target_Settings__c/fields/Lead_Target_Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Lead_Target_Batch_Size__c</fullName>
    <label>Lead Target Batch Size</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Batch_Target_Settings__c/fields/Line_Item_Target_Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Line_Item_Target_Batch_Size__c</fullName>
    <label>Line Item Target Batch Size</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Batch_Target_Settings__c/fields/Opportunity_Metrics_Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Metrics_Batch_Size__c</fullName>
    <label>Opportunity Metrics Batch Size</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Batch_Target_Settings__c/fields/Opportunity_Target_Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Target_Batch_Size__c</fullName>
    <label>Opportunity Target Batch Size</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Batch_Target_Settings__c/fields/Product_Line_Metrics_Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Product_Line_Metrics_Batch_Size__c</fullName>
    <label>Product Line Metrics Batch Size</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Batch_Target_Settings__c/fields/Rgn_Product_Line_Metrics_Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Rgn_Product_Line_Metrics_Batch_Size__c</fullName>
    <label>Rgn Product Line Metrics Batch Size</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Batch_Target_Settings__c/fields/Zero_Month_Rep_Target_Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Zero_Month_Rep_Target_Batch_Size__c</fullName>
    <label>Zero Month Rep Target Batch Size</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Batch_Target_Settings__c/fields/Zero_Month_Territory_Target_Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Zero_Month_Territory_Target_Batch_Size__c</fullName>
    <label>Zero Month Territory Target Batch Size</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Batch_Target_Settings__c/fields/Zero_Product_Lead_Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Zero_Product_Lead_Batch_Size__c</fullName>
    <label>Zero Product Lead Batch Size</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Batch_Target_Settings__c/fields/Zero_Rep_Product_Line_Target_Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Zero_Rep_Product_Line_Target_Batch_Size__c</fullName>
    <label>Zero Rep Product Line Target Batch Size</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Batch_Target_Settings__c/fields/Zero_Rgn_Product_Line_Target_Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Zero_Rgn_Product_Line_Target_Batch_Size__c</fullName>
    <label>Zero Rgion Product Line Targe Batch Size</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Perkin-UAT/force-app/main/default/classes/GSP_schTargetMetrics_TEST.cls
@isTest
private class GSP_schTargetMetrics_TEST
{
	@isTest
	private static void test_schTargetMetrics()
	{
		Batch_Target_Settings__c batchSettings = new Batch_Target_Settings__c(
			Name = 'Default',
			Lead_Metrics_Batch_Size__c = 100,
			Lead_Target_Batch_Size__c = 100,
			Line_Item_Target_Batch_Size__c = 100,
			Opportunity_Metrics_Batch_Size__c = 100,
			Opportunity_Target_Batch_Size__c = 100,
			Product_Line_Metrics_Batch_Size__c = 100,
			Rgn_Product_Line_Metrics_Batch_Size__c = 100,
			Zero_Month_Rep_Target_Batch_Size__c = 1000,
			Zero_Month_Territory_Target_Batch_Size__c = 100,
			Zero_Product_Lead_Batch_Size__c = 1000,
			Zero_Rep_Product_Line_Target_Batch_Size__c = 1000,
			Zero_Rgn_Product_Line_Target_Batch_Size__c = 1000);
		insert batchSettings;
		System.assertNotEquals(batchSettings.Id, null);
		
		String CRON_EXP = '0 0 0 3 9 ? 2026';
		Test.startTest();
		String jobId = System.schedule('testPEScheduledApex', CRON_EXP,  new GSP_schTargetMetrics());
      	
      	CronTrigger ct = [
      		SELECT
      			id,
      			CronExpression,
      			TimesTriggered,
      			NextFireTime
         	FROM
         		CronTrigger
         	WHERE id = : jobId];
         
         //System.assertEquals(CRON_EXP, ct.CronExpression);
         //System.assertEquals(0, ct.TimesTriggered);
         //System.assertEquals('2022-09-03 00:00:00', String.valueOf(ct.NextFireTime));
         Test.stopTest();
	}
}