Perkin-UAT/force-app/main/default/objects/Batch_Target_Settings__c/Batch_Target_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Batch Target Settings</label>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/Batch_Target_Settings__c/fields/Lead_Target_Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Lead_Target_Batch_Size__c</fullName>
    <label>Lead Target Batch Size</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Batch_Target_Settings__c/fields/Line_Item_Target_Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Line_Item_Target_Batch_Size__c</fullName>
    <label>Line Item Target Batch Size</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Batch_Target_Settings__c/fields/Zero_Month_Rep_Target_Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Zero_Month_Rep_Target_Batch_Size__c</fullName>
    <label>Zero Month Rep Target Batch Size</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Lead/fields/Global_Region__c.field-meta.xml
<CustomField>
    <fullName>Global_Region__c</fullName>
    <description>Automatic formua to divide leads into PKI Global Regions - APAC, EMEA, Americas</description>
    <formula>IF(ISBLANK(Country), &quot;None&quot;,

IF(CONTAINS(&quot;US:CA:PR:VI:PM:AR:BZ:BO:BR:CL:CO:CR:CW:EC:SV:FK:GT:GY:HN:MX:NI:PA:PY:PE:SR:UY:VE:AI:AG:AW:BS:BB:BM:KY:CU:DM:DO:GL:GD:GP:HT:JM:MQ:MS:KN:LC:VC:TC:TT:AN:VG:&quot;, Country), &quot;Americas&quot;,

IF(CONTAINS(&quot;AT:BE:CH:DE:DK:ES:FI:FR:GB:IE:IT:LU:NL:NO:PL:SE:AF:BH:BD:BT:BV:IO:KM:IN:IR:KW:MV:NP:OM:PK:QA:SA:LK:AE:YE:DZ:AD:AO:BJ:BW:BF:BI:CM:CV:CF:TD:CG:DJ:EG:GQ:ER:ET:FX:GF:GA:GM:GH:GI:GN:GW:IQ:CI:JO:KE:LB:LS:LR:LY:NU:MG:MW:KZ:LK:MV:SC:ML:MN:MR:MU:YT:MC:MA:MZ:NA:NE:NG:PT:RW:SM:ST:SN:SC:SL:SO:ZA:ES:SH:SD:SZ:TZ:TG:TN:UG:EH:ZM:ZW:CD:VA:AL:AM:AZ:BY:BA:BV:BG:HR:CY:CZ:EE:FO:MK:GE:GR:GL:HU:IS:IL:KZ:KG:LV:LI:LT:MT:MD:ME:RS:RO:RU:SK:SI:SY:TJ:TR:TM:UA:UZ:PS:SS&quot;, Country), &quot;EMEA&quot;,

IF(CONTAINS(&quot;JP:AS:AQ:AU:BN:KH:CN:CX:CC:CK:TP:FJ:PF:TF:GU:HM:HK:ID:KI:LA:MO:MY:MH:FM:MM:NR:NC:NZ:NU:NF:KP:MP:PW:PG:PH:PN:WS:SG:SB:KR:TW:TH:TK:TO:TM:TV:UM:VU:VN:WF&quot;, Country), &quot;APAC&quot;, &quot;Other&quot;))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Global Region</label>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Lead/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <description>Multi-select list, but prefer only one product line per lead for best results in reporting.</description>
    <inlineHelpText>Please select single PRIMARY product line for this lead.</inlineHelpText>
    <label>Product Line</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AA</fullName>
            </value>
            <value>
                <fullName>AGO</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>AMS</fullName>
            </value>
            <value>
                <fullName>ANP</fullName>
            </value>
            <value>
                <fullName>APS</fullName>
            </value>
            <value>
                <fullName>ARS</fullName>
            </value>
            <value>
                <fullName>ASE</fullName>
            </value>
            <value>
                <fullName>ASO</fullName>
            </value>
            <value>
                <fullName>ATT</fullName>
            </value>
            <value>
                <fullName>AVC</fullName>
            </value>
            <value>
                <fullName>AVS</fullName>
            </value>
            <value>
                <fullName>AWS</fullName>
            </value>
            <value>
                <fullName>BIO</fullName>
            </value>
            <value>
                <fullName>BTX</fullName>
            </value>
            <value>
                <fullName>CAT</fullName>
            </value>
            <value>
                <fullName>CCM</fullName>
            </value>
            <value>
                <fullName>CDI</fullName>
            </value>
            <value>
                <fullName>CHO</fullName>
            </value>
            <value>
                <fullName>CHS</fullName>
            </value>
            <value>
                <fullName>CKP</fullName>
            </value>
            <value>
                <fullName>CLH</fullName>
            </value>
            <value>
                <fullName>CLR</fullName>
            </value>
            <value>
                <fullName>CMG</fullName>
            </value>
            <value>
                <fullName>CRD</fullName>
            </value>
            <value>
                <fullName>CSA</fullName>
            </value>
            <value>
                <fullName>CSB</fullName>
            </value>
            <value>
                <fullName>DAB</fullName>
            </value>
            <value>
                <fullName>DAO</fullName>
            </value>
            <value>
                <fullName>DCS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Lead/fields/Region_Product_Line_Target_Lead__c.field-meta.xml
<CustomField>
    <fullName>Region_Product_Line_Target_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region Product Line Target Lead</label>
    <referenceTo>Region_Product_Line_Target_Leads__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Month_Rep_Target__c/Month_Rep_Target__c.object-meta.xml
<CustomObject>
    <description>SBE: EH Only - Part of the custom AOP reporting package developed by GSP from the UK. One of several custom objects this object is used to store each sales person&#39;s monthly base &amp; stretch quotas and then compare against their current sales funnel</description>
    <label>Month Rep Target</label>
    <nameField>
        <displayFormat>MRT - {00000}</displayFormat>
        <label>Month Rep Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Month Rep Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/Month_Territory_Target__c/Month_Territory_Target__c.object-meta.xml
<CustomObject>
    <label>Month Territory Target</label>
    <nameField>
        <displayFormat>MTTN-{0000}</displayFormat>
        <label>Month Territory Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Month Territory Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Global_Region__c.field-meta.xml
<CustomField>
    <fullName>Global_Region__c</fullName>
    <description>Formula to automatically report on PKI Global Regions - APAC, EMEA, Americas</description>
    <formula>IF(ISBLANK(Account.ShippingCountry), &quot;None&quot;,
IF(CONTAINS(&quot;US:CA:PR:VI:PM:AR:BZ:BO:BR:CL:CO:CR:EC:SV:FK:GT:GY:HN:MX:NI:PA:PY:PE:SR:UY:VE:AI:AG:AW:BS:BB:BM:KY:CU:DM:DO:GD:GP:HT:JM:MQ:MS:KN:LC:VC:TC:AN:VG:&quot;, Account.ShippingCountry), &quot;Americas&quot;,
IF(CONTAINS(&quot;AT:BE:CH:DE:DK:ES:FI:FR:GB:IE:IT:LU:NL:NO:PL:SE:AF:BH:BD:BT:IO:KM:IN:IR:KW:MV:NP:OM:PK:QA:SA:LK:AE:YE:DZ:AD:AO:BJ:BW:BF:BI:BV:CM:CV:CF:TD:CG:DJ:EG:GQ:ER:ET:FX:GF:GA:GM:GH:GI:GN:GW:IQ:CI:JO:KE:KZ:LB:LK:LS:LR:LY:NU:MG:MW:ML:MR:MU:YT:MC:MA:MN:MV:MZ:NA:NE:NG:PT:RW:SC:SM:ST:SN:SC:SL:SO:ZA:ES:SH:SD:SZ:TZ:TG:TN:UG:EH:ZM:ZW:CD:VA:AL:AM:AZ:BY:BA:BV:BG:HR:CY:CZ:EE:FO:MK:GE:GR:GL:HU:IS:IL:KZ:KG:LV:LI:LT:MT:MD:ME:RS:RO:RU:SK:SI:SY:TJ:TR:TM:UA:UZ:PS:SS&quot;, Account.ShippingCountry), &quot;EMEA&quot;,
IF(CONTAINS(&quot;JP:AS:AQ:AU:BN:KH:CN:CX:CC:CK:TP:FJ:PF:TF:GU:HM:HK:ID:KI:LA:MO:MY:MH:FM:MM:NR:NC:NZ:NU:NF:KP:MP:PW:PG:PH:PN:WS:SG:SB:KR:TW:TH:TK:TO:TM:TV:UM:VU:VN:WF&quot;, Account.ShippingCountry), &quot;APAC&quot;, &quot;Other&quot;))))</formula>
    <inlineHelpText>This field is populated from the Shipping Address on the Account</inlineHelpText>
    <label>Global Region</label>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Month_Rep_Target__c.field-meta.xml
<CustomField>
    <fullName>Month_Rep_Target__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Month Rep Target</label>
    <referenceTo>Month_Rep_Target__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Month_Territory_Target__c.field-meta.xml
<CustomField>
    <fullName>Month_Territory_Target__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Month Territory Target</label>
    <referenceTo>Month_Territory_Target__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Line</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/OpportunityLineItem/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <formula>PricebookEntry.Product2.product_line__c</formula>
    <label>Product Line</label>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/OpportunityLineItem/fields/Region_Product_Line_Target__c.field-meta.xml
<CustomField>
    <fullName>Region_Product_Line_Target__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region Product Line Target</label>
    <referenceTo>Region_Product_Line_Target__c</referenceTo>
    <relationshipLabel>Opportunity Product (Region Product Line Target)</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/OpportunityLineItem/fields/Rep_Product_Line_Target__c.field-meta.xml
<CustomField>
    <fullName>Rep_Product_Line_Target__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rep Product Line Target</label>
    <referenceTo>Rep_Product_Line_Target__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Region_Product_Line_Target__c/Region_Product_Line_Target__c.object-meta.xml
<CustomObject>
    <label>Region Product Line Target</label>
    <nameField>
        <displayFormat>RPLT-{0000}</displayFormat>
        <label>Region Product Line Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Region Product Line Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/Rep_Product_Line_Target__c/Rep_Product_Line_Target__c.object-meta.xml
<CustomObject>
    <label>Rep Product Line Target</label>
    <nameField>
        <displayFormat>RPLT-{0000}</displayFormat>
        <label>Rep Product Line Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rep Product Line Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/classes/GSP_batchTargetAssignment.cls
global class GSP_batchTargetAssignment implements Database.Batchable<sObject>, Database.Stateful
{
	private String strQuery;
	private String strObjectType;
	
	global GSP_batchTargetAssignment(String strObjectType)
	{
		System.debug('\n\nASSIGN TYPE: ' + strObjectType + '\n\n');
		this.strObjectType = strObjectType;
		if (strObjectType == 'OPPORTUNITY')
		{
			strQuery = 'SELECT Id, OwnerId, CloseDate, Month_Rep_Target__c, Territory2.Name FROM Opportunity WHERE Month_Rep_Target__c = null OR Month_Territory_Target__c = null';
		}
		else if (strObjectType == 'OPPORTUNITY_LINE_ITEM')
		{
			strQuery = 'SELECT Id, Product_Line__c, Rep_Product_Line_Target__c,  Region_Product_Line_Target__c, Opportunity.OwnerId,' +
				' Opportunity.CloseDate, Opportunity.Global_Region__c FROM OpportunityLineItem WHERE Rep_Product_Line_Target__c = null' +
				' OR Region_Product_Line_Target__c = null';
		}
		else
		{
			strQuery = 'SELECT Id, Product_Line__c, Global_Region__c, CreatedDate, Region_Product_Line_Target_Lead__c FROM Lead' +
				' WHERE Region_Product_Line_Target_Lead__c = null AND IsConverted = false';
		}
		
		if (Test.isRunningTest())
		{
			strQuery += ' LIMIT 1';
		}
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC)
	{
		return Database.getQueryLocator(strQuery);
	}
	
	global void execute(Database.BatchableContext BC, List<sObject> scope)
	{
		if (this.strObjectType == 'OPPORTUNITY')
		{
			GSP_targetAssignmentHelper.AssignOpportunityTargets((List<Opportunity>)scope);
		}
		else if (this.strObjectType == 'OPPORTUNITY_LINE_ITEM')
		{
			GSP_targetAssignmentHelper.AssignOpportunityLineItemTargets((List<OpportunityLineItem>) scope);
		}
		else if (this.strObjectType == 'LEAD')
		{
			GSP_targetAssignmentHelper.AssignLeadTargets((List<Lead>)scope);
		}	
	}
	
	global void finish(Database.BatchableContext BC)
	{
		Batch_Target_Settings__c batchSettings = Batch_Target_Settings__c.getValues('Default');
		
		// Process all lookups
		if (this.strObjectType == 'OPPORTUNITY')
		{
			GSP_batchTargetAssignment batch = new GSP_batchTargetAssignment('OPPORTUNITY_LINE_ITEM');
			Database.executeBatch(batch, Integer.valueOf(batchSettings.Line_Item_Target_Batch_Size__c));
		}
		else if (this.strObjectType == 'OPPORTUNITY_LINE_ITEM')
		{
			GSP_batchTargetAssignment batch = new GSP_batchTargetAssignment('LEAD');
			Database.executeBatch(batch, Integer.valueOf(batchSettings.Lead_Target_Batch_Size__c));
		}
		else if (this.strObjectType == 'LEAD')
		{
			// Start processing zeroing of fields
			GSP_batchZeroTargets batch = new GSP_batchZeroTargets('MONTH_REP_TARGET');
			Database.executeBatch(batch, Integer.valueOf(batchSettings.Zero_Month_Rep_Target_Batch_Size__c));
		}
	}
}