Perkin-UAT/force-app/main/default/objects/Batch_Target_Settings__c/Batch_Target_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Batch Target Settings</label>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/Batch_Target_Settings__c/fields/Lead_Metrics_Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Lead_Metrics_Batch_Size__c</fullName>
    <label>Lead Metrics Batch Size</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Batch_Target_Settings__c/fields/Product_Line_Metrics_Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Product_Line_Metrics_Batch_Size__c</fullName>
    <label>Product Line Metrics Batch Size</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Lead/fields/IGOR_PAC__c.field-meta.xml
<CustomField>
    <fullName>IGOR_PAC__c</fullName>
    <label>IGOR_PAC</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Lead/fields/Region_Product_Line_Target_Lead__c.field-meta.xml
<CustomField>
    <fullName>Region_Product_Line_Target_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region Product Line Target Lead</label>
    <referenceTo>Region_Product_Line_Target_Leads__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Month_Rep_Target__c/Month_Rep_Target__c.object-meta.xml
<CustomObject>
    <description>SBE: EH Only - Part of the custom AOP reporting package developed by GSP from the UK. One of several custom objects this object is used to store each sales person&#39;s monthly base &amp; stretch quotas and then compare against their current sales funnel</description>
    <label>Month Rep Target</label>
    <nameField>
        <displayFormat>MRT - {00000}</displayFormat>
        <label>Month Rep Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Month Rep Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/Month_Territory_Target__c/Month_Territory_Target__c.object-meta.xml
<CustomObject>
    <label>Month Territory Target</label>
    <nameField>
        <displayFormat>MTTN-{0000}</displayFormat>
        <label>Month Territory Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Month Territory Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Month_Rep_Target__c.field-meta.xml
<CustomField>
    <fullName>Month_Rep_Target__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Month Rep Target</label>
    <referenceTo>Month_Rep_Target__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Month_Territory_Target__c.field-meta.xml
<CustomField>
    <fullName>Month_Territory_Target__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Month Territory Target</label>
    <referenceTo>Month_Territory_Target__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/OpportunityLineItem/fields/IGOR_PAC__c.field-meta.xml
<CustomField>
    <fullName>IGOR_PAC__c</fullName>
    <formula>PricebookEntry.Product2.IGOR_PAC__c</formula>
    <label>IGOR_PAC</label>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/OpportunityLineItem/fields/Region_Product_Line_Target__c.field-meta.xml
<CustomField>
    <fullName>Region_Product_Line_Target__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region Product Line Target</label>
    <referenceTo>Region_Product_Line_Target__c</referenceTo>
    <relationshipLabel>Opportunity Product (Region Product Line Target)</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/OpportunityLineItem/fields/Rep_Product_Line_Target__c.field-meta.xml
<CustomField>
    <fullName>Rep_Product_Line_Target__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rep Product Line Target</label>
    <referenceTo>Rep_Product_Line_Target__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Region_Product_Line_Target__c/Region_Product_Line_Target__c.object-meta.xml
<CustomObject>
    <label>Region Product Line Target</label>
    <nameField>
        <displayFormat>RPLT-{0000}</displayFormat>
        <label>Region Product Line Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Region Product Line Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/Rep_Product_Line_Target__c/Rep_Product_Line_Target__c.object-meta.xml
<CustomObject>
    <label>Rep Product Line Target</label>
    <nameField>
        <displayFormat>RPLT-{0000}</displayFormat>
        <label>Rep Product Line Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rep Product Line Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/classes/GSP_batchTargetMetrics.cls
global class GSP_batchTargetMetrics  implements Database.Batchable<sObject>, Database.Stateful
{
	private String strObjectType;
	private String strQuery;
	
	global GSP_batchTargetMetrics(String strObjectType)
	{
		System.debug('\n\nMETRICS: ' + strObjectType + '\n\n');
		this.strObjectType = strObjectType;
		if (strObjectType == 'OPPORTUNITY')
		{
			strQuery = 'SELECT Id, IsClosed, IsWon, ForecastCategoryName, Month_Rep_Target__c, Month_Territory_Target__c, Amount' +
				' FROM Opportunity WHERE (Month_Rep_Target__c != null OR Month_Territory_Target__c != null) AND (CloseDate =' +
				' LAST_N_DAYS:365 OR CloseDate = THIS_MONTH OR CloseDate = NEXT_N_MONTHS:6) ORDER BY OwnerId';
		}
		else if (this.strObjectType == 'OPPORTUNITY_LINE_ITEM')
		{
			strQuery = 'SELECT Id, TotalPrice, Opportunity.ForecastCategoryName, IGOR_PAC__c, Rep_Product_Line_Target__c,' +
				' Region_Product_Line_Target__c, Opportunity.IsWon, Opportunity.IsClosed FROM OpportunityLineItem WHERE' +
				' (Rep_Product_Line_Target__c != null OR Region_Product_Line_Target__c != null) AND' +
				' (Opportunity.CloseDate = LAST_YEAR OR Opportunity.CloseDate = THIS_MONTH OR Opportunity.CloseDate = NEXT_N_MONTHS:6) ORDER BY Opportunity.OwnerId';
		}
		else if (this.strObjectType == 'LEAD')
		{
			strQuery = 'SELECT Id, Region_Product_Line_Target_Lead__c FROM Lead WHERE Region_Product_Line_Target_Lead__c != null' +
				' AND (CreatedDate = LAST_N_DAYS:365 OR CreatedDate = THIS_MONTH OR CreatedDate = NEXT_N_MONTHS:6)';
		}
		if (test.IsRunningTest())
		{
			strQuery += ' LIMIT 1';
		}
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC)
	{
		return Database.getQueryLocator(strQuery);
	}
	
	global void execute(Database.BatchableContext BC, List<sObject> scope)
	{
		if (this.strObjectType == 'OPPORTUNITY')
		{
			GSP_targetAssignmentHelper.SumOpportunityTargets((List<Opportunity>)scope);
		}
		else if (this.strObjectType == 'OPPORTUNITY_LINE_ITEM')
		{
			GSP_targetAssignmentHelper.SumProductLineTargets((List<OpportunityLineItem>)scope);
		}
		else if (this.strObjectType == 'LEAD')
		{
			GSP_targetAssignmentHelper.SumLeadTargets((List<Lead>)scope);
		}
	}
	
	global void finish(Database.BatchableContext BC)
	{
		Batch_Target_Settings__c batchSettings = Batch_Target_Settings__c.getValues('Default');
        if(!Test.isRunningTest()) {
            if (this.strObjectType == 'OPPORTUNITY')
            {
                GSP_batchTargetMetrics batch = new GSP_batchTargetMetrics('OPPORTUNITY_LINE_ITEM');
                Database.executebatch(batch, Integer.valueOf(batchSettings.Product_Line_Metrics_Batch_Size__c));
            }
            else if (this.strObjectType == 'OPPORTUNITY_LINE_ITEM')
            {
                GSP_batchTargetMetrics batch = new GSP_batchTargetMetrics('LEAD');
                Database.executebatch(batch, Integer.valueOf(batchSettings.Lead_Metrics_Batch_Size__c));
            }
            else
            {
                System.debug('\n\nDONE\n\n');
            }
        }
	}
}