Perkin-UAT/force-app/main/default/objects/B2B_Product_Shipping__c/B2B_Product_Shipping__c.object-meta.xml
<CustomObject>
    <description>This custom object is used to store the estimated shipping days and location for the product.</description>
    <label>B2B Product Shipping</label>
    <nameField>
        <displayFormat>SHP-{00000}</displayFormat>
        <label>Product Shipping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B2B Product Shippings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/B2B_Product_Shipping__c/fields/B2B_Estimated_Days__c.field-meta.xml
<CustomField>
    <fullName>B2B_Estimated_Days__c</fullName>
    <label>Estimated Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Product_Shipping__c/fields/B2B_Is_Active__c.field-meta.xml
<CustomField>
    <fullName>B2B_Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Product_Shipping__c/fields/B2B_Product__c.field-meta.xml
<CustomField>
    <fullName>B2B_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>B2B Product Shippings</relationshipLabel>
    <relationshipName>B2B_Product_Shippings</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Product_Shipping__c/fields/B2B_Sourcing_DC__c.field-meta.xml
<CustomField>
    <fullName>B2B_Sourcing_DC__c</fullName>
    <label>Sourcing DC</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1US6</fullName>
            </value>
            <value>
                <fullName>MXS1</fullName>
            </value>
            <value>
                <fullName>CL11</fullName>
            </value>
            <value>
                <fullName>B2S1</fullName>
            </value>
            <value>
                <fullName>TR11</fullName>
            </value>
            <value>
                <fullName>CN11</fullName>
            </value>
            <value>
                <fullName>TW11</fullName>
            </value>
            <value>
                <fullName>KRS1</fullName>
            </value>
            <value>
                <fullName>SGS2</fullName>
            </value>
            <value>
                <fullName>AUS1</fullName>
            </value>
            <value>
                <fullName>CNS1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/classes/B2B_SourcingDCInvocable.cls
public class B2B_SourcingDCInvocable {
    public class Request {
        @InvocableVariable(required=true)
        public String sourcingDC;

        @InvocableVariable(required=true)
        public List<String> productIdList;
    }

    public class Response {
        @InvocableVariable
        public List<B2B_Product_Shipping__c> productShippingList;
    }

    @InvocableMethod(label='Get Product Shipping List' description='Returns B2B_Product_Shipping__c records for given sourcingDC and productIdList')
    public static List<Response> getProductShippingList(List<Request> requests) {
        Set<String> allSourcingDCs = new Set<String>();
        Set<String> allProductIds = new Set<String>();
        Map<String, Set<String>> requestToProductIds = new Map<String, Set<String>>();

        // Collect all sourcingDCs and productIds
        for(Request req : requests) {
            if(req.sourcingDC != null) {
                List<String> sourcingDCList = req.sourcingDC.contains(';') ? req.sourcingDC.split(';') : new List<String>{req.sourcingDC};
                allSourcingDCs.addAll(sourcingDCList);
                requestToProductIds.put(req.sourcingDC, new Set<String>(req.productIdList));
                allProductIds.addAll(req.productIdList);
            }
        }

        // Query once
        List<B2B_Product_Shipping__c> allShippingRecords = [
            SELECT B2B_Estimated_Days__c, B2B_Sourcing_DC__c, B2B_Product__c
            FROM B2B_Product_Shipping__c
            WHERE B2B_Is_Active__c = true
            AND B2B_Sourcing_DC__c IN :allSourcingDCs
            AND B2B_Product__c IN :allProductIds
        ];

        // Map results for each request
        List<Response> responses = new List<Response>();
        for(Request req : requests) {
            Response res = new Response();
            List<String> sourcingDCList = req.sourcingDC.contains(';') ? req.sourcingDC.split(';') : new List<String>{req.sourcingDC};
            Set<String> productIdSet = new Set<String>(req.productIdList);

            res.productShippingList = new List<B2B_Product_Shipping__c>();
            for(B2B_Product_Shipping__c shipping : allShippingRecords) {
                if(sourcingDCList.contains(shipping.B2B_Sourcing_DC__c) && productIdSet.contains(shipping.B2B_Product__c)) {
                    res.productShippingList.add(shipping);
                }
            }
            responses.add(res);
        }
        return responses;
    }
}