Perkin-UAT/force-app/main/default/objects/Product2/fields/B2B_320X320_Large_Image_URL__c.field-meta.xml
<CustomField>
    <fullName>B2B_320X320_Large_Image_URL__c</fullName>
    <label>320X320 Large Image URL</label>
    <type>Url</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/B2B_Alternate_Products__c.field-meta.xml
<CustomField>
    <fullName>B2B_Alternate_Products__c</fullName>
    <label>B2B Alternate Products</label>
    <length>6000</length>
    <type>LongTextArea</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/B2B_Has_Related_Product__c.field-meta.xml
<CustomField>
    <fullName>B2B_Has_Related_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <label>B2B Has Related Product</label>
    <type>Checkbox</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/B2B_Large_Image_URL__c.field-meta.xml
<CustomField>
    <fullName>B2B_Large_Image_URL__c</fullName>
    <label>Large Image URL</label>
    <type>Url</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/B2B_Part_Number__c.field-meta.xml
<CustomField>
    <fullName>B2B_Part_Number__c</fullName>
    <label>Part Number</label>
    <length>255</length>
    <translateData>true</translateData>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/B2B_Sales_Org_And_Sales_Status__c.field-meta.xml
<CustomField>
    <fullName>B2B_Sales_Org_And_Sales_Status__c</fullName>
    <label>Sales Org And Sales Status</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1US0-Z3</fullName>
            </value>
            <value>
                <fullName>1US0-ZW</fullName>
            </value>
            <value>
                <fullName>1US0-ZY</fullName>
            </value>
            <value>
                <fullName>ATS0-Z3</fullName>
            </value>
            <value>
                <fullName>ATS0-ZW</fullName>
            </value>
            <value>
                <fullName>ATS0-ZY</fullName>
            </value>
            <value>
                <fullName>AUS0-ZW</fullName>
            </value>
            <value>
                <fullName>AUS0-ZY</fullName>
            </value>
            <value>
                <fullName>BES0-Z3</fullName>
            </value>
            <value>
                <fullName>BES0-ZW</fullName>
            </value>
            <value>
                <fullName>BES0-ZY</fullName>
            </value>
            <value>
                <fullName>BRS0-Z3</fullName>
            </value>
            <value>
                <fullName>BRS0-ZW</fullName>
            </value>
            <value>
                <fullName>BRS0-ZY</fullName>
            </value>
            <value>
                <fullName>CAS0-Z3</fullName>
            </value>
            <value>
                <fullName>CAS0-ZW</fullName>
            </value>
            <value>
                <fullName>CAS0-ZY</fullName>
            </value>
            <value>
                <fullName>CHS0-Z3</fullName>
            </value>
            <value>
                <fullName>CHS0-ZW</fullName>
            </value>
            <value>
                <fullName>CHS0-ZY</fullName>
            </value>
            <value>
                <fullName>CL10-ZW</fullName>
            </value>
            <value>
                <fullName>CL10-ZY</fullName>
            </value>
            <value>
                <fullName>CN10-9N</fullName>
            </value>
            <value>
                <fullName>CN10-ZW</fullName>
            </value>
            <value>
                <fullName>CN10-ZY</fullName>
            </value>
            <value>
                <fullName>DES0-Z3</fullName>
            </value>
            <value>
                <fullName>DES0-ZW</fullName>
            </value>
            <value>
                <fullName>DES0-ZY</fullName>
            </value>
            <value>
                <fullName>DKS0-Z3</fullName>
            </value>
            <value>
                <fullName>DKS0-ZW</fullName>
            </value>
            <value>
                <fullName>ESS0-ZY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/B2B_SKU__c.field-meta.xml
<CustomField>
    <fullName>B2B_SKU__c</fullName>
    <label>B2B SKU</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/classes/B2B_CreateRelatedProductsBatchTest.cls
@IsTest
public class B2B_CreateRelatedProductsBatchTest {
    
    @IsTest
    static void B2B_CreateProductMediaBatch_Test() {
        // Arrange
        Test.startTest();
        List<Product2> prodList = new List<Product2>();
        Product2 prod = new Product2(
            Name = 'Test Product',
            B2B_Part_Number__c = 'B2B_Part_Number__c',
            B2B_Large_Image_URL__c = 'http://www.perkinelmer.com/sample1.jpg',	//'https://example.com/sample1.jpg'
            B2B_320X320_Large_Image_URL__c = 'http://www.perkinelmer.com/sample1.jpg',
            B2B_Alternate_Products__c = 'Child',
            B2B_SKU__c = 'Parent',
            B2B_Has_Related_Product__c = true,
            B2B_Sales_Org_And_Sales_Status__c = 'ESS0-ZY'
        );
        prodList.add( prod );
        Product2 prod2 = new Product2(
            Name = 'Child Test Product',
            B2B_Part_Number__c = 'Child B2B_Part_Number__c',
            B2B_Large_Image_URL__c = 'http://www.perkinelmer.com/sample1.jpg',	//'https://example.com/sample1.jpg'
            B2B_320X320_Large_Image_URL__c = 'http://www.perkinelmer.com/sample1.jpg',
            B2B_SKU__c = 'Child',
            B2B_Sales_Org_And_Sales_Status__c = 'ESS0-ZY'
        );
        prodList.add( prod2 );
        insert prodList;

        String query = 'SELECT Id, B2B_Alternate_Products__c, B2B_SKU__c FROM Product2 where B2B_Has_Related_Product__c = true';
        B2B_CreateRelatedProductsBatch obj = new B2B_CreateRelatedProductsBatch( query );
        Id batchInstanceId = Database.executeBatch(obj, 5);
        Test.stopTest();
        // Assertions
        List<ProductMedia> productMedia = [SELECT Id FROM ProductMedia WHERE ProductId = :prod.Id];
        System.assertEquals(0, productMedia.size(), 'ProductMedia should be created for all images');
    }
}