Perkin-UAT/force-app/main/default/objects/Month_Rep_Target__c/Month_Rep_Target__c.object-meta.xml
<CustomObject>
    <description>SBE: EH Only - Part of the custom AOP reporting package developed by GSP from the UK. One of several custom objects this object is used to store each sales person&#39;s monthly base &amp; stretch quotas and then compare against their current sales funnel</description>
    <label>Month Rep Target</label>
    <nameField>
        <displayFormat>MRT - {00000}</displayFormat>
        <label>Month Rep Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Month Rep Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/Month_Territory_Target__c/Month_Territory_Target__c.object-meta.xml
<CustomObject>
    <label>Month Territory Target</label>
    <nameField>
        <displayFormat>MTTN-{0000}</displayFormat>
        <label>Month Territory Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Month Territory Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Month_Rep_Target__c.field-meta.xml
<CustomField>
    <fullName>Month_Rep_Target__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Month Rep Target</label>
    <referenceTo>Month_Rep_Target__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Month_Territory_Target__c.field-meta.xml
<CustomField>
    <fullName>Month_Territory_Target__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Month Territory Target</label>
    <referenceTo>Month_Territory_Target__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/OpportunityLineItem/fields/Region_Product_Line_Target__c.field-meta.xml
<CustomField>
    <fullName>Region_Product_Line_Target__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region Product Line Target</label>
    <referenceTo>Region_Product_Line_Target__c</referenceTo>
    <relationshipLabel>Opportunity Product (Region Product Line Target)</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/OpportunityLineItem/fields/Rep_Product_Line_Target__c.field-meta.xml
<CustomField>
    <fullName>Rep_Product_Line_Target__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rep Product Line Target</label>
    <referenceTo>Rep_Product_Line_Target__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Region_Product_Line_Target__c/Region_Product_Line_Target__c.object-meta.xml
<CustomObject>
    <label>Region Product Line Target</label>
    <nameField>
        <displayFormat>RPLT-{0000}</displayFormat>
        <label>Region Product Line Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Region Product Line Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/Rep_Product_Line_Target__c/Rep_Product_Line_Target__c.object-meta.xml
<CustomObject>
    <label>Rep Product Line Target</label>
    <nameField>
        <displayFormat>RPLT-{0000}</displayFormat>
        <label>Rep Product Line Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rep Product Line Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/classes/GSP_trgOpportunityMethods.cls
public with sharing class GSP_trgOpportunityMethods
{
    public static void UpdateTargets(Map<Id, Opportunity> opportunityMap)
    {
        for (Opportunity opportunity : opportunityMap.values())
        {
            opportunity.Month_Territory_Target__c = null;
            opportunity.Month_Rep_Target__c = null;
        }
        
        List<OpportunityLineItem> opportunityLineItems = new List<OpportunityLineItem>([
            SELECT
                Id,
                Region_Product_Line_Target__c,
                Rep_Product_Line_Target__c
            FROM
                OpportunityLineItem
            WHERE
                OpportunityId IN :opportunityMap.keySet()]);
        for (OpportunityLineItem opportunityLineItem : opportunityLineItems)
        {
            opportunityLineItem.Region_Product_Line_Target__c = null;
            opportunityLineItem.Rep_Product_Line_Target__c = null;
        }
        
        if (!opportunityLineItems.isEmpty())
        {
            update opportunityLineItems;
        }
    }
}