Perkin-UAT/force-app/main/default/objects/SIOP_Model_Cutoff__c/SIOP_Model_Cutoff__c.object-meta.xml
<CustomObject>
    <description>These will be the cutiff dates for the SIOP Model Entry</description>
    <label>SIOP Model Cutoff</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>SIOP Model Cutoff Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SIOP Model Cutoff</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/SIOP_Model_Cutoff__c/fields/CutoffDate__c.field-meta.xml
<CustomField>
    <fullName>CutoffDate__c</fullName>
    <inlineHelpText>Enter the Cutoff Date for each  Month and Year</inlineHelpText>
    <label>Cutoff Date</label>
    <type>Date</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SIOP_Model_Data__c/SIOP_Model_Data__c.object-meta.xml
<CustomObject>
    <label>SIOP Model Data</label>
    <nameField>
        <label>SIOP Data</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SIOP Model Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/SIOP_Model_Data__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>G_PICK_021_Territory_Super</valueSetName>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SIOP_Model_Data__c/fields/SIOP_Model_Master__c.field-meta.xml
<CustomField>
    <fullName>SIOP_Model_Master__c</fullName>
    <label>SIOP Model Master</label>
    <referenceTo>SIOP_Model_Master__c</referenceTo>
    <relationshipLabel>SIOP_Model_Data</relationshipLabel>
    <relationshipName>SIOP_Model_Data</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SIOP_Model_Data__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>G_PICK_450_SIOP_Data_Type</valueSetName>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SIOP_Model_Master__c/SIOP_Model_Master__c.object-meta.xml
<CustomObject>
    <label>SIOP Model Master</label>
    <nameField>
        <label>SIOP Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SIOP Model Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/SIOP_Model_Master__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <description>The Product line for the linked Product</description>
    <label>Product Line</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SIOP_Model_Master__c/fields/Product_Line_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_Line_Description__c</fullName>
    <description>The Product line for the linked Product</description>
    <label>Product Line Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/classes/SIOP_Create_Data_Fields_test.cls
/**
 * Class:SIOP_Create_Data_Fields_test
 * Author: (PWC)Vishwas
 * Created Date:29 july,2020
 * Functionality: test class for scheduler and batch apex class schedule_SIOP_Create_Data_Fields, SIOP_Create_Data_Fields respectively:ticket No.ITSFDC-2405
 */
@isTest 
public class SIOP_Create_Data_Fields_test {

    @testSetup static void setup() {
        // SELECT Id, Name, CutoffDate__c FROM SIOP_Model_Cutoff__c
        SIOP_Model_Cutoff__c SMC = new SIOP_Model_Cutoff__c();
        SMC.CutoffDate__c=Date.newInstance(Date.today().year(), Date.today().Month(), 5);
        insert SMC;
        // Create common test SIOP_Model_Master__c
        list<SIOP_Model_Master__c> mlist = new list<SIOP_Model_Master__c>();
        for(integer i=0;i<10;i++){
          SIOP_Model_Master__c testSIOPMaster = new SIOP_Model_Master__c();
		testSIOPMaster.name='test Master'+i;
		testSIOPMaster.Product_Line__c='test product line'+i;
		testSIOPMaster.Product_Line_Description__c='test Product Line Description'+i; 
            mlist.add(testSIOPMaster);
        }
        
		insert mlist;
        list<string> regions= new list<string>{'EMEAI','APAC','AMERICAS'};
        list<SIOP_Model_Data__c> dlist = new List<SIOP_Model_Data__c>();
        for(SIOP_Model_Master__c testSIOPMaster:mlist){
            for(string str:regions){
		SIOP_Model_Data__c testSIOPData = new SIOP_Model_Data__c();
		testSIOPData.name='07,2020.Actual.EMEAI.test Master';
		testSIOPData.Type__c='Actual';
		testSIOPData.Region__c=str;
		testSIOPData.Date__c=Date.newInstance(Date.today().year(), Date.today().addMonths(1).Month(), 27); 
		testSIOPData.SIOP_Model_Master__c=testSIOPMaster.id;
        dlist.add(testSIOPData);
       SIOP_Model_Data__c testSIOPData1 = new SIOP_Model_Data__c();
		testSIOPData1.name='07,2020.Region Ask-Orders.EMEAI.test Master';
		testSIOPData1.Type__c='Region Ask-Orders';
		testSIOPData1.Region__c=str;
		testSIOPData1.Date__c=Date.newInstance(Date.today().year(), Date.today().addMonths(1).Month(), 27); 
		testSIOPData1.SIOP_Model_Master__c=testSIOPMaster.id;
       dlist.add(testSIOPData1);
        SIOP_Model_Data__c testSIOPData0 = new SIOP_Model_Data__c();
		testSIOPData0.name='07,2020.Region Ask-Shipment.EMEAI.test Master';
		testSIOPData0.Type__c='Region Ask-Shipment';
		testSIOPData0.Region__c=str;
		testSIOPData0.Date__c=Date.newInstance(Date.today().year(), Date.today().addMonths(1).Month(), 27); 
		testSIOPData0.SIOP_Model_Master__c=testSIOPMaster.id;
       dlist.add(testSIOPData0);         
        SIOP_Model_Data__c testSIOPData2 = new SIOP_Model_Data__c();
		testSIOPData2.name='07,2020.PM Ask.EMEAI.test Master';
		testSIOPData2.Type__c='PM Ask';
		testSIOPData2.Region__c=str;
		testSIOPData2.Date__c=Date.newInstance(Date.today().year(),Date.today().addMonths(1).Month(), 27); 
		testSIOPData2.SIOP_Model_Master__c=testSIOPMaster.id;
        dlist.add(testSIOPData2);
        SIOP_Model_Data__c testSIOPData3 = new SIOP_Model_Data__c();
		testSIOPData3.name='07,2020.Final SIOP.EMEAI.test Master';
		testSIOPData3.Type__c='Final SIOP';
		testSIOPData3.Region__c=str;
		testSIOPData3.Date__c=Date.newInstance(Date.today().year(), Date.today().addMonths(1).Month(), 27); 
		testSIOPData3.SIOP_Model_Master__c=testSIOPMaster.id;
       dlist.add(testSIOPData3); 
        }
     }
        insert dlist;
    }


    static testMethod void testMethod1(){
        Test.startTest();
           // SIOP_Create_Data_Fields obj = new SIOP_Create_Data_Fields();
           //  DataBase.executeBatch(obj);
           schedule_SIOP_Create_Data_Fields obj = new schedule_SIOP_Create_Data_Fields();
            String sch = '0 0 20 * * ?';
          String jobID = system.schedule('Merge Job', sch, obj); 
            
        Test.stopTest();
    }
}