Perkin-UAT/force-app/main/default/objects/Custom_Exception__c/Custom_Exception__c.object-meta.xml
<CustomObject>
    <description>To Get the Batch_EnableRenewalQuotedOnContracts Class  Exception logs in this Custom object</description>
    <label>Custom Exception</label>
    <nameField>
        <label>Custom Exception Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/Custom_Exception__c/fields/Cart_Id__c.field-meta.xml
<CustomField>
    <fullName>Cart_Id__c</fullName>
    <description>To store cart id.</description>
    <label>Cart Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Custom_Exception__c/fields/Extended_Status__c.field-meta.xml
<CustomField>
    <fullName>Extended_Status__c</fullName>
    <label>Extended Status</label>
    <length>131071</length>
    <type>LongTextArea</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Custom_Exception__c/fields/Request_JSON__c.field-meta.xml
<CustomField>
    <fullName>Request_JSON__c</fullName>
    <label>Request JSON</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Custom_Exception__c/fields/Response_JSON__c.field-meta.xml
<CustomField>
    <fullName>Response_JSON__c</fullName>
    <label>Response JSON</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Perkin-UAT/force-app/main/default/classes/LogEntryController.cls
public without sharing class LogEntryController {
  public static void log(
    String requestBody,
    HttpResponse response,
    String apiName,
    Id cartId
  ) {
    String responseBody = response != null ? response.getBody() : 'No Response';
    String statusCode = response != null
      ? String.valueOf(response.getStatusCode())
      : 'N/A';

    logAsync(requestBody, responseBody, statusCode, apiName, cartId);
  }

  @future(callout=true)
  public static void logAsync(
    String requestBody,
    String responseBody,
    String statusCode,
    String apiName,
    Id cartId
  ) {
    List<Custom_Exception__c> existingLogs = [
      SELECT Id
      FROM Custom_Exception__c
      WHERE Cart_Id__c = :cartId
      LIMIT 1
    ];

    if (!existingLogs.isEmpty()) {
      Custom_Exception__c existingLog = existingLogs[0];
      existingLog.Request_JSON__c = requestBody;
      existingLog.Response_JSON__c = responseBody;
      existingLog.Extended_Status__c = statusCode;
      existingLog.Exception_Type__c = apiName;
      update existingLog;
    } else {
      Custom_Exception__c newLog = new Custom_Exception__c();
      newLog.Cart_Id__c = cartId;
      newLog.Request_JSON__c = requestBody;
      newLog.Response_JSON__c = responseBody;
      newLog.Extended_Status__c = statusCode;
      newLog.Exception_Type__c = apiName;
      insert newLog;
    }
  }
}