Perkin-UAT/force-app/main/default/objects/B2B_Commerce_Category__c/B2B_Commerce_Category__c.object-meta.xml
<CustomObject>
    <label>B2B Commerce Category</label>
    <nameField>
        <displayFormat>BCC-{0000}</displayFormat>
        <label>B2B Commerce Category Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B2B Commerce Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/B2B_Commerce_Category__c/fields/Child_Category__c.field-meta.xml
<CustomField>
    <fullName>Child_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Child Category</label>
    <referenceTo>ProductCategory</referenceTo>
    <relationshipLabel>B2B Commerce Categories (Child Category)</relationshipLabel>
    <relationshipName>B2B_Commerce_Categories1</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Commerce_Category__c/fields/Parent_Category__c.field-meta.xml
<CustomField>
    <fullName>Parent_Category__c</fullName>
    <label>Parent Category</label>
    <referenceTo>ProductCategory</referenceTo>
    <relationshipLabel>B2B Commerce Categories</relationshipLabel>
    <relationshipName>B2B_Commerce_Categories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Commerce_Category__c/fields/Technology_Type__c.field-meta.xml
<CustomField>
    <fullName>Technology_Type__c</fullName>
    <label>Technology Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Atomic Spectroscopy</fullName>
            </value>
            <value>
                <fullName>Chromatography</fullName>
            </value>
            <value>
                <fullName>Food Quality</fullName>
            </value>
            <value>
                <fullName>Molecular Spectroscopy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/ProductCategory/fields/B2B_Featured_Category__c.field-meta.xml
<CustomField>
    <fullName>B2B_Featured_Category__c</fullName>
    <defaultValue>false</defaultValue>
    <label>B2B Featured Category</label>
    <type>Checkbox</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/ProductCategory/fields/B2B_Featured_Category_Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>B2B_Featured_Category_Sort_Order__c</fullName>
    <label>B2B Featured Category Sort Order</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

Perkin-UAT/force-app/main/default/classes/B2B_CategoryNavTableControllerTest.cls
@IsTest
public class B2B_CategoryNavTableControllerTest {

    @TestSetup 
    static void makeData(){
        WebStore webStore = B2B_TestDataFactory.createWebstore('TestWebStore',true);
        ProductCatalog catalog = B2B_TestDataFactory.createProductCatalog('Test Catalog', true);
        ProductCategory category = B2B_TestDataFactory.createProductCategory('Test Category', catalog.Id, true); 
        ProductCategory category1 = B2B_TestDataFactory.createProductCategory('Test Category2', catalog.Id, true);
    }
    
    @isTest 
    static void testGetFeaturedCategories_Success() {
        Map<String,Object> mapParamsInput = new Map<String,Object>();
        Map<String,Object> result = new Map<String,Object>();

        Test.StartTest();
        ProductCategory category = [
            SELECT Id, B2B_Featured_Category__c, B2B_Featured_Category_Sort_Order__c
            FROM ProductCategory 
            WHERE Name = 'Test Category' 
            LIMIT 1
        ];
        
        ProductCategory category1 = [
            SELECT Id, B2B_Featured_Category__c, B2B_Featured_Category_Sort_Order__c
            FROM ProductCategory 
            WHERE Name = 'Test Category2' 
            LIMIT 1
        ];

        List<B2B_Commerce_Category__c> listToInsert = new List<B2B_Commerce_Category__c>();
        B2B_Commerce_Category__c commCat1 = new B2B_Commerce_Category__c(
        	Active__c = true,
            Label__c = 'Label__c',
            Parent_Category__c = category.Id,
            Child_Category__c = category1.Id,
            Technology_Type__c = 'Technology_Type__c'
        );
        listToInsert.add(commCat1);
        B2B_Commerce_Category__c commCat = new B2B_Commerce_Category__c(
        	Active__c = true,
            Label__c = 'Label__c',
            Parent_Category__c = category.Id,
            Child_Category__c = category.Id,
            Technology_Type__c = 'Technology_Type__c'
        );
        listToInsert.add(commCat);
        insert listToInsert;
        
        
        mapParamsInput.put('categoryId',category.Id);
        B2B_CategoryNavTableController obj = new B2B_CategoryNavTableController();
        B2B_CategoryNavTableService o = new B2B_CategoryNavTableService();
        result = B2B_CategoryNavTableController.fetchChildCategories(mapParamsInput);
        Test.StopTest();
        
        System.assertEquals(true, (Boolean)result.get('isSuccess'), 'Expected success when featured categories exist');
    }
    
    @isTest 
    static void testGetFeaturedCategories_Error() {
        Map<String,Object> mapParamsInput = new Map<String,Object>();
        Map<String,Object> result = new Map<String,Object>();

        Test.StartTest();
        result = B2B_CategoryNavTableController.fetchChildCategories(null);
        Test.StopTest();
        
        System.assertEquals(false, (Boolean)result.get('isSuccess'), 'Expected success when featured categories exist');
    }
    
    @isTest 
    static void testGetFeaturedCategories_Error1() {
        Map<String,Object> mapParamsInput = new Map<String,Object>();
        Map<String,Object> result = new Map<String,Object>();

        Test.StartTest();
        result = B2B_CategoryNavTableController.fetchChildCategories(mapParamsInput);
        Test.StopTest();
        
        System.assertEquals(false, (Boolean)result.get('isSuccess'), 'Expected success when featured categories exist');
    }
    
    @isTest 
    static void testGetFeaturedCategories_Error2() {
        Map<String,Object> mapParamsInput = new Map<String,Object>();
        Map<String,Object> result = new Map<String,Object>();
		mapParamsInput.put('categoryId',null);
        Test.StartTest();
        result = B2B_CategoryNavTableController.fetchChildCategories(mapParamsInput);
        Test.StopTest();
        
        System.assertEquals(false, (Boolean)result.get('isSuccess'), 'Expected success when featured categories exist');
    }
}