Perkin-UAT/force-app/main/default/objects/B2B_Commerce_Category__c/B2B_Commerce_Category__c.object-meta.xml
<CustomObject>
    <label>B2B Commerce Category</label>
    <nameField>
        <displayFormat>BCC-{0000}</displayFormat>
        <label>B2B Commerce Category Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B2B Commerce Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/B2B_Commerce_Category__c/fields/Child_Category__c.field-meta.xml
<CustomField>
    <fullName>Child_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Child Category</label>
    <referenceTo>ProductCategory</referenceTo>
    <relationshipLabel>B2B Commerce Categories (Child Category)</relationshipLabel>
    <relationshipName>B2B_Commerce_Categories1</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Commerce_Category__c/fields/Parent_Category__c.field-meta.xml
<CustomField>
    <fullName>Parent_Category__c</fullName>
    <label>Parent Category</label>
    <referenceTo>ProductCategory</referenceTo>
    <relationshipLabel>B2B Commerce Categories</relationshipLabel>
    <relationshipName>B2B_Commerce_Categories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/B2B_Commerce_Category__c/fields/Technology_Type__c.field-meta.xml
<CustomField>
    <fullName>Technology_Type__c</fullName>
    <label>Technology Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Atomic Spectroscopy</fullName>
            </value>
            <value>
                <fullName>Chromatography</fullName>
            </value>
            <value>
                <fullName>Food Quality</fullName>
            </value>
            <value>
                <fullName>Molecular Spectroscopy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/classes/B2B_CategoryNavTableService.cls
/**
 * @description       : 
 * @author            : Suhail Ahmed T 
 * @group             : 
 * @last modified on  : 03-04-2026
 * @last modified by  : Suhail Ahmed T 
**/
// test class- B2B_CategoryNavTableControllerTest
public without sharing class B2B_CategoryNavTableService {
    private static String firstCategoryLabel = 'Kits & Bundles';
    private static String lastCategoryLabel = 'Other Parts';
    public B2B_CategoryNavTableService() {

    }

    public static Map<String,Object> fetchChildCategories(Map<String,Object> mapParams){
        Boolean isSuccess = false;
        String message = '';
        System.debug('fetchChildCategories mapParams-- '+JSON.serialize(mapParams));
        if( mapParams.containsKey('categoryId') ){
            String categoryId = (String)mapParams.get('categoryId');
            if( String.isNotBlank( categoryId ) ){
                List<B2B_Commerce_Category__c> childCategoryList = new List<B2B_Commerce_Category__c>();
                if ( Schema.sObjectType.B2B_Commerce_Category__c.isAccessible() ) {
                    childCategoryList = [SELECT Id, Name, Active__c, Label__c, Parent_Category__c, Child_Category__c, Technology_Type__c 
                                         FROM B2B_Commerce_Category__c 
                                         WHERE Parent_Category__c = :categoryId AND Active__c = true 
                                         
                                        ORDER BY Technology_Type__c,Label__c];
                } else {
                    message = System.Label.B2B_Commerce_Category_Object_Access_Error;
                }
                if( ! childCategoryList.isEmpty() ){
                    Map<String,List<Object>> childCategoryMap = new Map<String,List<Object>>();
                    for( B2B_Commerce_Category__c childCategory : childCategoryList ){
                        List<Object> categoryList = !childCategoryMap.containsKey( childCategory.Technology_Type__c ) ?
                            new List<Object>() :
                        childCategoryMap.get(childCategory.Technology_Type__c);
                       
                         
                        if(childCategory.Label__c == firstCategoryLabel){
                            categoryList.add(0,childCategory);
                        }else if(childCategory.Label__c == lastCategoryLabel){
                            categoryList.add(1,childCategory);
                        }else{
                            categoryList.add(childCategory);
                        }
                        childCategoryMap.put(childCategory.Technology_Type__c ,categoryList );
                        
                    }
                    List<CategoryWrapper> categoryWrapperList = new List<CategoryWrapper>();
                    for( String technologyType : childCategoryMap.keySet() ){
                        CategoryWrapper wrap = new CategoryWrapper();
                        wrap.technologyType = technologyType;
                        List<Object> categoryList = childCategoryMap.get(technologyType);
                        if(!categoryList.isEmpty()){
                            if(categoryList.size() > 2 && 
                               ((B2B_Commerce_Category__c)categoryList[1]).Label__c == lastCategoryLabel){
                                categoryList.add(categoryList[1]);
                                categoryList.remove(1);
                            }
                        }
                        wrap.childCategoryList = categoryList;
                        categoryWrapperList.add(wrap);
                    }
                    mapParams.put('childCategoryMap', childCategoryMap);
                    mapParams.put('categoryWrapperList', categoryWrapperList);
                    isSuccess = true;
                }
                else{
                    message = System.Label.B2B_Commerce_Category_No_Child_Error;
                }
            }
            else{
                message = System.Label.B2B_Commerce_Category_Id_Blank_Error;
            }
        }
         else{
            message = System.Label.B2B_Commerce_Category_Id_Blank_Error;
        }
        mapParams.put('isSuccess', isSuccess);
        mapParams.put('message', message);
        return mapParams;
    }

    public class CategoryWrapper {
        @AuraEnabled
        public String technologyType;
        @AuraEnabled
        public List<Object> childCategoryList;
    }
}