Perkin-UAT/force-app/main/default/objects/Contact/fields/Lead_Owner_LDR_Conversion__c.field-meta.xml
<CustomField>
    <fullName>Lead_Owner_LDR_Conversion__c</fullName>
    <description>ANNUITAS PDG Program</description>
    <label>Lead Owner - LDR Conversion</label>
    <type>TextArea</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Contact/fields/Solution_Area_of_Interest__c.field-meta.xml
<CustomField>
    <fullName>Solution_Area_of_Interest__c</fullName>
    <description>ORIG:ANNUITAS PDG Program

NEW: SS This field is now used on Interaction, Interaction Assignment Rule, Lead, Contact, Oppty</description>
    <label>Solution Area of Interest</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Air</fullName>
            </value>
            <value>
                <fullName>Applied Genomics</fullName>
            </value>
            <value>
                <fullName>Biologics</fullName>
            </value>
            <value>
                <fullName>Cannabis</fullName>
            </value>
            <value>
                <fullName>Cell and Gene Therapy</fullName>
            </value>
            <value>
                <fullName>Chemicals</fullName>
            </value>
            <value>
                <fullName>Clinical Studies</fullName>
            </value>
            <value>
                <fullName>Digital Lab</fullName>
            </value>
            <value>
                <fullName>Energy</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Forensics and Security</fullName>
            </value>
            <value>
                <fullName>Geochemistry, Mining and Metals</fullName>
            </value>
            <value>
                <fullName>Life Science Research</fullName>
            </value>
            <value>
                <fullName>Material</fullName>
            </value>
            <value>
                <fullName>Maternal Fetal Health</fullName>
            </value>
            <value>
                <fullName>Newborn Screening</fullName>
            </value>
            <value>
                <fullName>Pre-Clinical Drug Development</fullName>
            </value>
            <value>
                <fullName>Pre-Clinical Drug Discovery</fullName>
            </value>
            <value>
                <fullName>QA/QC Drug Manufacturing Process</fullName>
            </value>
            <value>
                <fullName>Soil/Solids</fullName>
            </value>
            <value>
                <fullName>Strategic Services</fullName>
            </value>
            <value>
                <fullName>Water</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Account_Type_INF__c.field-meta.xml
<CustomField>
    <fullName>Account_Type_INF__c</fullName>
    <description>This field is used within Informatics quote process to drive related Price List.  Do not modify without contacting Informatics SalesForce.com support</description>
    <inlineHelpText>Price List requires Acct Type</inlineHelpText>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Commercial</fullName>
                <default>true</default>
                <label>Commercial</label>
            </value>
            <value>
                <fullName>Academic</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <description>Identify Customer Industry Application. Standardized Names (no double spaces, no space after slash, spaces before and after &#39;&amp;&#39;, use &#39;&amp;&#39; vs &#39;and&#39;, space after commas, lists do not have comma before last item and use &#39;&amp;&#39; before last item)</description>
    <label>Application</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Application_Market__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agricultural Genetics</fullName>
            </value>
            <value>
                <fullName>Agriculture Research</fullName>
            </value>
            <value>
                <fullName>Agrigenomics</fullName>
            </value>
            <value>
                <fullName>Air Testing</fullName>
            </value>
            <value>
                <fullName>Allergy DX</fullName>
            </value>
            <value>
                <fullName>Ancestry</fullName>
            </value>
            <value>
                <fullName>Animal Diagnostics</fullName>
            </value>
            <value>
                <fullName>Antibiotics</fullName>
            </value>
            <value>
                <fullName>API/Compound Analysis</fullName>
            </value>
            <value>
                <fullName>Authenticity &amp; Adulteration</fullName>
            </value>
            <value>
                <fullName>Autoimmun DX</fullName>
            </value>
            <value>
                <fullName>Automated Systems</fullName>
            </value>
            <value>
                <fullName>Basic Research</fullName>
            </value>
            <value>
                <fullName>Batteries, Power &amp; Utilities</fullName>
            </value>
            <value>
                <fullName>Beverages</fullName>
            </value>
            <value>
                <fullName>Biological Pathogens &amp; Toxins</fullName>
            </value>
            <value>
                <fullName>Biologics Development ADME/Tox</fullName>
            </value>
            <value>
                <fullName>Biologics Development Cell line development</fullName>
            </value>
            <value>
                <fullName>Biologics Development GLP Pre-clinical studies</fullName>
            </value>
            <value>
                <fullName>Biologics Development GLP Safety/Tox</fullName>
            </value>
            <value>
                <fullName>Biologics Lot Release</fullName>
            </value>
            <value>
                <fullName>Biomarker Development</fullName>
            </value>
            <value>
                <fullName>Biophysical characterization</fullName>
            </value>
            <value>
                <fullName>BioTherapeutic Manufacturing</fullName>
            </value>
            <value>
                <fullName>Blood Screening</fullName>
            </value>
            <value>
                <fullName>Bone Metabolism</fullName>
            </value>
            <value>
                <fullName>Cannabis/Hemp</fullName>
            </value>
            <value>
                <fullName>Cell Culture</fullName>
            </value>
            <value>
                <fullName>Chemical Food Safety</fullName>
            </value>
            <value>
                <fullName>Chemicals &amp; Mining</fullName>
            </value>
            <value>
                <fullName>Virology</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Application_Market__c.field-meta.xml
<CustomField>
    <fullName>Application_Market__c</fullName>
    <description>Identify Customer Market. Standardized Names (no double spaces, no space after slash, spaces before and after &#39;&amp;&#39;, use &#39;&amp;&#39; vs &#39;and&#39;, space after commas, lists do not have comma before last item and use &#39;&amp;&#39; before last item)</description>
    <label>Application Market</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Application_Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Academia &amp; Academic Research</fullName>
            </value>
            <value>
                <fullName>Air</fullName>
            </value>
            <value>
                <fullName>Alcoholic &amp; Non-Alcoholic Beverages</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Applied Genomics</fullName>
            </value>
            <value>
                <fullName>Basic Research</fullName>
            </value>
            <value>
                <fullName>Biologics/Vaccines Drug Development</fullName>
            </value>
            <value>
                <fullName>Biologics Manufacturing QA/QC</fullName>
            </value>
            <value>
                <fullName>Cannabis/Hemp</fullName>
            </value>
            <value>
                <fullName>Chemicals</fullName>
            </value>
            <value>
                <fullName>Chemicals &amp; Mining</fullName>
            </value>
            <value>
                <fullName>Clinical Diagnostics</fullName>
            </value>
            <value>
                <fullName>Contract Lab</fullName>
            </value>
            <value>
                <fullName>Dairy</fullName>
            </value>
            <value>
                <fullName>Detection</fullName>
            </value>
            <value>
                <fullName>Drug Discovery</fullName>
            </value>
            <value>
                <fullName>Drug QA/QC Manufacturing</fullName>
            </value>
            <value>
                <fullName>Edible Oils</fullName>
            </value>
            <value>
                <fullName>Energy</fullName>
            </value>
            <value>
                <fullName>Energy &amp; Petrochem</fullName>
            </value>
            <value>
                <fullName>Environmental</fullName>
            </value>
            <value>
                <fullName>Flavor &amp; Fragrance</fullName>
            </value>
            <value>
                <fullName>Forensics &amp; Security</fullName>
            </value>
            <value>
                <fullName>Fruits &amp; Vegetables</fullName>
            </value>
            <value>
                <fullName>Government/Academic</fullName>
            </value>
            <value>
                <fullName>Government &amp; Academia</fullName>
            </value>
            <value>
                <fullName>Imaging</fullName>
            </value>
            <value>
                <fullName>Immunodiagnostics</fullName>
            </value>
            <value>
                <fullName>Material</fullName>
            </value>
            <value>
                <fullName>Materials</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Application_Segment__c.field-meta.xml
<CustomField>
    <fullName>Application_Segment__c</fullName>
    <defaultValue>if($RecordType.DeveloperName =&#39;Informatics&#39;,&#39;Informatics&#39;,null)</defaultValue>
    <description>Identify Customer Industry</description>
    <label>Application Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>COVID</fullName>
            </value>
            <value>
                <fullName>Diagnostics</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Informatics</fullName>
            </value>
            <value>
                <fullName>Life Science</fullName>
            </value>
            <value>
                <fullName>Environmental</fullName>
                <isActive>false</isActive>
                <label>Environmental</label>
            </value>
            <value>
                <fullName>Food And Agriculture</fullName>
                <isActive>false</isActive>
                <label>Food And Agriculture</label>
            </value>
            <value>
                <fullName>Human Health &amp; Life Sciences</fullName>
                <isActive>false</isActive>
                <label>Human Health &amp; Life Sciences</label>
            </value>
            <value>
                <fullName>Human Health and Life Sciences</fullName>
                <isActive>false</isActive>
                <label>Human Health and Life Sciences</label>
            </value>
            <value>
                <fullName>Industrial</fullName>
                <isActive>false</isActive>
                <label>Industrial</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Renewal_Required_INF__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Required_INF__c</fullName>
    <label>Renewal Required?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Strategic_Market_INF__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Market_INF__c</fullName>
    <label>Strategic Market</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Life Sciences Research</fullName>
            </value>
            <value>
                <fullName>Clinical &amp; Translational</fullName>
            </value>
            <value>
                <fullName>Related Markets</fullName>
            </value>
            <value>
                <fullName>Production Support</fullName>
            </value>
            <value>
                <fullName>Academic &amp; Government</fullName>
            </value>
            <value>
                <fullName>Clinical</fullName>
            </value>
            <value>
                <fullName>Applied Markets</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/OpportunityLineItem/fields/End_Date_INF__c.field-meta.xml
<CustomField>
    <fullName>End_Date_INF__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/OpportunityLineItem/fields/Start_Date_INF__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_INF__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/License_Type_INF__c.field-meta.xml
<CustomField>
    <fullName>License_Type_INF__c</fullName>
    <label>License Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/classes/Test_Opportunity_Trigger_Handler.cls
@isTest
public class Test_Opportunity_Trigger_Handler {
   @testSetup static void setup() {
     Id opportunity_Informatics = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Informatics').getRecordTypeId();
     Pricebook2 standardPricebook = new Pricebook2(
            Id = Test.getStandardPricebookId(),
            IsActive = true,
            CurrencyIsoCode='USD'
        );
        Update standardPricebook;
        
        standardPricebook = [SELECT Id, IsStandard FROM Pricebook2 WHERE Id = :standardPricebook.Id];
        
        List<Product2> productLst = new List<Product2>();
        Product2 product = new Product2(
            Name = 'TestProduct',
            IsActive = true, 
            /*SBQQ__SubscriptionPricing__c = 'Fixed Price', 
            SBQQ__SubscriptionTerm__c = 12, 
            SBQQ__SubscriptionType__c = 'Renewable', */
            License_Type_INF__c = 'Perpetual'
        );
        productLst.add(product);
        
        Product2 prod = new Product2(
            Name = 'Services',
            IsActive = true, 
            /*SBQQ__SubscriptionPricing__c = 'Fixed Price', 
            SBQQ__SubscriptionTerm__c = 12, 
            SBQQ__SubscriptionType__c = 'Renewable',*/
           // License_Type_INF__c = 'Services'
            License_Type_INF__c = 'Perpetual'
        );
        productLst.add(prod);
        
        Product2 pro = new Product2(
            Name = 'TestProduct',
            IsActive = true, 
            /*SBQQ__SubscriptionPricing__c = 'Fixed Price', 
            SBQQ__SubscriptionTerm__c = 12, 
            SBQQ__SubscriptionType__c = 'Renewable',*/
            License_Type_INF__c = 'Maintenance'
        );
        productLst.add(pro);
        
        Product2 prodt = new Product2(
            Name = 'TestProduct',
            IsActive = true, 
            /*SBQQ__SubscriptionPricing__c = 'Fixed Price', 
            SBQQ__SubscriptionTerm__c = 12, 
            SBQQ__SubscriptionType__c = 'Renewable',*/
            License_Type_INF__c = 'Saas'
        );
        productLst.add(prodt);
        insert productLst;
         Pricebook2 pb = new Pricebook2(Name = 'Informatics price', Description = 'Price Book 2009 Products', IsActive = true,CurrencyIsoCode = 'USD' );
    insert pb;
        PricebookEntry pbEntry = new PricebookEntry(
            Pricebook2Id = standardPricebook.Id,
            Product2Id = prod.Id,
            UnitPrice = 120.00,
            IsActive = true
        );
        insert pbEntry;
         PricebookEntry pbEntry1 = new PricebookEntry(
            Pricebook2Id = pb.Id,
            Product2Id = prod.Id,
            UnitPrice = 120.00,
            IsActive = true
        );
        insert pbEntry1;
        
        Account a = new Account(Name='Testing3456',Industry ='Biotech',
                                BillingStreet='Street1',BillingCity='City1',BillingState='State',BillingCountry='US',BillingPostalCode='12345');
        insert a;
        
        contact con = new contact();
        con.Lead_Owner_LDR_Conversion__c=userinfo.getName();
        con.LastName= 'Last Name';
        con.AccountId=a.Id;
        insert con;
       
        Opportunity op = new Opportunity(Name='opp1',AccountId=a.Id,RecordTypeId=opportunity_Informatics,
                                              Renewal_Required_INF__c='Yes',Account_Type_INF__c='Academic',
                                              StageName='Stage 1 - Create/Plan',CloseDate=Date.today(),
                                              Strategic_Market_INF__c='Clinical',Type='New Account',
                                              ForecastCategoryName='Pipeline',CurrencyIsoCode = 'USD',
                                              Solution_Area_of_Interest__c='Energy',pricebook2Id=pb.Id);        
        insert op;
        
        OpportunityLineItem opportunityLineItem = new OpportunityLineItem(
                PricebookEntryId = pbEntry1.Id,
                Quantity = 3,
                UnitPrice = 1000,
                End_Date_INF__c=date.today(), 
                Start_Date_INF__c=date.today(),
                OpportunityId = op.Id);
        insert opportunityLineItem;
                
        
        
        OpportunityContactRole OppConRole = new OpportunityContactRole();
        OppConRole.ContactId=con.Id;
        OppConRole.OpportunityId =Op.Id;
        OppConRole.IsPrimary=true;
        insert OppConRole;
        
    }
    static testMethod void UpdateMethod2(){
        product2 prod=[select id,License_Type_INF__c from Product2 Where Name='Services' limit 1];
        prod.License_Type_INF__c = 'SaaS';
        Update prod;
       opportunity op  =[select id,StageName,Application__c,Application_Market__c,
                       Application_Segment__c,Renewal_Required_INF__c,Run_Rate_Opp_INF__c FROM Opportunity limit 1];
        op.StageName = 'Closed Won';
        op.Application__c = 'Virology';
        op.Application_Market__c = 'Clinical Diagnostics';
        op.Application_Segment__c = 'Diagnostics';
        op.Renewal_Required_INF__c = 'No';
        op.Run_Rate_Opp_INF__c = false;
        update op;
    }
    static testMethod void UpdateMethod3(){
       opportunity op  =[select id,StageName,Application__c,Application_Market__c,
                       Application_Segment__c,Renewal_Required_INF__c,Run_Rate_Opp_INF__c FROM Opportunity limit 1];
        op.StageName = 'Stage 6 - Implement (Closed)';
        op.Application__c = 'Virology';
        op.Application_Market__c = 'Clinical Diagnostics';
        op.Application_Segment__c = 'Diagnostics';
        op.Renewal_Required_INF__c = 'No';
        op.Run_Rate_Opp_INF__c = false;
        update op;
    }
    static testMethod void UpdateMethod4(){
        product2 prod=[select id,License_Type_INF__c from Product2 Where Name='Services' limit 1];
        prod.License_Type_INF__c = 'SaaS';
        Update prod;
        test.startTest();
         opportunity op  =[select id,StageName,Application__c,Application_Market__c,
                       Application_Segment__c,Renewal_Required_INF__c,Run_Rate_Opp_INF__c FROM Opportunity limit 1];
        op.StageName = 'Closed Won';
        op.Application__c = 'Virology';
        op.Application_Market__c = 'Clinical Diagnostics';
        op.Application_Segment__c = 'Diagnostics';
        op.Renewal_Required_INF__c = 'Yes';
        op.Run_Rate_Opp_INF__c = false;
        update op;
            test.stopTest();
        
    }
    
}