Perkin-UAT/force-app/main/default/objects/Contact/fields/PKI_SAP_Contact_ID__c.field-meta.xml
<CustomField>
    <fullName>PKI_SAP_Contact_ID__c</fullName>
    <description>PLEASE DO NOT EDIT OR UPDATE THIS FIELD IN DATALOADS ... IT IS AN EXTERNAL ID FIELD TO SAP</description>
    <externalId>true</externalId>
    <label>PKI SAP Contact ID</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Contact/fields/SAP_Contact_ID__c.field-meta.xml
<CustomField>
    <fullName>SAP_Contact_ID__c</fullName>
    <label>SAP Contact ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/Analytical_Cross_Sell_Peten__c.field-meta.xml
<CustomField>
    <fullName>Analytical_Cross_Sell_Peten__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Analytical Cross Sell Perten</label>
    <type>Checkbox</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/ATO_Products__c.field-meta.xml
<CustomField>
    <fullName>ATO_Products__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to check if the product is part of Assemble to Order(ATO) (Source: S-692538)</description>
    <inlineHelpText>Part of Assemble to Order</inlineHelpText>
    <label>ATO Products</label>
    <type>Checkbox</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/CPQ_Maintenance_Optional__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Maintenance_Optional__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Prevents this product from triggering required approval if associated maintenance is removed</inlineHelpText>
    <label>Maintenance Optional</label>
    <type>Checkbox</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/CPQ_Special__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Special__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Special</label>
    <type>Checkbox</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/Custom_Product__c.field-meta.xml
<CustomField>
    <fullName>Custom_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to define if this product  is a custom product .Set by Boomi Integration. (Source: S-695575 / S-692506)</description>
    <inlineHelpText>This field is used to define if this product  is a custom product .Set by Boomi Integration.</inlineHelpText>
    <label>Custom Product</label>
    <type>Checkbox</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/Ext_Warranty_Calculation__c.field-meta.xml
<CustomField>
    <fullName>Ext_Warranty_Calculation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Defines if this product should be included in the calculation. (Source: S-695040)</description>
    <inlineHelpText>Defines if this product should be included in the calculation.</inlineHelpText>
    <label>Ext Warranty Calculation</label>
    <type>Checkbox</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/FlagForUpdate__c.field-meta.xml
<CustomField>
    <fullName>FlagForUpdate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>FlagForUpdate</label>
    <type>Checkbox</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/Food_Cross_Sell_Analytical__c.field-meta.xml
<CustomField>
    <fullName>Food_Cross_Sell_Analytical__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Food Cross Sell Analytical</label>
    <type>Checkbox</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/In_SAP__c.field-meta.xml
<CustomField>
    <fullName>In_SAP__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to identify if a product is in SAP</description>
    <label>In SAP</label>
    <type>Checkbox</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/IsBundle__c.field-meta.xml
<CustomField>
    <fullName>IsBundle__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Set it to True if its a bundle product. This field will be used as a check to exclude the product line from sending to SAP (Source: S-692816)</description>
    <inlineHelpText>Set it to True if its a bundle product.</inlineHelpText>
    <label>IsBundle</label>
    <type>Checkbox</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/Special_Product__c.field-meta.xml
<CustomField>
    <fullName>Special_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to define if this product is a special product .Set by Boomi.(Source :S-695575 / S-692506)</description>
    <inlineHelpText>This field is used to define if this product is a special product .Set by Boomi.</inlineHelpText>
    <label>Special Product</label>
    <type>Checkbox</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_Fault_Code__c/SMAX_PS_Fault_Code__c.object-meta.xml
<CustomObject>
    <description>Fault Codes for SMAX_PS_Fault_Codes</description>
    <label>Fault Code</label>
    <nameField>
        <label>Fault Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fault Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_Fault_Code__c/fields/SMAX_PS_Code__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_Code__c</fullName>
    <label>Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_Fault_Code__c/fields/SMAX_PS_Code_Description__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_Code_Description__c</fullName>
    <label>Code Description</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_Fault_Code__c/fields/SMAX_PS_Complaint_Required__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_Complaint_Required__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Complaint Required</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_Fault_Code__c/fields/SMAX_PS_Fault_Code_Group__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_Fault_Code_Group__c</fullName>
    <label>Fault Code Group</label>
    <referenceTo>SMAX_PS_Fault_Code_Group__c</referenceTo>
    <relationshipLabel>Fault Codes</relationshipLabel>
    <relationshipName>Fault_Codes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_Fault_Code_Group__c/SMAX_PS_Fault_Code_Group__c.object-meta.xml
<CustomObject>
    <label>Fault Code Group</label>
    <nameField>
        <label>Fault Code Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fault Code Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_ProductPlant__c/SMAX_PS_ProductPlant__c.object-meta.xml
<CustomObject>
    <label>Product Plant</label>
    <nameField>
        <displayFormat>PPNT-{00000000}</displayFormat>
        <label>Product Plant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Plants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_ProductPlant__c/fields/SMAX_PS_Plant__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_Plant__c</fullName>
    <label>Plant</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_ProductPlant__c/fields/SMAX_PS_Product__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Plants</relationshipLabel>
    <relationshipName>Product_Plants</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_ProductSales__c/SMAX_PS_ProductSales__c.object-meta.xml
<CustomObject>
    <label>Product Sales</label>
    <nameField>
        <displayFormat>PSLS-{00000000}</displayFormat>
        <label>Product Sales Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Sales</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_ProductSales__c/fields/SMAX_PS_Product__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Sales</relationshipLabel>
    <relationshipName>Product_Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_ProductSales__c/fields/SMAX_PS_Sales_Unit_Code__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_Sales_Unit_Code__c</fullName>
    <description>Used for Boomi and SAP integration only.</description>
    <inlineHelpText>Used for Boomi and SAP integration only.</inlineHelpText>
    <label>Sales Unit Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_ProductSales__c/fields/SMAX_PS_SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_SalesOrg__c</fullName>
    <label>Sales Org</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_ProductSales__c/fields/SMAX_PS_SalesUnit__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_SalesUnit__c</fullName>
    <label>Sales Unit</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_ProductSales__c/fields/SMAX_PS_SAP_Deleted__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_SAP_Deleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deletion Flag</label>
    <type>Checkbox</type>
</CustomField>

Perkin-UAT/force-app/main/default/classes/SMAX_PS_WorkDetailManager_UT.cls
@isTest
public class SMAX_PS_WorkDetailManager_UT {

    @isTest
    static void updateUnitOfMeasureCodesTest() {
        
        contact c = new contact();
        c.FirstName = 'Garth';
        c.LastName = 'Vader';
        c.SAP_Contact_ID__c = 'testId';
        c.pKI_SAP_Contact_ID__c  = 'testId';
        insert c;
        
		product2 prod = new product2();
        prod.name = 'test name';
        prod.Analytical_Cross_Sell_Peten__c = false;
        prod.ATO_Products__c= false;
        prod.CPQ_Maintenance_Optional__c = false;
        prod.CPQ_Special__c = false;
        prod.CurrencyIsoCode = 'USD';
        prod.Custom_Product__c = false;
        prod.Ext_Warranty_Calculation__c = false;
        prod.FlagForUpdate__c = false;
        prod.Food_Cross_Sell_Analytical__c = false;
        prod.In_SAP__c = true;
        prod.IsActive = true;
        prod.IsBundle__c = false;
        prod.Special_Product__c = false;
        insert prod;
            
        SMAX_PS_ProductSales__c ps1 = new SMAX_PS_ProductSales__c();
        ps1.SMAX_PS_Product__c = prod.id;
        ps1.SMAX_PS_SAP_Deleted__c = false;
        ps1.SMAX_PS_SalesOrg__c = 'TUS1'; //this is salesorg Param
        ps1.SMAX_PS_SalesUnit__c = 'usa';
        ps1.SMAX_PS_Sales_Unit_Code__c = 'usa';
        insert ps1;
        
        SMAX_PS_ProductSales__c ps2 = new SMAX_PS_ProductSales__c();
        ps2.SMAX_PS_Product__c = prod.id;
        ps2.SMAX_PS_SAP_Deleted__c = false;
        ps2.SMAX_PS_SalesOrg__c = 'TUS2'; //this is salesorg Param
        ps2.SMAX_PS_SalesUnit__c = 'usa';
        ps2.SMAX_PS_Sales_Unit_Code__c = null;
        insert ps2;
        
        SVMXC__Service_order__c wo = new SVMXC__service_Order__c();
        wo.SVMXC__Contact__c = c.id;
        insert wo;
        
        SVMXC__Service_Order_Line__c detail1 = new SVMXC__Service_Order_Line__c();
        detail1.SVMXC__Service_order__c = wo.id;
        detail1.SMAX_PS_Use_Product_Sales_UOM__c  = true;
        insert detail1;

        SVMXC__Service_Order_Line__c detail2 = new SVMXC__Service_Order_Line__c();
        detail2.SVMXC__Service_order__c = wo.id;
        detail2.SMAX_PS_Use_Product_Sales_UOM__c  = false;
        insert detail2;
        
        SMAX_PS_WorkDetailManager.updateUnitOfMeasureCodes(detail1, 'TUS1', prod);
        SMAX_PS_WorkDetailManager.updateUnitOfMeasureCodes(detail2, 'TUS2', prod);
        
    }
    
    @isTest
    static void testFaultCode() {
        
        SMAX_PS_Fault_Code_Group__c fcg = new SMAX_PS_Fault_Code_Group__c();
        fcg.name = 'test';
        insert fcg;
        
        SMAX_PS_Fault_Code__c fc = new SMAX_PS_Fault_Code__c();
        fc.name = 'test';
        fc.SMAX_PS_Code_Description__c = 'Job Completed';
        fc.SMAX_PS_Code__c = 'JC01';
        fc.SMAX_PS_Fault_Code_Group__c = fcg.id;
        fc.SMAX_PS_Complaint_Required__c = 1;
        insert fc;
        
        SMAX_PS_Fault_Code__c fc1 = new SMAX_PS_Fault_Code__c();
        fc1.name = 'test';
        fc1.SMAX_PS_Code_Description__c = 'Application Problems';
        fc1.SMAX_PS_Code__c = 'IN01';
        fc1.SMAX_PS_Fault_Code_Group__c = fcg.id;
        fc1.SMAX_PS_Complaint_Required__c = 1;
        insert fc1;          
        
        SMAX_PS_Fault_Code__c fc2 = new SMAX_PS_Fault_Code__c();
        fc2.name = 'test';
        fc2.SMAX_PS_Code_Description__c = 'Advised';
        fc2.SMAX_PS_Code__c = 'AC01';
        fc2.SMAX_PS_Fault_Code_Group__c = fcg.id;
        fc2.SMAX_PS_Complaint_Required__c = 1;
        insert fc2;  

        contact c = new contact();
        c.FirstName = 'Garth';
        c.LastName = 'Vader';
        c.SAP_Contact_ID__c = 'testId';
        c.pKI_SAP_Contact_ID__c  = 'testId';
        insert c;

		product2 prod = new product2();
        prod.name = 'test name';
        prod.Analytical_Cross_Sell_Peten__c = false;
        prod.ATO_Products__c= false;
        prod.CPQ_Maintenance_Optional__c = false;
        prod.CPQ_Special__c = false;
        prod.CurrencyIsoCode = 'USD';
        prod.Custom_Product__c = false;
        prod.Ext_Warranty_Calculation__c = false;
        prod.FlagForUpdate__c = false;
        prod.Food_Cross_Sell_Analytical__c = false;
        prod.In_SAP__c = true;
        prod.IsActive = true;
        prod.IsBundle__c = false;
        prod.Special_Product__c = false;
        insert prod;
        
        SVMXC__Service_order__c wo = new SVMXC__service_Order__c();
        wo.SVMXC__Contact__c = c.id;
        insert wo;
        
        SVMXC__Service_Order_Line__c detail1 = new SVMXC__Service_Order_Line__c();
        detail1.SVMXC__Line_Type__c = 'Fault Code';
        detail1.SMAX_PS_InstallationFaultCode__c = fc1.id;
        detail1.SMAX_PS_CompletionFaultCode__c = fc.id;
        detail1.SMAX_PS_Fault_Code__c = fc.id;
        detail1.SMAX_PS_ActionFaultCode__c = fc2.id;
        detail1.SVMXC__Service_order__c = wo.id;
        insert detail1;

        SMAX_PS_WorkDetailManager.updateFaultCodes(new List<SVMXC__Service_Order_Line__c>{detail1}, new Map<id,SVMXC__Service_Order_Line__c>{detail1.id => detail1});
    }
    
    @isTest
    static void logDuplicateErrorsTest() {
        
        contact c = new contact();
        c.FirstName = 'Garth';
        c.LastName = 'Vader';
        c.SAP_Contact_ID__c = 'testId';
        c.pKI_SAP_Contact_ID__c  = 'testId';
        insert c;
        
        SVMXC__Service_order__c wo = new SVMXC__service_Order__c();
        wo.SVMXC__Contact__c = c.id;
        insert wo;
        
        SVMXC__Service_Order_Line__c detail1 = new SVMXC__Service_Order_Line__c();
        detail1.SMAX_PS_CancellationNumber__c = '123';
		detail1.SMAX_PS_SAP_Confirmation__c = 'confirmation';
        detail1.SVMXC__Service_order__c = wo.id;
        insert detail1;
        
        SVMXC__Service_Order_Line__c detail2 = new SVMXC__Service_Order_Line__c();
        detail2.SMAX_PS_CancellationNumber__c = '456';
		detail2.SMAX_PS_SAP_Confirmation__c = 'pending';
        detail2.SVMXC__Service_order__c = wo.id;
        
        SMAX_PS_WorkDetailManager.logDuplicateErrors( new List<SVMXC__Service_Order_Line__c>{detail1}, new Map<Id, SVMXC__Service_Order_Line__c>{detail1.id => detail2});

        
    }
    
    @isTest
    static void testIntegrationToggle() {

         contact c = new contact();
        c.FirstName = 'Garth';
        c.LastName = 'Vader';
        c.SAP_Contact_ID__c = 'testId';
        c.pKI_SAP_Contact_ID__c  = 'testId';
        insert c;
        
        SVMXC__Service_order__c wo = new SVMXC__service_Order__c();
        wo.SVMXC__Contact__c = c.id;
        insert wo;
        
        SVMXC__Service_Order_Line__c detail1 = new SVMXC__Service_Order_Line__c();
		detail1.SVMXC__Line_Status__c = 'Submitted';
        detail1.SVMXC__Service_order__c = wo.id;
        insert detail1;
        
        SVMXC__Service_Order_Line__c detail2 = new SVMXC__Service_Order_Line__c();
		detail2.SVMXC__Line_Status__c = null;
        detail2.SVMXC__Service_order__c = wo.id;
        
        SVMXC__Service_Order_Line__c detail3 = new SVMXC__Service_Order_Line__c();
		detail3.SVMXC__Line_Status__c = 'Canceled';
        detail3.SVMXC__Service_order__c = wo.id;
        insert detail3;
        
        
        SMAX_PS_WorkDetailManager.toggleIntegrationStatus(new List<SVMXC__Service_Order_Line__c>{detail1, detail3}, new Map<Id, SVMXC__Service_Order_Line__c>{detail1.id => detail2, detail3.id => detail2});
    }
    
    @isTest
    static void testDetailLineAndIntegration() {
        
        contact c = new contact();
        c.FirstName = 'Garth';
        c.LastName = 'Vader';
        c.SAP_Contact_ID__c = 'testId';
        c.pKI_SAP_Contact_ID__c  = 'testId';
        insert c;
        
        SVMXC__Service_order__c wo = new SVMXC__service_Order__c();
        wo.SVMXC__Contact__c = c.id;
        insert wo;
        
        SVMXC__Service_Order_Line__c detail1 = new SVMXC__Service_Order_Line__c();
		detail1.SVMXC__Line_Status__c = 'Submitted';
        detail1.SVMXC__Service_order__c = wo.id;
        detail1.SMAX_PS_SAP_Confirmation__c = '';
        insert detail1;
        
        SVMXC__Service_Order_Line__c detail2 = new SVMXC__Service_Order_Line__c();
		detail2.SVMXC__Line_Status__c = null;
        detail2.SMAX_PS_SAP_Confirmation__c = 'something fun';
		detail2.SVMXC__line_status__c = 'Confirmed';
        detail2.SVMXC__Service_order__c = wo.id;
        
        SMAX_PS_WorkDetailManager.updateDetailLineAndIntegrationStatus(new List<SVMXC__Service_Order_Line__c>{detail1}, new Map<Id, SVMXC__Service_Order_Line__c>{detail1.id => detail2});
	}
    

    @isTest
    static void testCancellation() {
        
         contact c = new contact();
        c.FirstName = 'Garth';
        c.LastName = 'Vader';
        c.SAP_Contact_ID__c = 'testId';
        c.pKI_SAP_Contact_ID__c  = 'testId';
        insert c;
        
        SVMXC__Service_order__c wo = new SVMXC__service_Order__c();
        wo.SVMXC__Contact__c = c.id;
        insert wo;
        
        SVMXC__Service_Order_Line__c detail1 = new SVMXC__Service_Order_Line__c();
		detail1.SVMXC__Line_Status__c = 'Canceled';
        detail1.SVMXC__Service_order__c = wo.id;
        detail1.SMAX_PS_IntegrationStatus__c = 'Pending';
        insert detail1;
        
        SVMXC__Service_Order_Line__c detail2 = new SVMXC__Service_Order_Line__c();
		detail2.SVMXC__Line_Status__c = 'Submitted';
        detail2.SVMXC__Service_order__c = wo.id;
        
        
       SMAX_PS_WorkDetailManager.cancelLines(new List<SVMXC__Service_Order_Line__c>{detail1}, new Map<Id, SVMXC__Service_Order_Line__c>{detail1.id => detail2});
    }
    
    
    @isTest
    static void testSummary() {
        
        contact c = new contact();
        c.FirstName = 'Garth';
        c.LastName = 'Vader';
        c.SAP_Contact_ID__c = 'testId';
        c.pKI_SAP_Contact_ID__c  = 'testId';
        insert c;
        
        SVMXC__Service_order__c wo = new SVMXC__service_Order__c();
        wo.SVMXC__Contact__c = c.id;
        insert wo;
        
        SVMXC__Service_Order_Line__c detail1 = new SVMXC__Service_Order_Line__c();
        detail1.SMAX_PS_CancellationNumber__c = '123';
		detail1.SMAX_PS_SAP_Confirmation__c = 'confirmation';
        detail1.SVMXC__Work_Description__c = 'BJKDNFJILWEJKHNF:KJLWEHDNOI:WRLJKEHFNOU:ILWEJRKHJFNO:WURLJGHNFWE:OUR>LIGHJFNWEPUILK>JHNEW:OIFLKVJWRENMIF:OLJKCDHWN :JWEKL>FM<N JEW:KL<>FNM';
        detail1.SMAX_PS_Concat_Part_Work_Description__c = 'blah';
        detail1.SMAX_PS_Material_Part_Description__c = 'blah blah';
        detail1.SVMXC__Service_order__c = wo.id;
        insert detail1;
        
        SMAX_PS_WorkDetailManager.addWorkSummary(new List<SVMXC__Service_Order_Line__c>{detail1});
    }
    
    @isTest
    static void testGetProductPlant() {
        
        contact c = new contact();
        c.FirstName = 'Garth';
        c.LastName = 'Vader';
        c.SAP_Contact_ID__c = 'testId';
        c.pKI_SAP_Contact_ID__c  = 'testId';
        insert c;
        
		product2 prod = new product2();
        prod.name = 'test name';
        prod.Analytical_Cross_Sell_Peten__c = false;
        prod.ATO_Products__c= false;
        prod.CPQ_Maintenance_Optional__c = false;
        prod.CPQ_Special__c = false;
        prod.CurrencyIsoCode = 'USD';
        prod.Custom_Product__c = false;
        prod.Ext_Warranty_Calculation__c = false;
        prod.FlagForUpdate__c = false;
        prod.Food_Cross_Sell_Analytical__c = false;
        prod.In_SAP__c = true;
        prod.IsActive = true;
        prod.IsBundle__c = false;
        prod.Special_Product__c = false;
        insert prod;
            
        SMAX_PS_ProductSales__c ps1 = new SMAX_PS_ProductSales__c();
        ps1.SMAX_PS_Product__c = prod.id;
        ps1.SMAX_PS_SAP_Deleted__c = false;
        ps1.SMAX_PS_SalesOrg__c = 'TUS1'; //this is salesorg Param
        ps1.SMAX_PS_SalesUnit__c = 'usa';
        ps1.SMAX_PS_Sales_Unit_Code__c = 'usa';
        insert ps1;
        
        SMAX_PS_ProductSales__c ps2 = new SMAX_PS_ProductSales__c();
        ps2.SMAX_PS_Product__c = prod.id;
        ps2.SMAX_PS_SAP_Deleted__c = false;
        ps2.SMAX_PS_SalesOrg__c = 'TUS2'; //this is salesorg Param
        ps2.SMAX_PS_SalesUnit__c = 'usa';
        ps2.SMAX_PS_Sales_Unit_Code__c = null;
        insert ps2;
        
        SMAX_PS_ProductPlant__c plant = new SMAX_PS_ProductPlant__c();
        plant.SMAX_PS_Product__c = prod.id;
        plant.SMAX_PS_Plant__c = 'test';
        insert plant;
        
        SVMXC__Site__c site = new SVMXC__Site__c();
        site.name = 'testSite';
        site.SMAX_PS_MaintenancePlant__c = 'test';
        insert site;
        
        SVMXC__Service_order__c wo = new SVMXC__service_Order__c();
        wo.SVMXC__Contact__c = c.id;
        wo.SVMXC__Site__c = site.id;
        insert wo;
        
        SVMXC__Service_Order_Line__c detail1 = new SVMXC__Service_Order_Line__c();
        detail1.SVMXC__Service_order__c = wo.id;
        detail1.SVMXC__Line_Type__c = 'Parts';
        detail1.SVMXC__Product__c = prod.id;
        insert detail1;

        SVMXC__Service_Order_Line__c detail2 = new SVMXC__Service_Order_Line__c();
        detail2.SVMXC__Service_order__c = wo.id;
        detail2.SMAX_PS_Use_Product_Sales_UOM__c  = false;
        insert detail2;
        
        SMAX_PS_WorkDetailManager.lookupProductPlant(new List<SVMXC__Service_Order_Line__c>{detail1}, new Map<Id, SVMXC__Service_Order_Line__c>{detail1.id => detail2});
    }
    
    @isTest
    static void testupdateWorkDetailPlantAndWorkCenter() {
        
        Id usageRecTypeId = SMAX_PS_Utility.getRecordType('SVMXC__Service_Order_Line__c', 'UsageConsumption').Id;
        
         contact c = new contact();
        c.FirstName = 'Garth';
        c.LastName = 'Vader';
        c.SAP_Contact_ID__c = 'testId';
        c.pKI_SAP_Contact_ID__c  = 'testId';
        insert c;
        
        SVMXC__Service_order__c wo = new SVMXC__service_Order__c();
        wo.SVMXC__Contact__c = c.id;
        insert wo;
        
        SVMXC__Service_Order_Line__c detail1 = new SVMXC__Service_Order_Line__c();
        detail1.RecordTypeId = usageRecTypeId;
        detail1.SVMXC__Line_Type__c = 'Labor';
        detail1.SVMXC__Service_order__c = wo.id;
        insert detail1;
        
        
        
        SMAX_PS_WorkDetailManager.updateWorkDetailPlantAndWorkCenter(new List<SVMXC__Service_Order_Line__c>{detail1}, null);
    }
}