Perkin-UAT/force-app/main/default/objects/Contact/fields/Solution_Area_of_Interest__c.field-meta.xml
<CustomField>
    <fullName>Solution_Area_of_Interest__c</fullName>
    <description>ORIG:ANNUITAS PDG Program

NEW: SS This field is now used on Interaction, Interaction Assignment Rule, Lead, Contact, Oppty</description>
    <label>Solution Area of Interest</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Air</fullName>
            </value>
            <value>
                <fullName>Applied Genomics</fullName>
            </value>
            <value>
                <fullName>Biologics</fullName>
            </value>
            <value>
                <fullName>Cannabis</fullName>
            </value>
            <value>
                <fullName>Cell and Gene Therapy</fullName>
            </value>
            <value>
                <fullName>Chemicals</fullName>
            </value>
            <value>
                <fullName>Clinical Studies</fullName>
            </value>
            <value>
                <fullName>Digital Lab</fullName>
            </value>
            <value>
                <fullName>Energy</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Forensics and Security</fullName>
            </value>
            <value>
                <fullName>Geochemistry, Mining and Metals</fullName>
            </value>
            <value>
                <fullName>Life Science Research</fullName>
            </value>
            <value>
                <fullName>Material</fullName>
            </value>
            <value>
                <fullName>Maternal Fetal Health</fullName>
            </value>
            <value>
                <fullName>Newborn Screening</fullName>
            </value>
            <value>
                <fullName>Pre-Clinical Drug Development</fullName>
            </value>
            <value>
                <fullName>Pre-Clinical Drug Discovery</fullName>
            </value>
            <value>
                <fullName>QA/QC Drug Manufacturing Process</fullName>
            </value>
            <value>
                <fullName>Soil/Solids</fullName>
            </value>
            <value>
                <fullName>Strategic Services</fullName>
            </value>
            <value>
                <fullName>Water</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Account_Type_INF__c.field-meta.xml
<CustomField>
    <fullName>Account_Type_INF__c</fullName>
    <description>This field is used within Informatics quote process to drive related Price List.  Do not modify without contacting Informatics SalesForce.com support</description>
    <inlineHelpText>Price List requires Acct Type</inlineHelpText>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Commercial</fullName>
                <default>true</default>
                <label>Commercial</label>
            </value>
            <value>
                <fullName>Academic</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <description>Identify Customer Industry Application. Standardized Names (no double spaces, no space after slash, spaces before and after &#39;&amp;&#39;, use &#39;&amp;&#39; vs &#39;and&#39;, space after commas, lists do not have comma before last item and use &#39;&amp;&#39; before last item)</description>
    <label>Application</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Application_Market__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agricultural Genetics</fullName>
            </value>
            <value>
                <fullName>Agriculture Research</fullName>
            </value>
            <value>
                <fullName>Agrigenomics</fullName>
            </value>
            <value>
                <fullName>Air Testing</fullName>
            </value>
            <value>
                <fullName>Allergy DX</fullName>
            </value>
            <value>
                <fullName>Ancestry</fullName>
            </value>
            <value>
                <fullName>Animal Diagnostics</fullName>
            </value>
            <value>
                <fullName>Antibiotics</fullName>
            </value>
            <value>
                <fullName>API/Compound Analysis</fullName>
            </value>
            <value>
                <fullName>Authenticity &amp; Adulteration</fullName>
            </value>
            <value>
                <fullName>Autoimmun DX</fullName>
            </value>
            <value>
                <fullName>Automated Systems</fullName>
            </value>
            <value>
                <fullName>Basic Research</fullName>
            </value>
            <value>
                <fullName>Batteries, Power &amp; Utilities</fullName>
            </value>
            <value>
                <fullName>Beverages</fullName>
            </value>
            <value>
                <fullName>Biological Pathogens &amp; Toxins</fullName>
            </value>
            <value>
                <fullName>Biologics Development ADME/Tox</fullName>
            </value>
            <value>
                <fullName>Biologics Development Cell line development</fullName>
            </value>
            <value>
                <fullName>Biologics Development GLP Pre-clinical studies</fullName>
            </value>
            <value>
                <fullName>Biologics Development GLP Safety/Tox</fullName>
            </value>
            <value>
                <fullName>Biologics Lot Release</fullName>
            </value>
            <value>
                <fullName>Biomarker Development</fullName>
            </value>
            <value>
                <fullName>Biophysical characterization</fullName>
            </value>
            <value>
                <fullName>BioTherapeutic Manufacturing</fullName>
            </value>
            <value>
                <fullName>Blood Screening</fullName>
            </value>
            <value>
                <fullName>Bone Metabolism</fullName>
            </value>
            <value>
                <fullName>Cannabis/Hemp</fullName>
            </value>
            <value>
                <fullName>Cell Culture</fullName>
            </value>
            <value>
                <fullName>Chemical Food Safety</fullName>
            </value>
            <value>
                <fullName>Chemicals &amp; Mining</fullName>
            </value>
            <value>
                <fullName>Virology</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Application_Market__c.field-meta.xml
<CustomField>
    <fullName>Application_Market__c</fullName>
    <description>Identify Customer Market. Standardized Names (no double spaces, no space after slash, spaces before and after &#39;&amp;&#39;, use &#39;&amp;&#39; vs &#39;and&#39;, space after commas, lists do not have comma before last item and use &#39;&amp;&#39; before last item)</description>
    <label>Application Market</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Application_Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Academia &amp; Academic Research</fullName>
            </value>
            <value>
                <fullName>Air</fullName>
            </value>
            <value>
                <fullName>Alcoholic &amp; Non-Alcoholic Beverages</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Applied Genomics</fullName>
            </value>
            <value>
                <fullName>Basic Research</fullName>
            </value>
            <value>
                <fullName>Biologics/Vaccines Drug Development</fullName>
            </value>
            <value>
                <fullName>Biologics Manufacturing QA/QC</fullName>
            </value>
            <value>
                <fullName>Cannabis/Hemp</fullName>
            </value>
            <value>
                <fullName>Chemicals</fullName>
            </value>
            <value>
                <fullName>Chemicals &amp; Mining</fullName>
            </value>
            <value>
                <fullName>Clinical Diagnostics</fullName>
            </value>
            <value>
                <fullName>Contract Lab</fullName>
            </value>
            <value>
                <fullName>Dairy</fullName>
            </value>
            <value>
                <fullName>Detection</fullName>
            </value>
            <value>
                <fullName>Drug Discovery</fullName>
            </value>
            <value>
                <fullName>Drug QA/QC Manufacturing</fullName>
            </value>
            <value>
                <fullName>Edible Oils</fullName>
            </value>
            <value>
                <fullName>Energy</fullName>
            </value>
            <value>
                <fullName>Energy &amp; Petrochem</fullName>
            </value>
            <value>
                <fullName>Environmental</fullName>
            </value>
            <value>
                <fullName>Flavor &amp; Fragrance</fullName>
            </value>
            <value>
                <fullName>Forensics &amp; Security</fullName>
            </value>
            <value>
                <fullName>Fruits &amp; Vegetables</fullName>
            </value>
            <value>
                <fullName>Government/Academic</fullName>
            </value>
            <value>
                <fullName>Government &amp; Academia</fullName>
            </value>
            <value>
                <fullName>Imaging</fullName>
            </value>
            <value>
                <fullName>Immunodiagnostics</fullName>
            </value>
            <value>
                <fullName>Material</fullName>
            </value>
            <value>
                <fullName>Materials</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Application_Segment__c.field-meta.xml
<CustomField>
    <fullName>Application_Segment__c</fullName>
    <defaultValue>if($RecordType.DeveloperName =&#39;Informatics&#39;,&#39;Informatics&#39;,null)</defaultValue>
    <description>Identify Customer Industry</description>
    <label>Application Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>COVID</fullName>
            </value>
            <value>
                <fullName>Diagnostics</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Informatics</fullName>
            </value>
            <value>
                <fullName>Life Science</fullName>
            </value>
            <value>
                <fullName>Environmental</fullName>
                <isActive>false</isActive>
                <label>Environmental</label>
            </value>
            <value>
                <fullName>Food And Agriculture</fullName>
                <isActive>false</isActive>
                <label>Food And Agriculture</label>
            </value>
            <value>
                <fullName>Human Health &amp; Life Sciences</fullName>
                <isActive>false</isActive>
                <label>Human Health &amp; Life Sciences</label>
            </value>
            <value>
                <fullName>Human Health and Life Sciences</fullName>
                <isActive>false</isActive>
                <label>Human Health and Life Sciences</label>
            </value>
            <value>
                <fullName>Industrial</fullName>
                <isActive>false</isActive>
                <label>Industrial</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/GP_OrderNum_INF__c.field-meta.xml
<CustomField>
    <fullName>GP_OrderNum_INF__c</fullName>
    <label>INF OrderNum</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Primary Contact)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Renewal_Required_INF__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Required_INF__c</fullName>
    <label>Renewal Required?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/OpportunityLineItem/fields/End_Date_INF__c.field-meta.xml
<CustomField>
    <fullName>End_Date_INF__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/OpportunityLineItem/fields/Start_Date_INF__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_INF__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/License_Type_INF__c.field-meta.xml
<CustomField>
    <fullName>License_Type_INF__c</fullName>
    <label>License Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Product2/fields/PricebookEntryID__c.field-meta.xml
<CustomField>
    <fullName>PricebookEntryID__c</fullName>
    <description>used for webmethods API</description>
    <label>PricebookEntryID</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/classes/INF_CreateRenewalOpportunityOnClosedWon.cls
@isTest(seeAllData=true)
public class INF_CreateRenewalOpportunityOnClosedWon{
    
    static List<Opportunity> OpptyList;
    static Id AccountRTId;
    static ID OpportunityRTId;
    
    static List<RecordType> rtList =[Select Id, DeveloperName, SobjectType  from RecordType 
                                     Where SobjectType IN ('Account','Opportunity')
                                     And DeveloperName IN('ProspectAccount','Informatics') ];
    
    
    static void getRecorDtypeIds(){
        if(rtList.size() > 0){
            for(RecordType r: rtList){  
                if(r.DeveloperName == 'ProspectAccount' && r.SobjectType == 'Account')
                    AccountRTId = r.id;
                if(r.DeveloperName == 'Informatics' && r.SobjectType == 'Opportunity')
                    OpportunityRTId = r.id;        
            }
        }
    }
    
    static testMethod void CreateRenewalOpportunityOnClosedWon()
    {
        getRecorDtypeIds();             
        /* Insert an Account */
        Account acc = new Account ();
        acc.RecordTypeId = AccountRTId;
        acc.name='Test Account#2-1-2018';
        acc.shippingStreet = 'Street1';
        acc.shippingCity = 'City1';
        acc.shippingState = 'State';
        acc.shippingCountry ='US';
        acc.shippingPostalCode = '12345';
        acc.Industry ='Biotech';
        acc.CurrencyIsoCode = 'USD';
        insert acc;
        
        Contact c = new Contact();
        c.AccountId = acc.Id;
        c.LastName = 'test';
        insert c;
        OpptyList = new List<Opportunity>();
        
        for (Integer i = 0; i < 10; i++)
        {
            OpptyList.add(new Opportunity(Name='OppTest'+i,AccountId=acc.Id,Probability=100,
                                          Renewal_Required_INF__c='Yes',RecordTypeId=OpportunityRTId,Account_Type_INF__c='Academic',Primary_Contact__c = c.Id,
                                          Solution_Area_of_Interest__c='Energy',StageName='Stage 6 - Implement (Closed)',LeadSource='Advertisement',CloseDate=Date.today(),
                                          Application__c = 'Virology', Application_Market__c = 'Clinical Diagnostics', Application_Segment__c = 'Diagnostics'));
        }
        insert OpptyList;
        
        Opportunity opp1 = new Opportunity (Name='Opp1',StageName='Stage 6 - Implement (Closed)',CloseDate=Date.today(),Solution_Area_of_Interest__c='Energy',Application__c = 'Virology', Application_Market__c = 'Clinical Diagnostics', Application_Segment__c = 'Diagnostics');
        insert opp1;
        
        Pricebook2  standardPb = [select id, name, isActive from Pricebook2 where IsStandard = true limit 1];
        Pricebook2 pbk1 = new Pricebook2 (Name='Test Pricebook Entry 1',Description='Test Pricebook Entry 1');
        insert pbk1;
        
        List<Product2> prod2List = new List<Product2>();
        Product2 prd1 = new Product2 (Name='Term test',ProductCode='CPH567',License_Type_INF__c='Term',
                                      Description='Test Product Entry 1');
        prd1.PricebookEntryID__c = pbk1.ID;
        prod2List.add(prd1);
        
        Product2 prd2 = new Product2 (Name='test product',ProductCode='CPH568',License_Type_INF__c='',
                                      Description='Test Product Entry 2');
        prd2.PricebookEntryID__c = pbk1.ID;
        prod2List.add(prd2);
        insert prod2List;
        
        List<PricebookEntry> pbeList = new List<PricebookEntry>();
        PricebookEntry pbe1 = new PricebookEntry (Product2ID=prd1.id,Pricebook2ID=standardPb.id,IsActive=true,
                                                  UseStandardPrice=false,UnitPrice=50);
        pbeList.add(pbe1);
        
        PricebookEntry pbe2 = new PricebookEntry (Product2ID=prd2.id,Pricebook2ID=standardPb.id,IsActive=true,
                                                  UseStandardPrice=false,UnitPrice=50);
        pbeList.add(pbe2);
        insert pbeList;
        
        List<OpportunityLineItem> oppLineItems = new List<OpportunityLineItem>();
        List<Opportunity> OppsUpdateRen = new List<Opportunity>();
        List<Opportunity> OppsUpdateNonRen1 = new List<Opportunity>();
        List<Opportunity> OppsUpdateNonRen = new List<Opportunity>();
        
        
        for(Opportunity opp : OpptyList){
            oppLineItems.add(new OpportunityLineItem(OpportunityID=opp.id,Start_Date_INF__c=Date.today(),End_Date_INF__c=Date.today(),TotalPrice=10,Quantity=1,PriceBookEntryID=pbeList[0].id));
            oppLineItems.add(new OpportunityLineItem(OpportunityID=opp.id,Start_Date_INF__c=Date.today(),End_Date_INF__c=Date.today(),TotalPrice=10,Quantity=1,PriceBookEntryID=pbeList[1].id));
            opp.StageName='Closed Won';
            opp.GP_OrderNum_INF__c ='ORD1234';
            opp.Solution_Area_of_Interest__c='Energy';
            opp.Application__c = 'Virology';
            opp.Application_Market__c = 'Clinical Diagnostics';
            opp.Application_Segment__c = 'Diagnostics';
            OppsUpdateRen.add(opp);
            
        }
        
        insert oppLineItems;
        test.startTest();
        update OppsUpdateRen;
        test.stopTest();
        
    }
    
    
    static testMethod void CreateNonRenewalOpportunityOnClosedWon()
    {
        getRecorDtypeIds();      
        /* Insert an Account */
        Account acc = new Account ();
        acc.RecordTypeId = AccountRTId;
        acc.name='Test Account#2-2-2018';
        acc.shippingStreet = 'Street1';
        acc.shippingCity = 'City1';
        acc.shippingState = 'State';
        acc.shippingCountry ='US';
        acc.shippingPostalCode = '12345';
        acc.Industry ='Biotech';
        acc.CurrencyIsoCode = 'USD';
        insert acc;
        
        
        Contact c = new Contact();
        c.AccountId = acc.Id;
        c.LastName = 'test';
        insert c;
        
        OpptyList = new List<Opportunity>();
        for (Integer i = 0; i < 10; i++)
        {
            OpptyList.add(new Opportunity(Name='OppTest'+i,AccountId=acc.Id,Probability=100,
                                          Renewal_Required_INF__c='Yes',RecordTypeId=OpportunityRTId,Account_Type_INF__c='Academic',Primary_Contact__c=c.Id,
                                          Solution_Area_of_Interest__c='Energy',StageName='Stage 6 - Implement (Closed)',LeadSource='Advertisement',CloseDate=Date.today(),
                                         Application__c = 'Virology', Application_Market__c = 'Clinical Diagnostics', Application_Segment__c = 'Diagnostics'));
        }
        insert OpptyList;
        
        List<Opportunity> OppNonren = new List<Opportunity>();
        for (Integer i = 0; i < 10; i++)
        {
            OppNonren.add(new Opportunity(Name='OppTests'+i,AccountId=acc.Id,Probability=100,
                                          Renewal_Required_INF__c='NO',RecordTypeId=OpportunityRTId,Account_Type_INF__c='Academic',Primary_Contact__c=c.Id,
                                          Solution_Area_of_Interest__c='Energy',StageName='Stage 6 - Implement (Closed)',LeadSource='Advertisement',CloseDate=Date.today(),
                                          Application__c = 'Virology', Application_Market__c = 'Clinical Diagnostics', Application_Segment__c = 'Diagnostics'));
        }
        insert OppNonren;
        
        
        Pricebook2  standardPb = [select id, name, isActive from Pricebook2 where IsStandard = true limit 1];
        
        Opportunity opp1 = new Opportunity (Name='Opp1',StageName='Stage 6 - Implement (Closed)',CloseDate=Date.today(),Solution_Area_of_Interest__c='Energy',Application__c = 'Virology', Application_Market__c = 'Clinical Diagnostics', Application_Segment__c = 'Diagnostics');
        insert opp1;
        
        Pricebook2 pbk1 = new Pricebook2 (Name='Test Pricebook Entry 2',Description='Test Pricebook Entry2');
        insert pbk1;
        
        List<Product2> prod2List = new List<Product2>();
        Product2 prd3 = new Product2 (Name='Term test product',ProductCode='CPH569',License_Type_INF__c='Term',
                                      Description='Test Product Entry 3');
        prd3.PricebookEntryID__c = pbk1.ID;
        prod2List.add(prd3);
        
        Product2 prd4 = new Product2 (Name='test product maint',ProductCode='CPH570',License_Type_INF__c='',
                                      Description='Test Product Entry 4');
        prd4.PricebookEntryID__c = pbk1.ID;
        prod2List.add(prd4);
        insert prod2List;
        
        List<PricebookEntry> pbeList1 = new List<PricebookEntry>();
        PricebookEntry pbe3 = new PricebookEntry (Product2ID=prd4.id,Pricebook2ID=standardPb.id,IsActive=true,
                                                  UseStandardPrice=false,UnitPrice=50);
        
        insert pbe3;
        
        List<Opportunity> OppsUpdateNonRen1 = new List<Opportunity>();
        List<OpportunityLineItem> oppLineItems1 = new List<OpportunityLineItem>();  
        for(Opportunity opp : OpptyList){
            oppLineItems1.add(new OpportunityLineItem(OpportunityID=opp.id,Start_Date_INF__c=Date.today(),End_Date_INF__c=Date.today(),TotalPrice=10,Quantity=1,PriceBookEntryID=pbe3.id));
            opp.StageName='Closed Won';
            opp.GP_OrderNum_INF__c ='ORD234';
            opp.Lead_Source__c='Event';
            opp.Run_Rate_Opp_INF__c=false;
            opp.Renewal_Required_INF__c='No';
            opp.RecordTypeId = Utility_Informatics.opportunity_Informatics;
            opp.Solution_Area_of_Interest__c='Energy';
            OppsUpdateNonRen1.add(opp);
            
        }     
        test.startTest();
        OppResetControl oppc = new OppResetControl();
        oppc.dummyMthd();
        system.debug('OppsUpdateNonRen1 >>>>>>>>'+OppsUpdateNonRen1);
        insert oppLineItems1;
        update OppsUpdateNonRen1;
        test.stopTest();
    }
}