Perkin-UAT/force-app/main/default/objects/Demo_Log__c/Demo_Log__c.object-meta.xml
<CustomObject>
    <label>Demo Log</label>
    <nameField>
        <displayFormat>INF-RML-{000000000}</displayFormat>
        <label>Demo Request No#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demo Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/Demo_Log__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <label>Assigned To</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dylan Fung</fullName>
            </value>
            <value>
                <fullName>Daniel Ubilla</fullName>
            </value>
            <value>
                <fullName>Emmanuel Escalante</fullName>
            </value>
            <value>
                <fullName>Demo Center</fullName>
                <default>true</default>
                <label>Demo Center</label>
            </value>
            <value>
                <fullName>Edgardo Gutierrez</fullName>
                <isActive>false</isActive>
                <label>Edgardo Gutierrez</label>
            </value>
            <value>
                <fullName>Franklin Jimenez</fullName>
                <isActive>false</isActive>
                <label>Franklin Jimenez</label>
            </value>
            <value>
                <fullName>John Baker</fullName>
                <isActive>false</isActive>
                <label>John Baker</label>
            </value>
            <value>
                <fullName>Luis Diaz</fullName>
                <isActive>false</isActive>
                <label>Luis Diaz</label>
            </value>
            <value>
                <fullName>Stepan Churukanov</fullName>
                <isActive>false</isActive>
                <label>Stepan Churukanov</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Demo_Log__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Demo_Log__c/fields/Primary_Product_INF__c.field-meta.xml
<CustomField>
    <fullName>Primary_Product_INF__c</fullName>
    <label>Primary Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Attivio</fullName>
            </value>
            <value>
                <fullName>CAFÉ  - Medical Review</fullName>
            </value>
            <value>
                <fullName>CAFÉ - RBM</fullName>
            </value>
            <value>
                <fullName>CAFÉ - RWE</fullName>
            </value>
            <value>
                <fullName>ChemDraw</fullName>
            </value>
            <value>
                <fullName>Columbus</fullName>
            </value>
            <value>
                <fullName>Elements</fullName>
            </value>
            <value>
                <fullName>E-Notebook Biology</fullName>
            </value>
            <value>
                <fullName>E-Notebook Chemistry</fullName>
            </value>
            <value>
                <fullName>E-Notebook Formulations</fullName>
            </value>
            <value>
                <fullName>iLab</fullName>
            </value>
            <value>
                <fullName>Inventory</fullName>
            </value>
            <value>
                <fullName>Inventory Ent</fullName>
            </value>
            <value>
                <fullName>Lead Discovery</fullName>
            </value>
            <value>
                <fullName>Lead Discovery Premium</fullName>
            </value>
            <value>
                <fullName>LimsLink</fullName>
            </value>
            <value>
                <fullName>Registration</fullName>
            </value>
            <value>
                <fullName>Signals Clinical</fullName>
            </value>
            <value>
                <fullName>Signals Data Factory</fullName>
            </value>
            <value>
                <fullName>Signals Lead Discovery</fullName>
            </value>
            <value>
                <fullName>Signals Medical Review</fullName>
            </value>
            <value>
                <fullName>Signals Notebook</fullName>
            </value>
            <value>
                <fullName>Signals Notebook - Biology</fullName>
            </value>
            <value>
                <fullName>Signals Notebook - Chemistry</fullName>
            </value>
            <value>
                <fullName>Signals Notebook for ChemDraw</fullName>
            </value>
            <value>
                <fullName>Signals Screening</fullName>
            </value>
            <value>
                <fullName>Signals Translational</fullName>
            </value>
            <value>
                <fullName>Spotfire Biology</fullName>
            </value>
            <value>
                <fullName>Spotfire Chemistry</fullName>
            </value>
            <value>
                <fullName>Spotfire Clinical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Demo_Log__c/fields/System_Days_Active__c.field-meta.xml
<CustomField>
    <fullName>System_Days_Active__c</fullName>
    <label>System Days Active</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>30 days</fullName>
            </value>
            <value>
                <fullName>60 days</fullName>
            </value>
            <value>
                <fullName>90 days</fullName>
            </value>
            <value>
                <fullName>120 days</fullName>
            </value>
            <value>
                <fullName>150 days</fullName>
            </value>
            <value>
                <fullName>180 days</fullName>
            </value>
            <value>
                <fullName>Retire</fullName>
            </value>
            <value>
                <fullName>15 days</fullName>
            </value>
            <value>
                <fullName>360 days</fullName>
                <isActive>false</isActive>
                <label>360 days</label>
            </value>
            <value>
                <fullName>7 days</fullName>
                <isActive>false</isActive>
                <label>7 days</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/classes/DemoLogTestClass.cls
/**************************************************************
  * 1. Jira Ticket(s) that relates to this class
  *    INC0341178
  * 2. Description - 
  *    Test class for apex class(DemoLogExpirationController).
  *
  *
  * 3. Objects referenced
  *    - Demo Log
  *
  * 4. Callouts to additional Components (including their methods) or None:
  *    - None
  *
  * 5. Dependant Class(es):
  *
  * 6. Test Class Name: DemoLogTestClass
  *
  * 7. Is @Invocable (Yes or No):  No
  *
  * 8. Author Name(s): 
  *    - Roshank Mehra(PWC) 2023.06.19
  * 
  * 
  * 9. Coverage Percentage - 100%
*************************************************************/ 
@isTest
public class DemoLogTestClass {
	@isTest
    public static void TestDemoLogExpiration(){
        PageReference p = Page.DemoLogExpiration;
        test.setCurrentPage(p);
        
        Demo_Log__c d = new Demo_Log__c();
        d.RecordTypeId = Schema.getGlobalDescribe().get('Demo_log__c').getDescribe().getRecordTypeInfosbyName().get('System Request').getRecordTypeid();
		d.Primary_Product_INF__c = 'Registration';
        d.Expiration_Date__c = Date.today();
        d.Assigned_To__c = 'Daniel Ubilla';
        d.System_Days_Active__c = '30 Days';
        insert d;
        
       ApexPages.currentPage().getParameters().put('Id',d.id);
       ApexPages.currentPage().getParameters().put('Days','30 Days');
       ApexPages.currentPage().getParameters().put('typ','Parked'); 
       ApexPages.currentPage().getParameters().put('Status','OFF');  
        
        DemoLogExpirationController dc = new DemoLogExpirationController();
        dc.submit();
        
    }
}