Perkin-UAT/force-app/main/default/objects/SMAX_PS_InventoryCount__c/SMAX_PS_InventoryCount__c.object-meta.xml
<CustomObject>
    <label>Inventory Count</label>
    <nameField>
        <displayFormat>INVC-{00000000}</displayFormat>
        <label>Inventory Count Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Counts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_InventoryCount__c/fields/SMAX_PS_DocumentDate__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_DocumentDate__c</fullName>
    <label>Document Date</label>
    <type>Date</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_InventoryCount__c/fields/SMAX_PS_PlannedDate__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_PlannedDate__c</fullName>
    <label>Planned Date</label>
    <type>Date</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_InventoryCount__c/fields/SMAX_PS_RequestedFrom__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_RequestedFrom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requested From</label>
    <referenceTo>SVMXC__Site__c</referenceTo>
    <relationshipLabel>Inventory Counts</relationshipLabel>
    <relationshipName>Inventory_Counts</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_InventoryCount__c/fields/SMAX_PS_Status__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_Status__c</fullName>
    <description>Added &quot;Approved&quot; which triggers Integration to SAP</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Recount Required</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Tech Complete</fullName>
                <isActive>false</isActive>
                <label>Tech Complete</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_InventoryCountLine__c/SMAX_PS_InventoryCountLine__c.object-meta.xml
<CustomObject>
    <label>Inventory Count Line</label>
    <nameField>
        <label>Inventory Count Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Count Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_InventoryCountLine__c/fields/SMAX_PS_BookedQty__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_BookedQty__c</fullName>
    <label>Booked Qty</label>
    <precision>12</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_InventoryCountLine__c/fields/SMAX_PS_InvCnt_Status__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_InvCnt_Status__c</fullName>
    <description>Added &quot;Approved&quot; to control integration to SAP</description>
    <label>Inventory Count Line Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Counted</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Recount</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_InventoryCountLine__c/fields/SMAX_PS_InventoryCount__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_InventoryCount__c</fullName>
    <label>Inventory Count</label>
    <referenceTo>SMAX_PS_InventoryCount__c</referenceTo>
    <relationshipLabel>Inventory Count Lines</relationshipLabel>
    <relationshipName>Inventory_Count_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_InventoryCountLine__c/fields/SMAX_PS_Product__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Inventory Count Lines</relationshipLabel>
    <relationshipName>Inventory_Count_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/SMAX_PS_InventoryCountLine__c/fields/SMAX_PS_ProductStock__c.field-meta.xml
<CustomField>
    <fullName>SMAX_PS_ProductStock__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Stock</label>
    <referenceTo>SVMXC__Product_Stock__c</referenceTo>
    <relationshipLabel>Inventory Count Lines</relationshipLabel>
    <relationshipName>Inventory_Count_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/classes/BD_Inventory_Count_TestUtil.cls
/**
 * Created by frankvanloon on 5/28/20.
 */

public with sharing class BD_Inventory_Count_TestUtil
{

	public static void createTestInventoryCount(String locName)
	{
		SVMXC__Site__c loc = [SELECT Id, Name, SMAX_PS_LocationCode__c, SMAX_PS_MaintenancePlant__c
			FROM SVMXC__Site__c WHERE Name = :locName AND SVMXC__Stocking_Location__c = TRUE];

		List<SMAX_PS_InventoryCount__c> existingCounts = [SELECT Id, Name, SMAX_PS_Status__c
			FROM SMAX_PS_InventoryCount__c WHERE SMAX_PS_RequestedFrom__c = :loc.Id];
		if (!existingCounts.isEmpty()) {
			System.debug('Existing Inventory Counts found, exiting... ' + existingCounts);
			return;
		}

		SMAX_PS_InventoryCount__c count = new SMAX_PS_InventoryCount__c(SMAX_PS_Status__c = 'Open',
			SMAX_PS_RequestedFrom__c = loc.Id, SMAX_PS_DocumentDate__c = Date.today(),
			SMAX_PS_PlannedDate__c = Date.today().addDays(14), OwnerId = UserInfo.getUserId());
		insert count;

		List<SMAX_PS_InventoryCountLine__c> lines = new List<SMAX_PS_InventoryCountLine__c>();
		List<SVMXC__Product_Stock__c> availStock = [SELECT Id, Name, SVMXC__Status__c, SVMXC__Product__c, SVMXC__Quantity2__c
			FROM SVMXC__Product_Stock__c WHERE SVMXC__Location__c = :loc.Id AND SVMXC__Status__c = 'Available'];
		for (SVMXC__Product_Stock__c stock : availStock)
		{
			SMAX_PS_InventoryCountLine__c line = new SMAX_PS_InventoryCountLine__c(SMAX_PS_InventoryCount__c = count.Id,
				SMAX_PS_ProductStock__c = stock.Id, SMAX_PS_Product__c = stock.SVMXC__Product__c, SMAX_PS_InvCnt_Status__c = 'Open',
				SMAX_PS_BookedQty__c = stock.SVMXC__Quantity2__c);
			lines.add(line);
		}
		insert lines;
		System.debug('Created Inventory Count with ' + lines.size() + ' lines.');
	}
}