Perkin-UAT/force-app/main/default/objects/Pricing_Condition__c/Pricing_Condition__c.object-meta.xml
<CustomObject>
    <description>CPQ object to store the pricing conditions from SAP under a Quote Line created by PWC SC-492</description>
    <label>Pricing Condition</label>
    <nameField>
        <displayFormat>PC-{00000}</displayFormat>
        <label>Pricing Condition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricing Conditions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/Pricing_Condition__c/fields/Condition_Type__c.field-meta.xml
<CustomField>
    <fullName>Condition_Type__c</fullName>
    <description>Field created by PWC SC-492</description>
    <label>Condition Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User Defined</fullName>
            </value>
            <value>
                <fullName>Default</fullName>
            </value>
            <value>
                <fullName>Tax</fullName>
            </value>
            <value>
                <fullName>Conditional</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Pricing_Condition__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <description>Field created by PWC SC-492</description>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Pricing Conditions</relationshipLabel>
    <relationshipName>Pricing_Conditions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Pricing_Condition__c/fields/SAP_CALCTYPON__c.field-meta.xml
<CustomField>
    <fullName>SAP_CALCTYPON__c</fullName>
    <description>Created by PwC as part of SC-492</description>
    <label>SAP CALCTYPON</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>O</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Pricing_Condition__c/fields/SAP_Net_Price__c.field-meta.xml
<CustomField>
    <fullName>SAP_Net_Price__c</fullName>
    <description>Field created by PWC SC-813</description>
    <inlineHelpText>Mapped to SAP field AMOUNT</inlineHelpText>
    <label>SAP Net Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Pricing_Condition__c/fields/SAP_Percentage__c.field-meta.xml
<CustomField>
    <fullName>SAP_Percentage__c</fullName>
    <description>Field created by PWC SC-492</description>
    <label>SAP Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Pricing_Condition__c/fields/SAP_Pricing_Condition__c.field-meta.xml
<CustomField>
    <fullName>SAP_Pricing_Condition__c</fullName>
    <description>Field created by PWC SC-492</description>
    <label>SAP Pricing Condition</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Pricing_Condition__c/fields/SAP_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>SAP_Unit_Price__c</fullName>
    <description>Field created by PWC SC-492</description>
    <inlineHelpText>Mapped to SAP field COND_VALUE</inlineHelpText>
    <label>SAP Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Perkin-UAT/force-app/main/default/classes/PricingConditionBatch.cls
/**
 * Batch class to fix Pricing_Condition__c on exiting Production quotes
 */
public class PricingConditionBatch implements Database.Batchable<sObject> {

    /**
     * Start method - Query Pricing_Condition__c for fix
     */
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([
            SELECT Id, Condition_Type__c, SAP_CALCTYPON__c, SAP_Percentage__c, SAP_Unit_Price__c, SAP_Net_Price__c, CurrencyIsoCode,
                SAP_Pricing_Condition__c, Quote_Line__r.SBQQ__Quantity__c, Quote_Line__r.SBQQ__Bundled__c,
                Quote_Line__r.SBQQ__ListPrice__c, Quote_Line__r.Rep_Total_Unit_Discount__c, Quote_Line__r.SBQQ__NetPrice__c
            FROM Pricing_Condition__c
            WHERE SAP_Net_Price__c = NULL
            AND (SAP_Unit_Price__c != NULL OR SAP_Percentage__c != NULL)
        ]);
    }

    /**
     * Execute method - Process each batch of Pricing_Condition__c
     */
    public void execute(Database.BatchableContext bc, List<Pricing_Condition__c> scope) {

        System.debug('=== EXECUTE METHOD START ===');
        System.debug('Scope size: ' + scope.size());

        List<Pricing_Condition__c> conditionsToUpdate = new List<Pricing_Condition__c>();
        for (Pricing_Condition__c condition : scope) {
            if (condition.Condition_Type__c == PricingConditionConstants.TYPE_USER_DEFINED
                || condition.Condition_Type__c == PricingConditionConstants.TYPE_DEFAULT) {
                condition.SAP_Net_Price__c = condition.SAP_Unit_Price__c;
                condition.SAP_Unit_Price__c = condition.SAP_Percentage__c;
                conditionsToUpdate.add(condition);
            } else if (condition.Condition_Type__c == PricingConditionConstants.TYPE_CONDITIONAL) {
                if (condition.SAP_Pricing_Condition__c == PricingConditionConstants.ZSLS) {
                    condition.SAP_Net_Price__c = condition.SAP_Unit_Price__c;
                    if (condition.Quote_Line__r.SBQQ__Quantity__c != 1) {
                        if (condition.Quote_Line__r.Rep_Total_Unit_Discount__c > 0) {
                            condition.SAP_Unit_Price__c = - condition.Quote_Line__r.Rep_Total_Unit_Discount__c;
                        } else if (condition.Quote_Line__r.SBQQ__Bundled__c) {
                            condition.SAP_Unit_Price__c = - condition.Quote_Line__r.SBQQ__ListPrice__c;
                        }
                    }
                    conditionsToUpdate.add(condition);
                } else if (condition.SAP_Pricing_Condition__c == PricingConditionConstants.ZSPC) {
                    condition.SAP_Net_Price__c = condition.SAP_Unit_Price__c;
                    if (condition.Quote_Line__r.SBQQ__Quantity__c != 1) {
                        condition.SAP_Unit_Price__c = condition.Quote_Line__r.SBQQ__NetPrice__c;
                    }
                    conditionsToUpdate.add(condition);
                }
            }
        }
        update conditionsToUpdate;

        System.debug('=== EXECUTE METHOD END ===');
    }

    /**
     * Finish method
     */
    public void finish(Database.BatchableContext bc) {
    }
}