Perkin-UAT/force-app/main/default/objects/Pricing_Condition__c/Pricing_Condition__c.object-meta.xml
<CustomObject>
    <description>CPQ object to store the pricing conditions from SAP under a Quote Line created by PWC SC-492</description>
    <label>Pricing Condition</label>
    <nameField>
        <displayFormat>PC-{00000}</displayFormat>
        <label>Pricing Condition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricing Conditions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/Pricing_Condition__c/fields/Condition_Type__c.field-meta.xml
<CustomField>
    <fullName>Condition_Type__c</fullName>
    <description>Field created by PWC SC-492</description>
    <label>Condition Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User Defined</fullName>
            </value>
            <value>
                <fullName>Default</fullName>
            </value>
            <value>
                <fullName>Tax</fullName>
            </value>
            <value>
                <fullName>Conditional</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Pricing_Condition__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <description>Field created by PWC SC-492</description>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Pricing Conditions</relationshipLabel>
    <relationshipName>Pricing_Conditions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Pricing_Condition__c/fields/SAP_CALCTYPON__c.field-meta.xml
<CustomField>
    <fullName>SAP_CALCTYPON__c</fullName>
    <description>Created by PwC as part of SC-492</description>
    <label>SAP CALCTYPON</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>O</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Pricing_Condition__c/fields/SAP_Net_Price__c.field-meta.xml
<CustomField>
    <fullName>SAP_Net_Price__c</fullName>
    <description>Field created by PWC SC-813</description>
    <inlineHelpText>Mapped to SAP field AMOUNT</inlineHelpText>
    <label>SAP Net Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Pricing_Condition__c/fields/SAP_Pricing_Condition__c.field-meta.xml
<CustomField>
    <fullName>SAP_Pricing_Condition__c</fullName>
    <description>Field created by PWC SC-492</description>
    <label>SAP Pricing Condition</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Pricing_Condition__c/fields/SAP_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>SAP_Unit_Price__c</fullName>
    <description>Field created by PWC SC-492</description>
    <inlineHelpText>Mapped to SAP field COND_VALUE</inlineHelpText>
    <label>SAP Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Perkin-UAT/force-app/main/default/classes/TestDataFactory.cls
@IsTest
public class TestDataFactory {

    /**
     * @description Helper method to create custom Pricebook2
     */
    public static Pricebook2 createPricebook() {
        // Create Custom Pricebook
        Pricebook2 customPricebook = new Pricebook2(
            Name = 'Test Pricebook',
            IsActive = true
        );
        return customPricebook;
    }

    /**
     * @description Helper method to create PricebookEntry
     */
    public static PricebookEntry createPricebookEntry(String pricebookId, String productId) {
        // Create Pricebook Entry
        PricebookEntry pbe = new PricebookEntry(
            Pricebook2Id = pricebookId,
            Product2Id = productId,
            UnitPrice = 100,
            IsActive = true
        );
        return pbe;
    }

    /**
     * @description Helper method to create Pricing_Condition__c
     */
    public static Pricing_Condition__c createPricingCondition(
        String quoteLineId, String code, String type, Decimal price, Decimal amount) {
        // Create Pricing Condition
        String calc = (type == PricingConditionConstants.TYPE_DEFAULT)
            ? PricingConditionConstants.CALCTYPON_C
            : (type == PricingConditionConstants.TYPE_USER_DEFINED)
                ? PricingConditionConstants.CALCTYPON_M
                : (type == PricingConditionConstants.TYPE_CONDITIONAL && code == PricingConditionConstants.ZVDI)
                    ? PricingConditionConstants.CALCTYPON_M
                    : PricingConditionConstants.CALCTYPON_B;
        Pricing_Condition__c pricingCondition = new Pricing_Condition__c();
        pricingCondition.Quote_Line__c = quoteLineId;
        pricingCondition.SAP_Pricing_Condition__c = code;
        pricingCondition.SAP_CALCTYPON__c = calc;
        pricingCondition.Condition_Type__c = type;
        pricingCondition.SAP_Unit_Price__c = price;
        pricingCondition.SAP_Net_Price__c = amount;
        return pricingCondition;
    }
}