Perkin-UAT/force-app/main/default/objects/Deal_Desk__c/Deal_Desk__c.object-meta.xml
<CustomObject>
    <label>Deal Desk</label>
    <nameField>
        <displayFormat>DD-{00000000}</displayFormat>
        <label>Deal Desk No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Desk</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Perkin-UAT/force-app/main/default/objects/Deal_Desk__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Deal Desk</relationshipLabel>
    <relationshipName>Deal_Desk</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Deal_Desk__c/fields/Request_For__c.field-meta.xml
<CustomField>
    <fullName>Request_For__c</fullName>
    <description>This field describes the options on what a deal desk is requested for (Source: RITM0099886)</description>
    <inlineHelpText>This field describes the options on what a deal desk is requested for .</inlineHelpText>
    <label>Request For</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Deal_Desk_Request_For</valueSetName>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Deal_Desk__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
                <default>true</default>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Re-Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Deal_Desk__c.field-meta.xml
<CustomField>
    <fullName>Deal_Desk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal Desk</label>
    <referenceTo>Deal_Desk__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IMAGE(IF( Weighted_Amount__c /  Amount &lt; 0.7, &quot;/img/samples/flag_red.gif&quot;,IF( Weighted_Amount__c /  Amount &lt; 0.81,&quot;/img/samples/flag_yellow.gif&quot;,&quot;/img/samples/flag_green.gif&quot;)),&quot;no status&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/objects/User/fields/ProfileName__c.field-meta.xml
<CustomField>
    <fullName>ProfileName__c</fullName>
    <description>formual to get the text value of the profile name</description>
    <formula>Profile.Name</formula>
    <label>Profile Name</label>
    <type>Text</type>
</CustomField>

Perkin-UAT/force-app/main/default/classes/OverrideDealDeskNewButtonController.cls
public with sharing class OverrideDealDeskNewButtonController {
    public String oppId {get;set;}
    public OverrideDealDeskNewButtonController(ApexPages.StandardController controller){
       oppId = ApexPages.CurrentPage().getparameters().get('id');
    }

    @auraEnabled
    public static  List<String> getRequestForValues(){
        List<String> pickListValuesList = new List<String>();
        Schema.DescribeFieldResult fieldResult = Deal_Desk__c.Request_For__c.getDescribe();
		for(Schema.PicklistEntry pickListVal : fieldResult.getPicklistValues()){
			pickListValuesList.add(pickListVal.getLabel());
		}   
        System.debug('pickListValuesList--->'+pickListValuesList);
        return pickListValuesList;
    } 

    @auraEnabled
    public static String checkAvailableDealDesk(String oppId){
        String returnStr;
        List<Opportunity> listofOpp = [SELECT Id, Name, (SELECT Id, Name FROM Deal_Desk__r WHERE Status__c != 'Cancelled') FROM Opportunity WHERE Id =: oppId];
        if(listofOpp != null && listofOpp.size() > 0){
            for(Opportunity iterOpp : listofOpp){
                if(iterOpp.Deal_Desk__r != null && iterOpp.Deal_Desk__r.size() > 0){
                    returnStr = 'ERROR';
                } else{
                    returnStr = 'SUCCESS';
                }
            }
        }
        return returnStr;
    }

    @auraEnabled
    public static String currentDDStatus(String dealdeskId){
        Deal_Desk__c ddObj = [SELECT Id, Name, Status__c FROM Deal_Desk__c WHERE Id =: dealdeskId];
        if(ddObj != null)
            return ddObj.Status__c;
        else
            return '';
    }

    @auraEnabled
    public static String currentUserProfile(){
        try{
            User userInfos = [select id, name, profileName__c from user where id =: userInfo.getUserId()];
            List<PermissionSetAssignment> psetAssign = [SELECT AssigneeId,PermissionSet.Name FROM PermissionSetAssignment where AssigneeId =: userInfo.getUserId() and PermissionSet.Name = 'Deal_desk_for_Approvers'];
            if((psetAssign != null && psetAssign.size() == 1)){
                return 'Approvers access';
            }else{
                return '';
            }
          }catch(Exception e){
            throw new AuraHandledException(e.getMessage()); 
          }
    }
}